### ISSUE TITLE
When using one menu bar search field, clear the other

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1052]
Idea by Julie Hochgesang of ASL Signbank, as you never want to use both simultaneously.

> Yeah my prediction would be that people wouldn't want to use them simultaneously - I haven't myself and I don't see other people doing so. They're actually confused about what the difference is between the two :) But I like your proposal - clearing one field when we start typing in the other. Yes, let's do it!

**Comment by ocrasborn** [comment]
Agree, good idea

**Comment by susanodd** [comment]
NOTE TO SELF: Some of the different menu options may share the same admin_gloss_list template. There are two context variables being used to store the form data fields, which are filled in by different views.

**Comment by susanodd** [comment]
@Woseseltops do we need to use Django-CMS? (Someone recommended this on stackoverflow as a solution to something similar to the following.)

It looks like the session variables / get parameters are retaining an old value in spite of not assigning anything in the url (no parameters in the url, but there are old values still obtained.)

**Comment by susanodd** [comment]
Regarding this issue, this should not be happening that both the search form and the menu bar are both filled in.
The search depends on whether you fill in the menu bar (and hit return after filling in the menu bar fields - i.e., gloss or sense search)
or otherwise you fill in the search form fields and use the "Search Sign" or "Sign or Morpheme" button below the search form.
These two search methods work independently and the other fields are ignored.

However, as mentioned above, for some reason old values seem to persist when nothing has been filled in. (I included a print statement in the code to see what the get_queryset method thinks its parameters are.)
(But I am not able to duplicate this behaviour. After several "nothing filled in" it started working again for some reason, without changing any code or typing anything in.)

**Comment by susanodd** [comment]
I repaired the Gloss Search Form, Reset button in #1074. It was not clearing (non-multi-select) select fields. 
This is fixed and is live now.

Regarding this issue, do you mean only the fields in the menu bar? (Search Gloss and Search Sense)
It does work to put something in both. But it works like an and.

**Comment by ocrasborn** [comment]
Not quite sure what Julie's idea was, but I'd say that executing a search (by hitting enter) from the menu bar fields (either one or both; I personally find the combination with operator 'and' useful) should clear both those fields. Is that what you're asking, @susanodd ?

**Comment by susanodd** [comment]
When should they be cleared? At first I assumed it was when you start typing in the normal fields below.
But on a new read it seemed like only one of the menu bar fields should work and the other gets cleared.
After you do a query the search form is filled in again with the fields you just filled in.
So you can see them and edit further.
If you also typed in menu bar fields then the form fields will be ignored. (It’s either menu bar or search form)

[I’m not sure whether Global Signbank is totallly different than ASL Signbank.
I didn’t make the form fields get filled in again until the query parameters were added.]

**Comment by susanodd** [comment]
So simple is as simple does.
