### ISSUE TITLE
Import CSV Gloss Update: new senses not found

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1118]
[new_senses.csv](https://github.com/Signbank/Global-signbank/files/13904720/new_senses.csv)

@susanodd can you check my file (ID is for sign KAAS,CHEESE,GOUDA,GOUDA in tstMH)? It may be my mistake as this is the first time I try something with CSV's, but the upload doesn't seem to detect new senses. I get "No changes were found."

**Comment by susanodd** [comment]
I tried it on my local computer. (Indeed it uses semicolons.)

Apologies that the feedback is useless!

It didn't do anything because there are already senses for that gloss.
It only works to create new senses. (That is there should not be any senses for the gloss yet.)

Change the gloss id to a different gloss that has no senses.
Then it works.

The command has been this way since before @ocrasborn left actually. Nobody else has apparently used it.

**Comment by susanodd** [comment]
In order to update senses, additional parsing is needed. There are some functions to do this, but the parsing and comparison to existing senses to see which ones had been updated was too complicated.

We would need a new command for updating or creating senses, separately from the gloss update, so there can be a row with Sense ID for each sense.
Sentences are done something like this.

**Comment by Jetske** [comment]
My bad! Indeed I thought I chose a gloss that didn't have senses yet, but it did.. I tried again with a gloss that didn't have senses and it worked so I'll close this issue.
