### ISSUE TITLE
For the CSV upload, provide an empty template

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1131]
Idea came out of a conversation with @uklomp .

**Comment by susanodd** [comment]
While working on #1132 I've revised the input so as not to require selection of the delimiter.
Here is the revised display for Import CSV Create with the help text moved to show the columns
The language columns are displayed dynamically, based on what dataset(s) are selected.

![csv-create-glosses-ngt](https://github.com/Signbank/Global-signbank/assets/24272544/ae51538c-c8b6-401f-b026-406c8764d103)

**Comment by susanodd** [comment]
![csv-update-lemmas-ngt](https://github.com/Signbank/Global-signbank/assets/24272544/24bb5187-7f02-46a2-b776-6086f6171d3d)

**Comment by susanodd** [comment]
Here are screenshots of the CSV Update Gloss page. I added a scrollbar for the various columns, with annotations.

![csv-update-gloss-scrollbar-1](https://github.com/Signbank/Global-signbank/assets/24272544/5e7bf54c-b9b9-4d22-b808-aafba6b971ea)

![csv-update-gloss-scrollbar2](https://github.com/Signbank/Global-signbank/assets/24272544/4903d365-f4df-4458-ae71-f06a128419be)

![csv-update-scrollbar3](https://github.com/Signbank/Global-signbank/assets/24272544/307c1d33-3dde-4580-8cd9-d72faee6be66)

![csv-update-scrollbar4](https://github.com/Signbank/Global-signbank/assets/24272544/dbb54728-b5e6-4862-ad18-10e9b685e180)

![csv-update-scrollbar5](https://github.com/Signbank/Global-signbank/assets/24272544/cdcd7636-0736-4196-afb4-11af84604335)

**Comment by susanodd** [comment]
@uklomp do the above screenshots help?

The CSV Create Gloss and the CSV Update Lemma pages are hopefully straightforward. The language columns on display are dynamic based on the selected dataset.

The CSV Update Gloss page has a scrollbar with some annotations. Although it's best to export a CSV to see what the data looks like in order to update it. I can insert popups to show the syntax of data.

More complicated and advanced would be to create an Excel spreadsheet that allows selection of the various fields.
(This would only be possible with the Field Choice type fields.) At the moment that would need to be on the back burner. I don't have Excel on Ubuntu. I guess we'd need to create some macros for Excel for Signbank Field Choice choices.)

But it is possible to make tooltips for the columns shown in the scrollbar.

**Comment by susanodd** [comment]
The screenshots above can be checked out live on signbank-dev.

**Comment by susanodd** [comment]
The above has been deployed to Signbank.

**Comment by susanodd** [comment]
Btw, with all the settings for Senses, Notes, Tags, these were needed to accommodate things that @ocrasborn wanted to do in the past.
If you don't know what to choose, just try it. You get feedback about what is going to be changed that you need to approve, so if you choose wrong, no problem.

(The morpheme column needs some work for CSV update as I've changed the morphemes a lot in the past months and didn't do the CSV yet it appears.)

**Comment by uklomp** [comment]
as discussed just now, please provide a downloadable .CSV template - thank you!

**Comment by susanodd** [comment]
I've got the download template working now. (It's not live yet.)

@Woseseltops [CODE DETAILS] I made it so both the database and the kind of csv are made available via the template. The download button is attached to a url that generates it.
The question is, this url at the moment needs these parameters to be provided.
What about ASL? Do you use the CSV routines? Do I just omit the Dataset column and the language between parentheses?
Since it's possible somebody could enter the url itself, I need to figure out what it should generate if the dataset/type of csv is missing.
The code is on branch csv_interface.
I guess I'll make a pull request so you can see what it is for ASL

**Comment by Woseseltops** [comment]
You mean the ASL installation? If I'm not mistaken they mostly add individual glosses, not in bunch like the Amsterdam users, so it's not something to worry about. Perhaps something like: if no dataset is provided, just take use the main one (I believe there's a setting like `MAIN_DATASET_ID` or something like thata)

**Comment by susanodd** [comment]
Okay, that's what I've done. It uses the Default dataset setting.

**Comment by susanodd** [comment]
@uklomp shall I put this on the production server? It's only on `signbank-susan` at the moment, awaiting approval from you in the pull request.

**Comment by susanodd** [comment]
@uklomp I looked at the csv file above in a text editor. That is not the downloaded template, that is something Excel did to it.

I has an "additional" header added to the top that was not in the template:

`Column1;Column2;Column3;Column4;Column5
`

@Jetske can you try this on Excel to see what Excel is doing to it?

It's on signbank-susan

The CSV for Create glosses.

The csv file that Excel exported to has that extra row added to it at the top.
Please try to see if that is an Excel setting or if it happens on importing or opening a CSV.

The Excel CSV somehow is wrong, but it's not the template that is wrong.
Does this happen all the time? That is the question.

@uklomp if you save a search results query to CSV then open this in Excel and edit it and then export it to csv, does that file also not import?
I need to understand if it's your Excel settings or if this always happens.
What version of Excel is it?

**Comment by uklomp** [comment]
I wanted to test this on signbank-dev so I searched for 'kamp' and got 6 results. When I clicked 'csv' it took ages to download the file, but then I finally got it, and then it turned out that its not only these 6 results, but the whole dataset? that's weird? 

Anyway. I took this file as a starting point for your question. Imported the CSV in Excel. Deleted ID gloss and all the columns on the right of 'annotation ID gloss (dutch)'. Then I put the name signs in that I wanted to upload. Uploaded the file on signbank-dev. It works! I'm attaching it here. 
[namesigns.csv](https://github.com/Signbank/Global-signbank/files/14276814/namesigns.csv)
Version of Excel: I think it's part of the Microsoft 365 package from the UVA, I can't find a version number...

**Comment by susanodd** [comment]
I'll check the bug that it is giving too many glosses when you save the CSV from the query. That has something to do with the session settings. (I am familiar with this bug. But it seems arbitrary when it shows up. (It's hard to duplicate the bug.)

Okay, the namesigns.csv also works on the branch csv_enhancement

I'll make the message more informative for the first file that has the extra row.
The error is that the headers were not found in the first row.
I can program it to ignore such a row.

**Comment by Jetske** [comment]
@uklomp I also tried opening the template and it seems to be a thing that Excel adds 'column' headers. 

Following these steps solves it: 
https://howardsimpson.blogspot.com/2019/08/excel-import-csv-not-using-use-first-row-as-headers.html

@susanodd it is probably an annoying error if the rest of the file is correct, so we could consider checking for these 'column' headers during an import and remove them then

**Comment by susanodd** [comment]
![message-first-row-csv](https://github.com/Signbank/Global-signbank/assets/24272544/2c01899b-504a-45b2-857f-39a0fd2668fe)

**Comment by susanodd** [comment]
I modified it to show the first row if it's not the headers.

But yes, it is annoying. I'll make it ignore this row as such.

It's necessary to have a correct header column, because that is used to construct a dictionary that is filled per row while processing.

**Comment by susanodd** [comment]
@Jetske how many rows should it skip while looking for the header row? I'll have it just skip one such row. But I'm wondering if it's possible to save csv and end up with more stuff added at the front.
We probably need some test csv files.
In the past it was other languages that caused problems. That's why the help text says to use LibreOffice. (@ocrasborn had some files with Chinese in them.)

**Comment by Jetske** [comment]
@susanodd well if a file with 'column' headers already in there is opened again, it again adds a similar row. This is however quite clearly noticeable in Excel so I would assume users then delete that row. But maybe you can check for more rows, and skip every row until the one that contains "Dataset"?

**Comment by susanodd** [comment]
Okay, I put in a counter for the number of rows checked looking for the header row.
I'll increase that to 2 say. But the new feedback above will show the Column row eventually.

**Comment by susanodd** [comment]
@uklomp this is working now on signbank-susan

Can you check this for yourself?

I tried the file above [naamgebaren-24-02-13.csv](https://github.com/Signbank/Global-signbank/files/14269630/naamgebaren-24-02-13.csv)
This works now.

Then I can deploy it to the signbank server.

**Comment by uklomp** [comment]
Yes!! it's working! :D

**Comment by susanodd** [comment]
Okay, thanks.

This is now on signbank too!

**Comment by susanodd** [comment]
Okay, I'll close this issue.
