### ISSUE TITLE
tags

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1143]
@ocrasborn I remember there used to be a tag for Radboud University in SignBank, but it's not there anymore. Can you tell me why? We are considering adding a few tags to label where the data came from (Corpus NGT for signs with a frequency, perhaps Radboud if you still think this label is handy for e.g. name signs, UvA for the dataset we're creating now, IPROSLA for signs added by Tom/Johan.... but it's up for debate)

**Comment by susanodd** [comment]
@uklomp Did you try creating a tag? You should be able to create them in the admin.
.... scroll down....
Pages
Sites
Tagging

**Comment by susanodd** [comment]
@uklomp Once you've created the new tags, you can use the CSV Import Update Glosses to add tags.

You can modify tags in a column this way:

As shown in the panel bar of the import page, there are toggles for tags:
One replaces the existing tags with the new tags.
The other adds the tag in the csv to the gloss, keeping its original tags.

(If you try out an option, you get a preview of what it will do. So if necessary you can choose the other toggle settings.)

You only need the Tags column (the field you're changing) an can remove most of the other columns except the required ones.

**Comment by susanodd** [comment]
It will be easier if you add tags to the glosses in the datasets before moving the glosses from Oefen. They'll retain the tags.

**Comment by susanodd** [comment]
Okay, I'm experimenting with this.
It looks like at the moment, Signbank needs to be rebooted for new tags to show up in the Search Gloss (publication fields) and Gloss Edit selection menus.
That isn't helpful.

**Comment by susanodd** [comment]
For the Radboud tags, some of the project tags were converted to Notes. If you search on Notes Type -> Project, you can find FMU glosses. **Form-Meaning Units (FMU)**

**Comment by uklomp** [comment]
OK, thanks. Maybe that's what happened with the Radboud tag. @susanodd  there's no action needed yet, I think I know how to add tags, thanks! I wanted to ask Onno for his opinion on having tags for different parts of the datasets.

**Comment by susanodd** [comment]
I'm working on it.

I fixed it so the new tags get reloaded (so signbank does not need to be rebooted)
But you need to enter them with underscores where spaces are.
project:_totally_new_tag

This is very confusing. As you can see, we haven't used this feature for a while.

Yes, hopefully @ocrasborn will respond.
They seem mainly used to flag things that are missing or wrong.

I added a toggle column in the Analysis -> Map Keywords to Senses page,
where you can toggle a tag for a gloss "Check Senses" on and off.
The idea was that people could browse the list of glosses and tick which ones need repair.

If you need something similar for other tags, we could make a Tags View page where you could browse the glosses and click tags on and off per row.

**Comment by susanodd** [comment]
@uklomp the code has been revised so that once you create new tags in the admin, they are immediately available.

(No reboot is needed.)

**Comment by uklomp** [comment]
@susanodd Onno responded via email. After his respons, I'd like to request the possibility to make a different set of labels: 
1. labels that function like the labels now, and can be created, added, deleted as the labels that already exist;
2. but preferably in another colour (green)
3. and preferably we can create labels that are only visible for a certain dataset (other users of other datasets requested this too)

**Comment by susanodd** [comment]
Okay, nice addition!

**Comment by susanodd** [comment]
Do you mean on gloss creation?

The gloss creation already has the user saved. If you search on Created By you can find them.

I don't know whether it's wise to add such a tag at gloss creation. The tags are meant to be dynamic and can toggle on and off.
You could do this by adding such a tag and then via CSV update after searching on Created By.
Or using the Toggle view after searching on Created By.

**Comment by susanodd** [comment]
You could create a Group for the UvA users.

I could add a search by Group, I guess. (Although that seems kind of dodgy, since the Groups are meant to allow certain permissions, so they probably shouldn't be visible what groups exist.)

I don't have a good answer.

**Comment by uklomp** [comment]
He responded and suggested that we have this different set of tags, not so dynamic, to indicate the source of the signs. So we came to the conclusion to have a tag for RU, for UvA and potentially later also other universities.
He also came up with the idea to assign these tags to users so that they're added automatically. I don't want to update the CSVs for hundreds of signs every month to add this new tag, to be honest.

**Comment by susanodd** [comment]
Hmmm. Do you want to have a specific group for UvA?

I'm wondering about some of the already existing signs. Because there has been some overlap with adding videos and editing signs. It would be weird if universities started owning signs? or started moving signs from one university to another?

I have zero ideas of how that works or should work. We just implement stuff.

I found it very cool to see you guys making your own signs in the Oefen dataset while you worked out the phonology or signing itself. Like the signs with the user name in them.

On the signs I moved, I added a -A or -B to some that already existed. So it's possible to do that in the sign annotation.
Keep in mind that all the videos also get that in the name of the video, since the annotation and ID is included in the filename.

**Comment by uklomp** [comment]
So, the idea is that it's visible which university added the sign. It is indeed also a bit about ownership, because we have a first version of the NGT dataset, composed from the corpus NGT, by the RU, and now there's the second version, including thousands of glosses (at the end of this year) composed by us. To distinguish between the sets, and to see what the source is, we think it's a good idea to add a tag for this. Is this clear? If not, let's talk about this during our next Thursday meeting.

**Comment by susanodd** [comment]
Yes!!

Another slight question, for the videos. Some of the signs (in Oefen) were first created without phonology, so the sign was created with the video. But say, for NGT, there have been signs created without any video when first created. There was a woman Lianne who spent several months last summer signing, filming videos, for signs in NGT.

For signs that have been updated, like adding or modifying phonology, this shows up in the Gloss Revision History.
For uploading videos, this shows up in the Gloss Video History.
(So maybe some extra information needs to be maintained about these aspects of what is stored? Or access to this information in a user friendly way?)

So what you want is kind of two datasets for NGT in a way.
Are the revisions at all interesting?

@Woseseltops received a zip file from @ocrasborn with videos to upload for 170 signs. Most of the signs are signed by the same person. And most seem to be remakes of videos. Plus there are new signs.
So is @ocrasborn still counted as a Radboud signer? He's created a bunch of signs for numbers this year, also.

**Comment by susanodd** [comment]
(I look at recently added signs about once per week to see what's been happening.)

**Comment by susanodd** [comment]
Yes, I can add the tag during the first save of the gloss. (But, this could mean the sign that's only the text has been added, without a video. So it may be premature to add a tag. This is why I hesitated to create glosses from a csv myself, because I would become the creator.
It may also be weird with batch uploads of videos, since that may be done my a systems person rather than the signer.

**Comment by susanodd** [comment]
We could add a field for "signer" for the person in the video? Then that person associated with the university or research project?

**Comment by susanodd** [comment]
@uklomp to make this easier, it would help to have a group for each university, research group. Then when a user creates a gloss, it will be easy to determine what tag to set.
Otherwise additional arguments will be needed for all the functions/methods to allow specification of the university.

Another possibility would be to add an affiliation to the User Profile, and this would be added as a tag to the gloss.

We're going to add API tokens to the User Profile, that the user can generate this. Then this will need to be written down somewhere by the user, since we can't see these, just like passwords.
I have yet to do this, since this needs to be on a real server, not on the PyCharm runserver (simulator).
To my surprise we never installed the Django Rest Framework (for APIs), in spite of talking about doing this for years.

So either put all the UvA users in a group UvA, etc. That is probably easiest. (You can do this as Admin.)

Or we can add a field for "signer" for the person in the video. (Hopefully this is also somebody that has a user name.)

For the videos that are extracted from the CNGT corpus, does something else need to be added to identify the origin of the signs?
Or do you want multiple affiliation tags added to signs?

**Comment by susanodd** [comment]
@uklomp I glanced at the recently created glosses. Nice!

(Does the window need to be smaller? You guys are really productive!)

I looked at a couple. Now I see, there are videos, but no phonology yet.

I'd try doing some searches, I guess on Created By, Created After, Has Video.
@ocrasborn had us implement some of the queries to not included glosses without phonology. (And others to ignore glosses with out Handedness.)
I'm wondering if that hinders some of the searches, since no results would be returned, or all the glosses would be returned if nothing is filled in except the video.

**Comment by uklomp** [comment]
1. I like the idea of adding an affiliation to a user profile for editors
2. I think the tag/label can be added when the gloss is created
3. Videos from the Corpus were glossed / saved / entered by RU so the tag RU would in fact be fine
4. I don't know yet how to deal with glosses added by Gomers system - probably we add the label UvA here as well
5. What do you mean with a smaller window? :) for the recently created glosses you mean, to have a smaller list? 
6. Your last message goes a bit too fast. You did some searches, and what is the question about the tags in this case?

**Comment by susanodd** [comment]
@uklomp for (5), yes, to have a smaller list. :)  It's set to 3 months now.

For (6), I was just curious whether you can find the glosses that you have created when you expect to find them. :)

[Babble explanation.
For example, the gloss Ijsbeer is really cool. I used that when developing the morphology searches and Relations View.
I suspect there are many more such cool glosses, but I can't find them if the phonology/morphology isn't flled in.
I was trying to check that the software works okay. We kind of need lots of data to test that it works properly.
So then I was wondering if you had done searches and didn't find things you were expecting to find. Then came up with the idea to add tags.]

With the UvA tag, that will help with searches, too. :)

[So then I was wondering if at the end of the project, as you mentioned, if you need additional information to be added, or able to be queried from the Video history or the Revision history in order to detect things you have corrected or improved.]

**Comment by uklomp** [comment]
(5) ok! :) 
(6) right, I get this now. Will think about this. Might be good to be able to see what we added in one year, what we revised in one year, etc... maybe per user even... but I need to think about this for a bit, maybe also wait till the system of Gomer is implemented.

**Comment by susanodd** [comment]
@uklomp I have the affiliiation tags implemented. I just need to make them look like tags.
You'll be able to add affiliations to users and to glosses.
Will you be wanting to add colours, so different colleagues can have their own colour for their affiliation or project?
Or would that look too distracting in the interface if people get carried away?
The current tags are blue because they're an imported package.
The new ones I implemented. (So at the moment, it's for users and glosses. The gloss affiliation can be calculated from the creator. We can make a command for this to do it for all the existing glosses. Then add it to the save command to automate it. You will be able to set them in the Gloss Edit as well. So you could make affiliations like projects, too.

But the question is: what colour?
Or do you want a field in the affiliation for that? (I'm guessing yes.)

**Comment by uklomp** [comment]
Sounds good!! Lets make them green, so one colour for all the affiliation tags. 
And lets look into automatically linking them after my holidays - so in April.

**Comment by susanodd** [comment]
> @susanodd Onno responded via email. After his respons, I'd like to request the possibility to make a different set of labels:
> 
> 1. labels that function like the labels now, and can be created, added, deleted as the labels that already exist;
> 2. but preferably in another colour (green)
> 3. and preferably we can create labels that are only visible for a certain dataset (other users of other datasets requested this too)

1 and 2 are implemented and on Signbank now.

The tags are only visible in the User Profile (Affiliation) and in Gloss Details.

For 3, normally you will only see tags for the datasets you can view.

They are not visible in the Search yet, nor can they be queried on yet.
We can easily implement a virtual environment command to add the affiliation tag to glosses based on the affiliation tag of the User who created the gloss.
They can also be added to the create gloss save (internally).
