### ISSUE TITLE
Add API endpoint 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1152]
Like discussed yesterday: 

1. API endpoint voor het toevoegen van glossen 
 --> Met resultaat van toevoegen in JSON response formaat 
2. API endpoint voor het bekijken van glossen 
--> JSON response in vorm van array bestaande uit alle elementen van het glos (glos ID, url naar filmpje, parameters) 
3. API authenticatie met lees/schrijf rechten ingesteld per gebruiker 
4. API token per gebruiker 

De API toegang is nodig voor het toevoegen van de glossen via derde-partij platform, in onze geval Gebarenoverleg Systeem. Dit systeem is onze workflow en hiermee volgen we onze methoden/stappen om onze glossen te bespreken en metadata aan te koppelen.

Gomer will answer your questions about this. @rem0g (maybe @Woseseltops can make Gomer admin as well, so he has labels etc and can add priority?)

**Comment by Woseseltops** [comment]
Although I'm anxious to add more dependencies, we should at least consider using the Django REST framework for this: https://www.django-rest-framework.org/ 

About the API token: I'm thinking about something a user can request once, and if they forget it, their only option to generate a new one... but should it also expire?

> (maybe @Woseseltops can make Gomer admin as well, so he has labels etc and can add priority?)

Sure, welcome @rem0g.

**Comment by susanodd** [comment]
Some of these API things are in the zipped file of #1149. That's a zipped file of json files.

**Comment by susanodd** [comment]
Bullet (2) is completed (described in #1149 as part of issue about already existing package API)

**Comment by rem0g** [comment]
Regarding (2) if video_url can be added, then it would be completed. The video url should be always viewable even without login,otherwise i could work with access (cookie) token in http request.

**Comment by susanodd** [comment]
Okay, great. It's included as "Link" in the gloss info (also without login).

Do you want a different structure for the json for videos/images?
Or as they are in the zipped file but for just one gloss?

I realised that Lemmas are not included at the moment. I'll add those too.

**Comment by rem0g** [comment]
Yes we have noticed the videos are not reachable via external url (directly to video url) when the glosses inweb are set at false, for example glosses added this year. 

Link is only url to gloss info indeed, so just only need raw video url. Then GOP will display the video as external url from Signbank, so we get up to date information.

**Comment by rem0g** [comment]
About InWeb; its not a problem because i can view the video with Cookie token via HTTP request.

**Comment by susanodd** [comment]
@rem0g the Video links and Lemmas are now included in the json retrieval. That's deployed on signbank.

**Comment by rem0g** [comment]
Perfect, (2) is completed indeed.

**Comment by Woseseltops** [comment]
I'm a bit confused about what API endpoints already exist, and which ones are still needed. Since this is a typical feature that needs documentation anyway, could you please create a structured overview at https://github.com/Signbank/Global-signbank/wiki/Signbank-API ? 

I think every endpoint description needs these things:
* Examples for how to call it
* Example output
* Information on authentication

**Comment by susanodd** [comment]
Okay, sure. I'm working on the zip video archive ones now.
(That will go on signbank-dev first.)

**Comment by susanodd** [comment]
@Woseseltops do you have a preference for where the specific urls live?
(Under signbank or under dictionary?)
Since the `package` was under dictionary I put the two `get_gloss_data` and `get_fields_data` under dictionary.

(I'm not entirely sure when something should be in the signbank urls.py level. Or if something different is needed to collect the api ones.

**Comment by susanodd** [comment]
@Woseseltops Okay, I added the urls with descriptions to the wiki.
Yet to do, examples.

**Comment by rem0g** [comment]
Is there an API endpoint for looking for glosses/senses?

**Comment by rem0g** [comment]
I am afraid we have to reopen 2) again. 

For querying i would have to need those fields under Phonology: 

https://signbank.cls.ru.nl/signs/search/#

Only those are filled in as far as i see in JSON: 
Handness, Strong Hand, Weak Hand, Location. 

Those are four fields, so yet 15 fields missing so far.

**Comment by susanodd** [comment]
@rem0g Okay, for specific information.
Do you want it to return fields with empty values as well?
Because of the size, I only included fields that are non-empty.

The fields above (Handness, Strong Hand, Weak Hand, Location) are for non-logged in users.

I can add the non-empty fields but the not logged in user will still only see the ones in Search.

Oh, did you try looking at your result in Analysis -> Query View ?
There you see columns for the fields you actually searched on.

Again, we can make it so you can use "prefab" queries (the stored ones).
I could make it so there are some available for everybody, like "published" queries.
At the moment, only the ones you yourself saved are shown to you.

(The length of the url for searches is awful otherwise.)

**Comment by rem0g** [comment]
When logged in and downloading the package (/dictionary/package/ ) those 15 fields are still missing, for example orientation is nowhere to be found. 

> Do you want it to return fields with empty values as well?
>Because of the size, I only included fields that are non-empty.
Only include when they are defined.

The results are same whether i am logged in / not logged in.

**Comment by rem0g** [comment]
When reading the Wiki, thank you for writing detailed information, i do see those fields returned for example https://signbank.cls.ru.nl/dictionary/get_gloss_data/5/4123/

Ideally, by standard those fields should also be included in the package.

**Comment by susanodd** [comment]
@rem0g the package url zipped functionality itself is used by ELAN.
So it returns the fields they have been using for a very long time.
I can make an additional url for getting the package zipped with all the fields.

As you can tell, I'm not such a fan of putting parameters in the url for the api.
It makes for a lot of extra code to check the parameters. Plus we had friendly hackers trying to insert code that way.
(The fields that accept regex are subject to this.)
It would be easiest to just add more / things to the url or use a different name.

**Comment by susanodd** [comment]
> When reading the Wiki, thank you for writing detailed information, i do see those fields returned for example https://signbank.cls.ru.nl/dictionary/get_gloss_data/5/4123/
> 
> Ideally, by standard those fields should also be included in the package.

I'll make an additional package url for the expanded fieldset, so I can leave the original as it is for MPI / ELAN users.

**Comment by susanodd** [comment]
@rem0g the urls that take the dataset ID and gloss ID are checked syntactically by Django.

I'm not sure if the one that's live is doing that. I tried to use it on my local iCloud signbank without the syntax description in the url (the \d+ part of the parameter) and the server didn't recognise the url at all.
Without the \d+ then the server itself gives an error that the page is not found. (So like if you put 'ff' as the dataset ID.)
I had coded it so that it just returned an empty result. (To be gracious.)

So the code itself checks for lots of things for the api versions.
The url that will upload and unzip a video archive has ever more checks on the input.
It returns error messages if the zip file has problems.

I'll document this, of course.

**Comment by rem0g** [comment]
For viewing videos without Inweb i am using alternative method to fetch video with CRSF token in header, but i am getting errors Signbank server doesnt have CORS policy. 

Can you add our server on the list for CORS policy? The address can be requested at my mailaddress of via my Inbox.

**Comment by susanodd** [comment]
> For viewing videos without Inweb i am using alternative method to fetch video with CRSF token in header, but i am getting errors Signbank server doesnt have CORS policy.
> 
> Can you add our server on the list for CORS policy? The address can be requested at my mailaddress of via my Inbox.

I'll ask @Woseseltops about that. We may need permission from the CNCZ computing services.

**Comment by susanodd** [comment]
@rem0g I added a url argument `extended_fields` to the (zipped) package functionality.

(This is ignored if the user is not logged in.)

This is available on the production server signbank now.

**Comment by susanodd** [comment]
> When logged in and downloading the package (/dictionary/package/ ) those 15 fields are still missing, for example orientation is nowhere to be found.
> 
> > Do you want it to return fields with empty values as well?
> > Because of the size, I only included fields that are non-empty.
> 
> Only include when they are defined.
> 
> The results are same whether i am logged in / not logged in.

The url argument `extended_fields=true` now yields all the fields in the zipped glosses.json file.

**Comment by susanodd** [comment]
> For viewing videos without Inweb i am using alternative method to fetch video with CRSF token in header, but i am getting errors Signbank server doesnt have CORS policy.
> 
> Can you add our server on the list for CORS policy? The address can be requested at my mailaddress of via my Inbox.

Yes, it's possible to do this inside the container. This needs to be done in the Apache settings.
I'll wait until @Woseseltops is here on Thursday.

**Comment by susanodd** [comment]
@Woseseltops here here!

**Comment by rem0g** [comment]
I would like to request a feature. 

When one or more fields of the gloss has been changed, call a webhook related to the dataset. 
For example if a user change field entry of ELEPHANT, then submit the form. A webhook will the be initiated and a new updated data will be send to registered webhook(s) related to the dataset. Which it would be signCollect.net/webhook for example. 

It would improve the sync between signcollect and signbank, it feels better than check and update the databse hourly which can lead to outdated data. Or signcollect has to request everytime the signbank API when a user updates the fields in signcollect.

**Comment by susanodd** [comment]
> I would like to request a feature.
> 
> When one or more fields of the gloss has been changed, call a webhook related to the dataset. For example if a user change field entry of ELEPHANT, then submit the form. A webhook will the be initiated and a new updated data will be send to registered webhook(s) related to the dataset. Which it would be signCollect.net/webhook for example.
> 
> It would improve the sync between signcollect and signbank, it feels better than check and update the databse hourly which can lead to outdated data. Or signcollect has to request everytime the signbank API when a user updates the fields in signcollect.

That's a nice idea. I need to figure out how to implement it. :)

**Comment by rem0g** [comment]
Ok, cant wait to test that out.

**Comment by susanodd** [comment]
> For viewing videos without Inweb i am using alternative method to fetch video with CRSF token in header, but i am getting errors Signbank server doesnt have CORS policy.
> 
> Can you add our server on the list for CORS policy? The address can be requested at my mailaddress of via my Inbox.

This is turned on now for signbank-dev !

The upload api is in a pull request awaiting approval from @Woseseltops so it's not on signbank-dev yet, 
but the `dictionary/info` one works.

**Comment by susanodd** [comment]
@rem0g CORS is turned on for signbank now.

**Comment by susanodd** [comment]
The signbank-dev database was updated to match signbank as of this morning. So the glosses of Oefen animals are now in NGT as on signbank.

**Comment by rem0g** [comment]
Ok great. What is the timeline to add glosses via API? And has document been updated to upload videos via the api with explainatiom how to do it? 

Thanks

**Comment by susanodd** [comment]
I haven't worked on "add gloss" yet. Just the importing videos.
I'll expand the wiki for the videos.
That code is complete now.
It's on branch `api_interface`.
I'll switch signbank-dev to that branc (tomorrow). (I didn't want to do it at the end of the day today.)

We have basic routines from the CSV imports, so I plan to adapt that code into api urls for individual glosses (rows).

**Comment by rem0g** [comment]
Ok, thank you. It would be Add/update glosses on all fields whether possible. Can you provide a date when that will be finished? End of this week or next week? We are going to work on glosses on Signcollect platform pretty soon, then it will handle all queries with Signbank.

**Comment by susanodd** [comment]
> Ok, thank you. It would be Add/update glosses on all fields if possible. Can you provide a date when that will be finished? End of this week or next week? We are going to work on glosses on Signcollect platform pretty soon, then it will handle all queries with Signbank.

End of next week is possibe. This week not. It took more time that expected with the import of videos to revise the command to work friendly with others. :)

**Comment by susanodd** [comment]
The Dataset Media Manager template is now on signbank-dev.

That works.

But I'm having trouble with allowing to upload a file on apache via the API command, on the server it complains that the zip file does not exist on my computer.

(This is the annoyance that we can't run apache on our own computers anymore, so can't fully test the code that needs a real server.)
(I spent the entire morning getting the Dataset Media Manager template to work on apache. Now this one doesn't work.)

**Comment by susanodd** [comment]
@rem0g I can test the API upload zip/ import uploaded videos now.

It works!!!

But I need to modify the returned paths to the videos since signbank is hard-coded in them instead of signbank-dev.

**Comment by susanodd** [comment]
@rem0g for creating glosses, are you able to make the various required fields in your POST request?
Can they be supplied to signbank in the url as arguments?
Or do you need some kind of json structure?

Here, I picked one of the ajax calls used in the Keywords mapping interface:

```
         $.ajax({
            url : url + "/dictionary/update/group_keywords/" + glossid,
            type: 'POST',
            data: { 'language': language,
                    'regroup': JSON.stringify(regroup),
                    'trans_id': JSON.stringify(trans_id),
                    'csrfmiddlewaretoken': csrf_token},
            datatype: "json",
            success : update_gloss_senses
         });
```

If I design the create url to follow that setup, then you can provide all the various fields (not the above, but for a create operation).
Then the signbank code will just look for the fields in data.

(I'll update the above example when I get farther along.)

Or otherwise, they'd be in the url.

**Comment by rem0g** [comment]
For now we could use crsf tolken, but i am hesitant to always keep using the token. It would be more preferable to use API token, because that can be retrached every time (in case of hack attack). 

POST request is not a problem, i assume CSV can be with POST formdata? And yes per gloss, and i would need all fields that can be processed by Django.

**Comment by susanodd** [comment]
Okay, I'm doing the create first. (Only five things.)

Yes, the CSV import has a clever form in it per gloss. I'm using that structure and reverse programming it. :)

**Comment by Woseseltops** [comment]
Hey @susanodd , great work with the wiki page. I've restructed a few things to make it more readable, and during this process, I noticed a few missing bits of info, which I've marked with `todo`... do you know what should be in these places?

Furthermore, some thoughts:
* The naming of the endpoints seems to be inconsistent: `get_gloss_data` and `get_field_data` has a verb, but `package` and `info` do not. I personally feel the option without verb is descriptive enough :)
* For the section 'updating_data', the standard in the world of APIs is to use `POST` instead of `GET`, to indicate that you're not reading but actually changing things. You could also consider `PUT` when creating new things. Using something other than `GET` has the added advantage that you can send a file along as an attachment, so you don't have to upload it to another server first ;) . See https://stackoverflow.com/questions/3938569/how-do-i-upload-a-file-with-metadata-using-a-rest-web-service

Let me know what you think!

**Comment by susanodd** [comment]
I have the method done now that checks whether a "create gloss" can be done. (There are 7 different possible error messages about the input parameters.)

I can make the actual create url to either succeed or to return error messages.
But that kind of ends up weird because if there are errors it can't return data in some of the success fields.
And I'm not sure how to structure the response. Do the errors need to be reported "per field" ?
Or just as "errors"?

The problem is, say, if the dataset parameter is wrong, then obviously it can't do anything else qua checking.
Then it needs to check that all the text parameters are non-empty and that all the correct languages are included.
This needs to be done for consistency of the database.
Then it also checks to make sure the annotation texts and lemma texts do not already exist.

I guess it can return an errors dictionary, with errors per field.

**Comment by susanodd** [comment]
Of course, the create api could just add suffixes to the annotations and lemmas if they already exist and create it anyway. (Just joking.)

**Comment by susanodd** [comment]
@rem0g The API url to create a gloss is finished.

But it's on branch csv_enhancement, not on api_interface.

The code for uploading videos is a pull request and is on signbank-dev and is still awaiting review.
There are 1449 lines of code to review.

So I put the API create gloss url on a different branch and it has its own pull request.

**Comment by susanodd** [comment]
@rem0g I made it so the ajax data looks like the dictionary that the CSV uses:

data: { 'Dataset': 'NGT',
            'Lemma ID Gloss (Dutch)': 'BLAUW',
           'Lemma ID Gloss (English)': 'BLUE',
           'Annotation ID Gloss (Dutch)': 'BLAUW',
           'Annotation ID Gloss (English)': 'BLUE'
          }

**Comment by susanodd** [comment]
@rem0g the above ajax url `/dictionary/api_create_gloss/5` is on `signbank` as well as on `signbank-dev`.

**Comment by susanodd** [comment]
@rem0g the url to create a gloss (shown in the wiki now) does not require the csrf token anymore.

**Comment by rem0g** [comment]
I have spend three hours to get the create gloss working and unfortunately its all wasted because:
1. with POST and GET i get varying results
2. it requires CSRF token

Please prodivde clear instructions (AJAX POST for example) to get it working.

**Comment by rem0g** [comment]
With https://signbank.cls.ru.nl/dictionary/api_create_gloss/5/ i am getting {} as response

With https://signbank.cls.ru.nl/dictionary/api_create_gloss/5 i am getting CSRF Token Error

**Comment by rem0g** [comment]
```
  var url = "https://signbank.cls.ru.nl";
    $.ajax({
      url: url + "/dictionary/api_create_gloss/5/",
      type: 'POST',
      data: {
        'Dataset': 'NGT',
        'Lemma ID Gloss (Dutch)': '`${glos}`',
        'Lemma ID Gloss (English)': '`${glos}`',
        'Annotation ID Gloss (Dutch)': '`${glos}`',
        'Annotation ID Gloss (English)': '`${glos}`',
      },
      datatype: "json",
      async: false,
      success: function (data) {
        console.log(data);

  }
```

With this one i am getting {} as response

**Comment by susanodd** [comment]
On signbank or signbank-dev ?

If not on signbank, can you try it on signbank?

(Signbank has the newest code, including the fix for csrf token. I need to check whether I pulled this to signbank-dev, which is on branch api_interface. Since I've been trying to add the api token, I may have not pulled it to signbank-dev yet, because there are bugs in setting up the new token.)

Otherwise, I need to check it on the master branch (signbank always has the master branch.)

**Comment by rem0g** [comment]
I have tried it on the main website https://signbank.cls.ru.nl

**Comment by susanodd** [comment]
Okay, I'll investigate.

There is a page for testing it:

https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/

You only need to be logged in, have change dataset permission, and change gloss permission.
(So it should work.)

The code in that template calls the above ajax code.

The template is dictionary/virtual_machine_api.html
and the javascript to handle the call is inside the template.

It should only return {} if the permissions are not okay.

**Comment by rem0g** [comment]
My permissions are: NGT, Oefen at Change Permission. It doesnt define dataset or gloss at my profile. 

I am getting "You dont have permission to use the test command" error.

**Comment by rem0g** [comment]
For the permissions to work i would need to have CSRF token in the POST data, right? 

That means the $.ajax code example will not work

**Comment by susanodd** [comment]
No, it shouldn't be necessary. Although, that is in that example template. (I'll try removing it.)

The example template (as it is, on dataset tstMH does work okay.)

![create-gloss-blue-tstMH](https://github.com/Signbank/Global-signbank/assets/24272544/220eb956-9519-4747-a9e0-6994d787ebe0)

The example template does a "pre" setup of ajax, so the parameters shown in the ajax call do not include it.

This part of the javascript:
```
$(document).ready(function(){
    // setup required for Ajax POST
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        crossDomain: false, // obviates need for sameOrigin test
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
});
```

(I'll try removing it. That was before @Woseseltops said to add the `@csrf_exempt` to the method.

(But your code should not need that bit of code.)

**Comment by susanodd** [comment]
Maybe we need to set up the crossDomain to true somewhere? (Like as the csrf exempt, perhaps there is another setting.)

**Comment by susanodd** [comment]
I can find things related to this, but I'm not sure if this needs to be in Apache (as for CORS) or middleware (Django setup).
It looks like it needs to be in the Http communication. But generally, Django does this. We only need to code JsonResponse (a predefined Django class.)

**Comment by rem0g** [comment]
At https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ i am still getting permission error with all possible permissions enabled.

**Comment by susanodd** [comment]
I just checked. You're in group Guest. :(

**Comment by uklomp** [comment]
![image](https://github.com/Signbank/Global-signbank/assets/147159596/4deccf7f-6912-4fe2-a2ba-dc0287e00696)

@susanodd let me know what to change otherwise!

**Comment by susanodd** [comment]
Yes, I checked. I added the view dataset permissions for NGT. (I'm not exactly sure when it uses the view one. The change one was set. And to be sure I set both variants of the view permission.)

**Comment by susanodd** [comment]
I removed that setup code and it works properly on master branch on my local machine.

I'll push that. (I don't know if Django behaves different if that code is there or not.)

**Comment by rem0g** [comment]
I am still getting permission denied unfortunately and Signbank doesnt respond anymore on the $.ajax code.

**Comment by susanodd** [comment]
Did you try logging out and closing all the signbank windows, etc. Then try logging in again and try the test template?

That should work to test your permissions.

**Comment by rem0g** [comment]
Yes, i did..

**Comment by susanodd** [comment]
Does the test template work? Or it doesn't work either?
I rebooted signbank.
Did you look at your Profile once logged in?
It should show that you have the permissions for NGT.

**Comment by rem0g** [comment]
https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ gives me permission error. 

I have looked at profile and it says i have permissions for: 

tstMH, Kata Kolok, NTS, CSL_Shanghai, NGT, VGT, BISINDO, LSFB, NGT-ns, IS_Whynot, LaSiMa, ASL, EmblemsNL, TSL, JSL, KSL, ZEI, ISL, IS_WFD1959, IS_WFD1971, IS_WFD1975, IS_WFD1979, IS_WFD2007, IS_2021, BaliHS, LSC, CARICOM, DRS, KS, Oefen

**Comment by rem0g** [comment]
Change and view permission. 

I am still getting permission error, even after logging out and in and reset cache.

**Comment by susanodd** [comment]
Sorry, I have no idea. !!!

Is @Jetske there with you guys? Can she try it as herself?

**Comment by rem0g** [comment]
No problems. 
@Jetske can you solve this with us asap as this have priority on my list.

**Comment by Jetske** [comment]
@rem0g it looks like you might not have had 'change' permission yet. I just added it for you for NGT. Do you need this permission for more datasets?

**Comment by susanodd** [comment]
That's weird because I also added it.

**Comment by Jetske** [comment]
@susanodd I added it on the dataset manager page on Signbank, not in admin.

**Comment by Jetske** [comment]
@susanodd then maybe the permission was indeed already set right.. Can you try again @rem0g?

And would I be able to test it in a way without adding to the NGT dataset? It doesn't allow me to add something to the test dataset (tstMH).

**Comment by susanodd** [comment]
I just gave you permission for tstMH

**Comment by susanodd** [comment]
@Jetske I found the migration that didn't exist. You changed the ordering of Language.

I generated a migration for this (well, PyCharm did automatically as I'm modifying the UserProfile.)

**Comment by rem0g** [comment]
https://signbank.cls.ru.nl/dictionary/test_abstract_machine/1/ and https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ are both still giving me permission errors. 

Username is gotterspeer, so not remog for clarity.

**Comment by susanodd** [comment]
I guess I should also add Oefen. (Since we're busy creating stuff for testing purposes)

**Comment by rem0g** [comment]
Thank you, i am now getting this while using the $.ajax query from signCollect website: 
{errors: 'User is not Staff.'}

I am already logged in. 

However i do have access to https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ (/1/ and /5/) and with both i am successful able to create glos.

**Comment by susanodd** [comment]
Okay, it looks like out of haste I may have messed up the error message. :)

I see you created a sign blauw. :)

**Comment by rem0g** [comment]
Yes, but still we need to get the $.ajax to work with csrfmiddlewaretoken.

I await any instructions for that.

**Comment by susanodd** [comment]
Yes, I busy working on that. I am doing it in combination with adding an Affiliation (New kind of tag for users and glosses) that shows up in the User Profile. (Because I already need to update the User Profile with a token.)
Related to this, we had some database consistency problems. (Hopefully resolved. There was a change to the Language model in a different issue, but no migration was made, and Django refused to apply new migrations, e.g. that's why the Rest Framework could not be installed last week.)
(But then with @Woseseltops we decided to implement the token from scratch instead of relying on yet more external modules.
But then it turned out that even doing it from scratch could not migrate the database. Because of that missing migration. The issue to reorder the Senses so the Dutch is always first, that required a database migration.)

**Comment by rem0g** [comment]
I solved it using python as intermediary, the code: 

```
def create_gloss(dataset, lemma_id_gloss_dutch, lemma_id_gloss_english, annotation_id_gloss_dutch, annotation_id_gloss_english):
    url = "https://signbank.cls.ru.nl/dictionary/api_create_gloss/5/"
    cookies = {
        'cookie_notification': 'functional',
        'cookies_consent': '-1',
        'sessionid': '',
        'csrftoken': '',
    }
    data = {
        'Dataset': dataset,
        'Lemma ID Gloss (Dutch)': lemma_id_gloss_dutch,
        'Lemma ID Gloss (English)': lemma_id_gloss_english,
        'Annotation ID Gloss (Dutch)': annotation_id_gloss_dutch,
        'Annotation ID Gloss (English)': annotation_id_gloss_english
    }
    r = requests.post(url, cookies=cookies, data=data)
    return r.text
```

Cookies are definitely needed to send POST data which is not possible with jQuery due to obvious security reasons.  And for API connection we ultimately would need API key and we will use python as intermediary because i am not comfortable to expose CSRF/API token publicly in html source code. 


Are other fields like Handeness, Weak Hand, etc possible to insert altogether?

**Comment by rem0g** [comment]
I have tested to create gloss with additional fields, unfortunately those will not be accepted. 

What is the status of update glos? 

The tested fields in python: 

data = {
        'Dataset': 'NGT',
        'Lemma ID Gloss (Dutch)': glos,
        'Lemma ID Gloss (English)': glos_engels,
        'Annotation ID Gloss (Dutch)': gloss,
        'Annotation ID Gloss (English)': glos_engelss,
        "Senses: Dutch": senses,
        "Handedness": Handeness,
        "Strong Hand": strongHand,
        "Weak Hand": weakHand,
        "Handshape Change": HandshapeChange,
        "Relation Between Articulators": RelationArticulators,
        "Location": handLocation,
        "Relative Orientation: Movement": relativeOrienationMovement,
        "Relative Orientation: Location": relativeOrienationLocation,
        "Orientation Change": orientationChange,
        "Contact Type": ContactType,
        "Movement Shape": MovementShape,
        "Movement Direction": MovementDirection,
        "Virtual Object": virtualObjectt,
        "Phonology Other": phonologyOther,
        "Mouth Gesture": mouthGesture,
        "Mouthing": mouthing,
        "Phonetic Variation": phoneticVariation,
        "Repeated Movement": RepeatedMovement,
        "Alternating Movement": AlternatingMovement,
        "Semantic Field": thema,
    }
    
    The gloss: https://signbank.cls.ru.nl/dictionary/gloss/47356/
    
    @Woseseltops @Jetske I would be glad if i can additional assistance as I have feeling @susanodd is doing this all on her own.

**Comment by rem0g** [comment]
```
{
    "response": "{\"errors\": [\"Lemma translation for Dutch already exists.\", \"Lemma translation for English already exists.\", \"This annotation already exists for language Dutch: ACHTERLICHTEN\", \"This annotation already exists for language English: REAR-LIGHT\"], \"createstatus\": \"Failed\", \"glossid\": \"\"}"
}
```

It should return gloss ID of the existing gloss for callback.

**Comment by susanodd** [comment]
@rem0g quoted these fields which are available in the gloss info (wiki and CSV):

data = {
        'Dataset': 'NGT',
        'Lemma ID Gloss (Dutch)': glos,
        'Lemma ID Gloss (English)': glos_engels,
        'Annotation ID Gloss (Dutch)': gloss,
        'Annotation ID Gloss (English)': glos_engelss,
        "Senses: Dutch": senses,
        "Handedness": Handeness,
        "Strong Hand": strongHand,
        "Weak Hand": weakHand,
        "Handshape Change": HandshapeChange,
        "Relation Between Articulators": RelationArticulators,
        "Location": handLocation,
        "Relative Orientation: Movement": relativeOrienationMovement,
        "Relative Orientation: Location": relativeOrienationLocation,
        "Orientation Change": orientationChange,
        "Contact Type": ContactType,
        "Movement Shape": MovementShape,
        "Movement Direction": MovementDirection,
        "Virtual Object": virtualObjectt,
        "Phonology Other": phonologyOther,
        "Mouth Gesture": mouthGesture,
        "Mouthing": mouthing,
        "Phonetic Variation": phoneticVariation,
        "Repeated Movement": RepeatedMovement,
        "Alternating Movement": AlternatingMovement,
        "Semantic Field": thema,
    }
    
These are actually exactly the headings you can Update in the CSV Update.

Is it possible for you to just create a CSV file for the updates?

Yes, I can implement this, as described in a different issue. (I intend to do this as part of code improvement for CSV processing. Abstract Machine stuff. Just because the CSV code is kind of unreadable.

But it seems a bit over-the-top to keep duplicating all the functionality of Signbank using urls instead of using Signbank.
This will also require excessive error processing for each url. (Duplicate of the CSV error processing.)

We had to deal with a consistency problem on the global database. (Due to a missing migration.)
Using more and more API commands will likely increase the risk of database constraint violation. (I.e., if one transaction has not completed before the subsequent request.)
The CSV Update processes per row, sequentially.
(Because Signbank would not be controlling when the API calls come in, this could go very wrong.)

Because SQLite is underneath Signbank, the entire database is locked when one gloss is updated. So this could have a detrimental or uncontrolled effect on normal users of Signbank if there are lots of API calls interspersed.

There is an (old) issue to port Signbank to MySQL but that is on a back burner. @Woseseltops was working on that.

**Comment by susanodd** [comment]
> ```
> {
>     "response": "{\"errors\": [\"Lemma translation for Dutch already exists.\", \"Lemma translation for English already exists.\", \"This annotation already exists for language Dutch: ACHTERLICHTEN\", \"This annotation already exists for language English: REAR-LIGHT\"], \"createstatus\": \"Failed\", \"glossid\": \"\"}"
> }
> ```
> 
> 
>      
>   
> 
> It should return gloss ID of the existing gloss for callback.

The above iis a result of Create Gloss.

The Gloss could not be created because something is wrong with the Lemma fields provided.
(You were trying to create a gloss that already exists, or trying to use lemmas that already exist.)

Do you want it to be something like "get_or_create" ?

(It is not this semantics, because if you are trying to create a "different" gloss, then the input is wrong. Like you need to add a "-B" or something.)

**Comment by rem0g** [comment]
CSV is not my preferable method, it should be done via API as stated in the original requirement.

https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ do have only those four fields and can you extend the fields as per my previous message? I imagine by extending the fields it shouldnt be time consuming.

Thanks.

**Comment by susanodd** [comment]
> CSV is not my preferable method, it should be done via API as stated in the original requirement.
> 
> https://signbank.cls.ru.nl/dictionary/test_abstract_machine/5/ do have only those four fields and can you extend the fields as per my previous message? I imagine by extending the fields it shouldnt be time consuming.
> 
> Thanks.

Yes, that's my plan!!

It's taking longer because I have been working on some of the other issues. I'm making Affiliation tags. That seems important because @uklomp wants the glosses to automatically have affiliation tags when created.
That is more or less done, except for displaying them to look nice.

**Comment by rem0g** [comment]
We are going to start with sC pretty soon so that would be lower priority, the high priority is create and update gloss via API. 

I have asked Ulrika to task your colleagues to work on the API and the underlying foundations too.

**Comment by susanodd** [comment]
@rem0g Branch `api_interface` is working on `signbank-dev` again.

If you want to test things with your own development work, it's best to use that one instead of the production server.

I made the wiki read urls available on the production server, since otherwise you won't see proper video links.

I'll get back to working on the update url.

**Comment by rem0g** [comment]
What would be the link of Signbank-dev?

**Comment by rem0g** [comment]
Any update about this?

**Comment by susanodd** [comment]
@Woseseltops is working on the API tokens.

**Comment by susanodd** [comment]
> What would be the link of Signbank-dev?

@rem0g It's the same as for signbank, but as signbank-dev instead.

I think @Jetske already sent that to you.

The template for testing the update gloss api is available on all the signbanks now. (It's on master.)

At the moment, we made it so only we can use it since it's only for testing and not meant to be used by end users.

It's the same idea as the gloss create testing template.

The API token is still not implemented. A bit of confusion here about who will code it.

Do you wish to be able to use the testing template for the gloss update?
It's not very interesting. I used it to test that the case-insensitive works and the multiselect fields work.
It's multilingual. That's the new thing. (But you need to have the interface language set, as for normal signbank commands.)
We needed it to be able to simulate the API calls while being logged in to Signbank.
@Jetske is working on the senses update. That will be added to the same template.

**Comment by susanodd** [comment]
Can this be closed? It looks like everything has been implemented as this original issue specifies. Other issues have extended this.
