### ISSUE TITLE
Two new panels / uitklapvensters

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1168]
We want to have two new fields / uitklapvensters when we open a sign's entry / when we see the gloss details. 
One above morphology, titled "Video's met non-manuele elementen" (see issue #1169)
and one between "notes" and "other media", titled "Voorbeeldzinnen" (see issue #1178)

The order of all the fields will then be (in Dutch):
Video's met non-manuele elementen
Morfologie
Fonologie
....
Aantekeningen
Voorbeeldzinnen
Andere media

**Comment by susanodd** [comment]
@uklomp for the new fields, if you know whether it will be a choice list or a text field, etc. that is needed in order to implement a database migration for the Gloss. And if the choice is used, that will be added to the Field Choices (The name of whatever the thing is of which there are choices for). Then in the admin, you will be able to add the actual choices.
If the field needs to be a structure (mini table) then a class can be made with the extra information for the field.

We can just make straight text fields to start, then you can fill in information and see if that is sufficient.

(An analogy would be say, Creator, which is then a user object that has first name, last name, and username.)

**Comment by susanodd** [comment]
For the videos, there can be a list of names or abbreviations that we can use in the code.

Think about when you upload such a video, if you need to be able to select what type of video it is, say.

nme
me

(are there particular abbreviations in use?)

**Comment by uklomp** [comment]
> @uklomp for the new fields, if you know whether it will be a choice list or a text field, etc. that is needed in order to implement a database migration for the Gloss. And if the choice is used, that will be added to the Field Choices (The name of whatever the thing is of which there are choices for). Then in the admin, you will be able to add the actual choices. If the field needs to be a structure (mini table) then a class can be made with the extra information for the field.
> 
> We can just make straight text fields to start, then you can fill in information and see if that is sufficient.
> 
> (An analogy would be say, Creator, which is then a user object that has first name, last name, and username.)

Are we talking about the same kind of 'fields' now? Because for issue 1169, I know that I'm requesting text fields under the video, and then this question applies. I will get back to that.

But in this general issue 1168, I don't mean fields that way. I mean the grey panels. I didn't know what it was called. So the panels we have now for phonology etc, this request is meant to add two more of those panels.
