### ISSUE TITLE
Signbank Wiki Api since_timestamp needs more explaination

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1177]
I expect since_timestamp at dictionary/package/ to be created after, but apparently it stands for updated since? I am getting different results from search query and the API endpoint when applying timestamp of 1 januarry 2024.

I have updated the wiki with explaination to add unix timestamp in seconds.

**Comment by susanodd** [comment]
Oh, I just looked at it. That's epoch format is awful looking.

**Comment by susanodd** [comment]
@rem0g do you need a different format for the since timestamp input?

I can add some additional options.

I noticed in the signbank admin that it actually records lots of things as version management. When you open the admin as yourself, it shows a long list of recent commands in the first page.
We keep an update history for the glosses. But it's with string fields, not objects for the updates. Only the gloss is an object.
You can see this in the Revision History panel of the gloss view.

The since timestamp seems to be for creation. Also in the Search panels. But Django does seem to keep track of things behind the scenes. I haven't tried doing anything with that. But you can see it in the Admin.

**Comment by rem0g** [comment]
Where can i access the signbank admin? I only see Profile and Logout.

**Comment by rem0g** [comment]
@Woseseltops @susanodd @Jetske any response to my question would be appreciated. My question about since_timestamp is not answered aswell.

**Comment by susanodd** [comment]
> Where can i access the signbank admin? I only see Profile and Logout.

This is via a different url, not via your profile.

We should not post the link on GitHub to avoid security risks. (University computing services who owns the infrastructure,
they get friendly hackers that keep trying to break in across the RU network and alert them to vulnerabilities. This has happened before. They try code injection. Signbank is open source, but the server itself has some different settings than those published in the code.)

Normally nobody needs to access the admin. The dataset manager can grant access via the Manage Datasets page in the menus.
If you need particular information that the admin stores then make a new isuses to suggest making this available.
It's dangerous to do things in the admin. It's basically all the "object tables". This is mega-huge and it is extremely slow to view things. It's not possible to update glosses there. It's only useful for checking the code if something is broken. For example, video paths.
You shouldn't need to look in the admin for anything.

**Comment by susanodd** [comment]
@rem0g if you go to View Available Datasets then choose for example NGT,
on the NGT page there are links (for the dataset manager) to Manage Media and Corpus Overview.
Those are specific pages for the dataset.
The Manage Media page is where you can upload the zip archives of videos.
There is a zip file from @ocrasborn for NGT videos he wanted imported.
You can view the contents of the zip file there.

You can try this out for Oefen with some examples to see how it works.
It's the same as the zip file import in the wiki, but here the feedback is easier to follow.
You can do this on signbank-dev too.
(I uploaded onno's NGT zip there too, while developing the code. I didn't finish importing all the videos on signbank-dev, so some are still visible in the import folder there. That's the development server.)
I'd advise to try things out on Oefen so then you're the only one doing stuff in that database.
We (@Jetske, @Woseseltops , @susanodd ) test things out on signbank-dev, so sometimes we edit glosses because we need to have data for testing. But normally we just do stuff in tstMH.)
(So you can keep using Oefen for your own work to test out your commands.)

**Comment by Woseseltops** [comment]
Just noticed I missed this issue earlier, apologies. Some replies to @rem0g in short form:

> Where can i access the signbank admin? I only see Profile and Logout.

At the moment you don't have access there. I believe, at least for this issue, it isn't needed, let me know if you feel otherwise.

> I expect since_timestamp at dictionary/package/ to be created after, but apparently it stands for updated since

The idea was that, every time you start ELAN, it would load all (relevant) Signbank videos... but to prevent this from being a huge download every time, you can also request only the changes since last time you downloaded. For that reason, I would expect changes and not creations... do you feel this needs to be better explained on the wiki?

**Comment by rem0g** [comment]
No problem!  And yes the wiki should be better explained what to expect from the API retrieval URL,  Also an explaination is missing.  

I will check if creations are also added besides the changes, because that would be helpful in reducing waiting times every time we want to update the JSON file.

**Comment by Woseseltops** [comment]
Okay, added a few lines. Feel free to close this issue if satisfied.

**Comment by susanodd** [comment]
> No problem! And yes the wiki should be better explained what to expect from the API retrieval URL, Also an example how to use is missing.
> 
> I will check if creations are also added besides the changes, because that would be helpful in reducing waiting times every time we want to update the JSON file.

@rem0g you can try testing how best to retrieve the recent changes (in an alternative way as well)?
For a test gloss, try updating all the various kinds of fields, then look in the Revision History panel to see/confirm what has been stored. If updates to any kinds of fields have not been stored, but you need this kind of update data, we can add more kinds to the revision history.

An additional API function could be added to retrieve specific kinds of recent gloss updates. I'm not sure to what extent you are setting fields/updates before putting a gloss onto Signbank. Or if after creation, you want to obtain updates every day? Or on demand when displayed? (What is the normal time you are using or want to use?)

(To reduce overhead for both sides. The "download" retrieves an extreme amount of data. If you keep needing to retrieve all of this over and over again it seems inefficient. We can also search in the GlossVideoHistory and GlossRevisionHistory based on timestamp. We have not done this before, but there is data here. Maybe some more complex kinds of queries for the Dataset Manager to check for particular time-sensitive time-dependent updates. As suggested in #1216 with tags.)
