### ISSUE TITLE
Stay in edit mode after adding a sense

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1185]
A colleague and me are in the process of adding multiple (groups of) senses to signs. When we added a new sense, the edit mode turns off and we need to click 'edit' again before we can add another sense. We'd like to stay in the edit mode after adding a sense.

We think automatically turning off edit mode is because of safety or something like that, but when we work on the phonology, we also are still in edit mode after changing a feature, so we're used to staying in edit mode while working on a sign, and are fine with explicitly clicking 'turn off edit mode'.

**Comment by susanodd** [comment]
Fyi, we had problems with staying in edit mode because senses can be reordered. 
The number of the sense is not a field of the sense and is calculated dynamically.
This can cause the transaction to fail if you keep editing instead of letting it complete.

**Comment by uklomp** [comment]
So, we should not want it?

**Comment by Jetske** [comment]
@susanodd because after adding/editing senses it does a reload of the page, I assume it doesn't make a difference for the sense ordering if it's then redirected to the gloss detail page in edit mode or not.

**Comment by susanodd** [comment]
Okay, that seems okay. There are other things done on a save because the numbering is via a signal. It also can return error messages. I don't recall if the error messages show up in Edit mode? (They sometimes hide things because they are just below the menu bar stuff. I know they can hide the scroll bar. The code that does all the repositioning is difficult to read.)

**Comment by Jetske** [comment]
@susanodd The tests still run OK and I see messages appear, so that looks alright :)
