### ISSUE TITLE
Implement authentication token for the API

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1187]
Related to #1152 

Discussion with @susanodd today. We decided on these things:
* One user will be able to generate multiple tokens
* For each token, they can specify the scope, which can be one or multiple datasets
* We want the tokens to expire after a while
* There should be a button in the profile. Once you generate it, it should say 'copy paste, you will never see this token again'
* There should a maximum of tokens the user can generate (maybe a setting)

**Comment by Woseseltops** [comment]
@susanodd, to make a view accessible as API endpoint:
* Use the Django decorator `@csrf_exempt`
* Get the token out of the request header

**Comment by susanodd** [comment]
@Woseseltops I'm having trouble creating the tokens. I need an appropriate example. 99 percent of all the web documentation turns out to be the Rest framework. And the searching gets worse when you add "without rest framework" or "not using rest framework". I tried adding Python 3.12 to it, since it's not supported by rest. I've been searching for 2 hours now.

**Comment by susanodd** [comment]
@Woseseltops this is separate from the previous paragraph.
I won't migrate the database using the auth_token.
Does this not work with Python 3.12 either?

`django.db.utils.DatabaseError: database disk image is malformed`

**Comment by susanodd** [comment]
@Woseseltops (read the above first). How to solve this?
Can we put the IP address of UvA in allowed servers in the apache settings?

The alternative is to implement the tokens from scratch.

**Comment by susanodd** [comment]
[OLD SCHOOL]

The token will be created by hand using old methods of creating keys for this.

I'm working on the session variable for dark mode (#1166).

I'm wondering:

When we create such a token for the API, isn't the actual "token" going to be visible in the calls to signbank from outside of signbank? (Session communication with the server.)
What's to stop spies from just listening in and grabbing the token?

This is what I was trying to ask on Friday @Woseseltops : is the "streaming" done on the (Rest) tokens done in order to make  the communicated tokens not be "visible" in their entirety to aliens trying to monitor communication to Signbank?

(Or do we need to encrypt them as well? Like for passwords.)

(This is not a nonsense question, the Google analytics records the communication, see the old issue about website statistics.)

**Comment by susanodd** [comment]
I made a first go at this, by creating a class for the tokens and accessing them in the User Profile.

But I am not the right person to code the creation and employment of these keys in the API communication.

@Woseseltops according to @Woseseltops has lots of experience using API tokens.

**Comment by Woseseltops** [comment]
Hey @susanodd , I read you were hoping I'd do this one! I'll start with how I would approach this one; perhaps once you see the design, you'll be faster actually implementing it, but we'll see :) .

Phase 1: have an auth token Django model. Once you create it, it automatically generates content like this:

```python
def generate_auth_token(length=16):
    """Generate a random authentication token."""
    alphabet = string.ascii_letters + string.digits
    return ''.join(secrets.choice(alphabet) for _ in range(length))
```

but it only stores the hash of this content

```python
def hash_token(token):
    """Hash the token using SHA-256."""
    hash_object = hashlib.sha256(token.encode())
    return hash_object.hexdigest()
```

You can store this like a normal Django model field. Furthermore, this token model stores who generated it, its expiration date, and (like we discussed) the scope, ie which datasets.

Phase 2: have a button on the user profile to generate such a token, and show the content only once.
Phase 3: add to the profile the number of active tokens for this user.
Phase 4: create a local script to send requests encrypted with the token. Should be something like this:

```python
import requests

def make_api_call(url, auth_token):
    headers = {
        'Authorization': f'Bearer {auth_token}',
        'Content-Type': 'application/json'  # Modify according to your API requirements
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()  # Raise an exception for HTTP errors (status codes 4xx, 5xx)
        return response.json()  # Assuming the response is in JSON format
    except requests.exceptions.RequestException as e:
        print(f"Error making API call: {e}")
        return None

# Example usage:
if __name__ == "__main__":
    url = 'https://api.example.com/data'  # Replace with your API endpoint
    auth_token = 'your_auth_token_here'  # Replace with your authentication token
    response_data = make_api_call(url, auth_token)
    
    if response_data:
        print("API call successful!")
        print("Response data:", response_data)
    else:
        print("API call failed.")
```

Phase 5: create a test API endpoint (view) with the decorator mentioned above, that as a first check verifies that a token with the same hash exists in our database.

```python
auth_token = request.headers.get('Authorization', '').split('Bearer ')[-1]
hashed_token = hash_token(auth_token)
```

If this works, this check should be added to all views.

**Comment by Woseseltops** [comment]
I also suggest yes, but it doesn't really matter :)

**Comment by uklomp** [comment]
Hi @Woseseltops , it's correct that you're waiting for Susan to implement this code, right? Or is this code for Gomer? In the meeting that I had with Susan, it seemed she was not sure about how to proceed. She knows by the way I'm asking about this :)

**Comment by susanodd** [comment]
I'm working on this now.

**Comment by susanodd** [comment]
This is on signbank-susan

I forgot how I set the CORS on the other servers.
It's still giving the error above.

@Woseseltops how to do this?

**Comment by susanodd** [comment]
Doesn't this defeat the purpose of using an API?

**Comment by susanodd** [comment]
Ouch! It gets past the API token now. I removed the method guardian permission checks because it was giving an error that no permission to change the dataset.

But now, it won't let it do an update because it says the user is anonymous.
`
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7b2a21e846b0>`

So basically, with the CORS and API token, it doesn't correctly determine the "Django user".

The code needs to be debugged on the actual apache server, because it can't run on PyCharm runserver.

We need to know who the user is that is using the API token in order to check permissions and allow the update/creation of a gloss. Also, this needs to be stored when the new gloss is saved.

**Comment by susanodd** [comment]
This still isn't working. The data is being ignored.

Do we have a plan B for this?

**Comment by susanodd** [comment]
1. What is worrying about this, the token appears unencrypted in the header. (As shown above in the code.)

Do we need something like this for sign collect to restrict usage?

```
CORS_ORIGIN_WHITELIST = (
    'google.com',
    'hostname.example.com',
    'localhost:8000',
    '127.0.0.1:9000'
)
```

2. The examples still aren't passing the data to Django. But it manages to process the API token successfully.

[So is the issue completed? The API token is implemented. We just don't know how to use it correctly. @Jetske assisted for several hours yesterday and we still couldn't get it to retrieve the data from the request.]

**Comment by susanodd** [comment]
> Okay annoying that the CORS module is not helping :( . I thought about this some more, and came to the conclusion is that the Signbank API might not need allow for CORS, as it will typically not be called from a browser. What if you do step 4 with Python, like the proposed example script above?

This initially had something to do with the order of declaration of the various parts in the settings file. The cors declaratives need to be before the signbank declaratives.

@Jetske and @susanodd spent today getting the create gloss api call to work. Some idiosyncratic naming conventions.

What remains is to rewrite the token generation to allow multiple datasets per token for the user profile page.

The Wiki needs to be updated to show the usage of the tokens, including the syntax.

**Comment by susanodd** [comment]
I'm working on the code to create the tokens, where as described above the token can be for multiple datasets.

How would such a token be used?

There is a multi-select for choosing the datasets before creating a token.

Suppose the user already has one token for datasets A and B.

What happens for the user when they select to create a token for just dataset A ?

This also seems a bit contradictory because when the user uses the API token, the user is determined and permission checks for the particular dataset are done in the normal way.
Is it redundant to have the token be for multiple datasets when the guardian permission checks will be done anyway?

**Comment by susanodd** [comment]
@vanlummelhuizen somebody is definitely trying to access stuff.

```
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:55 +0200] "GET /form.html HTTP/1.1" 302 929 "-" "curl/8.1.2"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:56 +0200] "GET /upl.php HTTP/1.1" 302 925 "-" "Mozilla/5.0"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:56 +0200] "\x16\x03\x01" 400 922 "-" "-"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:56 +0200] "GET /geoip/ HTTP/1.1" 302 923 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:57 +0200] "GET /favicon.ico HTTP/1.1" 302 933 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:57 +0200] "GET /1.php HTTP/1.1" 302 921 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:57 +0200] "GET /bundle.js HTTP/1.1" 302 929 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:48:58 +0200] "GET /files/ HTTP/1.1" 302 923 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:49:08 +0200] "GET /password.php HTTP/1.1" 302 935 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.233.155.168 etc.cls.ru.nl - - [02/May/2024:11:49:08 +0200] "GET /info.php HTTP/1.1" 302 927 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

None of those things exist on the site.
Can you complain to CNCZ? They ought to block whoever/whatever that IP is.

**Comment by susanodd** [comment]
And this:

```
104.47.2.254 etc.cls.ru.nl - - [02/May/2024:09:37:54 +0200] "HEAD /submitted/Dossier_-.pdf HTTP/1.1" 302 763 "-" "-"
104.47.2.254 etc.cls.ru.nl - - [02/May/2024:09:37:54 +0200] "HEAD /submitted/Dossier_-.pdf HTTP/1.1" 403 3981 "-" "-"
104.47.1.254 etc.cls.ru.nl - - [02/May/2024:09:37:55 +0200] "HEAD /submitted/Dossier_-.pdf HTTP/1.1" 302 763 "-" "-"
104.47.1.254 etc.cls.ru.nl - - [02/May/2024:09:37:56 +0200] "HEAD /submitted/Dossier_-.pdf HTTP/1.1" 403 3980 "-" "-"
```

Maybe that was you trying to view the file in the link?

**Comment by susanodd** [comment]
@Woseseltops I added the ajax call for creating a gloss to the wiki.
Only the first fields can be in the data for creation. (Dataset....Senses) The others need to be in an update once the gloss is created.

There is an example html file (without Django) in the pull request. 
`virtual_machine_api_test_token.html`  (see the pull request files)
You only need to put your own token in.
This is set up for the test dataset on signbank-dev.
This file needs to be with `file://` in your own browser.

**Comment by Woseseltops** [comment]
Clear, thanks @susanodd . For completeness, I believe that Signbank's API will mostly be called from Python.

Now that the token is implemented, what endpoints already require authentication? If you could list it here, I'll make sure to add this info to the wiki somehow.

**Comment by susanodd** [comment]
Okay, great. The wiki got a bit out of hand as four of us have worked on it.
Is it necessary to also add the API token to the read urls? It has only been added to the update ones.
All of the functionality is multilingual now. But the ones that take the "headers" get the language there, if provided, otherwise English is the default.
The original retrieval urls look at the language code provided by Django. (That was causing problems with the API token because it said the data in the ajax call was being fetched multiple times and it can only be fetched once. That is probably Django that does this. So I moved the language into the header.)

The wiki has become partly onoverzichtelijk because it has been written over several months, as more functionality became available.

**Comment by Woseseltops** [comment]
> Is it necessary to also add the API token to the read urls? It has only been added to the update ones.

I think so! Divya is using the `getLexiconIdentifications` end point, but she only ever gets `[NGT]` regardless of token.

**Comment by susanodd** [comment]
Okay.

I'm working on the update gloss to change lemma and annotation translations (#1243) at the moment.

**Comment by susanodd** [comment]
> > Is it necessary to also add the API token to the read urls? It has only been added to the update ones.
> 
> I think so! Divya is using the `getLexiconIdentifications` end point, but she only ever gets `[NGT]` regardless of token.

Where is this endpoint?

I added the token to the retrieval functions, but not yet to "package" or "info". (I'm not sure how people are calling those, since they are the original urls from before we started making an API. The package and info take parameters in the URL as GET. The new ones are POST.)

**Comment by Woseseltops** [comment]
It was dictionary/info, it's the function called `info()` in `dictionary/views.py`. Right now, ELAN authenticates the 'browser' way with credentials. I suggest to keep supporting this authentication method for a while in addition to the (not yet implemented) token, at least for this end point, so we're not forcing the ELAN devs to make changes. If we really do want to stop supporting the old auth, we should discuss with Divya.

**Comment by susanodd** [comment]
We can do both. The other API urls that are new support both. If the token is not found, it checks the normal way.
I can modify the original ones to do it this way. (This was needed to facilitate using the LANGUAGE.)
For info this will work, but the zip retrieval uses url parameters, not POST
