### ISSUE TITLE
When editing the index of notes, the UI overlaps

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1199]
Discovered by Julie from the ASL Signbank:

![image](https://github.com/Signbank/Global-signbank/assets/1909317/200c4684-85db-4d94-801b-77672761f697)

Annoyingly, if you try to debug this in the Chrome dev console, the overlapping buttons go away. Can be fixed by pausing script execution in the 'Sources' tab of the Chrome dev console.

**Comment by susanodd** [comment]
I'll look into this, since I'm fixing formatting issues in the dark option issue.
There's lots of problems with way too much code in the Gloss Detail template.
The columns are also messed up because some have dynamically more width necessary.
It looks like the column isn't wide enough so it's put it on top instead of underneath or to the right.
Maybe the width of the index field itself is too small or too wide, since it's just a toggle select thing. Then the save button isn't going to fit next to it.

**Comment by susanodd** [comment]
I tried setting this in the editable script as well as in the gloss_edit script to alter the input field that is created for the index.

It looks like its width is set so wide because it's a model field form for Integer. Probably the field type in models.py needs to be made into a small number field, or a byte field, it only needs 8 bits.
Then it should automatically be made smaller.

**Comment by susanodd** [comment]
@Woseseltops after quite a while of time has passed.

I put a console log in the gloss_edit_color.js code where it adds the new editable type for positiveinteger.

So the "input" has a width of circa 400 pixels.
And it's assigned the form class preview.
(This is used in Phonology for all the pull-down menus for field choices. It's that class preview that sets up how wide these lists are because they have to be opened and then the result of the selection is given to the ajax call for the field.)

So we probably can best solve it by splitting the edit panels so that "preview" class is only used for phonology.

Although I'm not sure. This field needs a different class assigned to its "form" object that surrounds the actual "input" field.
(The thing that keeps disappearing is the editable thing.)

**Comment by susanodd** [comment]
@Woseseltops I have it working now.
(It's Saturday.)

But there are still some weird column width problems in Gloss Detail View.
This is because everything is one giant table inside the right column.
And each panel has a different number of columns.
This causes some rows to force "other" rows to be stuck inside a too small or too wide column because of a different row.

I actually just skip over the 1000 lines used for one table row where senses are.

So I don't know if the width of some of those columns are causing other panels to have wrong sized columns.
Every panel seems to have hard-coded widths added to things to override the other rows messing with them.

I've made it so the Cancel and OK buttons are visible everywhere, and they don't cover up the actual input fields.
But on some they end up way to the right because of "other rows" width or column settings.
I suspect the browsers are not able to generate this dynamically with dynamic content in the columns.

**Comment by susanodd** [comment]
@Woseseltops the Gloss Edit and Morpheme Edit templates involve the code that needed to be updated for this issue.

It was in the specific Signbank editable routines. Both in the `jquery.editable.mini_colors.js` (specific for signbank with field choice colors) and in the setup in `gloss_edit_color.js` and `morpheme_edit_color.js`

Also, there was no field declaration in the Notes (DefinitionForm). This was causing some Django display issues since nothing was declared, no widget.

Those are all fixed now. Hopefully this translates to ASL!
