### ISSUE TITLE
Create Gloss via API must have all fields available

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1200]
Issue: I have tested to create gloss with additional fields, unfortunately those will not be accepted.  For now it only includes the first five fields.

The tested fields in python: 

```
data = {
        'Dataset': 'NGT',
        'Lemma ID Gloss (Dutch)': glos,
        'Lemma ID Gloss (English)': glos_engels,
        'Annotation ID Gloss (Dutch)': gloss,
        'Annotation ID Gloss (English)': glos_engelss,
        "Senses: Dutch": senses,
        "Handedness": Handeness,
        "Strong Hand": strongHand,
        "Weak Hand": weakHand,
        "Handshape Change": HandshapeChange,
        "Relation Between Articulators": RelationArticulators,
        "Location": handLocation,
        "Relative Orientation: Movement": relativeOrienationMovement,
        "Relative Orientation: Location": relativeOrienationLocation,
        "Orientation Change": orientationChange,
        "Contact Type": ContactType,
        "Movement Shape": MovementShape,
        "Movement Direction": MovementDirection,
        "Virtual Object": virtualObjectt,
        "Phonology Other": phonologyOther,
        "Mouth Gesture": mouthGesture,
        "Mouthing": mouthing,
        "Phonetic Variation": phoneticVariation,
        "Repeated Movement": RepeatedMovement,
        "Alternating Movement": AlternatingMovement,
        "Semantic Field": thema,
    }
    
```

**Comment by susanodd** [comment]
@rem0g this one is not possible.

Because there are many classes with foreign keys referencing each other it is not possible to add more fields to creation.
That needs to be done in an update, once the gloss, annotation id gloss, annotation id gloss translations, lemma, lemma translations OBJECTS have all been created for the new gloss.
Because, if anything goes wrong, those also need to be deleted.
The "other fields of the gloss" can also fail because the human input needs to be checked that it corresponds to a Field Choice OBJECT. Those also have constraints.

Any of these can fail so the create has to have been done successfully BEFORE can can update the objects.

The other command #1202 needs to be used instead.

**Comment by rem0g** [comment]
Ok, undersood. I am going to close this issue.
