### ISSUE TITLE
Create Gloss ID moest return ID when it already exists

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1201]
Issue: When creating Gloss via Gloss Create API, glossid stays empty. It should return glossid of the already existing Lemma (Dutch or English).

```
{
    "response": "{\"errors\": [\"Lemma translation for Dutch already exists.\", \"Lemma translation for English already exists.\", \"This annotation already exists for language Dutch: ACHTERLICHTEN\", \"This annotation already exists for language English: REAR-LIGHT\"], \"createstatus\": \"Failed\", \"glossid\": \"\"}"
}
```

**Comment by susanodd** [comment]
@rem0g for the above example, there are still errors.

It won't be possible to return one gloss ID if the error results refer to different glosses or different lemmas.

There are database constraints on things that can't be violated. Otherwise the entire database will be corrupted and can't be used by anybody.

The above can return say an ID for the conflicting lemma that already exists. Or a list of gloss ids for the conflicting annotations.

But if the intention of the API call is to "update" an existing gloss, it should call the other API #1202.

If all the fields in the above call MATCH exactly to an existing gloss, then that can be returned.

But if there are conflicts or ambiguity or multiple glosses or lemmas, then it still needs to return error messages.
But it can return a list of other glosses or lemmas that conflict.

This is because ALL the videos also make use of the Lemmas and Annotations, so this could mess up previously stored data.
(i.e., side effects).

**Comment by rem0g** [comment]
Ok, i am going to close this issue and solve on my own.
