### ISSUE TITLE
Gloss Create API with Senses as an extended field

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1207]
Since it is not possible to update Senses via CSV, we would need to create Senses via Create Gloss API immediately.

**Comment by susanodd** [comment]
Yes, this is possible!

See the Notes on the CSV Import Update Gloss pages. This is written there.

There are also some "radio buttons" on that page to turn on and off regarding what to do with the columns.
But as noted, you are not including those columns.

I needed to mention the senses because the import update CSV basically ignores Senses columns if the gloss already has senses. (Nothing will show up in the "Changes to Perform" you are shown before you apply the changes.

**Comment by susanodd** [comment]
You probably need a separate Create Senses for Gloss API.
(The glosses must exist first!)
The senses model also involves all the translation languages for the dataset. Just like the other fields.
Perhaps @Jetske can respond here.

It will still be a problem with keywords with commas in them. (This is ambiguous.)

**Comment by Jetske** [comment]
@rem0g what would the sense input (for both creation and update) look like? eg
```
"Senses: Dutch" : [["trefwoord", "trefwoord, gescheiden door komma's"], ["meer", "trefwoorden"]] 
"Senses: English" : [["keyword", "keyword, separated by commas"], ["more", "keywords"]] 
```
or
```
"Senses": {"Dutch" : [["trefwoord", "trefwoord, gescheiden door komma's"], ["meer", "trefwoorden"]], "English" : [["keyword", "keyword, separated by commas"], ["more", "keywords"]]}
```

**Comment by rem0g** [comment]
It can be done both, it's up to your preference then i can adapt my code to that.

**Comment by susanodd** [comment]
What about when the user omits translations, or the number of things does not match up? Empty lists?
Not offering translations is handled by the Gloss Edit Senses interface. They don't have to match up.
And how to match up the new data to the existing data in order to update, instead of replace.

**Comment by Jetske** [comment]
The senses absolutely have to match up, but that can be done by adding empty arrays in case there is no translation for a sense. It would be good to add a check for whether the sense arrays have the same length in every language. 

Other than that, for updating this would be similar to how update works in the gloss edit senses interface. An update will replace the old senses. But by then the existing senses are already loaded in your system @rem0g, right? So you don't start editing from scratch.

**Comment by rem0g** [comment]
Yes and for the senses english/dutch I can add array.length as verificaion before sending it.

**Comment by susanodd** [comment]
@rem0g could you perhaps give us an abstract description of how you wish to employ all of the different API urls?

From what @Jetske just asked, about saving them in your own system first, then "updating" them (by replacing them).

Are you making some kind of ( lambda x dot x ) identify function on not-updated fields?

So you are essentially passing the gloss "state" around (by including all the fields).

Is that what your setup is?

That is relevant to know, then we can simply identify things that have not been changed.
It would be better if you would come up with a shorthand. Such as only include fields that have changed in the dictionary
and do not include any "empty" value keys.
Otherwise lots of code is needed to compare your "new" field to the "existing" field to see whether it has been changed.
(The CSV import does exactly this, because it doesn't already know what the gloss fields contain.)

If you are programming as @Jetske describes then you will know on your side what has been changed.
So please only put those keys in the dictionary for all the "update" API routines.
That makes our life easier.

Otherwise, sure just replacing all the values with the new values would work. (But this is not a good idea because every choice field is a reference to a an object and there is a database table for these. So zillions of objects will be destroyed and created over time.)

**Comment by susanodd** [comment]
> Since it is not possible to update Senses via CSV, we would need to create Senses via Create Gloss API immediately.

This is incorrect.

It IS POSSIBLE to create Senses via the CSV.

It IS NOT POSSIBLE to update them.

**Comment by Woseseltops** [comment]
> Are you making some kind of ( lambda x dot x ) identify function on not-updated fields?
> So you are essentially passing the gloss "state" around (by including all the fields).
> Is that what your setup is?
> That is relevant to know, then we can simply identify things that have not been changed. It would be better if you would come up with a shorthand. Such as only include fields that have changed in the dictionary and do not include any "empty" value keys or "stays the same" value keys. Otherwise lots of code is needed to compare your "new" field to the "existing" field to see whether it has been changed. (The CSV import does exactly this, because it doesn't already know what the gloss fields contain.)

@susanodd it's definitely useful if @rem0g can show the systems he's building, so we better understand where these questions are coming from, so we'll organize something like that in the near future... but in this issue, let's focus on the relation between senses in the API ;)

**Comment by Jetske** [comment]
Example: 

![image](https://github.com/Signbank/Global-signbank/assets/10157482/b6370151-562f-4aba-87a3-6c9bae738749)

The fields are:
'sense_nl': "[['sense 1 keyword 1'],['sense 2 keyword 1', 'sense 2 keyword 2'],['sense 3 keyword 1']]"
'sense_en': "[['sense 1 keyword 1', 'sense 1 keyword 2'],['sense 2 keyword 1'],['sense 3 keyword 1']]"

@rem0g This does make it tricky to add apostrophes/quotation marks into senses, but that's not recommended anyway..

**Comment by rem0g** [comment]
Thank you! When using aposthropes/quotation marks its common slashes are added and it would be already done automatically when using json loads/dumps python.

**Comment by susanodd** [comment]
I'm trying to use this in the pull request.

The syntax as described yields an error, with a message showing the above example text.

Does the phrase "sense 1" need to be included? I only put the keywords there. Can "keyword" be multiple words?

What's wrong with this?

`[['een kleur'],['een soort bloem']]`

In the example, it shows single quotes around the keywords.
Does the list also need quotes around it, or is it a list?

**Comment by Jetske** [comment]
Yes, the errors stick even if it's a success when it was added before.. that is confusing indeed. 'Sense 1' shouldnt be in the list, that is just to show how the list should be formatted but must be replaces with the keywords of sense 1.
