### ISSUE TITLE
Remove 'video: refilm' tag when batch uploading videos

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#1216]
An extension of the Media Manager functionality (#1172): when uploading new videos, check whether there's a tag 'video: refilm' and if so, remove it.

Background: a typical workflow is to first link a quick and dirty webcam video to a new sign, add the tag 'video: refilm', and then later upload a studio version. Now that there's the batch upload functionality, it'd be helpful if any 'refilm' tags can be immediately removed. Agree, @uklomp ?

**Comment by rem0g** [comment]
I understand the approach but I don't agree since the videos are batch uploaded by editor via signCollect system, and they still have to be checked by other "stakeholders". E.g. other users has to approve if the videos are actually signed as described in gloss and phonology. 

It would be a better idea to modify the labels via API since we have such a stakeholder system for when 100% of stakeholders agree on the video and metadata each gloss, it pass the check and will publish the gloss on Signbank.

**Comment by susanodd** [comment]
@rem0g is your system going to keep comparing the states of e.g., videos between the two systems? I thought the idea was they you check the data/videos before you use the API to put them on Signbank? Or are you thinking to keep syncing more often between the systems while work is being done?

Maybe we need some additional time-related info. (#1177 ). There is also data in the GlossVideo / GlossVideoHistory. There is a datestamp in the latter. (I am only aware of this since working on the Media Manager.)
Perhaps we can work out how to provide the timestamp for the most recent video import/upload to assist in keeping track or narrow down what ones to check? The refilm video tags would be quite old compared to when a new video was imported/uploaded. (Updates to tags are stored in the GlossRevisionHistory.)

Of course, we should make sure that all kinds of necessary data is maintained. But we would be able to tell which glosses had changes to the video after such a refilm tag, etc was added. (I'm not sure when the updates to tags started being saved in the GlossRevisionHistory.)

**Comment by rem0g** [comment]
> @rem0g is your system going to keep comparing the states of e.g., videos between the two systems? I thought the idea was that you check the data/videos before you use the API to put them on Signbank? Or are you thinking to keep syncing more often between the systems while work is being done?

System is semi automatic, when users has done all checks on the glos (senses, phonology, videos, etc) then it will be completed and refilm will be removed also. 

With signCollect i am not sure if we will need the labels in the future, because it keeps state of all glosses being worked at the platform.

**Comment by susanodd** [comment]
@rem0g other researchers need the labels, also for other datasets.

**Comment by uklomp** [comment]
Let's close this issue for now since not everyone wants the requested feature. Moreover, its easier now to remove labels like refilm with the toggle annotation page.
