### ISSUE TITLE
Signbank API: When updating senses, the update is not reflected in last_timestamp

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1239]
We are running updater every 5 minutes and based on since_timestamp -5 minutes we retrieve a json file. And i noticed there is no change reflected in the json file when we update senses on signbank, other changes like phonology are fine.

**Comment by susanodd** [comment]
This is probably because senses are comprised of many relation objects and not a gloss field.

**Comment by susanodd** [comment]
I looked at some of the recently created glosses on NGT.
I see there are some numbers that were created and then the senses were update because the umlaut was some weird characters.
Are these the glosses you are trying to retrieve that were updated?
The update shows up in the Revision History of Gloss View.

https://signbank.cls.ru.nl/dictionary/gloss/48084/history
I'll see if the last_timestamp can search in the revision history data.
Can you give an example of a gloss that didn't show up as being updated, if this isn't one?

**Comment by rem0g** [comment]
The change should be reflected as we look to timestamp now - 5 minutes, so when i change the sense the glos doesnt show up in the glosses JSON file. When phonological information is updated it does. 

I have tested with this one: https://signbank.cls.ru.nl/dictionary/gloss/47350/. I do see senses update in the query but nothing in JSON.

**Comment by susanodd** [comment]
Okay, thanks! I will try to make it show up using the approaches mentioned above.

**Comment by susanodd** [comment]
I'm looking at the code where things are saved. But the code is already doing a gloss.save after it updates the senses.
So it's very weird that it is not registering as being updated. (It's already doing a dummy save on the gloss when the senses are updated. Perhaps because the gloss itself is not being changed -- only the relations with senses -- Django knows it's not been updated so doesn't update the lastUpdated field.

I revised this to update the field explicitly.

(But updating the senses does not work for me at all.)

**Comment by susanodd** [comment]
This has been deployed.
