### ISSUE TITLE
Enable deletion of a video

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#124]
- Now only replacing a video is possible
- In the Django admin, only a subset of videos are listed (those that were uploaded manually, rather than with the script?). Deleting videos there is thus not always an alternative. It's more of a priority to enable manual deletion in the user interface, than to adapt the video list in the Django admin so that it includes all videos.

**Comment by henrinie** [comment]
Are you sure that you can't delete a video?
In FinSL SB it is possible to delete videos on the gloss page and in the django-admin (on videos app).

**Comment by richardbank** [comment]
Apparently, the delete/revert video button is only shown when a second video is uploaded. It thus looks like the database has to know a video exists for a gloss in order to show the delete button; maybe this is not updated with batch uploading? Possibly related to @Woseseltops's PS in his last comment on  #66?

PS: reverting to an earlier video does not work. After adding a second (or even third) video, the delete/revert video button is shown, but it only deletes the most recent video, not reverting to earlier ones. This may need to be in a separate issue.

PPS: a possible catch here is that an old video may be shown after uploading a new one (like on Johan's machine), so be sure to refresh the page after uploading.

**Comment by henrinie** [comment]
The old video showing after uploading a new one is due to the browser caching it, because the filename stays the same.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , is this still relevant to the work on the video naming that you are doing? Can it simply be closed?

**Comment by vanlummelhuizen** [comment]
The Delete button is now reverting to the previously uploaded video. If it is the first uploaded video, it will be deleted. If you want this reversion system, this could be closed. If not, we should discuss.
