### ISSUE TITLE
Batch edit

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#1268]
* Somewhere in the search results there is a button 'batch edit'
* This button brings you to the `BatchEditListView`, where you see each search result as a row, and as columns:
  * The small video
  * The gloss annotation ID
  * Several editable gloss fields, which @uklomp will provide below
* Important: the `BatchEditListView` has only one `Apply` button (unlike the detail view, where you have to click `OK` for every change you make)

**Comment by susanodd** [comment]
I'm working on the BatchEditForm now.
For Senses, only existing senses can be edited (translations filled in, as discussed).

(At the moment, new senses cannot be created, and senses cannot be reordered. Gloss Edit will need to be used for that. Otherwise too much interface code is needed.)

**Comment by susanodd** [comment]
@uklomp do all glosses have senses?

If the gloss does not have senses, do you want an empty field to appear?
Or only to appear if a language has not been filled in? (Like a touch up edit.)

To avoid yet another method to create senses if possible?

**Comment by susanodd** [comment]
I have some of the fields done already. The toggles are implemented and work. There needs to be a button for the language fields. (Hence my question above. As you can see there are no fields for the senses for this gloss -- a copy in tstMH)

![batch-edit-wegdoen-1](https://github.com/Signbank/Global-signbank/assets/24272544/f54f895b-829c-4d85-b94f-fb8255607678)

**Comment by susanodd** [comment]
The plan is to show videos for similar glosses below when say Handedness, Strong Hand and Weak Hand have been filled in.

**Comment by susanodd** [comment]
Here is what goes wrong with displaying the senses this way

![batch-edit-brus-A-senses-display](https://github.com/Signbank/Global-signbank/assets/24272544/ac31222a-04c7-4122-878d-6a1277434a30)

**Comment by susanodd** [comment]
I can make it so the language fields also collapse to hide them. Suggestions are welcome!

**Comment by susanodd** [comment]
![batch-edit-ngt-kweek](https://github.com/Signbank/Global-signbank/assets/24272544/a148861a-5dae-4b9c-b26a-e18117be6fb7)

**Comment by susanodd** [comment]
More toggles added, showing highlighted sense translation field:

![batch-edit-ngt-kweek-2](https://github.com/Signbank/Global-signbank/assets/24272544/b8cc86d9-2caf-47d3-aba8-0bc2be500c72)

**Comment by uklomp** [comment]
> @uklomp do all glosses have senses?
> 
> If the gloss does not have senses, do you want an empty field to appear? Or only to appear if a language has not been filled in? (Like a touch up edit.)
> 
> To avoid yet another method to create senses if possible?
> 
> At the moment, there is Gloss Edit, Keywords Mapping Edit (this is also batch edit but just for senses), and API create gloss, and API update gloss.
> 
> The Analysis -> Keywords Mapping was meant to facilitate the change from the Keywords system to the Senses system for already existing glosses, since there were only keywords to begin with. These can then be split up into senses.

Not all glosses have senses, I'd like to be able to add them then yes, so a field would be good.
Would it be possible to have all English stuff in a column next to the Dutch stuff? At least for the senses, but preferably also for the glosses and lemmas. So not all underneath each other, but English next to Dutch.

**Comment by susanodd** [comment]
> Not all glosses have senses, I'd like to be able to add them then yes, so a field would be good. Would it be possible to have all English stuff in a column next to the Dutch stuff? At least for the senses, but preferably also for the glosses and lemmas. So not all underneath each other, but English next to Dutch.

I'll experiment with that next. I have the phonology fields working as shown above. Just need to keep adding more.

The query results has been done so it starts with the query results in the list.

I'm working on the language fields now.
I added a panel "language fields" with a button "save language fields" button in the toggles area.

![batch-edit-languages-fields-panel-save-button](https://github.com/Signbank/Global-signbank/assets/24272544/6b619dd3-c0f4-4dad-b5c9-917f1f035936)

I'll  modify the display to show the languages in columns.

Do you want more things in the Language Fields panel?
(The Save button is there so it's more like the phonology toggle buttons.)

A create button for senses?
A "assign lemma" to replace the lemma with an existing lemma?
Another option is to put the "new contents" in the languages panel and on update shove it into the fields to the left.
Then the fields on the left could look prettier.

I'll do the columns next and post a screenshot.

**Comment by susanodd** [comment]
Here's with columns (the display scrolls to the right):

![batch-edit-kweek-language-columns](https://github.com/Signbank/Global-signbank/assets/24272544/713d5de4-5145-4ef6-bd38-cb122c008366)


![batch-edit-kweek-language-columns-scroll-right](https://github.com/Signbank/Global-signbank/assets/24272544/dfdd4fa9-8ef7-40b0-80a4-69421421de25)

**Comment by uklomp** [comment]
I remember that we talked about making phonology work this way, but I didn't remember putting them in this BatchEdit as well. I'm not sure yet if it's a benefit, but it's also not a disadvantage I suppose.

Senses in two columns: looks way better, thanks.

What do you mean with language fields, I have no idea what they are?

**Comment by susanodd** [comment]
> I remember that we talked about making phonology work this way, but I didn't remember putting them in this BatchEdit as well. I'm not sure yet if it's a benefit, but it's also not a disadvantage I suppose.
> 
> Senses in two columns: looks way better, thanks.
> 
> What do you mean with language fields, I have no idea what they are?

The language fields (what I call them, code wise) are dependent on the translation languages of the dataset.
Here the user enters text
But they need to be generated dynamically in the input form, because of the languages/dataset
(the code is more complicated because it includes a language code, e.g., lemma_NNNN_nl
(for gloss NNNN lemma in Dutch)

Because batch edit is a giant input area, the form fields have the gloss id attached, the buttons have the id attached,...

The phonology is super easy to update this way, no pulldowns.

**Comment by susanodd** [comment]
This is implemented now, except for the senses

**Comment by susanodd** [comment]
FEEDBACK SCREENSHOTS updating text fields / language fields

![batch-edit-lemma-error](https://github.com/Signbank/Global-signbank/assets/24272544/bd90564b-10b3-4ea8-a755-ee10c8390c0e)

![batch-edit-no-changes](https://github.com/Signbank/Global-signbank/assets/24272544/f606c4e6-1456-4615-81d1-3a17078a4477)

![batch-edit-annotation](https://github.com/Signbank/Global-signbank/assets/24272544/c584cc00-6aa7-4dd3-8699-3cc59f4ac608)

![batch-edit-saved-to-dataset](https://github.com/Signbank/Global-signbank/assets/24272544/9d5ab78d-7df5-4db5-a4ea-6aea5e5406cd)

**Comment by susanodd** [comment]
[NOTE TO SELF] There might need to be a clear form button after an unsuccessful attempt to update the text fields.
(At the moment, the proposed changes still remain visible. Need to investigate.)

**Comment by susanodd** [comment]
@uklomp this is on signbank-dev now.

**Comment by susanodd** [comment]
> * Somewhere in the search results there is a button 'batch edit'
> * This button brings you to the `BatchEditListView`, where you see each search result as a row, and as columns:
>   
>   * The small video
>   * The gloss annotation ID
>   * Several editable gloss fields, which @uklomp will provide below
> * Important: the `BatchEditListView` has only one `Apply` button (unlike the detail view, where you have to click `OK` for every change you make)

One comment here, there are no small videos. The creation of small videos has been broken for a long time. There is a bug in the CNGT scripts.

**Comment by uklomp** [comment]
> > I remember that we talked about making phonology work this way, but I didn't remember putting them in this BatchEdit as well. I'm not sure yet if it's a benefit, but it's also not a disadvantage I suppose.
> > Senses in two columns: looks way better, thanks.
> > What do you mean with language fields, I have no idea what they are?
> 
> The language fields (what I call them, code wise) are dependent on the translation languages of the dataset. Here the user enters text But they need to be generated dynamically for the input form, because of the languages/dataset (the code is more complicated because it includes a language code, e.g., lemma_NNNN_nl (for gloss NNNN lemma in Dutch) Those are the internal labels attached to the text fields of the input form.
> 
> Because batch edit is a giant input area, the form fields have the gloss id attached, the buttons have the id attached,...
> 
> The phonology is super easy to update this way, no pulldowns.
> 
> What about calling them "Text Translation Fields" ? (There needs to be some way to identify them on the page.)
> 
> It would be possible to just hit Enter after updating some text. But that could go wrong if the user forgets to type enter. The fields will looked changed on the screen after editing the text. But there needs to be a signal to the computer that it is ready to save. (Hence the OK buttons all over the place in Gloss Edit.)
> 
> The text fields are handled differently because for each text field, there are some other objects attached. In contrast, the phonology fields are fields of the gloss itself. But the translated text fields are stored in other tables. So different implementation code is needed.

Ok, so if I understand correctly, you're asking me if we need more buttons and if it's OK to have one 'save' button? I think the 'create sense' would be a good option, like you suggested, and one 'save' button for all the language fields as well. Btw I think text fields would be a more common name yes.

**Comment by susanodd** [comment]
First version of similar glosses.
Of the available fields, you can turn them on or off to search by them for that gloss.
(There aren't enough fields yet for this.)

Here is the first version (without the videos yet, just the annotations of the similar glosses)
This is basically a search on Handedness 1, Location Head, Movement Shape Bow

![batch-edit-similar-glosses](https://github.com/Signbank/Global-signbank/assets/24272544/3adbdfb6-4086-4b93-adb0-8f5bad6e5176)

**Comment by susanodd** [comment]
I was trying to find the horns example at the live meeting.
I need to add a few more phonology fields for that....

**Comment by uklomp** [comment]
Shall we separate the 'batch edit phonology' and 'see similar glosses' from the current issue of making batch edit possible for lemma, glosses and senses? I'm getting confused now.

**Comment by susanodd** [comment]
> Shall we separate the 'batch edit phonology' and 'see similar glosses' from the current issue of making batch edit possible for lemma, glosses and senses? I'm getting confused now.

Do you want separate pages?

I thought the idea was to do all the editing in-line instead of using csv. :)

**Comment by susanodd** [comment]
I fixed a bug related to the page links at the bottom. (It was doing some weird stuff on the pages after 1,showing glosses that had not been queried.)

I haven't done the senses yet.

If you have a chance please try the Keywords Mapping (#1273).
(That is batch edit functionality to edit senses.)

**Comment by uklomp** [comment]
> > Shall we separate the 'batch edit phonology' and 'see similar glosses' from the current issue of making batch edit possible for lemma, glosses and senses? I'm getting confused now.
> 
> Do you want separate pages?
> 
> I thought the idea was to do all the editing in-line instead of using csv. :)

I want separate issues here on Github :)

**Comment by uklomp** [comment]
> I was trying to find the horns example at the live meeting. I need to add a few more phonology fields for that....
> 
> ![batch-edit-similar-koe-a-2s-hoofd-boog](https://private-user-images.githubusercontent.com/24272544/343169556-dbc94c7a-6ccf-4e39-b1e7-2645c93131d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTIxNjksIm5iZiI6MTcxOTQxMTg2OSwicGF0aCI6Ii8yNDI3MjU0NC8zNDMxNjk1NTYtZGJjOTRjN2EtNmNjZi00ZTM5LWIxZTctMjY0NWM5MzEzMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE0MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDI2NGM4Yzc0MjI0NTExZDk1YmU2Yzk3NjY2ZWI5NjU5ODQ5Y2UzMzZlMDlhOTMwMWM1NmUyMWZlY2I1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryTEIS_bwedib75txi1rn3G4TUKM83RFhCATxi5P898)

I don't see this. Where can I find these overviews? I went to signbank-dev and I tried several datasets but I don't see these phonology fields.

**Comment by uklomp** [comment]
As for 'horns', I meant the sign that is glossed as koe-a

**Comment by susanodd** [comment]
> > > Shall we separate the 'batch edit phonology' and 'see similar glosses' from the current issue of making batch edit possible for lemma, glosses and senses? I'm getting confused now.
> > 
> > 
> > Do you want separate pages?
> > I thought the idea was to do all the editing in-line instead of using csv. :)
> 
> I want separate issues here on Github :)

Can it still be on one page, or would you prefer "Batch Edit Text" and "Batch Edit Phonology" ?

**Comment by susanodd** [comment]
> > I was trying to find the horns example at the live meeting. I need to add a few more phonology fields for that....
> > ![batch-edit-similar-koe-a-2s-hoofd-boog](https://private-user-images.githubusercontent.com/24272544/343169556-dbc94c7a-6ccf-4e39-b1e7-2645c93131d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTIxNjksIm5iZiI6MTcxOTQxMTg2OSwicGF0aCI6Ii8yNDI3MjU0NC8zNDMxNjk1NTYtZGJjOTRjN2EtNmNjZi00ZTM5LWIxZTctMjY0NWM5MzEzMWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE0MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDI2NGM4Yzc0MjI0NTExZDk1YmU2Yzk3NjY2ZWI5NjU5ODQ5Y2UzMzZlMDlhOTMwMWM1NmUyMWZlY2I1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ryTEIS_bwedib75txi1rn3G4TUKM83RFhCATxi5P898)
> 
> I don't see this. Where can I find these overviews? I went to signbank-dev and I tried several datasets but I don't see these phonology fields.

I meant that I was trying to simulate your example where you made the horns sign (in real) and I was trying to figure out what phonology comprised the sign you were making.
(I do not know sign language, so I was trying to figure out what phonology I would need to put in the Gloss Search form in order to find signs with horns.

If I already know the sign KOE and I type in all the fields and search for this, I only find KOE.

To find more than one sign, I needed to ignore some of the phonology of KOE.

It worked to make a Boog near the Hoofd. (Search on Boog and Hoofd in the appropriate fields.)

**Comment by susanodd** [comment]
I revised the display as per feedback, fewer Sense labels
It looks a bit more user friendly now.

![batch-edit-kweek-fewer-headers-for-senses](https://github.com/Signbank/Global-signbank/assets/24272544/14983d1f-f471-4cc0-9f05-c23397772639)

**Comment by susanodd** [comment]
This is live on `signbank-dev`
```
Analysis -> Batch Edit
Analyse -> Batchbewerking
```

**Comment by susanodd** [comment]
Updating Senses and Create Sense are implemented.

This is on signbank-dev.

**Comment by susanodd** [comment]
The hyperlink annotation shown under the video is updated to show an update to the dataset default annotation.

**Comment by susanodd** [comment]
Most recent code is on signbank-dev.

Here, the panels are now collapsible and there are videos for the similar glosses. The values of the phonology fields are shown in the buttons now. You can turn the buttons on and off to refine the query.

![kweek-collapsed-panels](https://github.com/Signbank/Global-signbank/assets/24272544/7954e8b8-f28f-4f18-888c-2f8cf0c27561)

![kweek-similar-glosses-preview](https://github.com/Signbank/Global-signbank/assets/24272544/7b2ccd02-621f-4f72-896b-621b979ffff3)

**Comment by susanodd** [comment]
Text Fields panel OPEN on viewing. (User can explicitly close them.)

**Comment by susanodd** [comment]
> * Somewhere in the search results there is a button 'batch edit'
> * This button brings you to the `BatchEditListView`, where you see each search result as a row, and as columns:
>   
>   * The small video
>   * The gloss annotation ID
>   * Several editable gloss fields, which @uklomp will provide below
> * Important: the `BatchEditListView` has only one `Apply` button (unlike the detail view, where you have to click `OK` for every change you make)

For each gloss, there will be a SAVE TEXT button.
For the purpose of "atomic transaction" and "checking constraints" this is necessary. Otherwise, work by other users of signbank during the time a user is "busy" changing text fields, may interfere and prevent work from being saved.

Updates to the "text fields" of EACH gloss involves updates to the following TABLES / related objects to the gloss:

- Gloss
- LemmaIdglossTranslation
- AnnotationIdglossTranslation
- Keyword
- Translation
- SenseTranslation
- Sense
- GlossSense
- GlossRevision

Additionally, video files may be moved if lemma translations or gloss annotations of one gloss have been updated.

**Comment by Woseseltops** [comment]
Hey @uklomp (when you're back), Susan and I disagree about whether there should be 1 generic 'save/apply' button instead of a separate one for each gloss. I don't remember your viewpoint here? Susan does correctly note that if there's only one button, you might get a whole list of objections, similar to what you get when uploading a CSV.

**Comment by susanodd** [comment]
There are sufficient phonology fields now to show the similar glosses to KOE-A
(Observe that some "similar gloss fields" shown have been toggled off so to be ignored in the Query.)

![similar-glosses-koe-a](https://github.com/Signbank/Global-signbank/assets/24272544/66742dee-f671-4c7c-969a-042467d9f6fd)

**Comment by susanodd** [comment]
All but one phonology field added. Here's what the quick search on similar glosses looks like for KOE-A now.

![similar-koe-a](https://github.com/user-attachments/assets/f27c0eb0-76f5-489f-91cf-64b6104785ba)

**Comment by susanodd** [comment]
On initial view, all the phonology area are closed and only the text fields are visible.

![batch-edit-initial](https://github.com/user-attachments/assets/b0692b53-508c-4b9c-9ac7-afe72cd5d60f)

I designed it this way because this allows the users to check the phonology if necessary and correct it in a convenient way.

**Comment by uklomp** [comment]
Is it correct I can't go to batch edit if I did a sense search instead of a gloss search? I'd like to be able to batch edit with any kind of search results.

**Comment by susanodd** [comment]
Yes, signbank-test.

(It was moved to signbank-test because signbank-dev is being used by @vanlummelhuizen to work on the API permissions and updating the view dataset problem.

**Comment by uklomp** [comment]
Ok! 
A few feedback points:
1. The textfield where the pointer is, in the screenshot, is too small. I can't add any more characters, while I do need them.
2. I'd like 'enter' to mean 'save / finished' and not mean to go to the next line in a text field. I know this is the functionality when editing senses on the gloss detail page and that's fine, but in the batch edit when you're typing, you just want to continue to the next one and finish it with 'enter'. Adding multiple words to one number of senses can still be done with comma's.
3. As for the question of saving: right now, I'm under the impression that everything that I've typed so far, is saved. So I don't see the need for a save button at all. Is this the wrong impression?

**Comment by susanodd** [comment]
> Ok! A few feedback points:
> 
>     1. The textfield where the pointer is, in the screenshot, is too small. I can't add any more characters, while I do need them.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/147159596/350882777-cefbc73d-61a4-49d7-8aaa-fd29456b0f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzkxODEsIm5iZiI6MTcyMTYzODg4MSwicGF0aCI6Ii8xNDcxNTk1OTYvMzUwODgyNzc3LWNlZmJjNzNkLTYxYTQtNDlkNy04YWFhLWZkMjk0NTZiMGY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwOTAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzVmMDEwNTQ5NjZkYTJiNWM5NTEzMGFlMThmNTc1YTI0N2E2ZTU3NWU1NDIyMzFiMmEwMDJjMTVlODEyZjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jhsF741_JV9Vzq1zsBytveiD2j7Ma62wZtizQKlKoig)
> 

Okay, I can fix this. On a small screen there isn't enough space, although the entire page is really wide and the user can "pan" to the right. (I'm describing what happens on a small macbook 11 inch, it's not scrolling but you can keep moving to the right. I don't know what that's called, this is the only view that works like that for me, so I'm confused by the markup. But yes, I'll make it wider.)

>     3. I'd like 'enter' to mean 'save / finished' and not mean to go to the next line in a text field. I know this is the functionality when editing senses on the gloss detail page and that's fine, but in the batch edit when you're typing, you just want to continue to the next one and finish it with 'enter'. Adding multiple words to one number of senses can still be done with comma's.

Okay, I need to figure that out. I guess it will just be a save for that field then.

>     4. As for the question of saving: right now, I'm under the impression that everything that I've typed so far, is saved. So I don't see the need for a save button at all. Is this the wrong impression?

No, they are shown as updated on the screen but (as it is now, before doing request 3) they are only "saved" when you click the save. And if there are problems with the constraints, feedback is shown below the save button. For example, if you change it to something that already exists. There needs to be feedback and it's shown there. It can't be shown "inside" of the area where you type the new text because that is all generated dynamically.  It would be a mess to start showing feedback between the rows, say. But there needs to be a place to show the feedback because the updates to the lemma and annotation fields can fail.

I need to figure out what to do for implementing (3) because there can also be failure feedback.

**Comment by susanodd** [comment]
Do you already want to start using it once the text area is made wider?
And make the updates to the save later?

**Comment by uklomp** [comment]
No, the updates to the save are more important. 

If we do need a save button, I'd like one very clear save button (maybe even red or another bright color) on the top of the screen and on the bottom of the screen. But not a save button for every gloss.

**Comment by susanodd** [comment]
> No, the updates to the save are more important.
> 
> If we do need a save button, I'd like one very clear save button (maybe even red or another bright color) on the top of the screen and on the bottom of the screen. But not a save button for every gloss.

Okay, I need to think about this. I revised the answer above at the same time as you were typing.
There is a difficulty with "transactions" if it's "one" button.
You would basically need to do something like the way "Edit" is done in Gloss Edit to make sure nobody else is editing at the same time.

**Comment by susanodd** [comment]
@uklomp I can make it so the "senses text" can be updated without using the "Save" button, but the Lemma and Annotation text fields have the problems described above (because there are database constraints).

The "senses" text as they are now are done with the "save" button because:

when updating senses, the "old" senses are "replaced with" the new senses when they are updated.
This is ALSO how the API works. It replaces the old ones with the new ones.
(That is the solution that @Jetske came up with for updating the senses in the API.)

So I need to figure out if using an "update save per sense text field" has any adverse effects.
This probably needs to be completely re-implemented since this would be an "update of the sense itself" rather than an "update of the glosses senses".

(The other issue for moving around keywords to different senses does it that way; it is updating the individual senses, not all the senses, and not replacing the senses.)

**Comment by susanodd** [comment]
> No, the updates to the save are more important.
> 
> If we do need a save button, I'd like one very clear save button (maybe even red or another bright color) on the top of the screen and on the bottom of the screen. But not a save button for every gloss.

Okay, I can phrase the problem differently:
if there can't be a save button per gloss, then
there needs to be a "check consistency" button and an area of the layout for reporting inconsistency (for all the glosses on the page, similar to what CSV update does with feedback.)

**Comment by susanodd** [comment]
@Woseseltops kindly read the above problems with (1) having an update "per text field" (by hitting return)
and (2) having a single "apply" button for all the text fields.

- For senses, they are updated in this view the same way as how they are updated in the API. The original senses are deleted and the new senses are created. (This is per gloss.)
- For lemma and annotation fields, there may be constraint violations. If this happens the offending updates cannot be committed to the database.

**Comment by susanodd** [comment]
The button has been made blue (offline, not deployed yet).

**Comment by susanodd** [comment]
[IMPLEMENTATION]

The Batch Edit template does not make use of forms. The only "form" is the search form at the top.

Each gloss row and panels has its own gloss-suffixed element labels. All of the "toggle style commands" are associated with URL commands specific for the gloss. This allows fine-grained editing with minimal database locking.

The individual "input" fields are not associated with any forms. They are identified by "nesting scope" in the code. Everything is dynamic.

**Comment by susanodd** [comment]
Here is the version, live on signbank-test now.
The screenshot is at 80% because it's too wide to fit on my low resolution display.

![superwise-text-batch-edit-blue-buttons-80-percent](https://github.com/user-attachments/assets/236d6cff-6232-4a64-80e4-6f7874f11814)

**Comment by susanodd** [comment]
@uklomp can you try out the page again to see if the text areas are big enough now?
I made the screen much wider.

If I go ahead and make it work with return to save, it can only be for Senses because they don't have constraint violations.

[DETAILS]
The other two ought to be completely filled in before "save" in order to check database constraints on the complete "lemma" and the complete "annotation". (These are comprised of multiple languages, so database constraints apply to "all the languages at the same time. You need to  "modify" the fields you need to change, then have it check consistency. I relabelled the button to make it clear what it is actually doing. This is a necessary step.)
Here, for example, just like the API, it won't let you set the lemma to something that is shared by other glosses. We already discussed this a lot. The API also works this way. If glosses need to share the lemma this needs to be done in Gloss Edit.)

BUT for Senses, it is implemented in such a way (exactly as for the API) that the old senses are removed and the new senses are added.
I made it this way because that is how @Jetske solved the problem. (Recall that you can't update senses in CSV. That is due to complex pairing up of the senses and translations and the use of commas.)
So I'm not sure it's wise to "update" (i.e., erase and replace) allt the senses each time you update one field.

The Split Up Keywords is implemented in a totally different way. It updates the individual translation objects and does not "delete" and "make new ones".
But the implementation to do it this way is very complicated. This will take several more weeks to implement, since I'm working on the Delete for the API again now.

**Comment by susanodd** [comment]
@uklomp kindly check if the text fields are big enough now. :)

If you need extensive text in the individual sense text fields, there could be something else wrong.
Because there are "keywords" underneath.
The original senses are all composed of keywords. (As visible in the original Sense Edit of Gloss Edit.)
They are separated by commas.
They are also visible (initially) in the Split Senses view.
(I have since removed the extra empty fields there, only leaving one.)

There is a "potential" problem if you want to type extensive text inside of one Sense field because underneath there is a Keyword model and those are not infinitely long.
(It will end up too long to fit in the database table.)

**Comment by susanodd** [comment]
I am typing so much because when coding, the goal is to prevent bugs from happening.

**Comment by uklomp** [comment]
IF we use the regrouping first, then the text fields are big enough.

BUT if we want to batch edit and then are also working on translations, we might translate everything first although it's incorrectly in one group, and then translate it to one other English group - and then the text fields are still too small. See e.g. the screenshot.
Since I like the batch edit a lot in functionality, I think we might use this more often for translation and not always regroup first. So I'd like the text fields to accept more characters, maybe even four times as much. 

<img width="1867" alt="image" src="https://github.com/user-attachments/assets/d4ff06b7-dac8-40aa-b6bc-2e83c1e4e9c3">

**Comment by uklomp** [comment]
The blue button is very clear.

**Comment by susanodd** [comment]
> IF we use the regrouping first, then the text fields are big enough.
> 
> BUT if we want to batch edit and then are also working on translations, we might translate everything first although it's incorrectly in one group, and then translate it to one other English group - and then the text fields are still too small. See e.g. the screenshot. Since I like the batch edit a lot in functionality, I think we might use this more often for translation and not always regroup first. So I'd like the text fields to accept more characters, maybe even four times as much.
> <img alt="image" width="1867" src="https://private-user-images.githubusercontent.com/147159596/351648015-d4ff06b7-dac8-40aa-b6bc-2e83c1e4e9c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MTE5OTgsIm5iZiI6MTcyMTgxMTY5OCwicGF0aCI6Ii8xNDcxNTk1OTYvMzUxNjQ4MDE1LWQ0ZmYwNmI3LWRhYzgtNDBhYS1iNmJjLTJlODNjMWU0ZTljMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwOTAxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmUxMjgwN2FlMmU0Y2JiZTZkY2QzMThjNzdhM2UxNjhlNTIzYTQyYmJmZjg3ZGYwNDgxY2MyZjVjMDU5OWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DjDVycESiVzzBaojCs0sfnw4kNlyeH1PjVcPIqI590A">

Okay, that helps to understand what you expect to be able to do and how you wish to use the tool.

I probably need to totally re-implement the senses to support very long fields.
If all the text is in one field like that, it's not going to be able to be saved to the database at all. (The 100 characters is a problem here. Your text would just disappear actually and you probably would not realise this right away because most code fails gracefully so as not to give awful crash reports.)

I can alter the code so that it "splits" the text using the commas. (This was originally done when there were just keywords, before the senses model. The morphemes still use the original keywords and they are split up this way.)

I can make this be an independent step.
The idea would be that the really long text needs to be separated into keywords for the sense.
Then you won't be able to have commas "inside" the keywords at the start.
(That is only an issue if you want the words in a specific order or need punctuation. This used to frustrate users with the original keywords model since stuff would all of a sudden not match what they had typed in, duplicate keywords get removed because they are actually "keywords" and the same object can't appear twice inside a sense text.)

I'll give it a go at splitting it.
But then there will need to be multiple "keyword text" fields underneath (or inside of) each of the "sense text fields"
(like how the Split senses is that you can see the text in separate boxes)

**Comment by susanodd** [comment]
Does this one sort the languages correctly?
For me it is always putting Dutch first, also if the interface is NL.

I checked and there is a migration that sets the sort order to "-id" for Language.

It's not possible to modify the id field since this is an internal field. It's used by Django to reference the objects.

I'll need to check whats going on for Split Senses, because that ought to be putting Dutch/Nederlands always first.
Maybe the migration wasn't applied.

**Comment by uklomp** [comment]
Yes, here it's fine! Dutch left, English right.

**Comment by susanodd** [comment]
I modified it so that newline separates the keywords.
Now you can keep typing the translations inside a single sense field, separated by return
Then you can use the Split command in the other view to move them around

**Comment by susanodd** [comment]
This was deployed on signbank a few weeks ago. It is available in dark mode as well now.
