### ISSUE TITLE
Add API for NME Elements

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1297]
For https://github.com/Signbank/Global-signbank/pull/1263 we would need to have new API connection to add and upload NME elements.

**Comment by susanodd** [comment]
The NME objects have an "offset" field (the order index of display) and multilingual descriptions (GlossVideoDescription objects related to the GlossVideoNME object)

The creation is implemented via the gloss update method, then an update function to update the offset and the description.
Currently, you need to delete the video in Gloss Edit. Or you can update the fields. Or you can upload a new one.

So for the api urls there can be separate urls for each of these different edit functions.
Or you could think of them as a set and then update the nme videos as a set?

Analogous to updating "Senses" (for all the senses) or updating the different keywords / translations in them. (We didn't offer the latter because their IDs are not visible to users.)
But for the NME videos, the names of the videos follow a pattern for the gloss.
With "`_nme_N.mp4"` as the suffix/extension

I have no idea yet what would be simpler.

Somehow if you want to update the description or offset, then you will need to be able to reference the NME video.
So probably need them in the package / gloss retrieval API in order to have the respective file names.
Although if you know how many there are for a gloss, or know the offset that would suffice to identify the objects.
Analogous to how the sense numbers are used.

**Comment by susanodd** [comment]
This is proving difficult to do.

I am having trouble with the video file.

In spite of following instructions for doing so, when Django obtains the file, it thinks it's a dict instead of a file.

**Comment by susanodd** [comment]
The examples I find are all using PHP with ajax.

**Comment by susanodd** [comment]
I added the NME Videos to the package as a list of dictionaries.
Here the ID of the GlossVideoNME object is exposed as it is needed by the API in order to update the index and description fields.

```
        "NME Videos": [
            {
                "ID": "21216",
                "Volgorde": "2",
                "Omschrijving: Nederlands": "pompoen",
                "Omschrijving: Engels": "pumpkin",
                "Link": "http://localhost:8000//dictionary/protected_media/glossvideo/tstMH/PO/POMPOEN-42087_nme_2.mp4"
            }
        ]
```

**Comment by Woseseltops** [comment]
For completeness @susanodd , an example script to upload files via the API

```python
import requests

# The URL to which you want to upload the file
url = 'https://signbank.cls.ru.nl/dictionary/ENDPOINT'

# The path to the file you want to upload
file_path = 'path/to/your/video.mp4'

# Open the file in binary mode
with open(file_path, 'rb') as file:
    # Define the files parameter
    files = {'file': (file_path, file, 'application/octet-stream')}
    
    # Send the POST request
    response = requests.post(url, files=files)

# Check the response
print(response.status_code)
print(response.text)
```

**Comment by susanodd** [comment]
> For completeness @susanodd , an example script to upload files via the API
> 
> ```python
> import requests
> 
> # The URL to which you want to upload the file
> url = 'https://signbank.cls.ru.nl/dictionary/ENDPOINT'
> 
> # The path to the file you want to upload
> file_path = 'path/to/your/video.mp4'
> 
> # Open the file in binary mode
> with open(file_path, 'rb') as file:
>     # Define the files parameter
>     files = {'file': (file_path, file, 'application/octet-stream')}
>     
>     # Send the POST request
>     response = requests.post(url, files=files)
> 
> # Check the response
> print(response.status_code)
> print(response.text)
> ```

I"m failing to see how an entire "json" dictionary of fields to update can include a file field in it.

The above looks like how the server already does this inside other places where files are uploaded.

The API in this case needs more data that just a file.

**Comment by susanodd** [comment]
@Woseseltops are you assuming with the above code that the user is going to upload a video to some upload location? Not the final destination? (i.e., that no object will be created yet)

**Comment by susanodd** [comment]
@rem0g this is working now for creation!!

I need to revise it some more so the video ID is used for the update.

I did not use the code of @Woseseltops 
I figured out how to do it with an ajax call.

**Comment by rem0g** [comment]
I will need instructions how to communiate via API to upload, adjust and remove NME elements. Can you fill them in Wiki?

**Comment by susanodd** [comment]
Added to Wiki.
