### ISSUE TITLE
Increase allowed video upload size

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1311]
Increase it from 5mb to 10mb.

**Comment by susanodd** [comment]
@Jetske this should not be done in file 

https://github.com/Signbank/Global-signbank/commit/8b9248c3d80d0edfa22d0651b7043a3f77de9176#diff-0a3b59552c5f10906d3787110652f40ee700668282f92e358e0dfcc18633506a

It needs to be done in server_specific / server_specific.py
(on the server)
Otherwise it can't be merged and git overwrites the server specific secret key.

I fixed in on signbank, but beware when doing this on your own server.
Can this be in default instead?
Because we can't publish the secret key, the changes to this file are not actually merged into the server.
