### ISSUE TITLE
Error in example sentence upload

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1326]
A user reported an error:
![image](https://github.com/user-attachments/assets/a6788179-2973-4a49-b082-e9251b75d1b0)

It only seems to happen with one file.

**Comment by susanodd** [comment]
I know this error. Sometimes a save is in the middle of other commands that need its result.
I think it's also the file system. When you see those weird characters added to the filename.
If you come up with a good solution, please share!

**Comment by Woseseltops** [comment]
I have also seen this error; I thought it happened at random (the browser fighting with Django or something), but it seems like you can reproduce at will with a particular file, is that correct?

**Comment by susanodd** [comment]
Yesterday the entire server was blocking. I think it's the atomic things that cause this. Sqlite locks the entire database.

**Comment by susanodd** [comment]
@Jetske can you post an example of the filenames that didn't work because of extra dots?
Or of this file?

Which routine is it in the code that does this? (Where the atomic block breaks.)

[CODING]
I had to move a save to the end of the block. It happened once because of nested saves. It's kind of a problem because some objects need to be created and used by other objects.
You could also try creating the object using the e.g., newgloss = Gloss(...) instead of Gloss.objects.get_or_create(...)
The constructor does not put the object in a table yet, until you do save on it (at the end).
It seems it can be used in other code that also uses constructors that isn't saved yet. Then save them inside out nesting.

The lemmas sometimes cause problems because those need to be created before a gloss is created.
The video saving gets the first two characters from the lemma for the folder.
I needed to duplicate the code that retrieves the two characters so it is in the same python file.
(The code was causing problems when it was in a different file and retrieved. That was in the video model/app/folder)
(I think because all the models are importing from other models. The imports in dictionary/models.py are inline imports rather than at the top of the file to avoid recursion.)

**Comment by susanodd** [comment]
@Jetske I'm having a different error.

The id videoplayer is duplicate in Gloss Detail.
The sentence video has the same id as the gloss video and it can't run the javascript to load the video.

```
    function reloadVideo() {
        var video_player = document.getElementById("videoplayer");
        video_player_src = video_player.src;
        video_player_src = "";
        video_player.src = video_player_src;
        video_player.type = "video/mp4";
        video_player.load();
    }
```

**Comment by Jetske** [comment]
@Woseseltops No I have the file that gave this error, but can't reproduce it myself. 
@susanodd in the end I don't think the dot in the filename caused it (although better avoid it I guess). And yeah if there are duplicate id's that could be a problem.

**Comment by susanodd** [comment]
@Jetske has this been solved?

**Comment by Jetske** [comment]
@susanodd no it looks like a random error to me. I can't reproduce this so let's close it.

**Comment by Jetske** [comment]
Not completed
