### ISSUE TITLE
"Create citation form image" broken

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1349]
Some kind of nme field error pops up when clicking the button to create a citation form image in edit mode. I'll try to fix it, it's probably something small. Could be related to #1346 ?

**Comment by susanodd** [comment]
> Some kind of nme field error pops up when clicking the button to create a citation form image in edit mode. I'll try to fix it, it's probably something small. Could be related to #1346 ?

It could be an element id that it's reused or referenced in the javascript for record videos? (I can't control the record script that's there because it doesn't work for Ubuntu nor MacOS. So it could be that an element id was missed.)

**Comment by susanodd** [comment]
I tried looking at places in the code where the GlossVideo object is used. Sometimes PyCharm doesn't like the code:

![type_error_video_path_PyCharm](https://github.com/user-attachments/assets/60e01e52-f255-426e-9559-168b441321a6)

**Comment by susanodd** [comment]
I don't know what Django actually does when there are such type errors. Other code also has these kind of flags.

**Comment by Jetske** [comment]
Well the error I got is in how the gloss is retrieved, so something different. 

But I wanted to fix it using signbank-jetske but it broke down, so I might need your help on that if you're around today/tomorrow.

**Comment by susanodd** [comment]
> Well the error I got is in how the gloss is retrieved, so something different.
> 
> But I wanted to fix it using signbank-jetske but it broke down, so I might need your help on that if you're around today/tomorrow.

Okay, I'll be there in the afternoon.

All the gloss retrieval methods need the check that archived=False. That is (should be) used in the get methods for the views. It could be that one place has forgot that and it ends up still inside of (frozen) queries. The constraints still apply to archived glosses. Some code also includes archived glosses in order to check constraints on lemmas and annotations. (So a gloss could be visible then later not visible because of control flow.)

And the GlossVideo object retrieval needs to ignore the NME Videos and the Perspective Videos. (Those are similar to how Morphemes are retrieved, which are a subclass.) It could be that something got messed up during git merge since we were both updating the models at the same time.

**Comment by susanodd** [comment]
Check this method:

https://github.com/Signbank/Global-signbank/blob/7dd05ee6933e0fc87c39ac0b751c91edc86937cb/signbank/dictionary/templates/dictionary/gloss_detail.html#L790-L791

https://github.com/Signbank/Global-signbank/blob/7dd05ee6933e0fc87c39ac0b751c91edc86937cb/signbank/dictionary/models.py#L2376-L2380

**Comment by Jetske** [comment]
@susanodd how is that relevant to this issue?

**Comment by susanodd** [comment]
> @susanodd how is that relevant to this issue?

It's possible that an empty path is generated. (I revised some of the code with print statements because it's having trouble with creating this:
```

Video file: /var/www/writable/glossvideo/tstMH/KA/KAAS-8822.mp4
ffmpeg -v quiet -i /var/www/writable/glossvideo/tstMH/KA/KAAS-8822.mp4 -filter:v scale='iw*max(1,sar)':'ih*max(1,1/sar)' /var/www/writable/tmp/signbank-ExtractMiddleFrame/KAAS-8822.mp4-frames/all/frame-%5d.png
convert /var/www/writable/tmp/signbank-ExtractMiddleFrame/KAAS-8822.mp4-frames/middle/KAAS-8822.png -resize x180 /var/www/writable/tmp/signbank-ExtractMiddleFrame/KAAS-8822.mp4-frames/middle/KAAS-8822_320x180.png
Generating still images succes!
```


But here, in the loop that looks for the citation image, it does not find the one just created, it only tries to find a jpg one.

```
        for extension in settings.SUPPORTED_CITATION_IMAGE_EXTENSIONS:
            imagefile_path = videofile_path_without_extension.replace("glossvideo", "glossimage") + extension
            imagefile_path_exists = os.path.exists(os.path.join(settings.WRITABLE_FOLDER, imagefile_path))
            print('image path: ', imagefile_path)
```

`image path:  glossimage/tstMH/KA/KAAS-8822.jpg`


(I don't know why it's not trying 'png'.)

**Comment by susanodd** [comment]
I can't find where the initial "annotation" for the video file name is coming from. All the models in videos/models.py use "super" in the save methods.
And the "super" of `GlossVideo` is just `models.Model.`

**Comment by Jetske** [comment]
That problem is more related to #1346 so let's continue the discussion there. 

This issue was about the button on the gloss details page giving an error, that is now fixed.
