### ISSUE TITLE
Link Wordnet to Signbank

### ISSUE THREAD

**Issue by Jetske** [Signbank/Global-signbank#1350]
Add "Wordnet synsets" under senses

https://www.sign-lang.uni-hamburg.de/easier/sign-wordnet/index_ngt.html

E.g. 
https://www.sign-lang.uni-hamburg.de/easier/sign-wordnet/sign/ngt.1863.html
this page has a link to signbank -> do this in reverse in signbank, but instead don't link to the gloss but to every synset of that gloss

With a list like this:
![image](https://github.com/user-attachments/assets/c2c1f113-383c-41f7-a689-95ddb704c426)

**Comment by Jetske** [comment]
![image](https://github.com/user-attachments/assets/b3be28cd-d21e-4f74-a7bf-887f20687df7)

Okay I fixed the missing lemmas and descriptions with web scraping the urls that do work. It works, but is probably not really ideal as it takes quite long and there's a risk of too many requests. 

@Woseseltops @vanlummelhuizen if you have ideas let me know

**Comment by vanlummelhuizen** [comment]
@Jetske First a small technical remark/question about your command. In method `download_links_csv` you start a context with `with ...`:

https://github.com/Signbank/Global-signbank/blob/2c32b7f9377ac2bbc9da401f08c3fe57a50c7643/signbank/dictionary/management/commands/update_wordnet_links.py#L41-L48

It seems to me you end it prematurely on line 48. 

---

If I correctly understand what you are trying to do, I think it boils down to two questions:

1. When should the script run? Once a day, every hour or triggered by an event?
2. What should be done and what not? Can the script skip parts if they are not necessary at that time, so that it runs faster?

Depending on the answers we could find a better solution.

**Comment by Jetske** [comment]
@vanlummelhuizen Yes, that can probably be done without the 'with'

I would say ideally once a day. Everything should be done, as it is meant to update the synsets according to new versions of the different files that are downloaded. Each of these files may contain changes.

**Comment by Jetske** [comment]
Yes, to prevent too many requests it's probably better to check which links are updated and only edit the synsets in case of changes, rather than what is done now (delete everything and make again).

**Comment by Jetske** [comment]
@vanlummelhuizen done, now it just deletes the links between glosses and synsets and creates them again. The synsets themselves are not deleted, except if they are not used anymore. Only for new synsets it makes a web scrape request, if it could not be found in wordnet. That should make it much more efficient.

**Comment by Woseseltops** [comment]
Sam Bigeard emails me about this

> A head-up: I remember you automatically collect a CSV file from https://signwordnetannotation.pythonanywhere.com/ to get wordnet links for your signs. I changed the format of one of those files today. I'm guessing you only use the file "links_auto_generated.csv", in which case you can just ignore this message, as this file is unchanged. If you also use the file "signs_auto_generated.csv" then I removed fields related to our back-end which are unlikely to be of use to anyone.
