### ISSUE TITLE
archived glosses or deleted glosses

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1375]
I noticed that glosses aren't deleted anymore but now archived. This is great, as a colleague accidentally deleted a gloss and I was able to retrieve it. However, sometimes we really want to delete a gloss and/or lemma because we want to add a complete new entry with the same gloss and/or lemma (and that would be easier than adjusting the whole entry). I think for the deletion of a lemma, the deletion of the glosses is first needed. How do we now delete the glosses?

**Comment by susanodd** [comment]
> I noticed that glosses aren't deleted anymore but now archived. This is great, as a colleague accidentally deleted a gloss and I was able to retrieve it. However, sometimes we really want to delete a gloss and/or lemma because we want to add a complete new entry with the same gloss and/or lemma (and that would be easier than adjusting the whole entry). I think for the deletion of a lemma, the deletion of the glosses is first needed. How do we now delete the glosses?

This probably needs to be done in the management section. This is because there are lots and lots of other objects that potentially refer to the "to be deleted gloss".

We need to discuss this on our side. There are also a bunch of "signals" sent to other code when a gloss is deleted.
The archival was implemented in such a way so that nothing was done with the video files. They are just not shown. But if a gloss really is deleted, there is an avalanche of other objects being deleted. For example, senses, lemmas, lemma translations, sentences, gloss video (objects).

**Comment by uklomp** [comment]
So... in short: delete does not delete, and you need to talk about it on your side? let's talk about it the next meeting.

**Comment by susanodd** [comment]
Normally, if an object is deleted, all the related objects are also deleted. Related objects are previewed in the "Delete popup" of Gloss Edit if you choose the delete the sign.

Multiple choice

- just go ahead and delete all the related "cascaded delete" objects as well
- the user first deletes related objects by hand prior to deleting to make sure there are no surprise side effects
- since most relations are symmetric, delete the relations, make sure the related gloss doesn't need this
- the user deletes videos if they exist
- make sure deleting morphology where the morphemes are not used by other glosses does not delete the morphemes

**Comment by Woseseltops** [comment]
After discussion with @susanodd , could 'cleaning' an existing gloss also solve your problem? So an existing gloss looks identical again to a fresh gloss, as if you just made it.

**Comment by susanodd** [comment]
Teams Update

A Delete option will be offered in the Summary of the Lemma where you the glosses that share the lemma are shown.
That is where you can Restore a gloss. So it will also be possible to Trash a gloss.

**Comment by susanodd** [comment]
@Woseseltops ter informatie, this is what is logged when the "real delete" is done. I have DEBUG_VIDEOS turned on.
As you can see, something is wrong with reversion still. The paths are messed up. The deletion is triggered by gloss delete.

<details>

```
__str__ GlossVideo:  glossvideo/tstMH/KA/KAAS-4611.bak11025.bak
delete_files pre_delete:  glossvideo/tstMH/KA/KAAS-4611.bak11025.bak
delete_files settings.DELETE_FILES_ON_GLOSSVIDEO_DELETE:  False
__str__ GlossVideo:  glossvideo/tstMH/KA/KAAS-4611.mp4
delete_files pre_delete:  glossvideo/tstMH/KA/KAAS-4611.mp4
delete_files settings.DELETE_FILES_ON_GLOSSVIDEO_DELETE:  False
```

**Comment by susanodd** [comment]
![trash-button-next-to-archived-gloss-lemma-view](https://github.com/user-attachments/assets/3c246956-a203-455f-bbb4-4dbedd8c1006)

**Comment by susanodd** [comment]
This is live now.

**Comment by uklomp** [comment]
Yes, works exactly as it should be. Thanks.
In the pop-up message for deletion, it says 'Je verwijdert zo deze aantekening.' - aantekening should be 'glos'.

**Comment by susanodd** [comment]
> Yes, works exactly as it should be. Thanks. In the pop-up message for deletion, it says 'Je verwijdert zo deze aantekening.' - aantekening should be 'glos'.

It sounds like the translations are ambiguous. I need to check them. I haven't done that for a while.

**Comment by susanodd** [comment]
I fixed the translation. It was actually written as you say, a bad case of copy paste from translations for deleting comments.
