### ISSUE TITLE
BUG: NMM video is being displayed instead of Glos video

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1383]
For example: 

https://signbank.cls.ru.nl/dictionary/gloss/47011

I have only uploaded NMM video, but not deleted it. For now I am seeing only NMM video, while glos video has not been removed. There is also still from the Glos video.

**Comment by susanodd** [comment]
> For example:
> 
> https://signbank.cls.ru.nl/dictionary/gloss/47011
> 
> I have only uploaded NMM video, but not deleted it. For now I am seeing only NMM video, while glos video has not been removed. There is also still from the Glos video.

I see it. Do you know if the Annotation was changed? Did it used to be ABSTRACT without an A or B ? There is a video for a different ABSTRACT that does not exist anymore.
Maybe something is archived so does not show correctly. 

It must be fetching the wrong file for some reason.

**Comment by uklomp** [comment]
I know that this was the case for ABSTRACT but I also see it now here, where we didn't change the annotation:
https://signbank.cls.ru.nl/dictionary/gloss/46337/

**Comment by susanodd** [comment]
I had to modify the object retrieval. The subclass was not working.

Is it true that there is no normal video for the gloss?

The nme video file was moved to be the name of a normal video.
It used to have the correct name. There is an extra video without the -A or -B.

I can remove the video or else restore it to the correct filename?

**Comment by rem0g** [comment]
Yes,you can do anything you want with videos. 

I have reupload videos to the affected glosses with signCollect. Everything is ok for now. 

What can I do to detect this anomalies in the future?

**Comment by susanodd** [comment]
> At ABSTRACT-B, user states Lemma was changed and that happened.

Okay, something probably happened there. When the lemma is updated, it has a signal that moves around the video files.
(The folder may change name and the filename may change.) I will check if that is correct.

**Comment by susanodd** [comment]
> Yes,you can do anything you want with videos.
> 
> I have reupload videos to the affected glosses with signCollect. Everything is ok for now.
> 
> What can I do to detect this anomalies in the future?

I made a page to display all the gloss video object paths.
You need to be on Signbank to view it.
Manage Datasets -> NGT -> Manage Video Storage

https://signbank.cls.ru.nl/datasets/checks/5

It shows what is stored internally in the objects.

We are in the process of fixing the filenames for backups (you see them with bak bak patterns) so these will be changed and the files renamed.

**Comment by susanodd** [comment]
If you see a path that is totally wrong, in order to delete the wrong file/path/object you need to do this in Gloss Detail and delete the video.
If there was previously a backup video, all of a sudden a previous video will be shown. So you may need to do the "delete" several times.
The "delete" was implemented as an "undo" for a new upload.

(For really old videos the files could have disappeared already, with switching servers in the past. It could be on backup elsewhere if you find something that is missing that you don't have.)

The new video upload (that's for the gloss) uses the same code that is making the "bak" files. So some things may end up working differently. We typically test on tstMH not on NGT.

**Comment by susanodd** [comment]
@rem0g can you upload the normal video again?

There was something messed up and the "backup" video turned out to be the NME video.
So I downloaded it and then uploaded it again as an NME video.
But then the normal video disappeared.

I think there were multiple links to the same file.

The perspective videos are still there, you can see them in gloss edit in the lower area of the left column if you are in Gloss Edit.
But because the "normal" video is gone, you can't click on the icons to see them.
(Although the icons are visible.)

**Comment by rem0g** [comment]
I have reuploaded the video again!

**Comment by susanodd** [comment]
Okay, thanks!

This should be fixed now.

I moved all the backup files to the correct paths (for all the datasets).

The new (non-zip) upload uses the same code as the code that makes the backup file. So hopefully that is all working correctly now.
I also updated the code that is run when the lemma is changed. So that should also be working.

**Comment by susanodd** [comment]
@rem0g I fixed the video filenames with weird 7-characters. There were three.

It happens if the video file exists but without a corresponding GlossVideo object. That has been patched so that if a video is uploaded but the file name already exists, but no GlossVideo object is there, it will erase the existing file before uploading the new one.

I added another patch that lazily creates the GlossVideo object if it finds a video file with the correct name but no object.
That happens lazily in the Gloss List view and the Gloss Detail view. (I already let it retrieve and create the objects just by searching.)

This can happen (that a video file is stored, but no GlossVideo object has been created) this can happen if a transaction does not complete because the database gets locked.

The repairs should fix themselves.

If you notice that there is one of these paths, you can fix it by using GlossDetail. Download the video just to be safe.
Then delete the video. And it will find the "correct video path" and create the object. That's how I restored them. Now they have the correct filename again.

**Comment by susanodd** [comment]
This should be working okay now.

**Comment by uklomp** [comment]
@rem0g can we close this? :)
