### ISSUE TITLE
Video Still Choices When Creating Poster Image

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#1392]
As discussed in Team meeting.

@uklomp This is available on `signbank-susan`, as a button in Gloss Edit, next to the Create ("middle frame") button that already exists.

(Screenshots: https://github.com/Signbank/Global-signbank/pull/1393#issuecomment-2494277118)

See if the number of images at 15 fps is sufficient to choose from.

<details>
Since it takes time to generate the images, and they need to be viewable in the browser, there are two buttons inside the pop-up. One to generate the images and one to show the images. Then you can hover over them to choose.
A button at the bottom of the popup is for saving your selection. If you click Dismiss, and exit the modal, you can see the images when you open the modal again. They're deleted after you choose.

**Comment by susanodd** [comment]
@uklomp this has been deployed to signbank

**Comment by uklomp** [comment]
I think we agreed on not having the multiple buttons (generate still), and also on having less stills, right? 
so: when I click 'choose image' I already expect the stills to be there. It's okay if they still need to load (although it would be good to have the text 'images are being loaded' or something like that) but it's not necessary to then still click 'generate' in my opinion.
Then: I asked for 3 stills, you gave me 15 first, but now there are 45. That's too much, because now I need to scroll to see them all and there are too many options. Let's stick to 9 for now, so I can see them in a 3 by 3 display.

**Comment by susanodd** [comment]
> I think we agreed on not having the multiple buttons (generate still), and also on having less stills, right?
> so: when I click 'choose image' I already expect the stills to be there. It's okay if they still need to load (although it would be good to have the text 'images are being loaded' or something like that) but it's not necessary to then still click 'generate' in my opinion.
> Then: I asked for 3 stills, you gave me 15 first, but now there are 45. That's too much, because now I need to scroll to see them all and there are too many options. Let's stick to 9 for now, so I can see them in a 3 by 3 display.


The "choose image" is the original button. "Choose still" opens a model. There is only one button inside of the modal.

The number of stills is dependent on the length of the video. If the video is long there are more stills.

(The computer can't know which are the interesting images. If one tries IJSBEER there probably aren't enough since the middle bit is the part between IJS and BEER.)

I will let @Woseseltops decide. He approved it as it is now.

**Comment by Woseseltops** [comment]
> I think we agreed on not having the multiple buttons (generate still), and also on having less stills, right? so: when I click 'choose image' I already expect the stills to be there. It's okay if they still need to load (although it would be good to have the text 'images are being loaded' or something like that) but it's not necessary to then still click 'generate' in my opinion. 

I think so too, just reviewed the pull request by @susanodd to remove the final button as well :)

> Then: I asked for 3 stills, you gave me 15 first, but now there are 45. That's too much, because now I need to scroll to see them all and there are too many options. Let's stick to 9 for now, so I can see them in a 3 by 3 display.

This is an interesting problem to work on! Which stills do we choose as options? Proposal: let's cut the video in 8 equal pieces, and then perhaps some more cuts for the middle pieces because the best still is more likely to be near the middle. So I want to see the stills from:
* 13%
* 25%
* 38%
* 44%
* 50%
* 56%
* 62%
* 75%
* 88%

Do you have another view @uklomp ?

**Comment by uklomp** [comment]
No, sounds good!

**Comment by Woseseltops** [comment]
Or just generate all stills with ffmpeg, and just use Python to select the ones to show to the customers

**Comment by susanodd** [comment]
This is implemented now. There's a pull request but it's not put on a development server yet.

**Comment by susanodd** [comment]
@uklomp this is live now on Signbank.

It shows 9 still images.

**Comment by uklomp** [comment]
perfect! thank you!
