### ISSUE TITLE
delete empty sense group 

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1410]
We are now happily using the tool Split up Senses, and sometimes we regroup them in a way that we have less senses than before. When it saves, there is still an empty sense group (number): 

![image](https://github.com/user-attachments/assets/a0e48810-81b7-42a0-9358-64675c085b0b)
 
Please delete this empty group automatically.

**Comment by susanodd** [comment]
Okay.

Btw, It's possible to delete this by hand if you click on update/save in the Matrix area.

Because of the way it's viewed, there always needs to be empty cells created to allow filling in the table.
So extra cells are created duing editing.
They aren't deleted until you are finished editing.
Probably the above can be detected when the state changes to be as shown.

**Comment by susanodd** [comment]
This is fixed. It's a pull request now.

**Comment by susanodd** [comment]
@uklomp This is live now.

**Comment by uklomp** [comment]
thank you
