### ISSUE TITLE
search query doesnt work with split up senses

### ISSUE THREAD

**Issue by uklomp** [Signbank/Global-signbank#1427]
my colleague tries to find glosses starting with a B to start working on the 'split up senses tool' and first it worked, but they didn't get all the results so they tried again and now it's not working anymore. In multiple browsers: firefox and chrome.

![image](https://github.com/user-attachments/assets/a81b1fa1-beb3-4777-bc74-8ba52da49fda)

they got this result: 

![image](https://github.com/user-attachments/assets/a8bd33f9-d3e6-4f34-976a-446e6a31443b)

**Comment by susanodd** [comment]
I think I found the bug. There is a setting MAX_SCROLL_BAR that is interfering with the search results. The setting is very old. It is being used in the code of GlossListView.

**Comment by susanodd** [comment]
@uklomp this is live now

If you still experience anything strange, please keep track of the sequence of commands.

The fix assumes you:
do the "gloss search" then immediately go to the Split Up Senses page (i.e., using the results you just obtained)

The search results are stored in a session variable.

<details>

Otherwise,
For example,

If you do the search but do something else before going to the Split Up Senses page, we need to know the sequence.

Say, if you do a search, look at some glosses, etc., then go to Split Up Senses.

Keep track of the "stuff in between". Also if you have multiple windows open. The results are stored in a session variable.

(That would be some "other" part of the code is changing the search results or resetting the search type before you get to Split Up Senses.....

**Comment by uklomp** [comment]
thanks! I will ask my colleague if it works now.
