### ISSUE TITLE
name 'get_two_letter_dir' is not defined when uploading videos

### ISSUE THREAD

**Issue by rem0g** [Signbank/Global-signbank#1432]
<html>
<body>
<span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">"\n\n\n<span> </span></span><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n<span> </span></span><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n<span> </span></span><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n<span> </span></span><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n \n<span> </span></span><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n \n\n\n</span><div id="\&quot;summary\&quot;" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">\n<h1>NameError\n at /dictionary/api_update_gloss/46566/video</h1>\n<pre class="\&quot;exception_value\&quot;">name 'get_two_letter_dir' is not defined</pre>\n \n\n \n \n \n \n \n \n \n \n\n \n \n \n \n\n \n \n \n \n\n\n \n \n \n \n\n\n \n \n \n \n\n\n \n \n \n \n\n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n
Request Method: | POST
-- | --
http://signbank.cls.ru.nl/dictionary/api_update_gloss/46566/video
4.2.17
NameError
name 'get_two_letter_dir' is not defined
/var/www/repo/signbank/video/models.py, line 153, in get_video_file_path
signbank.api_token.wrapper
/usr/bin/uwsgi
3.12.2
['.',\n '',\n '/usr/lib/python312.zip',\n '/usr/lib/python3.12',\n '/usr/lib/python3.12/lib-dynload',\n '/var/www/env/lib/python3.12/site-packages']
Fri, 13 Dec 2024 14:46:43 +0100

\n</div><span style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">\n\n\n\n\n</span><div id="\&quot;traceback\&quot;" style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">\n</div>
</body>
</html>

**Comment by susanodd** [comment]
The code was changed in #1390.

Maybe it is using an older compiled python file. (?)

@vanlummelhuizen deployed the code on the server for that request and the new 

There were some glitches with deployment because of changes to the settings recently. When that happens, Django doesn't actually deploy the files and reports a merge conflict (because the server also has its own settings that are different than GitHub, because of the secret key setting.)

You need to wait until Monday to resolve. @vanlummelhuizen can check if something didn't deploy.

The server has been restarted a number of times with the revised code. So it would likely be that an old compiled python file is somehow being used. The function it is referring to used to be inside the file. But now it is imported from a common file.

**Comment by susanodd** [comment]
The code was changed in #1390.

Maybe it is using an older compiled python file. (?)

@vanlummelhuizen deployed the code on the server for that request and the new Synset links.

There were some glitches with deployment because of changes to the settings recently. When that happens, Django doesn't actually deploy the files and reports a merge conflict (because the server also has its own settings that are different than GitHub, because of the secret key setting.)

You need to wait until Monday to resolve. @vanlummelhuizen can check if something didn't deploy.

The server has been restarted a number of times with the revised code. So it would likely be that an old compiled python file is somehow being used. The function it is referring to used to be inside the file. But now it is imported from a common file.

(GitHub is actually blocking as I write this. It's been trying to reload for about 10 minutes.)

**Comment by Woseseltops** [comment]
Fix is live!
