### ISSUE TITLE
Create new record by duplicating an existing one

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#150]
Sometimes a new form has to be entered that is highly similar in e.g. phonology to an existing form. It would be convenient if we would have a 'duplicate sign' function. By a separate button in the detail view, or by a menu item under Sign? The gloss could be SOURCEGLOSS-duplicate, for instance, reminding the user to alter it right away.

**Comment by susanodd** [comment]
@ocrasborn do you want this to be restricted to the same dataset? Perhaps, not.

**Comment by susanodd** [comment]
This is nearly done.

**Comment by susanodd** [comment]
This issue has become related to #851 and #544.
Creating a new gloss from another needs to fill in the new fields.
I noticed that if something is left blank in the new copy gloss, it breaks the gloss list (hence CSV) and the sorting.
This is because those rely on fields not being empty.
I coded the copy-gloss function at the object level rather than via a form. While working on this, I accidentally created a bunch of gloss copies on my local signbank. Then these ended up inaccessible, but the software doesn't actually complain. We have assumed that the user will fill in the required fields themself.
I started out using the "-duplicate" suffix as shown above.
But this will also best make use of the "copy annotation fields to lemma fields" as requested by @ocrasborn in #869.
Then things won't be left empty by accident.

**Comment by susanodd** [comment]
@ocrasborn is there any desire to be able to use this functionality cross-dataset?

At the moment, I've added a "Copy" button to the Gloss Detail View.
That has the effect of 

1. creates a gloss as described in the issue (with -duplicate suffixes in the annotations).
2. copies the phonology fields to the new gloss
3. copies the dataset by way of the Lemma -- (recall that the dataset is a field of lemma)

At the moment, the new gloss then falls underneath the same lemma as the original one (in the same dataset)

Creating a gloss with identical phonology (copy gloss) requires that the new gloss is created before copying the phonology into the fields.

At the moment, the user has no means to change the dataset (via the lemma) of the gloss.
This was to avoid users hijacking signs.

**Comment by susanodd** [comment]
@ocrasborn if you desire to have this work cross-dataset, then it would probably need to be with two Gloss Detail Views adjacent on the screen, to see both glosses from both datasets. In order to copy-create the user needs to select the original gloss as well as the dataset, and this would likewise apply to the destination if it's a different dataset.

**Comment by susanodd** [comment]
I'll try using an in-between step by way of a modal so once the using clicks on Copy, it will show additional information where the user can choose to create the copy gloss in a different dataset.

**Comment by susanodd** [comment]
It's working now.

![copy-gloss-modal](https://user-images.githubusercontent.com/24272544/212914763-d41ebfdb-b38a-4259-9b80-dfa4ea4fd782.png)


![copy-gloss-to-other-dataset-edit-view](https://user-images.githubusercontent.com/24272544/212914806-df0c9fb3-21d6-4d37-9609-39091e60dd3c.png)

**Comment by susanodd** [comment]
And if you want to copy a gloss that is already a duplicate, it shows the feedback

![copy-gloss-already-duplicate](https://user-images.githubusercontent.com/24272544/212915861-2d70b8ee-726e-49f5-8100-e7e2afa2aaea.png)

**Comment by susanodd** [comment]
The copy gloss popup now looks like this:

![copy-gloss-source-target-dataset](https://user-images.githubusercontent.com/24272544/213141959-f44412e9-026d-4ed8-9076-0cb7e4c96349.png)

![copy-gloss-edit-new-gloss-top](https://user-images.githubusercontent.com/24272544/213141983-0399f569-f540-4db7-8ca1-7e6588f09a38.png)

**Comment by susanodd** [comment]
This has been pushed to branch `copy_gloss`

**Comment by susanodd** [comment]
**Note to Others**

Some preliminary patching to find variants code in views.py was included in the last push. (Not relevant to this issue.)

**Comment by susanodd** [comment]
This is live now.

**Comment by ocrasborn** [comment]
Thanks @susanodd
