### ISSUE TITLE
Implement search result bar cf. FinSL Signbank

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#182]
In the detail view, show a scrollable bar above the present template's info so that users can quickly navigate to earlier/later signs (search hits).
- See screenshot
- See https://github.com/Signbank/FinSL-signbank/issues/106
- See also https://github.com/Signbank/FinSL-signbank/issues/142 (centre current hit)
- any other related FinSL issues?
  ![screenshot 2016-07-04 16 25 05](https://cloud.githubusercontent.com/assets/10242207/16563943/223343b0-4205-11e6-9965-65bc7e50056e.png)

**Comment by Woseseltops** [comment]
I resisted the temptation to reinvent the wheel myself, but instead looked at the implementation by @henrinie , really liked it, and copy-pasted it bit by bit. It was spread out over several places, and it took some small adjustments to get it work in the NGT-Signbank, but it's there!

I'm not sure yet about how this new bar integrates with the rest of the elements on the page; let's discuss when you're back @ocrasborn .

**Comment by ocrasborn** [comment]
I think it's nice, @Woseseltops :-)
Let's save some vertical pixels by removing the string "Search results" at the top left; it scrolls out of view anyway, and users will quickly understand what it is and how it works.

**Comment by Woseseltops** [comment]
Agreed, done

**Comment by ocrasborn** [comment]
I just noticed that the text in the buttons in the bar use the field Lemma Gloss, rather than Annotation ID Gloss: Dutch. Please change it to use the latter. Or even better: use Annotation ID Gloss: Dutch when language is set to Dutch, and Annotation ID Gloss: English when language is set to English or Chinese.

**Comment by Woseseltops** [comment]
Good one. I changed it now so that the search results in the detail view use the annotation ID gloss field. This field contains the Dutch gloss names for the NGT Signbank, and English gloss names for the ASL Signbank.

As for using a different annotation ID field based on interface language, let's organize my mind on how everything works first. I think we have 3 unrelated language systems, being:

1. The interface language (Django feature)
----------------------------------
The NGT Signbank
* Dutch
* English
* Chinese

The ASL Signbank
* American English


2. The sign language (Signbank feature)
----------------------------
The NGT Signbank
* NGT
* Possibly some Chinese sign languages

The ASL Signbank
* ASL


3. The spoken language used to describe a particular gloss (NGT-Signbank feature)
--------------------------------------------------------------------------------
||NGT Signbank|ASL Signbank|
|------|-------|------|
|Main field|Dutch|English|
|Extra field|English|-|

What we want is to use a different field from system 3, based on what is used from system 1 (and later this might also be influenced by system 2). That means we need to define the link between system 1 and 3 somewhere, something like this:

NGT Signbank
* Interface language Dutch? Use main field
* Interface language English? Use extra field
* Interface language Chinese? Use extra field

ASL Signbank
* Interface language English? Use main field

Agree that this is the way to go, @ocrasborn ?

**Comment by henrinie** [comment]
Wow, you have really analysed the situation well.

I am not completely aware how you use these different fields in practise, but can't you just use the idgloss field (or whatever is the field name for the MAIN gloss name) for this. It would always be of the written language that is used in the lexicon.
I'd think that you wouldn't need to take into account the language chosen for the user interface, aren't the users interested in the gloss names since they are searching for them?

I would try to keep it simple and not make any extra fields. You might not need this 'feature' after all.

**Comment by Woseseltops** [comment]
> It would always be of the written language that is used in the lexicon.

That's the situation as we have it now, yes :). I agree that it covers most use cases. 

> You might not need this 'feature' after all.

I think a reason to have the feature would be when a non-Dutch speaking researcher is using the NGT-Signbank, and wants to know the meaning of all glosses. They would use and search for the 'extra annotation id gloss' field for this, because this one has the English variants (so they can see that the gloss BAL-A is BALL-A in English). However, the search result bar would only show the 'main annotation id gloss' (so BAL-A), which means that this researchers would have to click every result in the bar to know what it means.

**Comment by ocrasborn** [comment]
@Woseseltops , I think it would be good to discuss this again among the three of us when @vanlummelhuizen will take up the issues under milestone 6 (https://github.com/Signbank/NGT-signbank/milestone/6), sometime early next year. We can then get @henrinie 's input before we start implementing.

**Comment by ocrasborn** [comment]
Any reason to keep this open, @vanlummelhuizen and @Woseseltops ? I think no one is complaining about how it is currently implemented.

**Comment by vanlummelhuizen** [comment]
Ok, let's close it.
