### ISSUE TITLE
Put the Signbank package and patch function behind authentication

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#189]
This is a sub-issue for #186 .

**Comment by vanlummelhuizen** [comment]
I investigated some possibilites. It doesn't seem easy to use the existing authentication backend for a REST-like API thing like the package functionality. Using complete REST frameworks seem overkill.

The idea I have now is to use Signbank's existing login/authentication functionality in ELAN. This would require getting a login form cookie as well as a CSRF-token. With these a POST to /accounts/login, also including username and password, should work. ELAN's http client can hold the session cookie and use it for subsequent requests.

@Woseseltops @henrinie Do you have any comments?

**Comment by vanlummelhuizen** [comment]
I have this working now for the /dictionary/package part. @ocrasborn I assume we also want the serving of videos and images behind authentication. I think this could be combined with #163, i.e. videos and images should be served by Django instead of static.

**Comment by ocrasborn** [comment]
@vanlummelhuizen : yes, we do.

**Comment by henrinie** [comment]
@vanlummelhuizen I have somehow missed this conversation. This is embarrassing because you always answer my questions. I am terribly sorry for this.

I believe that the current authentication backend doesn't suit REST API's well, because it is based on sessions, and REST API's are supposed to be stateless.

I assume that you are going to need to process GET requests only, so they should be safe, unless you want to hide the materials including videos, gloss lists, and so on.
What we have decided to do is to not require authentication for ECV or for video-files. At least the videos will most likely be licensed with the CC license which allows pretty much "anything" anyway.
Also using complete REST might be overkill, if you only have to support GET and there is no need to implement HATEOAS (prodiving links to other materials).

So, if you/we need to support only GET requests, you might want to consider doing the same as us. It could save you the burden of having to implement something that might not be needed after all.

> videos and images should be served by Django instead of static.
As far as I know the recommendation seems to be that files are not served by Django. A webserver should rather be used for that.

**Comment by vanlummelhuizen** [comment]
@henrinie I am pretty sure I have some questions for me that are unanswered and just dangling around. If so, please notify me.

For now I have used the standard Django authentication with session in ELAN. Also since @ocrasborn would like to have the media behind authentication. I agree it is not the best solution, but the only one feasible right now. 

Also, the serving of media is now done by Django also because Onno wanted the media behind authentication. In a later stage, we are going to let the webserver do the serving.

**Comment by ocrasborn** [comment]
@vanlummelhuizen , can this issue be closed?

**Comment by vanlummelhuizen** [comment]
Yup.
