### ISSUE TITLE
Revise fields for ASL Signbank

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#195]
@Woseseltops , please revise the ASL fields (and their names) as follows (both detail view and search form):
- Hide following fields from all views: 1) useInstr "Annotation instructions"; 2) domhndsh "Dominant Handshape"; 3) subhndsh "Nondominant handshape"; 4) final_domhndsh "Final Dominant Handshape"; 5) _finalsubhndsh "Final Subordinate Handshape"; 
- Move the two fields "Language" and "Dialect" to a new panel Sociolinguistics, to be put below Syntax & Semantics in detail view and Search form
- Rename "Dialect" to "Regional dialect"
- Move semField "Semantic Field" from Syntax & Semantics to the top in the detail view, below Translation equivalents
- Rename panel Syntax & Semantics to Morphosyntax
- Rename handedness from "Type-of-2-handed signs" to "Handedness"
- Rename locPrimLH from "Placement Active Articulator RH" to "Location - major"
- Add fields under phonology: 1) domSF "Dominant hand - Selected Fingers" [editable list of field choices]; 2) domFlex "Dominant hand - Flexion" [editable list of field choices]; 3) oriChAbd "Abduction change" [binary: yes/no]; 4) oriChFlex "Flexion change" [binary: yes/no]
- Show the following fields under Phonology: 1) initial_secondary_loc "Location - minor 1"; 2) final_secondary_loc "Location - minor 2"; 3) movsh, field name "Path movement". All should be editable lists of field choices in Django.

**Comment by ocrasborn** [comment]
Please use the following order in Phonology:

Handedness
Location - major
Location - minor 1
Location - minor 2
Dominant hand Selected fingers
Dominant hand Flexion
Abduction change
Flexion change
Nondominant handshape
Path movement

**Comment by Woseseltops** [comment]
Done:
* Hide following fields from all views: 2) domhndsh "Dominant Handshape"; 3) subhndsh "Nondominant handshape"; 4) final_domhndsh "Final Dominant Handshape"; 5) _finalsubhndsh "Final Subordinate Handshape";
* Rename "Dialect" to "Regional dialect"
* Rename panel Syntax & Semantics to Morphosyntax
* Rename handedness from "Type-of-2-handed signs" to "Handedness"
* Rename locPrimLH from "Placement Active Articulator RH" to "Location - major"
* Add fields under phonology: 1234
* Show the following fields under Phonology: 123
* Please use the following order in Phonology

Not done yet, because this requires quite a fundamental change (hope to get it done today, or else Wednesday):
* Hide following fields from all views: 1) useInstr "Annotation instructions";
* Move semField "Semantic Field" from Syntax & Semantics to the top in the detail view, below Translation equivalents
* Move the two fields "Language" and "Dialect" to a new panel Sociolinguistics, to be put below Syntax & Semantics in detail view and Search form

Question for @ocrasborn 
* Do we want the new category 'Language & dialect' for the NGT Signbank as well? That would save me some work :).

**Comment by Woseseltops** [comment]
The main section (which is always visible), is now dynamic and thus configurable. I configured it for ASL Signbak so that these are also done:
* Hide following fields from all views: 1) useInstr "Annotation instructions";
* Move semField "Semantic Field" from Syntax & Semantics to the top in the detail view, below Translation equivalents

Not yet done: 
* Language & dialect
* Also linking the new dynamic main section to the search and admin pages.

Other notes: 
* I noticed that sometimes when changes values, I got errors in an alert window. It still works, though, so I'll investigate later what the error means.
* I want to investigate whether I can now remove the FIELDS['other'] .

**Comment by Woseseltops** [comment]
Done:
* Also linking the new dynamic main section to the search and admin pages.
* I want to investigate whether I can now remove the FIELDS['other'] .
* I still have to check whether this works for the Dutch Signbank.

Not done yet:
* Error alerts (ASL-Signbank only)
* Language & dialect

**Comment by Woseseltops** [comment]
Also fixed the error alert problem (turned out to be unrelated to this issue, strictly speaking). Only the langauge & dialect question for @ocrasborn remains.

**Comment by ocrasborn** [comment]
Ah, @Woseseltops , you were waiting for me. Yes, that's fine, please make the Lg/Dialect for NGT cf. ASL. If you would still get around to that in the coming hour, I can inform the US colleagues that everything is ready for importing their data.

**Comment by Woseseltops** [comment]
Yes, I was waiting but forgot about it :).

> If you would still get around to that in the coming hour, 

I was actually working on Signbank when you asked this, but only saw it now :(. Anyway, I quickly changed it in the detail view for both Signbanks. Not sure about the search view: it already kind of has its own section there, I would say?

**Comment by Woseseltops** [comment]
This can be closed, right?

**Comment by ocrasborn** [comment]
yes, think so too

**Comment by ocrasborn** [comment]
1) Some of the phonology field labels have reverted to old ones (I think) with the latest updates, please repair:
- Rename "Placement Active Articulator LH" to "Location - major"
- Rename "Initial Subordinate Location" to "Location - minor 1"
- Rename "Final Subordinate Location" to "Location - minor 2"
The order can stay as it is now.
2) The three fields above should each be connected to their own list of field choices. The first one can stay as it is, but new field choice lists have to be created for the latter two.

**Comment by vanlummelhuizen** [comment]
For 1: this can be done in the translation files. If I take a look in the ones for the global signbank I see that in conf/locale/en_US/LC_MESSAGES/django.po the translation is commented out. I guess the same version of the translation files are used on ASL Signbank.

For 2: the generation of the choice list can be done in the /admin. 

Main question for both 1 and 2: is everything the same for Global Signbank and ASL Signbank?

**Comment by ocrasborn** [comment]
@vanlummelhuizen : no, it is not the same: Global SB doesn't use the fields 'minor location 1/2', ASL SB does. And while we conceptually share the field 'major location', we use it differently, so it would be good to keep them apart using different field names, and tagging them somehow for the two different systems (for major location (simply 'Location' in Global SB), that is already done. What needs to change is to modify the field values attached to major vs minor location for ASL.

**Comment by vanlummelhuizen** [comment]
OK, if I understand you correctly, you want fields to be called differently for Global SB and ASL SB. On top of that, you want 2 of the three fields to have different field choices for Global SB and ASL SB. 

For the first, we need to have different translation files for both SB instances. For the second, we could make field choice list with the same name for bot SB instances, but they would contain different choices.

@Woseseltops any thoughts?

**Comment by ocrasborn** [comment]
Just to be sure, let me spell them out:
* Global SB
** Location ~ Field choices 1
ASL Signbank
** Major location ~ Field choices list 2
** Minor location 1 ~ Field choices list 3
** Minor location 2 ~ Field choices list 3

**Comment by vanlummelhuizen** [comment]
But Field choices 1 and Field choices list 2 could be the same thing if their contents (the actual field choices) are different, right? 
Also, Field choices list 3 could be in Global SB, it is not used anyway.

The reason for this is that it would prevent us making exceptions for the ASL instance. Otherwise, the ASL SB would become more like a fork of Global SB.

If Global SB and ASL SB (and perhaps other SB instances in the future) would diverge more and more, it could make sense to make phonology more dynamic, i.e. not have phonology as hardcoded fields of the Gloss model. Just a thought.

**Comment by Woseseltops** [comment]
> 1. Some of the phonology field labels have reverted to old ones 

Problem with the translation files, as correctly identified by @vanlummelhuizen . The old .po didn't include strings from the Python code (which is where these names are defined) for some reason. I 
* regenerated the .po file; the translations were correctly added gain automagically
* rebuild the .mo file
* restarted Signbank

Now it works.

> The three fields above should be connected to their own list of field choices.

Let me clear up the confusion (at least, I'm confused) by using the actual names:

Location fields used in the Global Signbank:

|Variable name|Full name|Name in the interface|FieldChoice list name|
|---------------------|-------------|---------------------------|-----------------------------|
|locprim|Location|Location|Location|

Location fields used in the ASL Sigbank

|Variable name|Full name|Name in the interface|FieldChoice list name|
|-------------------|-------------|-----------------------------|----------------------------|
|locPrimLH|Placement Active Articulator LH|Major location|Location|
|initial_secondary_loc|Initial Subordinate Location|Minor location 1|Location|
|final_secondary_loc|Final Subordinate Location|Minor location 2|Location|

The desired situation is to change that last column, so the three location fields in ASL no longer share the same list of field choices, right?

|Variable name|Full name|Name in the interface|FieldChoice list name|
|-------------------|-------------|-----------------------------|----------------------------|
|locPrimLH|Placement Active Articulator LH|Major location|Location|
|initial_secondary_loc|Initial Subordinate Location|Minor location 1|MinorLocation|
|final_secondary_loc|Final Subordinate Location|Minor location 2|MinorLocation|

As you can see, none of the three ASL location fields are used by the Global Signbank, so we can change them freely. However, changing the field choice list for the 'minor location' fields would basically mean a reset of these fields, while just by clicking around I can find some signs that have one or both fields set. What should happen with the values already there, @ocrasborn ?

**Comment by ocrasborn** [comment]
A nice table, as always :-). Resetting the fields would likely be OK after having inspected the current contents, which I was not able to do yet as the CSV export only contains NGT/Global fields... So perhaps address that one first, or you could send me an export of the database that you can make in another way.

**Comment by ocrasborn** [comment]
Here's the verdict from the American jury: the letter and number fields can be hidden for ASL, the WD and WP fields should stay. (See table in #434 for a description of all of these.)

**Comment by Woseseltops** [comment]
I'm a bit confused by this, so let me summarize our discussion chronologically:
* The connection between gloss fields and choice lists should change for the ASL Signbank.
* This requires that some existing data is deleted, question was if this is okay. 
* Onno wanted to check the existing data, but the CSV functionality turned out to be broken. This was fixed in #434 . 
* During this fixing, we walked into the general question what to do with a number of handshape related fields that only have a short label, as they are also listed in the CSV. 
* I guess this made Onno wonder if the Americans want the handshape fields at all, and the answer is partly, so that's something to work on.

... but notice that the original question is still open, @ocrasborn :

>  changing the field choice list for the 'minor location' fields would basically mean a reset of these fields, while just by clicking around I can find some signs that have one or both fields set. What should happen with the values already there,

**Comment by ocrasborn** [comment]
Ah right, @Woseseltops! Thanks for alerting me. I had missed that the CSV works again. Just inspected it, and yes, the present values for Location minor 1 and Location minor 2 can be erased, so that they can be linked to a new list of field values.

**Comment by Woseseltops** [comment]
Okay, I did the following:
* Rewired the location fields to field choice lists in both branches of the repository. Forgot that a second action had to be done, so lost quite some time here.
* Added the new field choice list Location Minor, with its 35 or so values.
* Made a backup of the American Signbank, then emptied the now rewired fields for all glosses.
* Verified that this new functionality works.

To do: hide the letter and number fields if they're not specified in the settings.

**Comment by Woseseltops** [comment]
> To do: hide the letter and number fields if they're not specified in the settings.

Four months later, but the setting is there :) . 

I guess this can be closed, right @ocrasborn ?

**Comment by ocrasborn** [comment]
yep
