### ISSUE TITLE
Allow for the selection of multiple Semantic Fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#242]
Currently a drop-down list where one can be selected

**Comment by susanodd** [comment]
This issue is subsumed by #762. It can be closed.

**Comment by susanodd** [comment]
This issue is live.

As described in #762, making the semantic field be multi-select entailed making a new class to support this.
As part of this, semantic fields are now visible in a pull-down menu under Settings.
`https://signbank.cls.ru.nl/dictionary/semanticfields/`
Here you see the (original) translations (obtained from Field Choice) but stored as to be associated with their semantic field object. In this way there can be more translation languages.
`https://signbank.cls.ru.nl/dictionary/semanticfield/5/`
Ultimately users will be able to add additional translations here in order to provide functionality for searching across multiple datasets. At the moment, this can be done in the Admin.
