### ISSUE TITLE
Speed up loading of search results

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#252]
Whole system seems to be slower since a week or six. Related to loading of pictures in search list? Micha thinks not: pics are only loaded when page is built, but nothing happens for a few seconds after selecting search from menu item.

**Comment by ocrasborn** [comment]
Loading the search page costed >20s this morning on Firefox/Mac!

**Comment by ocrasborn** [comment]
Maybe implementing #241 will solve part of the issue?

**Comment by henrinie** [comment]
I am unable to test this for you right now, because the search page doesn't seem to be working at all.

I remember checking your search page a few weeks back and noticing that you have poster images of the size of several Megabytes, so loading the search results caused hundreds of megabytes of image downloads for me at least.

A few ideas for speeding things up:
- Use JPG format images instead of PNG
- Prefetch the translations to reduce the amount of database queries, like in: https://github.com/Signbank/FinSL-signbank/blob/master/signbank/dictionary/adminviews.py#L396
- Change the default results per page number to something like 100 (you have 3000 currently)

**Comment by ocrasborn** [comment]
Thanks @henrinie . (The 3000 is the default alternative, which is a bit unfortunate, but what the search engine actually delivers is 500 right now. We might still cut that down, if it would speed things up, however.)

**Comment by henrinie** [comment]
Another thing that comes that comes to mind:
- Enable caching

**Comment by Woseseltops** [comment]
@ocrasborn can specify what 'it' refers to in the issue title? I see both mentions of 'whole system' and 'search page'. My approach would be drastically different depending on the answer :).

Just for fun (I really like optimizing code) I already did some experiments to see why the search page is so slow:
* About the images: I did an experiment where I disabled the images completely, and the page was still as slow as it was. This means Micha was right; the problem is that it takes too long to generate the page; images are only loaded AFTER the browser already displayed the page. Henri is btw also right that it is quite a lot of mbs we're downloading each time we're showing 500 images.
* Deleting the part of the code that takes 500 glosses extracted from the database as input, and generates an html table as output, was more fruitful: we went from about 9s to 0.5s . This means that the long waiting times arise from turning the template into an actual page.
* By strategically adding and removing code (I could not find a quick and easy tool to profile Django template rendering?), I found that this piece is eating up about 4 seconds:

          {% if gloss.morphemePart.all.count > 0 %}
              {% if gloss.morphemePart.all.count > 2 %}
              <span class="morpheme_in_gloss">({{gloss.morphemePart.all.count}} morphemes)</span>
              {% else %}
                  
                  <div class="morpheme_in_gloss">
                  {% for morphdef in gloss.morphemePart.all %}
                  <span><a class="morpheme_style" href="{{ URL }}/dictionary/morpheme/{{morphdef.pk}}/">{{ morphdef.annotation_idgloss }}</a>{% if not forloop.last %}, {% endif %}</span>
                  {% endfor %}
                  </div>
              {% endif %}
          {% endif %}

          {% if gloss.parent_glosses.all.count > 0 %}
          <div class="component_in_gloss">
          {% for component in gloss.parent_glosses.all %}
          <span><a  class="morpheme_style" href="{{ URL }}/dictionary/gloss/{{component.morpheme.pk}}/">{{ component.morpheme.annotation_idgloss }}</a>{% if not forloop.last %} + {% endif %}</span>
          {% endfor %}
          </div>
          {% endif %}

This code does multiple counts of morpheme parts, and does this for all 500 results, so this might be what's taking so long.

**Comment by ocrasborn** [comment]
Haha, yes, sorry: loading the search page had become very slow in the last... six? weeks. Splitting the loading of the search form and 'show all signs' solved part of this in an indirect way, as the first 500 were always loaded upon loading the search form. But the problem remains with displaying search results, like you found as well, and thus also with loading the 'show all signs' page.

**Comment by Woseseltops** [comment]
>  loading the search page had become very slow in the last... six? weeks

The findings in my previous comment basically mean: for each of the 500 glosses we display at the 'show all signs' page, we iterate twice over all morphemes to see if they belong to this gloss. Each extra morpheme added means 1000 more comparisons. I discovered Inge added around 150 morphemes in December (150*1000 = 150.000 comparisons each time the 'show all signs' page is displayed), which roughly matches the time you said the problem started. 

Some more measurements:

|Temporarily deleted code|Average load time|
|Nothing (current state)|10.16s|
|First part of the code that slows things down (showing morphemes this gloss consists of)|7.12s|
|Second part of the code that slows things done (showing the glosses this gloss is a compound of)|7.11s|
|Both|5.34s|

I already spent considerably time trying to optimize the second part about the compound, but apparently my hypotheses about what was slow exactly were wrong, because things did not go faster. To be continued.

**Comment by Woseseltops** [comment]
I've discovered a Django feature called prefetch_related, which solves exactly our problem of having to do so many separate database requests; it bundles them into 1 query (see https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.prefetch_related) . This indeed helps:

|Situation|Average load time|
|-|-|
|Before optimization|15s|
|After optimization|9s|

I've used the Dutch version for these measurements, because translating also takes some time; the English version is about 2s faster. Another finding is that the page still takes 4s to load even when it's not displaying any glosses (completely removed the forloop), so there's another place somewhere that is eating up performance. Again, to be continued.

**Comment by vanlummelhuizen** [comment]
So I did some experiments of my own. The code that adds at least a few seconds is https://github.com/Signbank/NGT-signbank/blob/25eb23f4718b15115926b092f803455439fd4af6/signbank/dictionary/adminviews.py#L665-L666. I am not sure what it does yet. 

The rest of the load time seems to be due to database queries and template rendering. When selecting only 10 results per page, the load time drops to around 300ms (on my local machine) when the code mentioned above is commented out.

I believe the database we use (SQLite) is slow compared to MySQL or PostgreSQL. Perhaps we could experiment with that?

**Comment by henrinie** [comment]
> So I did some experiments of my own. The code that adds at least a few seconds is https://github.com/Signbank/NGT-signbank/blob/25eb23f4718b15115926b092f803455439fd4af6/signbank/dictionary/adminviews.py#L665-L666. I am not sure what it does yet.

It creates a list of the search results and saves them to session for the "search results bar" on gloss page.

**Comment by vanlummelhuizen** [comment]
So the database is queried twice. This seems redundant.

**Comment by vanlummelhuizen** [comment]
Some more experiments. I printed the query from the queryset and ran it through sqlite in the commandline. It turns out this is very fast: 70ms. So why is the same thing taking ages in Django?

The sql file for testing:
```
.load /usr/lib/sqlite3/pcre.so
SELECT DISTINCT "dictionary_gloss"."id", "dictionary_gloss"."idgloss", "dictionary_gloss"."annotation_idgloss", "dictionary_gloss"."annotation_idgloss_en", "dictionary_gloss"."bsltf", "dictionary_gloss"."asltf", "dictionary_gloss"."aslgloss", "dictionary_gloss"."asloantf", "dictionary_gloss"."bslgloss", "dictionary_gloss"."bslloantf", "dictionary_gloss"."useInstr", "dictionary_gloss"."rmrks", "dictionary_gloss"."blend", "dictionary_gloss"."blendtf", "dictionary_gloss"."compound", "dictionary_gloss"."comptf", "dictionary_gloss"."handedness", "dictionary_gloss"."domhndsh", "dictionary_gloss"."subhndsh", "dictionary_gloss"."final_domhndsh", "dictionary_gloss"."final_subhndsh", "dictionary_gloss"."locprim", "dictionary_gloss"."final_loc", "dictionary_gloss"."locVirtObj", "dictionary_gloss"."locsecond", "dictionary_gloss"."initial_secondary_loc", "dictionary_gloss"."final_secondary_loc", "dictionary_gloss"."initial_palm_orientation", "dictionary_gloss"."final_palm_orientation", "dictionary_gloss"."initial_relative_orientation", "dictionary_gloss"."final_relative_orientation", "dictionary_gloss"."domSF", "dictionary_gloss"."domFlex", "dictionary_gloss"."oriChAbd", "dictionary_gloss"."oriChFlex", "dictionary_gloss"."inWeb", "dictionary_gloss"."isNew", "dictionary_gloss"."inittext", "dictionary_gloss"."morph", "dictionary_gloss"."sedefinetf", "dictionary_gloss"."segloss", "dictionary_gloss"."sense", "dictionary_gloss"."sn", "dictionary_gloss"."StemSN", "dictionary_gloss"."relatArtic", "dictionary_gloss"."absOriPalm", "dictionary_gloss"."absOriFing", "dictionary_gloss"."relOriMov", "dictionary_gloss"."relOriLoc", "dictionary_gloss"."oriCh", "dictionary_gloss"."handCh", "dictionary_gloss"."repeat", "dictionary_gloss"."altern", "dictionary_gloss"."movSh", "dictionary_gloss"."movDir", "dictionary_gloss"."movMan", "dictionary_gloss"."contType", "dictionary_gloss"."phonOth", "dictionary_gloss"."mouthG", "dictionary_gloss"."mouthing", "dictionary_gloss"."phonetVar", "dictionary_gloss"."locPrimLH", "dictionary_gloss"."locFocSite", "dictionary_gloss"."locFocSiteLH", "dictionary_gloss"."initArtOri", "dictionary_gloss"."finArtOri", "dictionary_gloss"."initArtOriLH", "dictionary_gloss"."finArtOriLH", "dictionary_gloss"."iconImg", "dictionary_gloss"."iconType", "dictionary_gloss"."namEnt", "dictionary_gloss"."semField", "dictionary_gloss"."wordClass", "dictionary_gloss"."wordClass2", "dictionary_gloss"."derivHist", "dictionary_gloss"."lexCatNotes", "dictionary_gloss"."valence", "dictionary_gloss"."tokNo", "dictionary_gloss"."tokNoSgnr", "dictionary_gloss"."tokNoA", "dictionary_gloss"."tokNoV", "dictionary_gloss"."tokNoR", "dictionary_gloss"."tokNoGe", "dictionary_gloss"."tokNoGr", "dictionary_gloss"."tokNoO", "dictionary_gloss"."tokNoSgnrA", "dictionary_gloss"."tokNoSgnrV", "dictionary_gloss"."tokNoSgnrR", "dictionary_gloss"."tokNoSgnrGe", "dictionary_gloss"."tokNoSgnrGr", "dictionary_gloss"."tokNoSgnrO", "dictionary_gloss"."creationDate", "dictionary_gloss"."lastUpdated", "dictionary_gloss"."alternative_id" FROM "dictionary_gloss" LEFT OUTER JOIN "dictionary_morpheme" ON ( "dictionary_gloss"."id" = "dictionary_morpheme"."gloss_ptr_id" ) WHERE ("dictionary_morpheme"."gloss_ptr_id" IS NULL AND ("dictionary_gloss"."idgloss" REGEXP '(?i)' || 'A'  OR "dictionary_gloss"."annotation_idgloss" REGEXP '(?i)' || 'A' )) ORDER BY "dictionary_gloss"."idgloss" ASC;
```

The command I used:
```
time sqlite3 ../../../writable/database/signbank.db < ~/tmp/signbank_search_query.sql > /dev/null
```

------
After reading http://blog.etianen.com/blog/2013/06/08/django-querysets/ I used the queryset iterator() method on the code in https://github.com/Signbank/NGT-signbank/blob/25eb23f4718b15115926b092f803455439fd4af6/signbank/dictionary/adminviews.py#L665-L666. That works! I does not take a 3 extra second.

**Comment by henrinie** [comment]
> So the database is queried twice. This seems redundant.
Is it really? On FinSL I don't see any extra queries because of this. Querysets are supposed to be lazy.

We have two additional queries on glosses:
one query for getting the count of glosses, and 
one for getting the tags for each gloss.

**Comment by henrinie** [comment]
> Some more experiments. I printed the query from the queryset and ran it through sqlite in the commandline. It turns out this is very fast: 70ms. So why is the same thing taking ages in Django?

This is most likely not due to one query. I am not sure how deep you guys have looked, but I have optimized the queries somewhat. The thing that was slowing us down the most was zillions of small queries, for example getting tags for each gloss used to be one extra query. So if you were searching for 1000 glosses, you have 1000 extra queries.

You can battle these with prefetch_related, making only one query beforehand for the related objects. Django degug toolbar is a useful tool for looking at the queries of each request. https://github.com/jazzband/django-debug-toolbar

**Comment by Woseseltops** [comment]
Discussed Django and database queries with Erwin this morning, and figured this might be a good moment to pick up this issue again. I had a look at the code again, but can no longer find a quick win where we can make the code that displays the search results smarter; that is, the processing times is the sum of various smaller processing times for individual columns instead of a single bottle neck.

Let's go in another direction. I see two solutions:
* Start experimeting with MySQL as backend instead of SQLite - but it's unclear whether that will work, given @vanlummelhuizen 's finding that SQLite in isolation seems fast enough. If the problem is that we're doing a lot of queries, MySQL might not solve that.
* Only load 10 signs at once at first, and then with AJAX load in more and more results after the page has loaded. This way, you can already look at the first results while the rest is being retrieved.

Have a preference, @vanlummelhuizen ? By the way, is this issue still relevant, @ocrasborn ?

**Comment by Woseseltops** [comment]
Fun fact: with 749MB the database would easily fit into Applejack's memory. Maybe we can utilize that somehow to serve the gloss info faster.

**Comment by henrinie** [comment]
@Woseseltops it seems that postgresql is recommended everywhere in the django community, I would suggest using it instead of MySQL. We used to use MySQL in the past, but had some problems with migrations and moved to postgresql.

Which ever you choose, it will probably be faster than SQLite, especially if your database is on a network drive. SQLite might not do any internal caching too, making it slower compared to a real dbms.

Most of that 794MB is probably django-reversion, so the "real size" might be much less. You could indeed cache the results within django, for example using the fairly simple local memory caching: https://docs.djangoproject.com/en/2.0/topics/cache/#local-memory-caching
If you don't set it up right, it might be confusing for the users who try to update some fields, but they still see the cached values. I would first try other ways of speeding up the queries.

@Woseseltops if you use django-debugtoolbar you can see the queries each view makes. I have tried to minimize the amount of queries made, and it seems to have an effect of the speed in FinSL. In some cases django makes additional queries for every row, and you can end up having thousands of individual queries for one view, preloading those could help speeding things up, but I think you already do that to some extent.

**Comment by ocrasborn** [comment]
Actually, I'm quite happy with the current load times. Now that the images are loaded after the text, it's very usable indeed.
Some images take a long time to load, though: the ones that come from big movies. We compress the standard Signbank movies (white background) to a small file size, but the temporary videos like those from webcams or from other projects (blue-ish background) are sometimes more than 5MB for a few seconds. The resulting image also seems to be large (didn't check). With new datasets from outside users coming in, it might be good to recompress things on the Signbank side. Maybe just for the images: could you check @Woseseltops that indeed these sometimes are larger than need be? Or should we generate stamp-sized images just for the list view?

**Comment by ocrasborn** [comment]
Ah thanks @henrinie !

**Comment by vanlummelhuizen** [comment]
@Woseseltops I think we better first investigate the number of database queries. @henrinie 's suggestion of the debugtoolbar could help.

**Comment by Woseseltops** [comment]
> Now that the images are loaded after the text, it's very usable indeed.

I might be mistaken, but I don't think we changed anything here? As far as I'm aware, browsers always load images after the text.

> Maybe just for the images: could you check @Woseseltops that indeed these sometimes are larger than need be? Or should we generate stamp-sized images just for the list view?

Not sure what is the desired behavior, but I can describe the current state: I see images of various sizes in Signbank. Some common sizes are 658x372, 856x482 and 428x242 . Each time you search, these images are send in full size to your browser, and minimized and cropped on the fly by that browser to create the 115x115x thumbnails. Each time you open a detail page, also these same pictures are sent, but this time the browser only minimizes (if needed). 

What we could create a 115x115 image of every existing and new image, and send these instead?

> I think we better first investigate the number of database queries

Okay, spent some time today installing the toolbar; whether we want to speed thing up or not, this is probably a good idea anyway. It slowed down Signbank quite a bit, so it's not activated by default, but you can see if you uncomment the middleware in base.py . For your local installation you also need to run 'pip install django-debug-toolbar' to get it working. I didn't have the patience yet to wait for the results of the even more slowed down 'all signs' page :) .
