### ISSUE TITLE
Capture videos via webcam

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#266]
Cf. idea by @henrinie , https://github.com/Signbank/FinSL-signbank/issues/212#issuecomment-274079767

**Comment by ocrasborn** [comment]
If there's time left before Sept 1 2019, let's take this over from FinSL Signbank; end of the thread there was that it was stable enough.

**Comment by Jetske** [comment]
![scrsh](https://user-images.githubusercontent.com/10157482/215138713-c5c1e938-778b-4794-bde5-1b61bab35cc4.jpg)

This is what I have now. On the left is the live webcam stream and on the right you can playback the recorded video.

I kind of forgot to use the FinSL version and used WebRTC instead of RecordRCT. If you want though, I can try to switch to that. It takes some time to figure out but it could be more stable. 

The upload button does not always work so I need to figure out why, and maybe also add some checks for a limit to the length/size of the video. And it still needs styling as well. 

But if you have any feedback at this point, let me know.

**Comment by susanodd** [comment]
It looks really exciting!!

**Comment by Jetske** [comment]
![image](https://user-images.githubusercontent.com/10157482/215735379-1bb63d09-d4e0-4013-b0cc-305c58fc8b45.png)

Update: it looks a lot better now and also seems to be quite stable. I tried multiple browsers and had no problems. 

I also added a little figure overlay  to the recording box to guide people where they should be placed in the frame. With webcams I can imagine that people tend to sit too close to the screen or too high.

**Comment by susanodd** [comment]
The video capture via webcam can be added to the Feedback Pages. (#873 is live now)

**Comment by susanodd** [comment]
This is a really nice feature!

@ocrasborn see if this works for you?

(Related. Cross platform browser usage seems to be weird. Chrome upload / Firefox viewing. #886)

**Comment by Jetske** [comment]
@ocrasborn somehow Firefox cannot read the mp4 files recorded in other browsers. The other browsers I tried (IE, Opera, Vivaldi, Edge, Brave) don't seem to have this problem. 

I'm curious if it works on apple though!

**Comment by susanodd** [comment]
@Jetske , this is the error that arises when trying to convert this already uploaded video on the server using the new `convert_to_mp4`:

When a non-mp4 is found, it prints the path and the type (before trying to convert):

`Non-MP4 video file found:  /var/www/writable/glossvideo/tstMH/Fi/Fietsmandje test-44099_gWkW6Em.mp4 application/x-empty`

It thinks the type of the video file is `application/x-empty`

Then this failure:

`/var/www/writable/glossvideo/tstMH/Fi/Fietsmandje test-44099_gWkW6Em.mp4: Invalid data found when processing input`

It succeeded on buffelmozzarella. I'll see if that's visible on Mac later. (That one was recorded on Firefox.)

**Comment by susanodd** [comment]
There seem to be quite a few "backup" files that were created for Fietsmandje. The code that makes a backup is perhaps doing something. Only the oldest file is non-empty. But the one shown above (in the error messages) is the one in GlossVideo.

```
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 14:23 Fietsmandje test-44099.mp4
-rwxrwx--- 1 ubuntu signbank-writable 989997 Mar  6 12:35 Fietsmandje test-44099.mp4.bak17156
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 15:06 Fietsmandje test-44099_81sT9uW.mp4
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 15:05 Fietsmandje test-44099_8SABKf7.mp4
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 14:30 Fietsmandje test-44099_HbliWq3.mp4
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 14:29 Fietsmandje test-44099_a72txns.mp4
-rwxrwx--- 1 ubuntu www-data               0 Mar  9 15:21 Fietsmandje test-44099_gWkW6Em.mp4
```

**Comment by susanodd** [comment]
The webcam video recorded on Firefox is visible on Safari now!

**Comment by Jetske** [comment]
Yes, sorry, I was trying all sort of files and they can be deleted. 

But that is useful. Should all other files except for the last uploaded mp4 be bak files?

**Comment by susanodd** [comment]
I'm not exactly sure. It's whatever that reversion code is doing. I suspect multiple "backup" things are running simultaneously. I suspect they are supposed to stay in GlossVideo (The ones with bak seem to stay there.)
This was also the reason for the extra command to find dangling video files. At the moment I don't think any code physically deletes any video files.

**Comment by susanodd** [comment]
We could probably best put a tool inside of Admin for the actual files (including those that are not in GlossVideo). Probably the command you made could be put there, although it's for the virtual environment now (but never merged).
I added a folder `video_backups` under writable in the last commit in order to fix the weird files. It copies them first. Your video functions could make use of that too.

`BACKUP_VIDEOS_FOLDER = 'video_backups'
`

**Comment by susanodd** [comment]
Another one from yesterday is empty:
`-rwxrwx--- 1 ubuntu www-data 0 Mar  9 15:22 FIETSTAS-44102.mp4`

I'm going to delete all of those fietstas test videos and also from GlossVideo.

Maybe a test is needed to check that the video has data.

**Comment by susanodd** [comment]
I removed all the empty files. The wrongly named one (that was in GlossVideo) I copied it via via ponyland to my own computer and uploaded it to the gloss. It's there now! And only the one video in GlossVideo, with the correct name.

**Comment by rosestamp** [comment]
I tried using this feature and I signed a test sign twice but the video cut off after 1 sec

**Comment by susanodd** [comment]
I checked the GlossVideo admin to look at new videos to see if any have the wrong group (that has been repaired, but there can be some uploaded before it was repaired.)

The sign NGT 1,5-A seems to have a new video (gloss 2895). (Or a newly uploaded video.)
But it looks like the video isn't complete when viewed. (I assume the hand should go all the way up?)

**Comment by susanodd** [comment]
@Jetske is this working okay now?

**Comment by Jetske** [comment]
Looks like it's working fine when recording in Chrome (and I assume most other browsers) and then it is visible in Firefox, but recording videos in Firefox is disabled. I don't know about safari at the moment...

**Comment by susanodd** [comment]
No, Safari doesn't allow it.

I'll close this now.

**Comment by susanodd** [comment]
On Firefox, there is no way to dismiss the modal that says it's not available

![webcam-recording-not-available-no-dismiss](https://github.com/Signbank/Global-signbank/assets/24272544/5b69f12d-2afb-4164-8a60-4e8074de8482)

**Comment by susanodd** [comment]
On Firefox, there is no way to dismiss the modal that says it's not available

Now trying it on Chrome on Ubuntu.

It records okay and can see the preview. But when I upload it, only the image is visible. The video is not visible.

**Comment by Jetske** [comment]
@susanodd I had a lot of trouble getting it to work in Firefox, it was disabled to prevent having bad video files saved that can't be viewed in Chrome. We can look at it again, if necessary. Are there complaints from users about this?

**Comment by susanodd** [comment]
> @susanodd I had a lot of trouble getting it to work in Firefox, it was disabled to prevent having bad video files saved that can't be viewed in Chrome. We can look at it again, if necessary. Are there complaints from users about this?

Probably no complaints. But I need to be able to record videos somehow in order to finish the feedback issue #1258 

At the moment, I have no computer and no browser that succeeds.

**Comment by susanodd** [comment]
This almost works on Safari. It turns on the camera and I see myself in the video window. But then there's a website (not Apple) message that I need to use a different browser.
I think it should go ahead and record, not check the browser. It will work. It turned on the camera and it started recording, but the camera can't be turned off then because the site didn't do anything, it gave the message.
In safari you ge a red camera icon in the browser window bar and can see the camera is on.

Maybe we can use the Apple on @vanlummelhuizen's desk to work this out?

**Comment by susanodd** [comment]
I looked up what software works with Safari and it's maybe the same as is being used by signbank? Maybe it didn't work yet when the feature was added? MediaStream

**Comment by Jetske** [comment]
I think recording works in all browsers, but then saving the video gives most trouble. Because in some browsers the stream has a different format than in other browsers, or something like that. I'm not exactly sure. When we were testing it months ago, videos that were recorded in Firefox could not be viewed in Chrome. The other way around it did work, so that's why I restricted the option.

**Comment by susanodd** [comment]
> I think recording works in all browsers, but then saving the video gives most trouble. Because in some browsers the stream has a different format than in other browsers, or something like that. I'm not exactly sure. When we were testing it months ago, videos that were recorded in Firefox could not be viewed in Chrome. The other way around it did work, so that's why I restricted the option.

Any ideas how to solve this? It doesn't work to record in Chrome either.

**Comment by Woseseltops** [comment]
Closing this for now, let's reopen (or better: start a separate issue) if users actually complain
