### ISSUE TITLE
Create new panel Minimal Pairs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#277]
* See #110 for the definition of a minimal pair
* List all minimal pairs in the detail view in a new panel "Minimal Pairs" below the Phonology panel
* Table format: Gloss / Field name / Value of the presently selected sign / Value of the minimally contrasting sign

**Comment by susanodd** [comment]
Here's what this looks like.
![minimal_pairs_gloss_panel](https://cloud.githubusercontent.com/assets/24272544/24354752/676793b8-12f3-11e7-87b1-ef02210b22ed.png)
At present, this is generated dynamically and is quite slow. @ocrasborn should this become pre-calculated information in the database?

**Comment by susanodd** [comment]
I revised the code to comply with one undefined field and the rest matching. (The previous version shown above allowed a minimal pair to have an additional field when one of the fields was empty. I removed that. Now the ZWART-A gloss only has two minimal pairs.)

I'm wondering what to do about glosses with identical phonology, if anything. These are not shown in Minimal Pairs, but they are kind of visible in a backwards sort of way.
See the example screenshots below of ZWART-A (which has Minimal pairs ALLEEN-A and WOKKEL-B), ALLEEN-A and WOKKEL-B (which are identical), and then see the signs ONWEER and ELEKTRICITEIT-D, which are both identical to ZWART-A, as well as minimal pairs of both ALLEEN-A and WOKKEL-B.)

![zwart-a](https://cloud.githubusercontent.com/assets/24272544/24455106/b5e48644-148e-11e7-96fe-58771bf989da.png)
![alleen-a](https://cloud.githubusercontent.com/assets/24272544/24455128/c2f33240-148e-11e7-9115-e3dff74aee11.png)
![wokkel-b](https://cloud.githubusercontent.com/assets/24272544/24455141/c963e34a-148e-11e7-994d-a980826fa1b3.png)
![onweer](https://cloud.githubusercontent.com/assets/24272544/24455149/d21733e8-148e-11e7-8010-38a0798e5e4b.png)
![elektriciteit-d](https://cloud.githubusercontent.com/assets/24272544/24455158/d67008d4-148e-11e7-8acd-604ca2402aaf.png)

As a user, this seems kind of weird, since it seems to be hidden.
Do we want this kind of information about glosses with identical phonology to be showable?

**Comment by ocrasborn** [comment]
Hi @susanodd -- Good question! Signs with identical phonology can have three different kinds of status for us:
1. They are true homonyms: same form, unrelated meanings. In this case we manually classify them as such by linking them to each other in the panel Related Signs
2. They are homonyms, but really their meaning is not so distinct, rather overlapping. In such a case after discussion in our annotation meeting we would choose to delete one of the two.
3. They have identical phonological descriptions by mistake: we need to alter one or the other or both.
To help us with this workflow, it would be really useful if these could somehow be displayed in a separate area (w/header in red) at the bottom of the new page: "Identifcal phonology but not marked as homonym".

**Comment by susanodd** [comment]
Oh, that's nice!

**Comment by ocrasborn** [comment]
Oh, and a response to your first question earlier on: yes, if it's slow, we should harvest these relations overnight rather than generating them dynamically.
If we do so, it would be useful to have a manual way to update that part of the database during the day. Reason: if people have done a lot of work e.g. on removing false homonyms, they should have a way to refresh the views.

**Comment by susanodd** [comment]
Okay, i added the "identical phonology" pop-down for when the matching glosses haven't been added as homonyms. Here are screen shots.

![onweer-popdown-identical-1](https://cloud.githubusercontent.com/assets/24272544/24546171/500a5f2e-160a-11e7-9a7c-a7492c7a4b45.png)
![onweer-popdown-identical-2](https://cloud.githubusercontent.com/assets/24272544/24546174/54a1bd66-160a-11e7-9078-673c3cd103b0.png)

The gloss SusanTest-D is the same gloss (homonym to ONWEER) but with the identical phonology as Homonyms instead.

![susantest-d-homonyms](https://cloud.githubusercontent.com/assets/24272544/24546181/57ae30ca-160a-11e7-88ad-06ba7bab179b.png)

I placed the (optional, red) pop-down underneath the Minimal Pairs pop-down since the data in the model is retrieved in the same method (to avoid additional method invocations). When we pre-compute the data, this can be retrieved more efficiently and placed elsewhere in the gloss detail view.

**Comment by ocrasborn** [comment]
I think for the final version (when it is pre-computed):
* it would be good to have it immediately below Phonology;
* with a red 'alert' panel title as you have now (as we will need to do something with each and every one);
* make the contents un-editable (the system will recompute overnight when we have addressed our to-do's);
* and have the panel only appear if there is content in it.

**Comment by ocrasborn** [comment]
One other thing: for the pre-computation (as for the dynamic one), I think we would like not to generate lists of all signs that do not have any phonology specified yet. Note: it seems that the two binary fields "Repeated movement" and "Alternating movement" always have a value ("No") even when we have done nothing about them.

**Comment by susanodd** [comment]
Repeated movement and Alternating movement have a default of "not checked". So that's true, it's either Yes or No; there is no distinction between "No" and "Not filled in". It would seem the database type needs to be changed to reflect this.
Other fields that have not been filled in (might) have either "-" or "-----" or "N/A". At places in the code that test for "empty" values, comparison is also done to '' and ' ' and None. This might have to do with evolution of the database contents.

**Comment by susanodd** [comment]
Okay, the Identical Phonology is now right after phonology, and it's only shown if it's not empty. It's not editable.
![uitnodigen](https://cloud.githubusercontent.com/assets/24272544/24616099/71446bfc-1890-11e7-9993-5e583a6cc319.png)

**Comment by susanodd** [comment]
I adjusted the gloss_detail view to not show the Repeated movement and Alternating movement when these are False.
When you search for a sign, you can choose -------, True, False, or Unknown. But the default value in the database schema is False rather than Unknown. In my offline database, there are no signs with Unknown.

**Comment by susanodd** [comment]
![wokkel-b-no-false](https://cloud.githubusercontent.com/assets/24272544/24659964/8de331e4-194e-11e7-8d80-033e7857a7f4.png)

**Comment by ocrasborn** [comment]
One more request, @susanodd : could you change the panel titel by removing the "ALERT: " and "!"? The red colour by itself is enough of an alert to us that something more needs to be done.

**Comment by susanodd** [comment]
![gezicht-a-no-alert](https://cloud.githubusercontent.com/assets/24272544/24661512/d52b182e-1952-11e7-82d6-8c750fef1a42.png)

**Comment by susanodd** [comment]
Question: The phonology field "Phonetic Variation", at the moment I am either including or omitting comparison of this field for minimal pairs. (Two versions of the code, seeing how it works.)
An example is the glosses ONWEER, KLEUR-A and KLEUR-B. (In my off-line database.)
KLEUR-B has this filled in. It's a write-in field.
(See the phonology in the screenshots below.)
KLEUR-A is a minimal pair of ONWEER on field Strong Hand.
The question is: KLEUR-B also differs from ONWEER on field Strong Hand.
But it also differs from ONWEER on Phonetic Variation.
Should Phonetic Variation be counted among the fields compared for Minimal Pairs?

![onweer-minimal-pairs-060617](https://cloud.githubusercontent.com/assets/24272544/26826542/eadc3eda-4ab9-11e7-952b-a56bab70c497.png)

![kleur-a-minimal-pairs-060617](https://cloud.githubusercontent.com/assets/24272544/26826613/f10c2d4c-4ab9-11e7-89d7-7ce65f6191dd.png)

![kleur-b-minimalpairs-060617](https://cloud.githubusercontent.com/assets/24272544/26826618/f602a4a2-4ab9-11e7-8fb8-851e9d1b0916.png)

**Comment by ocrasborn** [comment]
Ah, good question @susanodd . Please ignore the field Phonetic variation for the minimal pair computation.

**Comment by susanodd** [comment]
So for the above example, KLEUR-B is also a minimal pair of ONWEER on field Strong Hand.

**Comment by susanodd** [comment]
Okay, the MInimal Pairs are implemented now. Dynamically. And it's fast now!
There had been a problem with "empty" values using many different encodings. And with glosses that had no phonology at all. That was causing thousands of minimal pairs for each empty gloss.
That's fixed now, empty phonologies are ignored.
I just need to make a version of gloss_detail that's a slightly different name so it can be uploaded for testing.

**Comment by susanodd** [comment]
The Gloss Detail View with Minimal Pairs and Homonyms has been committed. Now we're just waiting for @Woseseltops . :)

**Comment by susanodd** [comment]
https://signbank.science.ru.nl//dictionary/gloss/1775/

**Comment by ocrasborn** [comment]
I discussed this with the ASL team; they'll also want this once the ASL SB has been moved to the US.

**Comment by Woseseltops** [comment]
Working my way through the 'tbc after asl migration' issues. I think the ASL SB has this now, agree this can be closed @ocrasborn ?

**Comment by ocrasborn** [comment]
I think this needs to be adapted for the ASL phonology fields: as they are largely different from the NGT fields, it now appears that any sign has a zillion minimal pairs. @susanodd , could you take this up?

**Comment by susanodd** [comment]
This issue was introduced some time ago.
Since then,  a "Minimal pairs list" view has been added under Analysis. The Minimal Pairs computation has also undergone a number of revisions as part of other issues (e.g., display of Boolean fields, removal of hard-coded queries).

@ocrasborn, can you check whether this issue can be closed? There are much fewer minimal pairs than there used to be. Some glosses may have minimal pairs because of sparse phonology. If you look at the Minimal Pairs list of the Analysis menu, you get an overview. It's easier to check for anomalies there.
As an example, the Shanghainese sign NEARBY-B has 27 minimal pairs. It has 3 phonology fields defined.

**Comment by ocrasborn** [comment]
Although created with an eye on linguistic (phonological) analysis, the minimal pair list helps us identify errors in the phonological description, including incomplete (sparse) phonologies. Human signers quickly identify a 'false' minimal pair, and this will prompt them to double-check whether the phonology is OK. As far as I can see, the function works well, so I'll close this.
