### ISSUE TITLE
Fill Feedback menu items

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#29]
• "Site feedback" should lead to http://signbank.science.ru.nl/feedback/generalfeedback.html
• "Report a missing sign" should lead to http://signbank.science.ru.nl/feedback/missingsign.html

**Comment by susanodd** [comment]
I've been debugging the feedback pages. Lots of stuff was broken.
The hyperlinks to the signs now accommodate datasets. 
The hyperlink url is now the gloss id rather than the annotation id gloss.
The feedback now works for morphemes as well as signs.
I added modals to the feedback summary so that one can still Cancel a delete in case of accidents.
Delete works now. As in Steve's original code, the deleted feedback records are just hidden.
Uploaded videos are now found.

**Comment by susanodd** [comment]
There is actually some recent feedback!
https://signbank.cls.ru.nl/feedback/overview/

**Comment by vanlummelhuizen** [comment]
@ocrasborn Very old issue. Please check and close if OK.

**Comment by ocrasborn** [comment]
All looks good to me now, thanks @susanodd !
