### ISSUE TITLE
Allow for frequencies from different data sets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#354]
Both for NGT and for other sign languages, we have multiple data sets from which frequencies can be extracted. Can we somehow make the no. of frequency fields (and searching for them) more dynamic, based on what a script generates (and of course we'll also need to adapt the script).

**Comment by vanlummelhuizen** [comment]
Frequencies are now taken from the Corpus NGT. How are datasets identified? How will the CNGT datasets correspond with Signbank datasets?

**Comment by ocrasborn** [comment]
Hadn't thought about it much yet. Perhaps by directory name at a certain level, making sure there's one corpus per repository? Multiple repositories could exist per language/data set, and the repositories would be under a directory that has  the language/data set name as the parent level.

**Comment by ocrasborn** [comment]
We talked about this in our demo today:
* We would also need to provide a way for users to upload EAF files (and upload updates)
* We would need a standard format for metadata that links the file name of the EAF file to a region (CSV file; column 1 EAF file name minus extension; column 2 Region of Signer 1; column 2 Region of Signer 2; etc. if there are more signers). Signer identities can then be extracted from the Participant tag of the EAF files. In this way we also force annotators to use the Corpus NGT conventions for glossing multiple people: each on a different tier.
* We would need to explain to users that Signbank will extract gloss frequencies from all tiers that have the type 'gloss' (so force them to adopt to the Corpus NGT conventions in this sense; which I think is a good idea anyway)
* something more, @vanlummelhuizen ?

**Comment by ocrasborn** [comment]
Addition to what we discussed: let's not be specific about what the metadata categories are (using just region), but let us extract the relevant feature from the metadata. If users find age groups more important than regions, let them add a feature for that. Instead of having a column "Region" and letting the values in that column determine the field names, use any text from a column Category to determine field names. So a table could look like this:

<table> <tr> <th>Session</th> <th>Category</th> </tr> <tr> <td>0001</td> <td>Region: Washington</td> </tr> <tr> <td>0002</td> <td>Region: Philly</td> </tr><tr> <td>0001</td> <td>Register: narrative</td> </tr> <tr> <td>0002</td> <td>Register: discussion</td> </tr></table>

**Comment by Woseseltops** [comment]
A suggestion on how to do this. 

Back end storage
-----------------------
We currently have a panel 'Frequency' on the gloss detail view, showing the values of 14 hardcoded fields (all starting with `tokNo` in the code). Instead of all of that, we add a new panel 'Usage data', which lists so-called `GlossFrequency` objects linked to the particular gloss. 

A GlossFrequency object then contains these fields:
* gloss (foreign key), the field to which this object is linked.
* dataSource: a free text field where you can name the corpus used to collect the usage info, but could be anything.
* frequencyCategory: a field choice; I expect the choices will be named as in Onno's example above 'Region: Washington' or 'Register: discussion'.
* frequency: the actual frequency.

Note that this is just one solution in a very large solution space; curious for your opinion @ocrasborn and @vanlummelhuizen .

Visualization
-----------------
The next step can be that we can specify somewhere (the settings file? some admin page?) which frequency categories belong together in a 'frequency category group'; for example 'Gender: male' and 'Gender: female' are one group. If a gloss then has data for all categories in such a category group, it could show its data in the form of a pie chart. If the category group is about regions or cities etc, of course a map would be better where brighter colors mean a higher frequency.

If the gloss is part of a lemma and the other gloss(es) also have data for the same category, it would be nice to automatically show their pie chart as well. This way, if there for example is a female variation of a sign, you can see that immediately: instead of the normal singular pie chart, you see multiple, and you see that the distribution male/female is widely different among the pies. Perhaps when there is more than one pie chart, a horizontal bar chart with a bar per gloss makes more sense.

If we have multiple glosses to visualize, we could also (add the option to) flip the dimensions: instead of showing within a gloss how often it's used (for example) by men vs women, you could visualize within such a category how often gloss a vs gloss b chosen; maybe we see that men always pick gloss a while women vary. 

The latter approach is most evident when visualizing locations: we don't want an individual map for each gloss, but instead per region which gloss they pick. I'm not sure yet how exactly we should visualize that on a map: do we put a small pie chart on each region, or do we for example give gloss a the color red, gloss b the color blue, and make the region purple when the distribution is 50-50%. The second visualization might be nicer, but doesn't scale to more glosses.

To do
-------
* Check relations with issues #107, #113, #228
* Create mockup of the visualization I propose

**Comment by Woseseltops** [comment]
Relations with other issues:
* This proposal would be helpful for #107, but #107 is more.
* This proposal would provide everything needed for #113 
* This proposal would completely fix #228

**Comment by Woseseltops** [comment]
The most basic case:

![pies](https://user-images.githubusercontent.com/1909317/64247296-d7e34b80-cf0e-11e9-853e-6118fdaedbe9.png)

When there are more glosses sharing a lemma:

![barsx](https://user-images.githubusercontent.com/1909317/64247318-e16cb380-cf0e-11e9-965d-088047a0c0a3.png)

When you click the swap axes button:

![barsy](https://user-images.githubusercontent.com/1909317/64247396-137e1580-cf0f-11e9-901e-5ca8c169e479.png)

Again, curious for your opinions, in particular @ocrasborn

**Comment by susanodd** [comment]
The title of the issue says to allow for frequencies from different data sets (datasets).
At the moment, data sets (datasets) are e.g., Shanghainese, NGT, ASL, etc. (Which also may or may not happen to be Sign languages.)
At the moment, the signs in one dataset are "different" from the signs in another dataset.
That's how they've been implemented, with the gloss id being unique (also across datasets).
The sign of one dataset does not appear in another dataset.

Perhaps a new title is needed for the issue?
It's more a new kind of frequency.
Or it's a way to create datasets dynamically based on metadata features of glosses.
Or we now want to have both datasets and data sets.

**Comment by Woseseltops** [comment]
> The title of the issue says to allow for frequencies from different data sets (datasets).

Yeah in this issue data set/dataset does not mean 'Signbank Dataset' but 'external source of information', like a corpus. Let's call it 'corpus' for now.

**Comment by susanodd** [comment]
I made the frequencies panel in gloss detail view display as a barchart.
This is an alternative display of data we already have. (Original, followed by barchart.)
Original
![gloss-detail-frequencies-open-a](https://user-images.githubusercontent.com/24272544/64693668-12f9f780-d498-11e9-8344-669d30a537f9.png)

Horizontal barchart
![gloss-detail-frequencies-open-a-barchart](https://user-images.githubusercontent.com/24272544/64693678-18574200-d498-11e9-8f59-d46923129399.png)

**Comment by susanodd** [comment]
Here is an alternative Lemma View showing the frequency of the Occurrences of the different Glosses of the Lemma Open. (Showing real data.)

![lemma-frequency-view-open](https://user-images.githubusercontent.com/24272544/64694106-33768180-d499-11e9-8fd9-deb00a62d2fa.png)

**Comment by Woseseltops** [comment]
I discussed the back-end storage I describe above with @vanlummelhuizen and he pushed me into the direction of a more complicated but full-featured solution instead of the relatively simple thing I proposed. @susanodd was waiting for my write-up of it for weeks, so here it finally is.

Corpus:
* name, string
* description, string
* speakers_are_cross_referenced, bool

Document:
* identifier, string
* corpus, foreign key
* creation_time, datetime

Speaker:
* identifier, string
* gender, char with choices
* age, int
* location, string

GlossFrequency:
* speaker, foreign key
* document, foreign key
* gloss, foreign key
* frequency, int

Storing all of this allows us to visualize all kinds of cool things if we desire so later. 

The `speakers_are_cross_referenced` field indicates whether there is a way to know if a person named Jan in one document is the same person as Jan in another document. If false, counting how many different speakers you have for a particular gloss does not make sense (because you might count a speaker more than once).

**Comment by Woseseltops** [comment]
Okay I've implemented the models and created the database migration... next step would be to dive into the Corpus NGT data and create the code to populate the database.

**Comment by susanodd** [comment]
I started doing that.

**Comment by susanodd** [comment]
In the spirit of #115, I added a tab to Gloss Detail View for Frequency View.
The new view displays already existing frequency data per region.

**Comment by susanodd** [comment]
I'm working on extracting information from the eaf files.
The glosses are identified via the ANNOTATION_VALUE nodes.
Some of these values begin with tilde (~). Is this significant @ocrasborn?
Some of the values are actually long phrases that seem to describe a sign rather than be a sign.
Possibly these are comments.
They sometimes seem to be describing what one is seeing rather than an actual sign.

As an example, there are annotations with "TOLK" as well as "~TOLK".
Is this like "approximately TOLK".
Or like a non-signer using air quotes?

**Comment by susanodd** [comment]
An example of a weird value that looks like a processing error:

`<ANNOTATION_VALUE>GROEP-A@besloten groepje/5+0.9/1+5/GROEP-A@besloten groepje WEG-B PT:1 AFSPRAAK-E GROEP-A@besloten groepje AFSTAND-HOUDEN-VAN/0/0/1s VRIEND-A/2 PO</ANNOTATION_VALUE>`

**Comment by ocrasborn** [comment]
Hi @susanodd ,
* The tilde signifies a possible false start, or an otherwise incomplete articulation; please leave these out of the calculations. Other special characters that should impact the counting: # starts a fingerspelling string; these will not be in Signbank if they are more than one letter, and can be disregarded altogether just like ~
* The annotation above I cannot find. In the corpus I can only find the string "besloten groepje" on a tier called meaning, tier type 'translation_dep'. Indeed a processing error?

**Comment by vanlummelhuizen** [comment]
@ocrasborn the strange annotation is in EAF 434, tier OOH SpreadingL S1, at 1 minute 55.680 seconds. 

@susanodd the strange annotation should probably not be counted as a sign because it is not on a EAF tier for annotating signs. Did you look into how frequencies are calculated now: 

https://github.com/Signbank/Global-signbank/blob/5f6241bffe0f047e5e568f1e91a204edfa81d951/signbank/tools.py#L1910-L2006
https://github.com/vanlummelhuizen/CNGT-scripts/blob/master/python/signCounter.py

**Comment by susanodd** [comment]
The meta data for the speakers of the NGT corpus is in the settings file METADATA_LOCATION.
I wrote a function to read in this file and store the data in the new Speaker model.
There is an additional field for 'Preference hand', with the values present in the data: 
left, right, both, unknown.
This needs to be added to the Speaker model.
@Woseseltops? It's fewer steps if you make the migration, since it can be done on the live server and the database will be cron'd in fewer steps than if I do it.

**Comment by susanodd** [comment]
@vanlummelhuizen, thanks for the explanation of the tiers in the eaf. I have been browsing the files and trying out different functions to see how the CNGT scripts work. I was trying to see what, if any, additional information might be present in the files.

**Comment by Woseseltops** [comment]
After discussion with @susanodd , we decided to add a handedness field to the Speaker model, since we have this info in the corpus. We might find cool things like that gloss x is only used by left handed signers or something like that.

**Comment by Woseseltops** [comment]
Outcome of discussion in #601: the term 'lemma' is much narrower than I originally assumed. Everywhere where I said lemma, I actually mean 'synonyms'... that is, multiple glosses sharing a meaning but not a form.

**Comment by susanodd** [comment]
I have the frequency visualization for speakers as shown in the mock-up above ready.
We're still waiting on the CNGT script to be made live by @vanlummelhuizen.

**Comment by susanodd** [comment]
![open-c-gender](https://user-images.githubusercontent.com/24272544/68298241-2c36b300-0099-11ea-9edc-d6dfd274ada6.png)
![open-c-age](https://user-images.githubusercontent.com/24272544/68298250-3062d080-0099-11ea-953d-c017b5d42203.png)
![open-c-age-distribution](https://user-images.githubusercontent.com/24272544/68298256-35278480-0099-11ea-8957-ac96dcad830f.png)

**Comment by susanodd** [comment]
Here's Geel-A, Geel-B, Geel-C.

![yellow-A](https://user-images.githubusercontent.com/24272544/68299167-76209880-009b-11ea-9cd3-2efaef4f1ee3.png)
![yellow-B](https://user-images.githubusercontent.com/24272544/68299173-7b7de300-009b-11ea-989e-bb7419821dbf.png)
![yellow-C](https://user-images.githubusercontent.com/24272544/68299184-820c5a80-009b-11ea-9215-cbcba7f92ce5.png)

**Comment by susanodd** [comment]
Here is Age for voetballen-A, voetballen-B, voetballen-C.

![voetballen-A-age](https://user-images.githubusercontent.com/24272544/68300301-c7318c00-009d-11ea-88b8-9f11c26ba924.png)
![voetballen-B-age](https://user-images.githubusercontent.com/24272544/68300307-cbf64000-009d-11ea-9601-47fca8857022.png)
![voetballen-C-age](https://user-images.githubusercontent.com/24272544/68300320-d1538a80-009d-11ea-89db-1b83911eb972.png)

**Comment by Woseseltops** [comment]
I just spent some time investigating maps that could be colored from Javascript, and found that jVectormap serves our goals nicely. I need to import (1) a JS code library, (2) a css file, and (3) a map (in the form of JSON), and then I can create a map like this:

	var data = {"NL-GE": 10,'NL-LI':5};

	$('#nl-map').vectorMap({map: 'nl_merc',series:{regions:[{values: data,scale: ['#C8EEFF', '#0071A4'],normalizeFunction: 'polynomial'}]}});

Result

![image](https://user-images.githubusercontent.com/1909317/68308069-84c37b80-00ac-11ea-90ad-816e2560c958.png)

**Comment by vanlummelhuizen** [comment]
@Woseseltops nice find!

**Comment by ocrasborn** [comment]
@Woseseltops : yes, a nice map, but I'm not sure how it would fit our purposes. The metadata regions for the Corpus NGT centre around the five NGT dialect areas which do not overlap with provinces, but closer to cities: Groningen, Amsterdam, Rotterdam, Voorburg/Zoetermeer, and Den Bosch/Eindhoven (St. Michielsgestel). How could we represent that visually? Five circles of different sizes overlaid on those locations perhaps?

**Comment by susanodd** [comment]
I just pushed the most recent changes to the Frequency View.
Now the Speaker data looks like @Woseseltops's mockup.
Additionally, there is data shown for variants of the gloss.

**Comment by Woseseltops** [comment]
> yes, a nice map, but I'm not sure how it would fit our purposes. 

Hmm yeah I didn't think that part through, but I see that jVectorMaps supports putting circles of different sizes and colors on the map out of the box.

This is related to a discussion I had with @vanlummelhuizen some time ago on how to visualize the distribution of >2 synonyms. How do we explain that, for example, Groningen users use option A 50% of the time, option B 40% of the time, and option C 10% of the time? Probably the best solution would be to draw piecharts on the map.

**Comment by susanodd** [comment]
![football-age-distribution-variants](https://user-images.githubusercontent.com/24272544/68763733-74198500-0619-11ea-96c5-67a78b75be39.png)

**Comment by susanodd** [comment]
![football-gloss-voetballen-a](https://user-images.githubusercontent.com/24272544/68763749-809ddd80-0619-11ea-9fea-b0f34e54d8ff.png)

**Comment by susanodd** [comment]
![football-variants-voetballen-b](https://user-images.githubusercontent.com/24272544/68763776-8f849000-0619-11ea-997a-fb60e56d32d4.png)
![football-variants-voetballen-c](https://user-images.githubusercontent.com/24272544/68763782-93b0ad80-0619-11ea-964f-1f8bdb6c6444.png)

**Comment by Woseseltops** [comment]
This is looking really good @susanodd ! Awesome.

Some remarks:
* Something I don't see in the screenshots yet is the option to compare synonyms/variants in one go, as that was the main reason for visualizing this info in the first place. That is, I also want the pie charts about VOETBALLEN-B to be available in the frequency view of VOETBALLEN-A. This could in the form of a different piechart for each synonym, BUT there could also be different charts for each value (so, for men, what percentage says VOETBALLEN-A, what percentage VOETBALLEN-B, etc). Perhaps you can switch between these two ways of visualizing with a button 'swap axes'? 
* Related to the previous point, I feel the presentation could be a bit more dense with the charts closer together?
* Also, we have more horizontal space than vertical, so perhaps the legends could go to the side? 
* Matter of personal taste, but I feel like the colors in my mockup fit a little better with the rest of Signbank's interface :)

**Comment by susanodd** [comment]
I'm fixing the colours now to be as shown in @Woseseltops mockups.

I noticed it's possible on the Age Distribution Variants, to "cross off" the different variants and hide them in the "vertical bar stack" (Feature of chartjs.)

(i'm using GEBAREN-A as a test sign. I noticed that the overlap of GEBAREN-A in both VGT and NGT is confusing because there is no frequency data for VGT. I'll add something to the "no frequency data is available" to mention the Dataset.)
Note: the template for frequency view is using the NGT dataset files at the moment.

**Comment by susanodd** [comment]
I'll work on the first bullet next. I made the colors be monochrome and I removed some vertical space between the charts. I need to see if there's a way to make the number of age ranges be dynamic.

**Comment by susanodd** [comment]
I made a panel with pie charts showing variants, per female and per male. (see screenshots).
For the example gloss, WEG-B, the pie ends up a grey blob.
It's too computational to prevent almost identical greys from appearing next to each other for the variant slices. The variant labels are used to look up colors in a table.
With the happy colors, the data structure is populated so the colors all differ from other colors.
Although it's not color blind safe.

![gloss-variants-monochrome](https://user-images.githubusercontent.com/24272544/70907426-207bcc00-2009-11ea-813c-d27378ee7147.png)

![gloss-variants-happy-colors](https://user-images.githubusercontent.com/24272544/70907437-2671ad00-2009-11ea-9bd1-2b55236a4211.png)

**Comment by susanodd** [comment]
At the moment, there are different open/close panels for the different displays.
The Variants Age Distribution panel chart can hide different variants from the display.
And similarly with the female and male Gloss Variants pie charts.

In the (older) Variants Speaker Data panel (last one in the display), the pie chart for ages shows age ranges. If you hide one of the slices, it doesn't expand the other ranges. In @Woseseltops's original mock-ups the slices were child, adult, elderly. Are these defined anywhere for signers?

@ocrasborn, what is the most useful way to view speaker ages?

**Comment by susanodd** [comment]
Here it is with bar charts instead of pie charts.

![gloss-variants-barchart-female-male](https://user-images.githubusercontent.com/24272544/70915255-d3542600-2019-11ea-87e4-6ef760a5d82c.png)

**Comment by Woseseltops** [comment]
I added my idea with the colors @susanodd . The code shows my line of thinking with only changing the hue:

`
var signbank_colors = ['hsl(1, 62%, 45%)','hsl(130, 62%, 45%)','hsl(65, 62%, 45%)','hsl(195, 62%, 45%)','hsl(30, 62%, 45%)','hsl(230, 62%, 45%)'];
`

![image](https://user-images.githubusercontent.com/1909317/71265858-72915a00-2347-11ea-820f-23d5ceec970b.png)

**Comment by Woseseltops** [comment]
Hi @susanodd , I was playing around with all the new frequency visualizations we (mostly you) developed, and after some time I realized I still could not quickly get the information I was interested in: if there are differences between groups in terms of lexical choices. Reasons for this are that the piecharts are large and in general take a lot of space, that a lot of panels need to be opened and closed, etc. I made a new mockup for a layout that shows everything at once in a more concise way:

![freq-redesign-2](https://user-images.githubusercontent.com/1909317/71996440-817b7600-323c-11ea-8102-9ef4461a8ea5.png)

The third part (maps for the region) is still missing, and the bar charts would only be shown if there are more version of a sign. Very curious for your opinion on this mockup @susanodd

**Comment by susanodd** [comment]
@Woseseltops, I'm working on this. It's a bit quirky because it's chart data rather than graphics. It's not possible to place them freely. Here, the variants are stacked in horizontal bars for female and male (upper right in your mock-up), but it's a generated chart from the data. So far I haven't been able to determine what axis parameters to git rid of space between the two bars. The vertical axis is data over the two categories Female and Male. But the "ticks" on the access seem unresponsive.

![female-male-variants-horizontalbar](https://user-images.githubusercontent.com/24272544/72262621-962e8400-3617-11ea-9287-9e7256ab98a1.png)

**Comment by susanodd** [comment]
The only "plus" thing is that you can "cross off" variants and leave the rest of the data to reformat itself. Plus you can hold the cursor over the bars and see the actual data values in a table.Those are both provided by chartjs.

**Comment by Woseseltops** [comment]
Hey @susanodd , could you you make sure it's a bit clearer to me what you are working on and what's open for me to pick up? Thanks :)

**Comment by susanodd** [comment]
I'm modifying the charts to correspond to your markup. Nearly done. The difficult one is the variation with all variants in the same bar.

**Comment by susanodd** [comment]
@Woseseltops and @susanodd noticed some weird behaviour that the variants were not found for WEG-A but they were all shown, including WEG-A when looking at other variants. This was determined to be a legacy code glitch from when annotations became multilingual. This was diagnosed with help from @vanlummelhuizen. The problem arose when the focus gloss didn't have all the language translations. Now the dataset default language is used for finding variants. At the moment, this is Dutch for NGT.

The variants bars are all the same length now. The displayed data in the hover is now formatted separately as a tooltip and the raw data is not rounded. Strangely enough, bars that didn't add up to 1 were ending up shorter. Even when they were larger than 1. So much for calorie counting eating a pie. You still only have 1 pie. Not 101 percent.

The next thing to do is to add (esp. for variants) a toggle between raw summaries and percentage summaries.

**Comment by Woseseltops** [comment]
Outcome of discussion with @susanodd : we want a circular legend. If this is not possible with ChartJS, we'll build the legend ourselves.  Advantages:
* We can actually have the circles
* We no longer have a legend for every single gloss
* Might solve problems @susanodd is having with percentual vs absolute bar charts.

Possibly we lose the option to remove categories from the graph... but Susan thinks she might be able to save it.

**Comment by susanodd** [comment]
![new-layout-follows-mockup](https://user-images.githubusercontent.com/24272544/73255521-948cc080-41c0-11ea-8a8a-29c9b7caaba1.png)

**Comment by susanodd** [comment]
I revised the charts and layout considerably to look like the mockup.
What remains to be done are the (percentage) labels on the pie charts.
Plus functionality to toggle between percentage and raw.

**Comment by Woseseltops** [comment]
This is truly awesome @susanodd !

**Comment by susanodd** [comment]
The most recent updates are live now. Toggling between percentages and raw has been added.

**Comment by susanodd** [comment]
@Woseseltops, perhaps you can have another go at making Signbank colours? At the moment, the colours for male/female display overlap those assigned to variants, making it a bit confusing.

**Comment by ocrasborn** [comment]
For the binary category male/female, why not simply use light/dark grey?

**Comment by ocrasborn** [comment]
Two other requests in relation to this issue:
1. Could you move the Frequency View one tab to the left, so that Revision History (the more administrative part of the information) is at the end?
2. Could you expand all panels by default?
On my mac (tested in Safari, Chrome, and Firefox) the scaling of the figures is way off (too large) at the moment, but that may have already been addressed, haven't read all the issue updates yet.

**Comment by susanodd** [comment]
Genders have been made shades of grey.

**Comment by susanodd** [comment]
I revised the layout considerably.
The default is now that the Speaker Data panel open.
It doesn't work to put this panel ahead of the others because its size is not fixed and it ends up hiding the other charts.
I didn't get it working yet to make the speaker data (with variants) less wide.
There are numerous charts displayed and they end up displacing each other onto other rows.

**Comment by susanodd** [comment]
![speaker-data-frequency-shades-of-red](https://user-images.githubusercontent.com/24272544/74164246-cfacdc00-4c23-11ea-8296-57a047718d96.png)
![speaker-data-shades-of-red-raw](https://user-images.githubusercontent.com/24272544/74164364-f834d600-4c23-11ea-9e5d-74ded9eedfb9.png)

**Comment by susanodd** [comment]
i realise the colours look a bit weird. I had it as greys but distinguishing different greys is more difficult.
I used @Woseseltops idea and varied the saturation and lightness on the Darkred of the Signbank menu. Enough so that hovering still distinguishes different values, and values next to each other are different enough.

**Comment by susanodd** [comment]
Above you see examples of toggling between Percentage view and Raw view.

**Comment by susanodd** [comment]
![frequency-greyscale](https://user-images.githubusercontent.com/24272544/74228542-f3722f80-4cc0-11ea-8064-5388ef234aca.png)

**Comment by susanodd** [comment]
Back to greyscale.
We can wait and see what happens if shades end up too close.
If there aren't enough shades (more than 12 variants) it reverts to happy colors.

**Comment by ocrasborn** [comment]
Just playing around with this, @susanodd , and noticed something odd for the following item (haven't yet found it anywhere else): https://signbank.science.ru.nl/dictionary/gloss/445/frequency
The Age Distribution panel shows dozens of occurrences, whereas the other (like the panel in the regular detail view) only show 2 occurrences. Why oh why?

**Comment by ocrasborn** [comment]
On a different note: in Safari and also in Chrome on my mac, the graphs are WAY too big, they need to be scaled down at least by 25%, possibly more.

**Comment by vanlummelhuizen** [comment]
> Just playing around with this, @susanodd , and noticed something odd for the following item (haven't yet found it anywhere else): https://signbank.science.ru.nl/dictionary/gloss/445/frequency
> The Age Distribution panel shows dozens of occurrences, whereas the other (like the panel in the regular detail view) only show 2 occurrences. Why oh why?

@ocrasborn If you hover over each part of a chart, some extra information pops up. This helped me to notice that the pie chart of the Speaker data only deals with MOEDER-C, while many other charts deal with MOEDER-C, MOEDER-B and OUDER-B. Every chart that deals with multiple glosses, the glosses are in the legend. It seems that the same goes for other glosses, e.g. https://signbank.science.ru.nl/dictionary/gloss/2693/frequency. So, the calculation is not the problem here. I think the interpretation is. The question is now: do we need to make it more intuitive and if yes, how?

**Comment by susanodd** [comment]
The sizes of the frequency charts has been reduced! This has been pushed to github.

**Comment by susanodd** [comment]
I'm working on #756 now. Each Dataset Corpus will have speakers.
From the models, as they are,  the Speakers are not linked to a specific corpus.
https://github.com/Signbank/Global-signbank/issues/354#issuecomment-539999856

This has become a slight glitch because the Speaker Identifiers in the Dataset Metadata file may end up being the same.
Where to fix this in the model, @Woseseltops @vanlummelhuizen ?
We can't exactly make up new identifiers because they are used in the EAF files.
And a speaker may appear in documents associated with more than one dataset or corpus.
https://github.com/Signbank/Global-signbank/blob/9d0bddac2ed6ce631fc75f97de7821fa98ea9d3d/signbank/dictionary/models.py#L2419-L2425

**Comment by susanodd** [comment]
I've revised the formatting of the Frequency View to be more compact. It's also computed from the GlossFrequency objects for the dataset. It used to be hard-coded using the frequency fields (for CNGT). Now it's obtained from the corpus of the dataset.
This has been done as part of #756.

**Comment by susanodd** [comment]
The Gloss Frequency View functionality that supports displaying the graphs has been upgraded!
(Also relevant for #756 and #283 as some bugs have been fixed and the code works for new to be created corpora.)

New code (my local server) uses chartjs v. 3.5.1.
Old code (online Signbank) uses chartjs v. 2.9.3.
This required some major rewriting to the javascript.
It's all working now!
The upgrade was needed to support labels on the charts as well as other features.

**Comment by Woseseltops** [comment]
Situation right now (assumptions)
* The main way we identify speakers objects in Signbank is the default Django way: with private keys. That is, speaker.pk .
* The speaker.identifier field is filled with the identifier as mentioned in the EAF file.
* Multiple EAF files could use the same identifiers, which can make things messy: if in EAF file A a speaker has identifier 1, and in EAF B a speaker has identifier 1, this is probably not the same speaker... but there is no way to tell in the current set up.

Are these assumptions correct, @susanodd ?

Proposed solution
* Make sure we never use speaker.identifier to uniquely identify a speaker (and use private keys instead).
* Add an extra field speaker.eaf_file to 'store' from which file the identifier was taken. 

What do you think @susanodd ? And what would be the best way to identify an EAF file? The filename? Or is there something else in the content that is probably unique?

**Comment by Woseseltops** [comment]
> The EAF files are identified now (as Documents) with the filename minus the extension.

I had a look at some EAF files, and noticed that there are about 2400 for CNGT alone, and I assume all of these 2400 share their speaker identifiers. Maybe we the EAF identifier should be filename minus numbers minus extension?

> For display purposes in the Corpus View (aka DatasetFrequency View) the speaker id known the the user (Participant) is shown. Never the pk.

Ah, I see... so it's not so much a problem for the underlying logic, but just for display purposes... Building on my proposal above, maybe we can now display both the eaf_file (filename minus extension), followed by a slash, followed by the speaker identifier? So a speaker would look like 'CNGT/1'?

**Comment by Woseseltops** [comment]
Or, as a more elegant alternative to my suggestion above, EAF files are connected to a Corpus object, right? Can't we link Speaker objects to Corpus objects, and for display purposes use the corpus, followed by a slash, followed by the speaker identifier ?

**Comment by susanodd** [comment]
Yes, that is correct.
Documents are linked to the Corpus object basically. That's what it's for.
It was weird to realise that Speakers are not linked to anything, but the GlossFrequency objects are linked to Speakers.
At the moment, nothing is done with the Corpus field `speakers_are_cross_referenced`

You need to also read @ocrasborn 's comments about EAF files being used in multiple datasets. (#756).

**Comment by susanodd** [comment]
I started wondering about the Speakers when I started testing reading in a Speaker file multiple times.
At the moment, this does nothing.
But if somebody would modify the Age or Handedness inside the meta file, then the new data will replace the old data.
I implemented reading it in again as an update. (This is only on my local machine now.)
But then I started wondering about the Speakers also because they are anonymous. The Age is actually a number, not a date.
So you could have the same Speaker participating in different research at different Ages. No idea what to do about that!
It would be a speaker but at different ages.

**Comment by susanodd** [comment]
We could internally postfix the speaker identifier (field) with _metafilename.
Sloppy but we could then see how far we get.

**Comment by ocrasborn** [comment]
@susanodd , can this be closed?
