### ISSUE TITLE
Clean ups and refactors

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#358]
Issue for gathering things in the code that could be cleaned up or refactored. E.g.

- Remove all semi colons at the end of a line in Python code

**Comment by Woseseltops** [comment]
Good idea @vanlummelhuizen, these are the points that were still lying around in #114. Since these points are no longer really ASL-related, I'll close that one. 

Quick:
---------
* Delete all temporary ~ files from the repo
* Remove obsolete field 'init_text'
* Remove various symlinks from the media folder
* Rename scripts in bin folder
* Remove all unused imports

More effort:
----------------
* Rename media folder to static folder
* UserProfile should be in registration app

> I did a quick search for 'auslan', 'bsl', 'ucl' and 'legacy'. 'auslan' and 'bsl' are still found it quite a number of places. Changing some things involves Django migrations [...].
> 
> Note to self: the search command I used was
> 
> grep -iR -P 'auslan|bsl|ucl|legacy' * | grep -v Binair | grep -v -P '^django' | grep -v -i -P 'jquery|bootstrap|migration' | less

**Comment by vanlummelhuizen** [comment]
I asked @susanodd to do some code cleaning:

* Unused imports
* __future__ imports
* print statements; replace with Django logging? https://lincolnloop.com/blog/django-logging-right-way/
* Circular imports, including local imports; difficult!
* Commented out code; just remove, because it is also in git
* long lines; fold, see PEP
* (Multiple) blank lines; see PEP
* unused/deprecated code (methods, functions, ...); search for 'deprecated'
* remove semi colons
* comments that refer to git issues

**Comment by vanlummelhuizen** [comment]
In signbank.dictionary.models, there is Gloss.get_video() and Gloss.get_video_url(). From the look of it, there is unreachable code in both. I expect we can get rid of it (perhaps all of Gloss.get_video_url()).

**Comment by susanodd** [comment]
The get_video_url was assigning a constant video path as the result.
 return '/home/wessel/signbank/signbank/video/testmedia/AANBELLEN-320kbits.mp4'
That's been commented out.
There's more on the hand.
There's another method get_video_path (which uses gloss.idgloss as the name) which is called by get_video.
It's not entirely clear why there are so many different methods.

**Comment by susanodd** [comment]
The get_video_url was assigning a constant video path as the result.
 return '/home/wessel/signbank/signbank/video/testmedia/AANBELLEN-320kbits.mp4'
That's been commented out.
There's more on the hand.
There's another method get_video_path (which uses gloss.idgloss as the name) which is called by get_video.
It's not entirely clear why there are so many different methods.

**Comment by vanlummelhuizen** [comment]
* A small thing: in dictionary/views.py - import_csv() the error variable is initialized with False. Check whether it could be initialized with [] (empty list).
* Also in dictionary/views.py - import_csv(), but problably in many other places: find unused variables and remove them (PyCharm is you friend here).

**Comment by susanodd** [comment]
The error variable has always been False. (I wasn't the one to do this, it was used in order to be able to distinguish between no errrors so far and not initialised yet. I left it as it was. I'm trying to recall why. I think it was concatenating the error messages rather than making a list of strings. I will check it out!)

**Comment by vanlummelhuizen** [comment]
Are the management commands in 

* signbank/dictionary/management/commands/ingest_csv.py
* signbank/dictionary/management/commands/permissions.py

used or useful? @Woseseltops @susanodd @ocrasborn

**Comment by Woseseltops** [comment]
No, @vanlummelhuizen , these have been there seen the Steve era which means I was not aware of them until last month. You can also see this in the history ( https://github.com/Signbank/Global-signbank/commits/master/signbank/dictionary/management/commands/ingest_csv.py ) : although there are commits that touch these files, they are all automated replacements.

**Comment by vanlummelhuizen** [comment]
Thanks @Woseseltops 

Next: Do you see any use for 

* https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/templates/dictionary/update_video.html
* https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/templates/dictionary/update_result.html

? If not, I suggest we delete these files. @susanodd

**Comment by susanodd** [comment]
No, I can't find any links to these files. The second one looks like a draft / development version of something given the way the feedback is shown for an invalid form.

**Comment by Woseseltops** [comment]
Same story. Things from the Steve era that we don't use, can be removed.

**Comment by susanodd** [comment]
I'm working on the Gloss Search in #830.

**Comment by susanodd** [comment]
I'm working on get_queryset in #816.

**Comment by susanodd** [comment]
This issue is still active, although most of the original bullets have been addressed during code modification in other issues. And the FieldChoice and ModelTranslation involved lots of code improvement.

An issue that remains in the CSV functions.
I've been fixing some bugs there with Notes and Model Translation (missing languages the past months as arose during tests (now fixed).

I propose to revise the CSV import / export to make it more parametric.
In doing the "tests" on exporting and importing, the code is sometimes inconvenient for the user.
I'll see what I can come up with. The actual code still makes use of a variable called "stage" that was from the Steve era.

**Comment by susanodd** [comment]
See previous comment.
