### ISSUE TITLE
Discard duplicates in CSV import of series of values

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#370]
When importing keywords (and likely other comma-separated values in fields, can't think of an example right now), the CSV import function stumbles over duplicate items. Change the function so that duplicates are automatically discarded.

**Comment by susanodd** [comment]
@ocrasborn have you got an example of a value that is duplicated?
In the code, adding keywords relies on the (django) function get_or_create, so it should avoid duplicates that way. In the database, I did find e.g., duplicates with small differences: 
'aan de ene kant ...' versus 'aan de ene kant...' (the first one has a space).

Is your example with keywords in the same cell in the CSV file?
The import routine procedes through the CSV file and for each gloss, it executes the database update for the e.g., keywords that are different (changed). It looks like subsequent changes to the same gloss would override previous rows, if different. (The update_keywords routine erases the old keywords and saves the new keywords, for each of those, it uses get_or_create.)

Can you give some more details for your example?

**Comment by ocrasborn** [comment]
No duplicates in the database, but in the CSV file that we altered outside SB and then tried to import. So we had a cell saying 'leuk, aardig, leuk, sympathiek', for instance.

**Comment by susanodd** [comment]
Okay, this is fixed.

**Comment by susanodd** [comment]
Regarding duplicates, I'm working on Issue #42 for complex values and it's possible to import Relations to other signs.
What happens with Relations to other signs where the same "other gloss" is in two different relations with a Gloss (row) being imported (complex value with partial duplicates)?
Can another (target) gloss be related to a source gloss in two different relations?
The question arises when the same target has two different roles.
I started out deleting the old relations and creating the new relations for the imported CSV.
Then I made a version to modify the role if there is already a relation with a different role.
(Because if you first export a CSV and modify it, that's probably what you're doing.)
But now I'm thinking that there might be two different roles between the source and target.
Is this possible? If so, then it's probably better to delete the old relations and add the new ones rather than try to modify the old ones.

**Comment by susanodd** [comment]
I figured this out. The target gloss of a relation can be in more than one relation with the source.
I'll also check for duplicates in the complex values.

**Comment by vanlummelhuizen** [comment]
@susanodd Is this done?

**Comment by susanodd** [comment]
Yes, a long time ago.
