### ISSUE TITLE
ASL SB: The image disappears when you alter the Lemma Gloss field

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#394]
* Is that a freaky effect or what?! When I change it back, it appears again. Remember that file names are now based partly on the Lemma ID Gloss field --> My diagnosis: the picture file name does not appear to be changed when the Lemma ID Gloss field is changed.
* For the movie, no such problem (I think, but then the movie didn't display in the first place, and it seems like you're working on this as I type, @Woseseltops !)
* But, possibly related: When I edit a lemma gloss in my new test sign, the edit field that appears shows a lot of leading and trailing spaces around the gloss. Not so for the Annotation ID Gloss field.

**Comment by Woseseltops** [comment]
The extra problem caused by trailing spaces is what made this problem really messy confusing for me; when I fixed that (simply a matter of removing them from the template, fortunately), I could finally see what was happening... which turned out to be exactly what you describe: the picture name does not change when you edit the lemma field. Turned out to be related to file extensions, which were not remembered correctly. I think I fixed it now!

PS
We also had both problems (trailing space, picture names not changing) in the NGT Signbank, so I will also fixed this on the main branch.

**Comment by Woseseltops** [comment]
Report from Julie:

> Image sometimes disappears when changing lemma ID but not always. It used to be all the time but now it's unpredictable.

> Image disappears when changing lemma - continuing issue - when I edit ASB entries for suggested signs, if I change the lemma, the uploaded image disappears. Changing the annotation ID gloss doesn’t affect anything though.

And because Julie only does high quality bug reports, there is a video of the problem as well: https://www.dropbox.com/s/alw0her9c4t70nb/FileMissingAfterChangingLemma.mov?dl=0__;!!HJOPV4FYYWzcc1jazlU!ozRBLNZUDAz2udQnCMAEwAL-emYDrSAnwIQ4Q3163pBv3qzRtt7I3vnZq9Lpu8pT5Q$

**Comment by susanodd** [comment]
The video helps a lot.
Related to this I think: #763. I added a comment about a setting in the video/models.py file.
In the video, it looks like the small "d" typo at the start could be causing the implementation to look for or create or move files to a new folder with the first two characters.
The video shows the initial characters Annotation as "~D".

**Comment by susanodd** [comment]
I tried doing this on my local server.
I have two glosses matching DINO for ASL (on Global there is also a dataset ASL, so I'm trying it there with the Global code.)
One is as shown above (gloss id 26714 on Global) with the Annotation "DINOSAURd".
Because I have no videos, I first uploaded a video for this sign. (Apologies, it's a video for #A.)
I tried changing this to be "DINOSAUR" and I got a different error message.
![error-dinosaur-annotation](https://user-images.githubusercontent.com/24272544/127139524-29044aa7-068c-4794-a8b4-8922c0deed68.png)

In error text, it shows the text:
`The annotation idgloss translation text 'DINOSAUR' is not unique within dataset 'ASL' for gloss '26714'.`

**Comment by susanodd** [comment]
The code in the video is an older version than on Global. The update options for a Lemma are different now.
I don't know if that has anything to do with the error shown, if the newer code resolves that error.
With the example error above, that shouldn't happen either. So the code for updating the Annotation field needs to be user friendly if it's not possible.

**Comment by susanodd** [comment]
Here is the current version on Global.
![update-lemma-dinosaur](https://user-images.githubusercontent.com/24272544/127142244-86d01417-5b24-412f-b6bc-373b71a6c968.png)

**Comment by susanodd** [comment]
Here is how the Global works. (This is an old ASL, but it has the DINOSAUR gloss above.)
First, here is a search on Lemma's starting with "^DIN" (using the carrot).

![lemma-asl-carrot-DIN](https://user-images.githubusercontent.com/24272544/127143355-1e622fed-b0ea-4b8f-9df4-75cc7da4924e.png)

Then in Gloss Edit, using the "Choose other" Lemma button, and typing in DIN to get the list:

![ASL-DINO-choose-other-lemma](https://user-images.githubusercontent.com/24272544/127143473-d6c6d51a-6684-4b89-a022-c3544f6e6729.png)

**Comment by susanodd** [comment]
I realise I haven't got to the part of making the image disappear. I noticed the code doesn't correspond to Global, and from the video, it wasn't entirely sure what the analogous operation would be? Setting a different Lemma? Or editing the (existing) Lemma to end up with a different Lemma (i.e., Editing the current lemma)?
It's correct that changing the Lemma should not cause any change to the image or video. But modifying the Annotation can do so, as commented above.

**Comment by susanodd** [comment]
Is this still a bug?

**Comment by susanodd** [comment]
I fixed a test that was causing an error regarding moving files. #724 

As I recall this issue is related to changing the annotation so that its first two characters become different than the subfolder in which it was stored.

**Comment by ocrasborn** [comment]
@susanodd , can this be closed?

**Comment by susanodd** [comment]
Yes this can be closed.
