### ISSUE TITLE
Add automated testing

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#400]
Since some time now there are three people working on NGT-Signbank instead of one. And since the code base is growing more and more things can be broken after a change. We could benefit from automated tests as opposed to testing by hand, giving us more time for real development in the long run.

I propose @susanodd will look into this as one of her todos. 

@ocrasborn what do you say?

**Comment by Woseseltops** [comment]
I support this idea. I'm losing quite a lot of time by manually having to test 5 or so of the most important features every time I put something live. Automated tests would both release this time for more meaningful work AND test things more extensively.

By the way, I don't think we need to have 99% test coverage or anything (which I sometimes read software development companies want). I suspect the usage of features in software follows a Pareto distribution where few features are used most of the time and most features are only used a few times... so we can start really small. I think 5-10 tests will cover 90% of how Signbank is used.

**Comment by ocrasborn** [comment]
@ocrasborn agrees, @vanlummelhuizen!

**Comment by vanlummelhuizen** [comment]
@ocrasborn alright, I will set the wheels in motion. @susanodd, let's talk about this when we are both around. (One small wheel in motion...)

**Comment by Woseseltops** [comment]
Notes:
* https://docs.python.org/3.6/library/unittest.html
* @vanlummelhuizen taught me about Selenium this morning http://www.seleniumhq.org/
* Github contains 'hooks', which will allow us to do something automatically each time something happens, like running tests each time a commit is done. Would be nice to not have to worry about tests, but just get an email if we accidentally break something.

**Comment by vanlummelhuizen** [comment]
Note:

A while back @ocrasborn added some test users on the live server. Of course, we will use those for testing.

**Comment by Woseseltops** [comment]
Another reason to do this, and preferably do this soon: somewhere in 2018 Signbank will need to migrate from the old to the new Applejack. Would be really convenient and efficient if we had automated tests before that, so I can have an overview of all functionality that is not working yet.

**Comment by Woseseltops** [comment]
Idea for test: the 'create ECV' option.

**Comment by vanlummelhuizen** [comment]
Selenium and Python: http://selenium-python.readthedocs.io/

**Comment by vanlummelhuizen** [comment]
Unittest in Django: https://docs.djangoproject.com/en/1.11/topics/testing/overview/

**Comment by Woseseltops** [comment]
Test idea: log in as a user with low permissions, and see if this user can still do what he is allowed to do (we mis permissions bugs because we're superuser status).

**Comment by Woseseltops** [comment]
Set this to blocking: we accidentally broke the ASL Signbank for the second time this week without realizing. We need to have this fast.

**Comment by vanlummelhuizen** [comment]
Soms of us may want to take that course :)

**Comment by susanodd** [comment]
Theory versus practice.
Lots of our methods are several hundred lines long.

**Comment by henrinie** [comment]
Are ASL and NGT out of sync in production? If not, would this issue be solved if they were kept in sync?

Have you considered starting managing this with versions? You would be more aware of what has changed, and it would be easier to move between different versions. This might possibly slow down the continuous integration cycle, but probably would have a positive impact on the rate things would break.

I think that you should definitely start adding tests, but it might also not directly solve this problem you are having.


Offtopic:
By the way, you seem to have changed the repo name from NGT-signbank to Global-signbank. This might cause some headache to people trying to figure out what is NGT-signbank and what is Global-signbank, as the name NGT-signbank has been referred for the software in some papers, documents and so on.

**Comment by susanodd** [comment]
@ocrasborn can you give a summary of the four test users and what they can each do?
user-dataset, user-editor, user-guest, user-researcher
I am working with these, but it's not clear to me what the intended permissions of these users is meant to be with respect to the datasets.
At the moment (my database is sync'd with the online signbank from last thursday): 

User user-dataset can view NGT and BISINDO but not change any datasets.
This user belongs to group Editor. (This group has lots of permissions but not view or change dataset.)

User user-guest can view TestDatasetMicha and can change TestDatasetMicha
This user belongs to group Guest. (This group has no permissions.)

User user-editor can't do anything and isn't in any group.

User user-researcher can't view or change any datasets.
This user belongs to group Researcher which can export_csv, search_gloss, and view_advanced_properties

**Comment by ocrasborn** [comment]
Hi @susanodd , the four test users were created some time ago to test the different group permissions. We didn't have the group Dataset Manager yet at that time (I created that one this week, as a prelude to upcoming permission changes), so perhaps it was just created to mess around with object permissions a bit as a test? The datasets that these users have access to are set in the Object Permissions of the different datasets, independently of the group that they are part of. Does that help?
Let me change the user-editor to be in the group Editor, and user-dataset to be in the group Dataset Manager, that will be clearer for everyone.

**Comment by ocrasborn** [comment]
oh, @susanodd , and let's scale up the password complexity now that the user names are on the street ;-)

**Comment by Woseseltops** [comment]
Idea for test: the create CSV option .

**Comment by susanodd** [comment]
python bin/develop.py test -k

**Comment by Woseseltops** [comment]
Okay, I'm also going to work on this because I need it so badly for ASL. 

My first obstacle is that I'm annoyed that the whole Django testing module takes so much time to load before it even starts running the tests, which makes iterating a lot harder. I spent almost a whole day trying to fix this, but with no success. Stack Overflow suggests the problem is in the fact that migrations have to be re-executed on the test-database (which might be unlikely, given the fact that we're reusing an existing test-database). There are several solutions to this (special settings, separate plugin, etc), but I got none of them working in the end.

For the tests themselves, I've will start with the basic creating, reading, updating and deleting (CRUD) of a gloss, and I have done CR so far. For UD I want to use the update_gloss function in update.py , because that's how it's done in the interface as well. (todo 1)

My first test basically ignores the whole dataset system, which created problems for ASL before. Therefore I also want to create a test that checks whether you can discover some glosses when having activated the correct dataset, and nothing otherwise. (todo 2)

**Comment by henrinie** [comment]
@Woseseltops 
Testing is indeed rather slow, which is frustrating me as well. It is because the test database has to be initialized every time you run tests.
You mention that you are reusing an existing test database, but have you confirmed that? By default when running django tests, the test database gets destroyed after tests have been run.

To try to speed up testing you could try running it with the `--keepdb` flag.
> -k, --keepdb          Preserves the test DB between runs.
https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-test-keepdb

I've found it to speed up the tests quite a lot, since it doesn't migrate a new database each time.

**Comment by Woseseltops** [comment]
Thanks @henrinie , we're indeed using the keepdb flag. I wonder how much slower everything would go without it :( .

**Comment by henrinie** [comment]
@Woseseltops 
Well that sound painful! How slow is it?
What kind of test are you running, and what kind of setup do you have?

**Comment by henrinie** [comment]
@Woseseltops I tried to get Global-signbank running, but it seemed to take too much time, so instead of committing changes I suggest changes in here.

https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/tests.py#L19-L20
Remove the loop, as it is querying for all objects like that, and then looping them over - just a database query is much faster. Change to:
`total_nr_of_glosses = Gloss.objects.filter(handedness=4, idgloss=''thisisatemporarytestgloss').count()`

https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/tests.py#L34-L37
Similar thing is going on. Change to:
`found = Gloss.objects.filter(handedness=4, idgloss=''thisisatemporarytestgloss').exists()`

Maybe those lines are slowing down the tests - probably depends how many objects it actually loops over. Hope this helps. I really don't know why your tests are slow though, you don't seem have that many on the master branch.

**Comment by Woseseltops** [comment]
Thank you for your input, but the problem is it takes 2m30 before the tests even start. 

I just had a look around in the Django test code, and the problem is in:
* test/runner.py, function setup_databases, where the slow part refers to
* test/utils.py, function setup_databases, where the slow part refers to
* db/backends/base/creation.py, function create_test_db, where the slow part refers to
* db/backends/base/creation.py, function serialize_db_to_string, where the slow part refers to this line:

```
serializers.serialize("json", get_objects(), indent=None, stream=out)
```

Looks like the problem is that it's putting the whole test database into a single JSON string. Our databases turned out to be largely filled by with reversion info and django session info. If I remove that (resulting database goes from 749MB to 4.5MB!), so there is a lot less to serialize,  running tests only takes 43 seconds. 

If I also remove `'dictionary_gloss','dictionary_translation','dictionary_annotationidglosstranslation','dictionary_keyword','dictionary_relation'` we go to 1.5MB and only 4 seconds.

**Comment by henrinie** [comment]
@Woseseltops 
Wow, now I understand your frustrations. If it really takes 2m30s it is pretty slow indeed, significantly slowing down development. With the `--keepdb` option, does running the tests a second time take as long?
It still seems rather weird though, as 750MB isn't really a very big database. I don't understand why it loads the whole database as json though, if you have a large database wouldn't you run out of memory?
On the other hand, shouldn't the test database be empty once initialized? So it shouldn't be loading your whole database into the test database, afaik.

Maybe you should delete the revision history, django-reversion offers management commands for this. The oldest versions aren't compatible with the latest models anyway, so they are mostly useless. This would at least speed up your tests for right now.

**Comment by Woseseltops** [comment]
> I don't understand why it loads the whole database as json though

Maybe to be able to quickly reset the situation in between tests, or something like that?

> if you have a large database wouldn't you run out of memory?

Yeah, or the whole framework becomes incredibly slow, like the problem we had. In the actual Django code it actually mentions that it won't work with large databases indeed.

Anyway, I created a script that can quickly initialize a fresh test database that won't slow down the Django test framework, documented here: https://github.com/Signbank/Global-signbank/wiki/How-to-run-unit-tests

Furthermore, I finished my CRUD tests. Next up is a series of tests to check if the search functionality returns the correct things, based on both your search terms and permissions.

**Comment by Woseseltops** [comment]
Search things I want to test:
* Basic: I add a gloss, then search for it by idgloss and handedness... do I get it back.
* Datasets: I add the gloss to a dataset I don't have access to... I shouldn't find it anymore.

I made a start today, but my search returns nothing so far... I think because my test user has no dataset selected. Feel free to jump in if you feel like it, Micha or Susan.

Furthermore, I went through the problems we had with ASL, and we also need tests that:
* Check whether you can add videos (do I get a HTTP 200 at the expected URL afterwards?)
* Check whether you can delete videos (do I get no HTTP 200 afterwards?)

**Comment by susanodd** [comment]
Ahoy, @Woseseltops!
I got it to return query results. You need to modify these lines;
        client = Client(enforce_csrf_checks=True)
        response = client.get('/signs/search/?handedness=4', follow=True)
[I also added a self.user.save() after granting permission for the dataset. Not sure if that matters. Not sure if that is needed or not.]

After that, the returned set of glosses is non-empty!

(I did it on a test-database copy of the real one. I altered your testSearchForGlosses function by commenting out the new gloss creation, since I'm not sure off the top of my head which fields need to be non-empty. If the database generates an error it might just return nothing.)
Regarding the query parameters, there are actually a few more that are non-empty, including the csrf token. Also some for displaying properly.
We'll find out I guess if the absense of other parameters messes things up.

**Comment by Woseseltops** [comment]
Okay, @susanodd and I have figured it out. It's not the suggestions that Susan did above, but instead I needed the stupid permissions 'dictionary.search_gloss' and 'view_dataset'. The rest of the code was okay. It worked for Susan, because she is not working on an empty database, but instead on a database that already had a few glosses where inWeb was true, and then you don't need the search_permission . 

I've now written a test that creates some glosses and then finds them back with a search query, but only if the right dataset is selected.

Next up: the video tests that I described above.

**Comment by Woseseltops** [comment]
While migrating Signbank to the new Applejack, I found myself manually checking if Xsendfile (only show images when you're logged in) was working, so an automated test for that would also be good.

**Comment by Woseseltops** [comment]
Okay, I think all tests are there now! I just added a test that checks if you can add and delete videos, and as well integrated a check that you cannot see videos if you're not logged in.

By the way, @vanlummelhuizen, your test about creating glosses is failing in production... I think something changed there?

**Comment by ocrasborn** [comment]
Next up: #410

**Comment by Woseseltops** [comment]
Ha! Turns out the gloss creation test by @vanlummelhuizen was simply not working because of a typo in a string. Fixed that, now it works. As we now have basic functionality tested, let's close this issue and create smaller ones if needed later.
