### ISSUE TITLE
When creating new glosses through CSV import, fill the creator and creation date fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#402]

**Comment by susanodd** [comment]
I'm working on this. I came across a couple of bugs related to datasets and gloss creation.

**Comment by susanodd** [comment]
Question: when importing, there is a column for dataset. In the Dataset pull-down menu where one can view datasets and whether one has access or has selected them, there isn't any information about what Languages are associated with these datasets.
After a new gloss is to be created via import, a table is to be displayed showing the various columns.
At the moment this table seems to show columns for all the languages of all the datasets the user has access to rather than just the language fields (columns) in the import file.
There is currently a chicken or egg error and I can't tell where it's coming from. It looks like it's attempting to access these "other" languages.

**Comment by susanodd** [comment]
![available-datasets](https://user-images.githubusercontent.com/24272544/34986822-49cf8780-fab9-11e7-86e7-e96827cf1dca.png)
![selected-datasets](https://user-images.githubusercontent.com/24272544/34986827-4e279ffc-fab9-11e7-8f85-bf1a63a9b848.png)
![glosses-to-create-columns](https://user-images.githubusercontent.com/24272544/34986831-51e94b22-fab9-11e7-9351-a16698a3472c.png)

**Comment by susanodd** [comment]
The csv file in the example has one row and it has columns for Dutch and English.
@vanlummelhuizen added the functionality to show the extra columns. (I have access to all the datasets on my machine. It seems to be showing extra columns for Chinese and Norwegian because of that. But is this correct?)
The question is, where is this information about what languages are relevant for the dataset I'm trying to import (create) my new gloss into? If you look at the Datasets information (the first two screen shots), there isn't any information about languages.

**Comment by susanodd** [comment]
I modified the code to display only columns for languages of the selected datasets rather than all datasets the user has access to.
The creator and creation date are added implicitly to newly created glosses.
This is on github.

**Comment by ocrasborn** [comment]
Did you find where the info on the 'translation languages' is for each dataset, @susanodd ? The place where I specify them when creating a dataset is in the django admin under datasets, wouldn't know how to look it up otherwise.

**Comment by ocrasborn** [comment]
Oh, @susanodd , for the existing glosses in the two datasets Shanghainese and Kata Kolok, would you be able to set the creation date to Jan 1, 2018? The creator can be hannahlutzenberger for Kata Kolok, and me for Shanghainese.

**Comment by susanodd** [comment]
This may require a database change. There aren't any fields for creator and creation date for the datasets themselves. @vanlummelhuizen ?

**Comment by ocrasborn** [comment]
That's right, and that can stay that way: we don't need  entry date / creator fields for data sets.

**Comment by vanlummelhuizen** [comment]
Commit https://github.com/Signbank/NGT-signbank/commit/183c31ce4442f3214156f795d2989ecd0d5e5967 is for #391. Sorry.

**Comment by susanodd** [comment]
The creationDate (= now) and creator (= user) are now set implicitly in the online add_new_sign and add_new_morpheme routines. The Annotation ID Gloss fields are now required in the template.
The Morpheme Type selection is still as it was (optional).

**Comment by vanlummelhuizen** [comment]
This is live now.
