### ISSUE TITLE
Make Lemma ID Gloss and Annotation Instructions multilingual cf. other gloss fields

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#405]

**Comment by vanlummelhuizen** [comment]
If you mean the pop up thingy when clicking on the ? of 
![screenshot-2018-2-22 signbank search signs](https://user-images.githubusercontent.com/16682631/36546642-38c1fdba-17ec-11e8-9ac2-ee4ec935cf11.png)

it is translated text, but there are no translation for it yet. Any takers?

**Comment by vanlummelhuizen** [comment]
OK, I understand now. Forget my previous post. (although it is something that needs to be done)

**Comment by vanlummelhuizen** [comment]
@ocrasborn, all LemmaIdglossTranslations are live now.

**Comment by susanodd** [comment]
This seems to have broken some of the other pages and functions that use dataset_id.

**Comment by susanodd** [comment]
The gloss wesseltest is crashing the code because the gloss has no dataset. I'm rewriting the raw queries because dataset is now in the lemma table, and adding additional tests to make sure the lemma and dataset are not empty before trying to compute other things that use the dataset. The dataset field used to be a none value if not set, but now because it's via a join to another table the Django raw query mechanism keeps crashing on the wesseltest sign.
Good test sign, @Woseseltops!
(The wesseltest sign in question is actually hidden to other pages because it has no dataset. But it's hanging around in the database.)

**Comment by Woseseltops** [comment]
Is this done now we merged your branch, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
Yes
