### ISSUE TITLE
Add logo to the left of the title in the header

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#411]
* Related to #226, renaming from NGT to Global
* See the att. SVG file with transparency

[GlobalSigbank_logo_white.svg.zip](https://github.com/Signbank/Global-signbank/files/1674033/GlobalSigbank_logo_white.svg.zip)

**Comment by Woseseltops** [comment]
Done. Forgot to label 3941c678 .

About the logo itself:
* It's meant to represent the sign for Signbank, amirite? And the circular part maybe the globe?
* Cool, SVG. SVG files are cool because (1) they are typically super small and thus fast, (2) you can zoom in as long as you want, the image stays pretty and (3) we can change it by code (for example, the color).
* There was a large empty area around the logo. I removed this area with InkScape.

Questions:
* I guess this is only for our Signbank, right?
* I guess we also want this as website icon, right?
* I already caught myself trying to use the logo as a home button. Do we want that?

**Comment by ocrasborn** [comment]
Cool! 
It's not really the sign for Signbank, no. It was created by a deaf artist who had a whole story about it, she will still explain on video (which we will subtitle) what her ideas about the logo were.
Answers:
* Only for the Nijmegen installation, not the ASL SB, indeed.
* Yes, good to use it as the icon if it's stlll interpreteble at very small size.
* Home button for... you mean to return to the home page? Yes, why not.

**Comment by Woseseltops** [comment]
>  if it's stlll interpreteble at very small size

Tried it, answer: no. I can make the lines thicker, not sure if the artist would agree.

> Home button for... you mean to return to the home page? Yes, why not.

Done.

**Comment by ocrasborn** [comment]
The artist would die! But if it's a special version only for the favicon, then yes let's do that. As long as the header logo stays as it is.

**Comment by Woseseltops** [comment]
Any news about the favicon? I vaguely remember you working on it.

**Comment by ocrasborn** [comment]
just emailed you the alternative version I have

**Comment by Woseseltops** [comment]
Thoughts, @ocrasborn ?

**Comment by ocrasborn** [comment]
I think it would be good to maintain the circle (with its opening) primarily, and less so the hands. Could you try that out?

**Comment by Woseseltops** [comment]
> I think it would be good to maintain the circle (with its opening) primarily, and less so the hands. Could you try that out?

You mean like this?

![signbank_ico](https://user-images.githubusercontent.com/1909317/36843663-e91b7dfe-1d4f-11e8-98cc-9933491e922a.png)

Feeling creative, a quick idea that keeps the idea of the hand inside a circle, but flips the colors (like the Github Icon):

![signbank_ico](https://user-images.githubusercontent.com/1909317/36843726-19ede4e4-1d50-11e8-9049-dc5e97afe1e2.png)

**Comment by ocrasborn** [comment]
Let's do the hand in the circle, nice!

**Comment by Woseseltops** [comment]
Done. Made it so the hand changes color with the background. You might need to do a Shift+F5 or CTRL+F5 to see it.

**Comment by ocrasborn** [comment]
Nice!
