### ISSUE TITLE
Restrict searching to the same dataset when linking a sign 

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#416]
* When linking a sign in the panels Morphology or Relations to Other Signs, it is now possible to link to all signs from any dataset. Linking should be restricted to the same sign as the one that is being edited. (This would then automatically align with the right permissions, as editing a sign entails having write access to the dataset.)
* Examples: compound parts, homonyms/hyponyms/etc.

**Comment by susanodd** [comment]
I fixed the Relations to Other SIgns.

**Comment by susanodd** [comment]
This part of the python code is Ajax calls to the database.
It's done by functions gloss_ajax_complete, morph_ajax_complete, and handshape_ajax_complete.
I added a session variable for the Gloss's Dataset in order to pass this information to the ajax functions.
(The ajax functions use pattern matching completion on the url calls. The ajax code dynamically keeps fetching matches with the typed prefix. The Dataset check is just a check before including a match in the results to be shown on the page.)
The morphemes lookahead will work the same way.
I'm not sure about the Handshapes.
We've hard-coded the language names into the handshape_ajax_complete code.
That will likely cause problems for ASL. Is ASL using a Handshapes table?

**Comment by susanodd** [comment]
One thing that needs to be addressed, the lookahead, if you start typing a prefix that doesn't exist in your dataset, there is nothing shown to choose from.
But the way the code is implemented, if you type something in as a string (rather than selecting from the list), it doesn't work. The code has apparently always been this way.
With new datasets, where there aren't many signs, this might be confusing.
Probably the ajax calls need to be modified to show all matches if the user hasn't successfully come up with a first character for which glosses (morphemes, handshapes) exist.

**Comment by susanodd** [comment]
Oops, Morpheme's don't have a Dataset. Those will remain the same as they were.

**Comment by susanodd** [comment]
No, wait, they do have a Dataset! There weren't any morphemes in my Test Dataset so none were found to select from.
Probably some feedback is needed.

**Comment by ocrasborn** [comment]
As far as I can see, it works very nicely also for Morphemes now. And, elegant!, it presents a message when no morphemes are available for that dataset yet. Well done.
