### ISSUE TITLE
Specify type of access in dataset overview

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#421]
On the page _View available datasets_, access is now displayed as a single value. Turn this into two columns, that display the Django object permissions VIEW DATASET ("View" in column header) and CAN CHANGE DATASET (column header: "Edit").

**Comment by susanodd** [comment]
I modified the Dataset List View to show the access as described.
But to my surprise, on my local signbank (**), both of the Access columns show Ja Ja for all datasets.
When I look at the admin page for e.g., AdaSL, I am not shown as a user with any permissions, 
and no groups are listed for this dataset. (See the screenshot below.)

** my local database was updated yesterday to the most recent online database

![dataset-permissions-user-group](https://user-images.githubusercontent.com/24272544/36028219-78648616-0d9e-11e8-8d5c-cb917fabe36b.png)

![view-datasets-ja-ja](https://user-images.githubusercontent.com/24272544/36028494-7a87b9d0-0d9f-11e8-9791-e29c295377e6.png)

**Comment by susanodd** [comment]
Maybe the View display needs to query the actual users who specifically have permissions rather than using the Group Editor setting.
When I look at the permissions for Group Editor, it looks like the Editor should be able to view and edit available datasets, but (based on my understanding of English) it's not clear whether this would also mean actually looking inside those datasets. I would expect the Group Editor permission would allow one to add and remove datasets, but that for a specific dataset, permissions to be on the admin page shown above for the dataset.

**Comment by ocrasborn** [comment]
Hi @susanodd , I've just started to spell out some of the permissions of the different groups on the wiki, see there. Won't be complete, for sure. My intention is a hierarchical setup of the groups: let only Publishers create datasets, let only Publishers and Dataset Managers (new group since this morning) edit user permissions for their dataset, and let Publishers and Dataset Managers and Editors  (but not Researchers and Guests) add and change contents of datasets.
Note that there is currently no permission yet to assign to Dataset Managers (#423) and up to let them manage users, nor an interface for this user management (#422 ).
I hope that we can then avoid having to assign permissions to individual users, managing everything through groups.

**Comment by ocrasborn** [comment]
Just checked: you're not a superuser, so I don't understand either why it says 'yes' to all datasets in both columns for you.

**Comment by susanodd** [comment]
Yes, that was the problem. On my local machine I was. Now I'm just an Editor.

**Comment by ocrasborn** [comment]
Works! Thanks @susanodd
