### ISSUE TITLE
Set up a page for Dataset Managers under menu Dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#422]
* Menu item/page should only be visible for groups Dataset Manager and Publisher
* Page should contain a list of datasets for which the user has been assigned as a dataset manager (= #423 )
* Page should display and allow for modifying object permissions for the dataset. Perhaps not displaying the list of all users, which will become larger and larger, but by searching for First name and/or Surname?

**Comment by susanodd** [comment]
I started working on this. So far, without manager permissions, just to see what the interface can be.
Here is an example with the lists of view and change users for each dataset.
I made it be username, with a tooltip hover to show first_name and last_name.
I'll work on how to allow updating the permissions next. There might need to be a detail view.

![dataset-manager-tooltip-user](https://user-images.githubusercontent.com/24272544/36904098-fdcafcc6-1e2f-11e8-94c5-a8d482076e01.png)

**Comment by ocrasborn** [comment]
Perhaps you already had this in mind, @susanodd , but it would be good to filter this list in such a way that a dataset manager can only see the datasets for which s/he has management permissions (#423). If only for privacy's sake.

**Comment by susanodd** [comment]
Here's what it looks like now. (See below.) I put in parameter checking for various cases (10 different error messages and 6 different success messages). The functionality currently uses the Dataset Manager group and the change_dataset permission (for the logged in user) in order to change the permissions (of other users).

![dataset-manager-select-user](https://user-images.githubusercontent.com/24272544/37029776-dcb33a74-2138-11e8-8331-85fb44daa8bb.png)
![dataset-manager-info](https://user-images.githubusercontent.com/24272544/37029786-e0f438cc-2138-11e8-9c17-7fdf6ef7b03a.png)

**Comment by susanodd** [comment]
I'll work on the revised Dataset Manager permissions (the emails) next. I'll put this version online so it can be experimented with.
Offline, I'm superuser on my local signbank, so I had to login as the test user-dataset in order to view the page properly (with a dataset list restricted to those the user can manage).
I made it so the staff and superuser status isn't shown in the list of users, as can be seen above.

**Comment by ocrasborn** [comment]
Would it be an idea to also list the current users in two columns to the right of "Users View Dataset" and "Users Change Dataset"? Or would that become too tight? The nice thing would be that managers then immediately see the result of what they do in the updated list.

**Comment by susanodd** [comment]
The list is visible after you click on Manage. It is updated after you add a user.
It folds back up at the moment so you have to click on Manage again to see the updated list.
I will alter the display.

**Comment by susanodd** [comment]
![dataset-manager-list-view-users](https://user-images.githubusercontent.com/24272544/37094454-4003415c-2213-11e8-8104-79827026e70f.png)

**Comment by susanodd** [comment]
I modified the page so that after you have added a permission for a user, the Manage area stays open so you can see the changed list.

**Comment by susanodd** [comment]
Yes.
