### ISSUE TITLE
Ensure that video and image data are stored in separate sub-folders per dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#426]
* Now they're all under the same folders glossvideo/, othermedia/, glossimage/, removed_glosses/.
* handshapeimage/ should remain a system-wide folder

**Comment by vanlummelhuizen** [comment]
@ocrasborn What do you want to have as sub-folder name: dataset ID, name or acronym? What is the reason for this request by the way?

**Comment by ocrasborn** [comment]
The reason for the request is that different datasets (and their media, it also holds for all images) have diferent owners and different permissions for sharing. It is good to keep the media organised according to dataset for that reason, and moreover it is sometimes convenient when we want to get the media from the server for a specific dataset.
Let's use Acronym for the folder names.

**Comment by vanlummelhuizen** [comment]
Note that managing media by Signbank will become a bit more complicated, possibly resulting in a few errors here and there.

Just an alternative idea: create a view that lists download urls for all media files of a specified dataset, either in html (with links), json or txt for use with tools such as wget.

**Comment by susanodd** [comment]
I wouldn't mind coding this issue. I recently dug into the image and video naming in filenames and paths in order to get rid of numerous errors in the server error.log involving special characters.

**Comment by susanodd** [comment]
What Micha said, using a view seems like a good idea to me too.
There is no correlation between users of signbank and users of the file system underneath.

**Comment by ocrasborn** [comment]
Well, if it's a lot of work, we shouldn't do it (now). How about another alternative, would that be less impactful? That is, to prefix all the videos and images with the dataset acronym (followed by underscore)?

**Comment by vanlummelhuizen** [comment]
It would involve changes in

(adding video)
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/video/views.py#L40
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/video/views.py#L50
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/video/views.py#L56

(getting video)
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/dictionary/models.py#L1402
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/dictionary/models.py#L1411
* https://github.com/Signbank/Global-signbank/blob/6b294a8458f29a192d198a9ee5b2ceebe432ef24/signbank/dictionary/models.py#L1430

**Comment by vanlummelhuizen** [comment]
This issue together with #522 are now done. Can you confirm it is working @ocrasborn ?

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen : almost done, I would say. Two observations along with requests:
* The old system seems to coexist with the new one now; could you manually clean up the remains of the old system (assuming that this is indeed a remnant)?
* I created a test item for dataset EmblemsNL, uploaded a picture in the video field (which was allowed, interestingly enough) for the gloss BOOS, the image of the "video" is correctly generated, but on the server it is not stored in a subfolder BO/ under EmblemsNL/, but rather directly under EmblemsNL/. Replicated it for another dataset (testOC_LSC), this time with a video: same thing. Both the video and the image are not stored in a two-letter subfolder yet. Could you still address this, so that all media are stored in two-letter subfolders, like they were? (Note that the old, existing, media, were correctly kept in their subfolder; it's just the new ones for which it doesn't yet seem to happen.)

**Comment by vanlummelhuizen** [comment]
@ocrasborn I am confused. All videos and images are in a two-letter directory inside the dataset directory:

glossvideo/testOC_LSC/te/test1_en-36395.mp4
glossvideo/EmblemsNL/BO/BOOS-36625.mp4

Those paths are also in the GlossVideo objects.

So unless you manually moved the files AND changed the database, I think it is all correct.

Or am I missing something?

**Comment by ocrasborn** [comment]
@vanlummelhuizen : hm. I must have looked with my elbow. All looks good now.

Could you still clean up the old folders, if you're convinced everything has been successfully copied?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done for videos. There are some remaining videos (I counted 11) that are not moved to a dataset folder. The reason is that the glosses they belong to are not in a dataset. There are 36 of those. Those orphaned glosses are inaccessible through the web application. Would it be wise to create a default dataset to collect them?

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done for images as well. Note that I moved the file to a backup folder instead of deleting them. So if something appear to be wrong, we should be able to get the files back.

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen , I just double-checked it was all in good shape: yes, insofar as the folder structure looks good for the datasets; but no, in the sense that for both videos and images there are some leftover folders like glossvideo/BE/ and glossimage/CH/. (Some of the glosses they link to still exist, some not, it seems. Some were generated on the days you reported the above changes, some long before.) Could you look into this?

**Comment by vanlummelhuizen** [comment]
What I found:

glossvideo:
- "BEZOEKEN-A", 4745: no dataset
- "BIJNA-B", 4727", 4745: no dataset
- "DRONGO-FESTIVAL", 3213: dataset NGT, **moved by hand**
- "HELPEN-A:1", 4747: no dataset
- "HELPEN-A                                    ", 4746: no dataset
- "                                            HELPEN-A                        ", 4747: no dataset, _note that the ID is the same one of the above_
- "HOORN", 4726: no dataset
- "LOPEND-VOORTBEWEGEN", 4751: no dataset
- "LOPEND-VOORTBEWEGEN-B", 4750: no dataset
- "OVER+GETAL-C", 4428: dataset NGT, **moved by hand**
- "PLAATSEN", 4748: no dataset.

glossimage:
- "BIJNA-B", 4727: no dataset
- "                                            HELPEN-A                        ", 4747: no dataset
- "HOORN", 4726: no dataset
- "LOPEND-VOORTBEWEGEN", 4751: no dataset
- "LOPEND-VOORTBEWEGEN-B", 4750: no dataset
- "PLAATSEN", 4748: no dataset
- "wesseltest", 3107: no dataset
- "1", 10153: dataset LSFB. no related GlossVideo
- "2", 10648: dataset LSFB. no related GlossVideo
- "3", 10590: dataset LSFB. no related GlossVideo
- "4", 11723: dataset LSFB. no related GlossVideo
- "5", 10798: dataset LSFB. Has an GlossVideo refering to glossvideo/NGT/5-/5-2449.mp4
- "5", 2449: dataset LSFB. no related GlossVideo
- "6", 11378: dataset LSFB. no related GlossVideo
- "7", 11386: dataset LSFB. no related GlossVideo
- "8", 9436: dataset LSFB. no related GlossVideo
- "9", 9386: dataset LSFB. no related GlossVideo

All things that do not have a dataset, cannot be moved to a directory with the dataset name. All things without a GlossVideo are not used because of that.

**Comment by ocrasborn** [comment]
I removed the remaining stray videos/images with their parent folder, all clean now.
