### ISSUE TITLE
Cannot upload videos for signs that do not have a video yet

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#437]
Could replace a video for a test sign that already had one, though.

**Comment by vanlummelhuizen** [comment]
Should be fixed now. Please test.

Note: I came across a gloss that had many spaces in lemma idgloss at the beginning and at the end (wesseltest6). This resulted in an error when uploading a video. When displaying the lemma idgloss, the spaces are not shown because of how a browser displays multiple (normal) spaces, so this is hard to spot. I will look into this for a bit now.

**Comment by vanlummelhuizen** [comment]
OK. There are two of those: wesseltest6 en HELPEN-A. No idea how this has happened. Perhaps the versioning system will help.

**Comment by vanlummelhuizen** [comment]
The changes of HELPEN-A that introduced the spaces were made on November 15, 2017. The changes of wesseltest6 that introduced the spaces were made on December 22, 2017. For this gloss some spaces were added for each time the gloss was changed.

**Comment by vanlummelhuizen** [comment]
I did some minor tests editing the gloss and see whether new spaces were introduced. There were none. Perhaps we just repair the two glosses and revisit this issue when this problem reoccurs? @ocrasborn
