### ISSUE TITLE
Backup stopped working

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#444]
Error message (also for NGT):

lockfile creation failed: cannot write PID lockfile
ERROR: Another cometbackup process is still running: /vol/archive/backups/asl-signbank. Canceling backup.

All went fine until this time.

**Comment by Woseseltops** [comment]
Aah yes the archive disk was full, also a problem for other things we're backing up. Removed some stuff, now there's space again.

**Comment by ocrasborn** [comment]
New error:
lockfile creation failed: cannot write PID lockfile
ERROR: Another cometbackup process is still running: /vol/archive/backups/asl-signbank. Canceling backup.

**Comment by Woseseltops** [comment]
Hmm archive was full again. I have turned off the ASL backups (it doesn't run here anymore) and removed the (horribly outdated, anyway) backups to make some room. The biggest space eaters, however, are old archived datasets nobody uses anymore. I've started a small project to find out which ones can be removed.

Please keep this issue open until I have done this.

**Comment by Woseseltops** [comment]
Currently removing unused datasets.

**Comment by Woseseltops** [comment]
OK, this morning at 500h a new backup was finally created again, so I think we're good. 

One thing I discovered which is good to keep in mind: while the backup creation mechanism stopped working, the mechanism that intelligently cleans up more and more backups as they get older (so that you three backups for yesterday, a daily backup for last week, or weekly backup for last month, etc) worked perfectly, meaning almost everything was cleaned up already. Next time, when the backups are failing, this cleaner should be turned off.

Let's keep this issue open a little longer to see if the backup directory fills up nicely again.

**Comment by Woseseltops** [comment]
The backups are back up!

**Comment by Woseseltops** [comment]
Turns out I cannot simply get an overview of the main disk space users on /vol/archive , because (1) I get all kinds of permission problems and (2) it takes ages (probably related to the fact that this is a network disk). For that reason, I asked C&CZ to do it for me, 

Furthermore, I received my first backup error this morning. I've made some changes to my mailbox filters to make sure that it's not moved to my 'cron' folder immediately (which I rarely visit), let's see if that works.

**Comment by ocrasborn** [comment]
Hell broke loose! Keep your manual backup!

**Comment by Woseseltops** [comment]
> Hell broke loose! Keep your manual backup!

I still have it, let me know if you need it. 

> curious what the outcome will be

Okay, I think I found the problem: one backup mechanism running since dec 2017 did not have the cleanup schedule defined, so we were storing 3 backups without deleting anything. This explains why /vol/archive kept filling up while it didn't before. I've added a cleanup schedule now, let's see if that fixes it.

**Comment by ocrasborn** [comment]
I see on the server that the backups are being created, but the log emails don't list the remaining backups anymore like they used to. Did something change there?
Oh, @Woseseltops , and are things also OK for the ASL SB?

**Comment by Woseseltops** [comment]
>  Oh, @Woseseltops , and are things also OK for the ASL SB?

I checked, and American backups are being created, but not cleaned up again *sigh*

Okay, with all of the different backup procedures I'm starting to get confused again, so let's throw a table at it :). ( [Not like this](https://i.gifer.com/R7i9.gif) )

|Server|Location|Backup frequency|Backup working|Clean up schedule|Clean up working|Remarks|
|--|--|--|--|--|--|--|
| Applejack | Signbank database folder | 1 per d | Yes | After 2 w: 1 per w, after 1 m: 1 per m | Unclear yet | Problems with the next backup blocked this one. |
| Applejack | /var/www | 1 per 2d | Yes, but the backup processes don't finish | After 1 w: 1 per w; after 1 m: 1 per m | Yes, but cleanup process doesn't finish | First the lack of cleanup filled the /archive disk, now hanging processes fill up /tmp |
| Yale server | Signbank database fodler  | 1 per d | Yes | After 1 w: 1 per w; after 1 m: 1 per m | No | Disk is slowly filling up |

**Comment by Woseseltops** [comment]
Update on the 3 backup processes:
* Applejack/SB db: I see a daily backup, but nothing is cleaned up yet. This is possibly because we have nothing more than 2 weeks old. 
* Applejack/general: I'm not making backups right now, because I am waiting for a cleanup to finish. Not done yet, bit I see a lot of old unnecessary backups have been removed already.
* Yale/Sb db: I was surprised to find only a backup of yesterday this morning. Now that I have studied the schedule, my hypothesis is that cometbackup works slightly different from how I thought it worked. I have now commented out some unnecessary lines which I originally thought were harmless, but in my new mental model were causing the problem.

**Comment by Woseseltops** [comment]
The two backup and cleanup processes for the databases are now working correctly. The general Applejack process for the whole repo is also working, but I discovered that the way I configured the cleanup does not match will with the bidaily schedule. I think it's now safe to set it back to daily, that should fix it.

**Comment by Woseseltops** [comment]
|Server|Location|Backup frequency|Backup working|Clean up schedule|Clean up working|
|--|--|--|--|--|--|
| Applejack | Signbank database folder | 1 per d | y | After 2 w: 1 per w, after 1 m: 1 per m | y |
| Applejack | /var/www | 1 per d | y | After 1 w: 1 per w; after 1 m: 1 per m | y |
| Yale server | Signbank database folder  | 1 per d | y | After 1 w: 1 per w; after 1 m: 1 per m | y |
