### ISSUE TITLE
Allow selection of multiple search values + searching for values in dropdown list

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#455]
@vanlummelhuizen successfully used _Django Select2_ for this in other project.

**Comment by susanodd** [comment]
This has been implemented for the Phonology section.
Twelve of the drop-down menus now allow multiple selections. The selected choices appear in the field. (See the screenshot below.)
The other eight (Phonology) drop-down menus are more or less Booleans.

![query-glosses-multiple-select](https://user-images.githubusercontent.com/24272544/41099570-38ab2566-6a5f-11e8-8044-65ef4f8e3820.png)
![query-multiple-results](https://user-images.githubusercontent.com/24272544/41099577-3e5625a6-6a5f-11e8-9d5a-3bf21455a421.png)

**Comment by susanodd** [comment]
Added multiple selection for semantic fields, named entities, and word classes.

**Comment by Woseseltops** [comment]
Can this be closed?

**Comment by ocrasborn** [comment]
Hi @Woseseltops , we still need to do this for the ASL SB -- or is that only because I checked it for phonology fields that are different from the Global SB ones? (No, I don't think so. Also the syntax & semantics fields are partly different, btw).

**Comment by susanodd** [comment]
I added it to the "list" fields (pull-down menu choices).
Sure, okay. Except will need some trickery to do it in the javascript.
The javascript part for each of these fields makes use of the Django-generated ids for the various pieces of code generated for that field. (Yes, I hard coded it!)

**Comment by susanodd** [comment]
(I had to inspect the code generated for the template to see what that parts are called!)

**Comment by susanodd** [comment]
Oh, yes, another aspect, the kind of "get" for the values set in the form changes, depending on whether it's a multi-select (array of values) or a single value.
So that also needs some trickery.

**Comment by susanodd** [comment]
So far, I've made the two main "duplicate code" areas be loops over the field names in a list, so it's no longer hard coded and takes up much less space.
(That's i.e. the Javascript that initializes the select pull-downs in the template, and the get_queryset filtering of the database using the multiply selected fields.)

I will put this list into the settings, as you suggest, although it's not really a "choice" because only fields that are pull-down lists can be made multiple select. (e.g., you must not put other kinds of fields into the multiple select list setting.)

Another place the multiple select implementation appears in in the forms fields.
As this is declarations, I need to work out how best to implement this.
I can make each field be an if-else based on whether it's in the multiple select list or not, and make two different declarations. I don't know at the moment whether a declaration itself can be parameterized in the declaration. I'll look into this.

**Comment by susanodd** [comment]
The multiple selection pull-down lists and labels now appear in the chosen interface language.

**Comment by susanodd** [comment]
Okay, it's been modified as suggested by @Woseseltops!

**Comment by susanodd** [comment]
Multiple select now allows to explicitly select "empty". This is useful to find near matches to a focus gloss.

**Comment by Woseseltops** [comment]
Sounds done... right @susanodd ?

**Comment by susanodd** [comment]
yes
