### ISSUE TITLE
Relations to other signs broken for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#457]
Possibly related to datasets: it's no longer possible to select another sign when creating a reference in the panel "Relations to other signs". However, the user doesn't know what to expect there, types in a string, saves, and is returned to the home page while nothing has been added. Please repair and make available on the US server sometime this week.

**Comment by ocrasborn** [comment]
It might be worth taking up issue #379 at the same time.

**Comment by Woseseltops** [comment]
Okay, this works again. Turns out the live gloss suggestion ajax helper didn't work because it couldn't handle interface language names longer than 2 chars (like en_US). I've removed the 2 char requirements on both branches, and will now add a super simple unit test to verify this suggestion ajax helper is still working.

**Comment by Woseseltops** [comment]
Added the test as well. Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes, good!
