### ISSUE TITLE
Fix searching for users who are not logged in

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#473]
* First address #472 
* For ASL, searching for 'public' items works, but for Global, an empty list results. I reckon the latter is caused by the fact that when someone is not logged in, no dataset is selected and thus, searches return nothing. We should start by repairing this for NGT (by making NGT always selected when someone is not logged in?), but keep the issue open to think a bit more about how to do this in the future.
* First thing that jumps to mind: we could add a setting 'Open to public' for datasets. When it is set, anonymous users can select a dataset from the dataset menu, and then everything can go as for logged in users. Hm. Maybe this is actually sufficient, and the way to fix access to NGT now: only check 'public' for NGT.
* Of course, the field 'In web dictionary' will still determine whether individual items are accessible to the public.

**Comment by susanodd** [comment]
What do you want to do about morpheme components of signs?
Morphemes are normally shown as decorators on the Annotation ID Gloss fields.
This is a problem if the morphemes do not have inWeb set to True.
 (See the screenshots below, row SIGNBANK.)
If the user is not logged in, they can be hidden. (First screenshot.)

But what should happen when a logged in user queries inWeb signs? Do you want to see the same results as for an anonymous user?
(The second screenshot is what it looks like now with inWeb set to True.)
Should the GEBAREN-A annotation be hidden in the results because inWeb is False?

![anonymous-show-all-query](https://user-images.githubusercontent.com/24272544/43327198-0fe8f5d0-91bb-11e8-8f46-e922701f3657.png)
![inweb-query-results-user-logged-in](https://user-images.githubusercontent.com/24272544/43327210-19077178-91bb-11e8-84f3-2a0fc30fe20e.png)

**Comment by susanodd** [comment]
Okay, the morphological hyperlinks on the sign remain as they are.

**Comment by susanodd** [comment]
I noticed in the urls that searching for morphemes requires login.
Now search by an anonymous user only finds signs with inWeb set.
And the pull-down menu only shows Search sign (not morpheme or sign or morpheme.)

**Comment by ocrasborn** [comment]
@susanodd , that's how it should be: morphemes should not be accessible to anonymous users, also not when linked to signs with InWeb set.

**Comment by susanodd** [comment]
I need to remove the hyperlinks to handshapes for anonymous users....

**Comment by susanodd** [comment]
Handshape hyperlinks have been removed for anonymous users. Pushed to github.

**Comment by Woseseltops** [comment]
Looks like this is done. Happy @ocrasborn ?
