### ISSUE TITLE
Refactor CSV import function

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#483]
@vanlummelhuizen thinks the code for the CSV import could be a lot more elegant so we can extend it faster it the future. Use the existing unit tests to verify that any changes still give the same results, and create more unit tests if you still feel afraid to break something when working on this.

**Comment by susanodd** [comment]
Probably I should work on this. I finished adding import of Notes to the functionality and noticed most the code is very unreadable. This is partly due to the "stages" of processing the data, which are communicated to the template.
An idea would be to separate the functionalities "create new glosses via csv import" from the "update existing glosses via csv import" as two menu items.
With the introduction of Datasets, Lemma translations, and Annotation translations, lots of overhead has crept into the code to check all of these. I guess that would be the place to start, moving this to separate functions, with parameters to say what kind of import it is.

**Comment by ocrasborn** [comment]
Yes, good idea to separate the two functions, @susanodd

**Comment by susanodd** [comment]
Okay, I split the functions. At the moment, the new code co-exists with the existing code.
Once the new code has been put on the live server, I can revise the menu links to link to the new code, with separate choices for import csv create glosses and import csv update glosses. It has to be done in two steps to avoid breaking the existing menu choices.

**Comment by susanodd** [comment]
Additionally, there needs to be export and import csv functions for lemmas. I still need to write this.

**Comment by susanodd** [comment]
Also needed for this, upon activating the new menu choices, the tests need to be revised to refer to the new code instead. (Reminder to self.)

**Comment by susanodd** [comment]
Links to the separate Import CSV Create and Import CSV Update pages have been put in the pull-down menu.
(Appologies for the cryptic names!)

**Comment by susanodd** [comment]
I added functionality for the user to specify the csv column delimiter. This was based on a file problem reported by @ocrasborn. The functionality is commented out. It can be uncommented to activate it.

**Comment by ocrasborn** [comment]
Thanks @susanodd ! Let's leave that in by default, I suggest, it will be of use to anyone.

**Comment by vanlummelhuizen** [comment]
@susanodd do we need to keep this issue open still?

**Comment by susanodd** [comment]
I'll check.

**Comment by susanodd** [comment]
I restored the delimiter specification option that had been approved earlier.

**Comment by susanodd** [comment]
It's live now, so can close the issue.
