### ISSUE TITLE
Add a flag 'Accessible for other users' to datasets

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#484]
* On the info page for each dataset, allow for dataset managers to indicate that their dataset is available for access by others (upon request, and following the conditions specified in the field that is already there) --> create a binary field, with a checkbox on the dataset page that by default is not checked
* When new users register, only list the datasets (for which they can apply to get access to) that have value 'true' for this new binary field
* Please put the field above "Conditions of use by others" on the dataset info page
* The aim of this new field is to prevent getting a lot of requests from people who are just curious, in a phase when dataset managers are still creating their data. New collaborators can of course register and then be manually added without the dataset manager getting prompted by email.
[sorry @susanodd if it all sounds a bit clumsy , but it's Friday afternoon...]

**Comment by susanodd** [comment]
Should this be different than the is_public field? That's not currently visible in the detail view.

The glosses have an inWeb field.

There is a method get_selected_datasets_for_user that, if the user is anonymous, sets the selected_datasets to the public_datasets, if any are available, otherwise to the DEFAULT_DATASET

Does there need to be any change to this?
Is Accessible to others different than is_public? Does it need to be?
Does the setting of selected_datasets to public_datasets for anonymous users make sense?
There aren't very many inWeb glosses, so in a way it doesn't do anything.

From your description above, it seems like is_public can be used for Accessible by others.
And then just leave the selected_datasets as the DEFAULT for anonymous users, filtered by the inWeb setting.

**Comment by Woseseltops** [comment]
What's the status of this @susanodd ? Still waiting for input form Onno?

**Comment by Woseseltops** [comment]
Okay, does that mean this issue is done, @susanodd ?

**Comment by susanodd** [comment]
Yes
