### ISSUE TITLE
Global Signbank, science versus cls in URL gives an error.

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#485]
After Issue #448, the URL signbank.cls.ru.nl   ... works.
But if you navigate e.g., to Signs > Search, it flips to: signbank.science.ru.nl ...
If you then modify "science" back to "cls", it gives an error, as shown below.
(It does this on @vanlummelhuizen's machine too.)

![niet-beveiligd](https://user-images.githubusercontent.com/24272544/44032486-883d2818-9f07-11e8-913a-095295a90e5e.png)

**Comment by Woseseltops** [comment]
>  If you then modify "science" back to "cls", it gives an error, as shown below.

I think this HTTPS certificate problem for signbank.cls.ru.nl has already been fixed by Ben in the mean time

> But if you navigate e.g., to Signs > Search, it flips to: signbank.science.ru.nl ...

This was because at most places, we were using absolute urls for a reason that's no longer valid. I therefore changed all of them (> 100, what a task!) to relative urls: from now on, if you start at cls.ru.nl, it won't 'flip' back to science.ru.nl (unless I forgot a link somewhere).

**Comment by Woseseltops** [comment]
PS
It looks like this also fixed the weird double slashes we had in our links. If a particular solution to a problem accidentally solves other problems as well, it is usually the Right solution.

**Comment by ocrasborn** [comment]
Oh no!

**Comment by Woseseltops** [comment]
You can close this is if you fixed your own problem @susanodd :)

**Comment by susanodd** [comment]
Yes, I fixed it.
