### ISSUE TITLE
Generate minimal pair list

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#486]
* Minimal pairs are now displayed in the Related Signs view per sign. Please add a menu option "Minimal pair list" that, just like the Homonym List menu item does for homonyms, displays for each sign which minimal pairs a sign takes part in.
* Please calculate and list these per selected dataset only for minimal pairs within a dataset, so not comparing forms across datasets.

**Comment by susanodd** [comment]
![minimalpairs-list](https://user-images.githubusercontent.com/24272544/44398433-185e6a00-a544-11e8-9932-0fc370b91c9d.png)

**Comment by susanodd** [comment]
Question about minimal pairs. In going through the display (a previous step to what you see above), I had to look closer at the glosses 1000-B and TOEVOEGEN-B.
It looks like there are more than one fields that are different.
In the phonology fields that are compared, the field absOriPalm has a value (6) for 1000-B but no value for gloss TOEVOEGEN-B. But this field is currently not visible in GlossDetailView nor used to compute minimal pairs. Indeed absOriPalm is missing from the FieldChoice table.
Are the glosses 1000-B and TOEVOEGEN-B minimal pairs? Is a field missing from the computation?
I know at one point, we limited the fields because it was taking too much time.

**Comment by ocrasborn** [comment]
Yes, we should add that field absOriPalm to the computation, also for the display in the Detail View and the Related Signs view. Thanks for spotting that @susanodd

**Comment by susanodd** [comment]
Okay, I added the absOriPalm field to the views and minimal pairs computation as part of this issue.
The minimal pairs page will be at /signs/minimalpairs/ (It won't be live @Woseseltops can put it on the server.) I added hyperlinks to the focus gloss and other gloss.
I made the absOriPalm field available on the Gloss Search page, so you can select multiple values as for the other choice fields.

**Comment by susanodd** [comment]
This is on the live server since yesterday.

**Comment by Woseseltops** [comment]
Happy @ocrasborn ?

**Comment by ocrasborn** [comment]
Very happy!

**Comment by susanodd** [comment]
@ocrasborn, this issue is where the AbsOriPalm field is mentioned.
It's now possible to use the Frequency page to see how many signs use this field.
The field RelOriLoc has some choices that start with AO.

![freq-absoripalm](https://user-images.githubusercontent.com/24272544/45819396-82556500-bce4-11e8-9c80-f49275368dbe.png)

![frequency-reloriloc](https://user-images.githubusercontent.com/24272544/45819406-884b4600-bce4-11e8-9e11-3f9cf47d5faf.png)

**Comment by ocrasborn** [comment]
(just emailed you @susanodd , but just for completeness:)
I found that Absolute orientation is in the CSV export I just made, so I’ll use that to double-check that the field content is stored in an alternative way. So, please remove it again everywhere, including the detail view and the CSV export.
