### ISSUE TITLE
Create a frequency report for values under Phonology and Semantics

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#497]
* The addition of frequencies to the pull-down menus in the detail view was a first great step forward. To facilitate the user, I'd like to have a page with an overview of frequencies for all values in all fields with field values under Phonology and Semantics. A simple but very long table would be a good first step, but if you can think of a nice more compact display, that'd be good of course. Perhaps four columns with each a value + frequency pair?
* Again, calculate frequencies for the selected datasets.
* The easy thing would be to add an extra item in the sign menu. However, I'm tempted to look ahead and start a new menu 'Data analysis', where we could also add the homonym list and the minimal pair list (I think that is a page already, but not yet a menu item, am I right?)

**Comment by susanodd** [comment]
I pushed an initial version of a frequency page for the phonology fields. It's on github.

**Comment by ocrasborn** [comment]
Good @susanodd ! What is the URL with which I call this?
One idea for further functionality: create two views, one like this, one sorted by frequency (high > low).

**Comment by vanlummelhuizen** [comment]
This is live now.

**Comment by susanodd** [comment]
https://signbank.cls.ru.nl/signs/frequencies/

**Comment by susanodd** [comment]
Okay, the sorting on my local computer works, but it's not the same on the live server. It seems I omitted something from the commit....

**Comment by ocrasborn** [comment]
Nice, even in its unsorted form ;-)!
One improvement: relabel the column header "Choice frequencies" simply to "Frequencies"

**Comment by susanodd** [comment]
I implemented a toggle feature to show and hide the various fields (rows).
Here there is a button for each field. It's quite a few buttons. I'll try to make a multi-select list instead of buttons. Probably some highlighting is needed to show what has actually been toggled.
Any suggestions @ocrasborn?

I'll work on the order of the frequencies too.

![toggled-frequencies](https://user-images.githubusercontent.com/24272544/45554573-12a02f80-b837-11e8-981d-f8fab8287956.png)

**Comment by ocrasborn** [comment]
Two suggestions:
* Put the selection toggle buttons in the order of the fields in the detail view
* Try out inverting columns and rows: some fields have so many values (strong hand, weak hand), that the table is unreadable. Also in printouts it'd look better I reckon. As we'd then have tables with many many rows, consider creating multiple sets of value-frequency columns, columns containing max. 10 rows. Fields could still be separated by lines like now.

**Comment by susanodd** [comment]
Okay, after lots of tweaking, this is what it looks like now. You can select the fields you want to see from a multiple select drop-down (they are alphabetized), the results are displayed vertically, and there's a button to hide/show the 0 values.

![improved-frequency-display](https://user-images.githubusercontent.com/24272544/45632583-f6ea9280-ba9d-11e8-9f3d-83249a5740e0.png)

**Comment by susanodd** [comment]
I didn't do a sorting by frequency version yet because there are so many 0 values I wanted to hide those first.

**Comment by susanodd** [comment]
The new display has been pushed to github.

**Comment by vanlummelhuizen** [comment]
And it is live now.

**Comment by susanodd** [comment]
Finally got the sorting buttons working!
You can toggle between sort by frequency and sort by label.

![sort-by-label](https://user-images.githubusercontent.com/24272544/45810017-f2a2bd00-bcc9-11e8-8a28-f3bd7e4acbc1.png)

![sort-by-frequency](https://user-images.githubusercontent.com/24272544/45810028-f8000780-bcc9-11e8-8efa-1a9ed5fcbaf7.png)

**Comment by susanodd** [comment]
Pushed to github.

**Comment by vanlummelhuizen** [comment]
@Woseseltops could you put this live since you are working on something on the live server?

**Comment by susanodd** [comment]
Pushed again, had skipped over the third item in the list by accident. Now it's sorting all the labels.
(The first labelled item is '-', followed by 'N/A'. Then the rest.)

**Comment by susanodd** [comment]
@ocrasborn, regarding the Semantics fields, do you want these in a separate section, separate pull-down, or a separate page? At the moment, only the Phonology fields are offered.

-- So far, the fields weakprop/drop and letter/number are ignored. Not sure how to handle these since they're dependent.

-- Semantics fields

In the settings file, there are five sets of fields: main ('useInstr', 'wordClass'), phonology, semantics ('iconImg', 'namEnt', 'semField', 'valence'), frequency (the tok fields), and handshape. There's additional lists for multiple select fields.

-- Should 'wordClass' be in semantics instead of main? Do you also want this frequency?

**Comment by ocrasborn** [comment]
Hi @susanodd : 
* Word Class should stay where it is now, with main;
* Let's leave the weak drop/prop fields for now
* But include the four semantics field in a separate section like you propose, that is a header label Semantics plus a search field where only the four semantic fields appear (but above the results, so right below the phonology search field.
* I think we can make it a bit more condense by putting the label and the search field on a single row, don't you think?

**Comment by susanodd** [comment]
Do you care if the phonology and semantics results are interleaved?
(e.g, if the user selects from both phonology and semantics)
If I need to list the results for phonology first, then semantics, it makes the display more complicated to maintain sorting at at additional level (phonology fields followed by semantics fields).
It would be easier to just sort all the fields.
The individual tables for each field will be sorted of course.

**Comment by susanodd** [comment]
![frequencies-pho-sem](https://user-images.githubusercontent.com/24272544/45950505-5f86c180-c000-11e8-86a2-645f54170def.png)

**Comment by susanodd** [comment]
At the moment, all of the results shown for a particular field (its choices) are in a 2-column table inside a div inside a table cell (third column of the results table).
That is used in order for the jquery to identify the cells in order to show / hide and sort.
Probably the little tables need to be formatted to be the same width. Right now they're dependent on the width of the field label in the language being used.

**Comment by susanodd** [comment]
This has been pushed to github.

**Comment by susanodd** [comment]
The raw query now accounts for the new lemma model and changes to the dataset id. (#405 )

**Comment by susanodd** [comment]
@ocrasborn are you happy with this?
