### ISSUE TITLE
ECV not yet usable on new server

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#499]
@vanlummelhuizen and I think that there are still two things needed on the new applejack to make the ECVs usable in ELAN again:
- Configure the cron job on the new server that updates all the ecvs overnight (?)
- Install the thingie that ensures that http-requests are not automatically converted to https, so that ELAN can read http://applejack.science.ru.nl/static/ecv/ngt.ecv (and the others)

**Comment by ocrasborn** [comment]
Did I formulate this correctly, @vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
I think this will be clear to @Woseseltops.

**Comment by Woseseltops** [comment]
> Configure the cron job on the new server that updates all the ecvs overnight (?)

I was thinking this was fixed already... turned out to be wrong. I've added my oneliner from #433 , please keep this issue open so I can check whether is works.

 > Install the thingie that ensures that http-requests are not automatically converted to https, so that ELAN can read http://applejack.science.ru.nl/static/ecv/ngt.ecv (and the others)

I thought ELAN could handle HTTPS these days? Because we don't have the HTTP variant for ASL either. Made everything ending in ".ecv" available over http anyway. 

PS the correct address is https://signbank.science.ru.nl/static/ecv/ngt.ecv :)

**Comment by Woseseltops** [comment]
> Configure the cron job on the new server that updates all the ecvs overnight (?)

This issue was still open because I still needed to check this. I just did, it works.
