### ISSUE TITLE
Allow for CSV import of Notes

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#514]

**Comment by susanodd** [comment]
I"m working on this now. It seems the code hasn't been revised for some time. It's a bit broken.

**Comment by susanodd** [comment]
@ocrasborn, a few questions.
There are four fields displayed for Notes in Gloss Detail View. (At the moment, these are not exported either.)
For CSV import, do you need all of the fields? Or can the default be used for Published (default=True in the Definition model) or can it inherit this? Is this related to the publication status?
And what about the Count (Index) field? This seems to be arbitrary. It's possible (in Gloss Edit) to set two notes with identical Type and Index. And it doesn't seem to sort on this either. (Is that a bug, should the Index be doing something?)

**Comment by susanodd** [comment]
I've added Notes to the Export CSV functionality.
Now it's possible to search for glosses that have Notes, and then export these to csv.
(This has not been pushed yet, since I have some questions.....)
If you look at the gloss 1164, you will see it has 3 identical notes.
@ocrasborn ? Should duplicates be automatically removed? Or flagged in red? They are three separate database records, but there is no uniqueness requirement on the Definition model fields, so apparently nothing stops a user from entering the same thing again.

**Comment by susanodd** [comment]
In order to import Notes, there needs to be a comparison with the already existing Notes to detect changes.

**Comment by susanodd** [comment]
I made it so the export ignores the duplicates. But they probably need to be flagged in the Detail View.

**Comment by susanodd** [comment]
Export CSV Notes has been pushed to github.

**Comment by susanodd** [comment]
CSV import of Notes has been pushed to github.
There is user feedback in the Changes summary for formatting the new Notes.
