### ISSUE TITLE
Make ASL search result scroll bar cf. the Global SB one

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#533]
For Global Signbank, we have changed what's in the horizontal 'search result scroll bar': no longer the Lemma ID Gloss, but the Annotation ID Gloss. For ASL, we still have to do this.

**Comment by Woseseltops** [comment]
It's related to the code directly above this line https://github.com/Signbank/Global-signbank/blob/master/signbank/dictionary/adminviews.py#L880

**Comment by Woseseltops** [comment]
> For ASL, we still have to do this.

Actually, we did do it, but it failed because of mismatch in language code format (en-us vs en_US); coincidentally, this is the exact same problem as the one that caused #542, just showing up in another mechanism in another part of the application. I solved it by changing the fallback to use the first language code from the settings, which has the correct format.

Happy @ocrasborn ?
