### ISSUE TITLE
Remove language prefix from the display of Lemma ID Glosses

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#534]
Both in the detail view and in the list view, the Lemma ID Gloss value is preceded by the content language of that field. Please remove the language: it's already embedded in the field label/column label.

**Comment by susanodd** [comment]
I made the change on my computer as you request, but...
It seems the lemma translations in the detail view aren't actually columns. They are separated by a comma.
If the language tag is removed, then you just have a list of translations.
Do you want each lemma language on a separate line in the detail view, or as a table?
They could be separate rows that are invisible if there is no translation yet for a language.

It seems the lemma lookahead isn't working anymore when you want to edit a lemma in the gloss detail view.
There is a Lemma Update that can be navigated to via the Lemma List View and clicking on the update icon.
(Note: This lemma update has been revised and pushed to github #529, but I noticed it's not the new version yet on the server. I made it so you can edit the translations of the lemma instead of having to delete a lemma "translations tuple" and create a different "translations tuple". That is what was causing problems with CHAIRMAN. It wasn't possible to get rid of the "-" in the Chinese field. @Woseseltops and @susanodd, we changed it to CHAIRMAN1 in order to expose the error in the counts. It was required to change both fields, since CHAIRMAN was permanently stuck to "-". Hence the revised Lemma Update view.)

Maybe the lemma update in gloss detail view would be better as a hyperlink to a different update page, rather than trying to update the lemma translations (as a side effect of updating the lemma of the gloss).
(It's kind of ambiguous whether, upon updating the "lemma" fields, if you want it to refer to a different lemma altogether, or if you are trying to update the lemma translations of the lemma it currently refers to. This is the reason for creating new import/export CSV lemma facilities.)

Perhaps in the gloss detail view, it should navigate to a specific view for the lemma in order to update it? As for that in the Lemma List view.

**Comment by vanlummelhuizen** [comment]
@ocrasborn By list view, do you mean Recently added signs? In All signs or the search results the lemma is already split into a column for each dataset language.
And for the detail view: the lemma is now a single row because gloss-lemma is one entitiy. Also, changing it involves selecting a new lemma or creating a new one, i.e. changing the reference to the lemma, not changing part of a lemma, i.e. a lemma-translation.

@susanodd I agree with your observation that removing the language tags in the detail view would result is just a list of translations.
Lemma lookahead when Editing a gloss is working as far I can see.

**Comment by ocrasborn** [comment]
@vanlummelhuizen : 
* with list view, I meant the display of the search results. I see that it's no longer there for ASL. However, the column labels still add "(American English)" to the glosses. that's good for Global Signbank, but weird for ASL SignBank. In the list of Proposed New Signs and Recently Added Signs (from menu Signs), the language label is already removed from the column headers, so that's still to be done for the list of search results.
* For detail view: same thing: the field labels for the glosses should not contain the language label like in Global SB.

**Comment by vanlummelhuizen** [comment]
The language in the column header in the search results and the like is now dependent on SHOW_DATASET_INTERFACE_OPTIONS.

**Comment by vanlummelhuizen** [comment]
The languages for the lemma idgloss translation as displayed in Gloss detail view are now dependent on SHOW_DATASET_INTERFACE_OPTIONS.

**Comment by vanlummelhuizen** [comment]
@ocrasborn This will be available on ASL Signbank after the next update.

**Comment by ocrasborn** [comment]
Great!
