### ISSUE TITLE
Hardcoded list of fields in GlossSearchForm not complete for ASL

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#536]
If I see things correctly, the required fields for ASL were removed by @susanodd  in this commit 546fa1817  . She must have had a good reason for it :)

Temporary fix in production right now: manually readd them.
Best fix: fill this field dynamically from the settings

**Comment by susanodd** [comment]
Yes, I was making the code rely on settings rather than be explicit.
I didn't know it was there for ASL. I thought it was from Steve.
This is the opposite to the problem before, that there were extra things not used by ASL.

Can such code be surrounded by settings checks as for SHOW_DATASET_INTERFACE_OPTIONS as for ASL versus Global?

**Comment by susanodd** [comment]
@Woseseltops and @susanodd solved this issue. The field names in the Gloss and Morpheme Search Forms are now via the settings.

**Comment by Woseseltops** [comment]
I think is solved. We'll reopen if problems appear.
