### ISSUE TITLE
Define search result default sort order

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#539]
Right now, it's pk, but the ASL guys would prefer alphabetically by annotation . Maybe this could be a setting?

**Comment by susanodd** [comment]
See Issue #524. Default sorting is now alphabetically by Annotation ID Gloss plus the Default Keywords Language setting.

**Comment by susanodd** [comment]
(The previous default sorting was causing the count to be wrong for Global.)

**Comment by ocrasborn** [comment]
I'm afraid this is not yet working. I'm logged in (ASL), search for glosses ^f, to find (random pick) FLIRT - FRIDAY - FORGET - FOOTBALL-BALL - FASHION-MODEL (Annotation ID Glosses)

**Comment by ocrasborn** [comment]
For Global, please also sort by _Annotation ID Gloss (English)_ as the default (for all datasets).

**Comment by Woseseltops** [comment]
It was indeed not yet working. Took me quite some time to figure out why, but the reason was simple: we were putting our ordered search results in a set, which removes duplicates, but apparently sets forget about order (fyi @susanodd ). I've solved it now by simply skipping the 'set' step, but this might mean I have reintroduced duplicate search results.

**Comment by susanodd** [comment]
I'm working on the GlossListView at the moment in conjunction with #542.
Regarding the sorting, the `list(set` constructors you mention are in the fall-through case for sorting.
The only fields using this case are Translations.

I can't tell what sorting is (supposed to be) doing for translation equivalents.

In the GlossList view, all translations are shown intermingled in the same column display.
I'm not actually sure what "sorting" is doing with this data. (It doesn't look like it's sorting, but then again, the order of things changes, but they're not sorted either way.)
Maybe because all languages are shown in the same column? Does this mess up the result?
Do there need to be separate columns in the Gloss List view, @ocrasborn?

For #542 , I've revised the code so the headers for the Gloss List are generated rather than hard coded. That's why I'm looking at the headers and sorting in that issue (the little triangles are also generated now for the header.)

I just noticed the Dutch language of the translations columns is "Mogelijke vertalingen in het Nederlands". (So presumably other languages shouldn't be shown?)

**Comment by Woseseltops** [comment]
Hey @susanodd , I just verified that sorting based on annotations works correctly, even after all changes which introduce Ajax etc; if you have other questions related to sorting, please open a new issue for it :) . 

The open point for this issue is a DEFAULT sort order, which I think is still not there: if I search on the global Signbank right now, everything is still ordered by pk.

**Comment by susanodd** [comment]
Okay, I'll see why that is.

**Comment by susanodd** [comment]
This was caused by a sloppy string comparison. It's been fixed. Pushed to github.

**Comment by susanodd** [comment]
Happy @Woseseltops ?

**Comment by Woseseltops** [comment]
Confirmed it works.

**Comment by susanodd** [comment]
This seems to be broken again.

**Comment by susanodd** [comment]
Somehow this got totally messed up since it was working in July. The python sorting routines were messed up because the templates were  passing incorrect order_by parameters, which were being ignored.  To fix this, explicit order_by parameters are used in each of the sorting routines and passed to the order_by in the python code.

**Comment by susanodd** [comment]
This has been fixed. Some other bugs with sorting via the arrow buttons have also been fixed
Textual columns: Annotations, Lemmas, Translations.
Non-textual columns (e.g., Handedness, Location). Rows with empty data in the column being sorted are put at the end by using a pair sort.

**Comment by susanodd** [comment]
This has also been fixed for Morpheme List View.
Because sorting functionality was changed elsewhere for glosses, the Morpheme keywords (abstract meaning column) are now shown per translation language. This corresponds to that of the sorting functions (the little triangles for sorting columns).

**Comment by Woseseltops** [comment]
Hey @susanodd , since you are the one that reopened the issue, you can also be the one to verify it works again and close it :)
