### ISSUE TITLE
No phonology info in list view on ASL Signbank

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#542]
![image](https://user-images.githubusercontent.com/1909317/52328617-84e4fc80-29f0-11e9-9c4d-a9afe009f117.png)

While the phonology info is definitely there:

![image](https://user-images.githubusercontent.com/1909317/52328628-8d3d3780-29f0-11e9-9022-f28114431816.png)

**Comment by Woseseltops** [comment]
Okay this works now. The problem was in the gloss object method 'generate_translated_choice_list_table' , which generated translations for the language code 'en_US', while the expected language code was 'en-us'. I've now added a simple online that translated from the one language code format to the other... not sure if this is the prettiest solution though.

(cc @susanodd if you're interested)

**Comment by ocrasborn** [comment]
Ah, I closed this before testing. My test item ZERO has a Location - Major specified (namely Neutral), but this does not appear in the list view.

**Comment by Woseseltops** [comment]
Okay it took me some time, but I think I know what is going on here. In general, on the ASL Signbank you see different fields for two reasons:

1. From the total set of available fields, they use another subset. So where the Global Signbank might use fields [a,b,c,d], the ASL Signbank might use [c,d,e,f] . An example of a (only used by global) is `locPrim`, an example of b (used by both) is `handedness`, an example c (only used by ASL) is `locPrimLH`.
2. Even for the overlapping fields, they use the Django localization features to give them different names.  For example, while both Signbanks use the field `subhandsh`, it's called 'Weak hand' in the Global Signbank but 'Nondominant handshape' in the ASL Signbank.

The columns you see in the list view are translated, following bullet 2, but do not take account bullet 1. That is, you see the fields `[handedness, domhndsh, subhndsh, locprim]`, but `domhndsh` and `locprim` are not being used by the ASL Signbank and thus always empty. To make things even more confusing:
* there somehow *are* translations (as explained in bullet 1) for these unused fields in the en-us translation file
* instead of `locprim`, the ASL Signbank uses the similar looking field `locprimLH`.

The problem thus is that the phonology columns in the list view are hardcoded. I can see two solutions:
* Easy: hide a phonology column from the list view if it's not used (=specified in the settings)
* Harder: create a new setting specifying the phonology columns for the list view

I personally think the easy option would be good enough, as I get the impression these phonology columns are not used all that often. What do you think @ocrasborn ?

**Comment by ocrasborn** [comment]
Agree, @Woseseltops . But then other fields do need to appear; and wouldn't that come down to the Harder solution?

**Comment by susanodd** [comment]
The harder solution might be better, adaptable to different kinds of information.

For issue #572, to hide Tags for anonymous users,  I had to add a check for whether a user is anonymous many times in code. (In the Search parameters, in the Header above results, in the Sort order buttons underneath the header, and in the actual row display. Each part of information is displayed separately. The checks have to be done for each different part of the display.)

Maybe there is a general way to solve visible versus hidden information.

**Comment by susanodd** [comment]
I can work on this. It's also unfortunate coding for Global.

There are iterations per row (gloss) as well as iterations per header column and per gloss field value.
Plus additional checks on how to display each cell of the table, whether it's visible for the user (is the user anonymous, does the field apply to the dataset or language.

It makes more sense to put the fields to display in a setting. (Solution 2 above.)
Then all iterations can iterate over this, instead of each iterating over its own code.

What is also kind of tangled into the display is the checks for whether the user is anonymous.
There are numerous checks at the cell level.
It was sometimes unclear at what level it should be checked if the user can see the information.
At the level of the data item, or at the page level.
It would reduce the amount of code if this could be at an outer level rather than per cell.

**Comment by Woseseltops** [comment]
Seems like both @ocrasborn and @susanodd prefer the harder but more flexible solution, so let's go for that!

**Comment by susanodd** [comment]
@Woseseltops, regarding the field locprimLH

Suppose there is a new setting (for Global) like this:
`GLOSS_LIST_DISPLAY_FIELDS = ['handedness', 'domhndsh', 'subhndsh', 'locprim']`
Then for ASL, locprim would be changed to locprimLH (read on)
So we know what fields we are displaying.

I checked the implementation to find out where the table header in the gloss list view comes from (first image in this issue, see above). Global (English) is Location. (This is also the name of the field in models.py)
Header 'Location' corresponds to field 'locprim' in the new setting.
But then the "Location - major" of ASL is actually obtained by doing `{% trans "Location" %}`

But the (English) description of locprimLH in the models.py is actually `"Placement Active Articulator LH"`

So an ASL setting that swaps 'locprimLH' for 'locprim' won't work as expected.
`GLOSS_LIST_DISPLAY_FIELDS = ['handedness', 'domhndsh', 'subhndsh', 'locprimLH']`
The name in the model probably has to change?
At the moment, the template is obtaining the headers from "trans" of the English.
(Rather than via the field's verbose name in the model.)

**Comment by susanodd** [comment]
Okay, it seems there's also a translation for `"Placement Active Articulator LH"`

Which is also quite strange because the code is currently translating "Location".

Problem solved!

**Comment by susanodd** [comment]
I'm nearly there. (See the screenshot in #580).
The headers and gloss rows are now generated so the columns aren't hard coded; they now depend on a new setting (mentioned above) for header fields. (Solution harder above.)

The search panel is still hard coded. I'll see if that can be simplified.

**Comment by susanodd** [comment]
Solution 2 has been implemented and pushed to github.
There is a new setting for the display of phonology fields. The ASL settings file (master branch) has been ujpdated to reflect this.
The solution relies on ajax calls to generate the gloss list table header (and sorting buttons) as well as for each gloss row. The javascript / jquery has been revised to support this so that only the glosses visible on the current page are called for display.
The lemma view has similarly been modified. Only visible lemma groups are displayed.

Although the use of Ajax was motivated as an object-oriented dynamic way to display the tables, this has an additionally advantage that only the glosses visible on the page are displayed. The previous version generated data for all objects in the (multi-page) table. The new code is faster.

Because the table is generated as it's displayed rather than waiting eons before it displays, the choice of how many glosses per page to display has been modified. The display of 3000, 2000, and 1000 glosses is no longer in the pull-down menu.
(Note @ocrasborn: please try out the new code when it gets put on the live server. The big choices can be put back again, it's a tradeoff because the table is being generated and getting longer, so you can't scroll completely until it's drawn. Just like before, but now it starts displaying faster.)

Pagination has been fixed as well. And it now also restores the paginate_by setting if you toggle to Lemma View and then back to Gloss List View.

The hover over video display also works as soon as the row has been displayed.
(Note @Woseseltops: the limit on how many glosses were displayed and whether video preview was displayed has something to do with the amount of rows. It didn't seem to be necessary anymore with the dynamic display of rows. Can you check - once live - whether the functionality is okay? I haven't got enough videos on my local server.)

**Comment by susanodd** [comment]
@Woseseltops, this has been pushed to github. See the description above for what has been implemented.

**Comment by Woseseltops** [comment]
Wow @susanodd this must have been a lot of work. I just checked and noticed:
* The phonology fields are still there, so this looks good.
* The whole search functionality (for example, the 'all signs' page) feels a lot faster now.
