### ISSUE TITLE
Changing sort order in list view undoes the search

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#544]
If I click on the arrow in the search results to change the sort order, Signbank forgets about the search and shows all signs (taking endlessly with NGT and LSFB selected, 7,000+ records).

**Comment by ocrasborn** [comment]
I think it's a broader problem: CSV export also does not 'listen' to the search results any more, but instead exports all signs from the selected datasets.

**Comment by ocrasborn** [comment]
(Applies both to Global and ASL SB)

**Comment by vanlummelhuizen** [comment]
@ocrasborn I cannot reproduce this problem. Perhaps I do not understand it correctly. Otherwise someone secretly or unintentionally solved it.

**Comment by ocrasborn** [comment]
I still have the problem. Step by step:
* I select datasets NGT and LSFB
* I search for gloss 'mother'; getting: Number of matches: 8 out of 7582.
* I click on any of the up/down sort arrows above the list of hits, and (after many seconds) I get:  Number of matches: 7582 out of 7582. Datasets: NGT, LSFB. (But sorted like I had asked for.)

**Comment by ocrasborn** [comment]
This issue has popped up again!

**Comment by susanodd** [comment]
This might be linked to the #851 .
I've fixed it so far, but it needs more testing.
The show_all wasn't being set all the time. And sometimes when using show_all, because of this, it still had the query parameters in the form fields, in spite of showing the list properly. So when you did an export CSV, it was using the hidden (visible in the form fields) parameters so the export was showing the previous search instead of show_all.
When I tried looking at the sorting, the parameters were also in the form on show_all. But the sort did not show up wrong until you tried sorting, so it looked like it redid the sort again. But it was because it still had parameters in the form.

The #851 has been fixed, so that may resolve this issue as well.

**Comment by susanodd** [comment]
I noticed the "x" button is also missing in the results bar to turn off the sort.

**Comment by Jetske** [comment]
@susanodd so the sorting problem is solved, right? The problem doesn't seem to occur when I try it. 
Then I can try to find the missing "x" button.

**Comment by susanodd** [comment]
I think it's solved, yes.

**Comment by susanodd** [comment]
@Jetske well done!!
The little red arrow is back too!!
