### ISSUE TITLE
All ECVs except for dataset NGT are empty

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#552]
The log messages have been telling me the ECVs are correctly regenerated overnight, but now we're starting to use a few other than NGT, we find that they are all empty. In particular, Shanghainese and LSFB are the ones I checked.

**Comment by susanodd** [comment]
Are you looking at the names or the acronyms?

**Comment by Woseseltops** [comment]
Did some good old bughunting together with @susanodd today. Turns out glosses got lost in the sorting mechanism (not the first time this happened, so the two of us are experts at exactly this problem B) ). This was because it was sorting by dataset default language, which for a lot of datasets is empty. 

Quick fix: setting a default language for each dataset.
Also needed: give an error if it's sorting by a language that is not set.

**Comment by ocrasborn** [comment]
Hm. Now the Shanghainese version is available, but LSFB is still empty (http://signbank.science.ru.nl/static/ecv/lsfb.ecv)

**Comment by susanodd** [comment]
There was an error in how the setting was used in the code to select the language. This has been fixed and pushed to github.

**Comment by ocrasborn** [comment]
All looks good now.
