### ISSUE TITLE
Lookahead thinks science is a different server than cls

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#555]
The lookahead form fields for showing e.g., lemma choices in Gloss Detail View does not show any choices if the url has cls in it instead of science.

**Comment by Woseseltops** [comment]
It now works for both cls.ru.nl and science.ru.nl . There was still a Javascript `url` variable that was filled with the `URL` setting from Django, which is set to science.ru.nl, and apparently this variable was used by the typeahead functionality. Browsers do not like two separate websites making internal requests to each other from Javascript, which explains why typeahead did not work from cls.ru.nl . The fix was stop filling the Javascript `url` variable with the Django setting; it's now a relative link.

**Comment by Woseseltops** [comment]
Strange, this https://signbank.cls.ru.nl/dictionary/ajax/gloss/ge does not work yet.

**Comment by vanlummelhuizen** [comment]
@Woseseltops My commit https://github.com/Signbank/Global-signbank/commit/793dada88fdf03bf73f5e7b7d32cff636e280cc5 solved a strange bug. On my local instance I had to select some target dataset(s) and log in and log out to make it work, but https://signbank.cls.ru.nl/dictionary/ajax/gloss/ge is working again. Agreed?

**Comment by Woseseltops** [comment]
793dada is my favorite commit now :)
