### ISSUE TITLE
New page won't show

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#560]
Created a new page in Admin, About / Acknowledgments. The menu item appears, but the page content from Django doesn't show. Instead: page not found.

**Comment by susanodd** [comment]
Can you remember when the last time was that you were able to add a new page?

The database seems to be locked right now.
But I am also not able to fix it on my local machine.

In the python code for pages urls (pages/urls.py), it uses a builtin feature "patterns".
But this seems to be an older version of python because PyCharm shows it underlined in red.
Perhaps this obsolete code is no longer supported.

**Comment by susanodd** [comment]
Okay, I got it to work on my site.
I added a trailing "/" to the url of the page.

It didn't work to do this on the live server because it gave an error that the database is locked.
You can wait a while and try it again.
If you have a sqlite browser open, shut that. That seems to lock the database.

**Comment by susanodd** [comment]
Need to wait until people stop using signbank apparently in order to get the database unlocked.

Then add a trailing "/" to the url of the page in admin.

**Comment by ocrasborn** [comment]
Ah of course! Thanks @susanodd , solved
