### ISSUE TITLE
Rethink where to show info: tab vs panel

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#599]
Recently two new tabs were introduced: the revision history and the frequency view. This made me realize I cannot think of a good reason why we put some info in the detail view, but simply in a different panel, while other info gets its own tab. 

Let's redivide the info in some logical way. The simplest way would be that a separate tab can only mean a separate audience. That is, we would have only two tabs, one for the general public (public view) and one for researchers (detail view). Downside would be that there is a LOT of information in this detail view. If we would want to divide this info into separate tabs, there are multiple categories of info:
1. About the individual sign: lemma, translations, morphology, phonology.
2. About the sign's 'place in the lexicon': Relations to other/foreign signs, the relations view, frequency.
3. Meta info only relevant in the context of Signbank: publication status, revision history, notes, other media.

Do we want separate tabs for all three, or do we group info? For example, category 1 and 2 as a the new detail view and category 3 as a new tab 'meta'? Curious for your opinions @ocrasborn , @susanodd  and @vanlummelhuizen .

**Comment by vanlummelhuizen** [comment]
I think separating sign info in an 'intra' and 'inter' part, as well as a meta part, is a good idea. 

We could make tabs for each on the part of the page with all the panels. Also, we may want to the let the left and right side scroll independently.

Perhaps choosing between Public and Detail view is not really necessary: if you have the permission to view the Detail view, you will get it. Otherwise you will get the public view.

One thing I noted was that the Relations View tab is (almost?) covered by the Relations to Other Signs panel and Minimal Pairs panel.

**Comment by susanodd** [comment]
Some of these depend on the particular sign. There are some signs with more than 15 minimal pairs.

For the Frequency panel, I was thinking that this will grow depending on what things are added.
It's kind of at a different level than the others because it's the gloss within the corpus. And this may evolve.
The History view is more operational. That could also show e.g., which glosses are actively under development and by how many researchers.

**Comment by Woseseltops** [comment]
> I think separating sign info in an 'intra' and 'inter' part, as well as a meta part, is a good idea.
> if you have the permission to view the Detail view, you will get it. Otherwise you will get the public view.

So 3 tabs: intra, inter, meta. Sounds clean, I like it. A downside of not including the public view in the tabs is that some users might be actually working on a public dictionary, and without the tab wouldn't be able to see what the end users see... but perhaps in that case we could add a small button that only people in the 'public-dictionary-creator' group can see or something like that.

> For the Frequency panel, I was thinking that this will grow depending on what things are added.
It's kind of at a different level than the others because it's the gloss within the corpus. And this may evolve.

Ah I see your point. The frequency info is different from the other 'inter' bits of info in that it comes from external corpora. In particular when there are multiple corpora, we could have quite a lot of graphs and visualization options, and then a separate tab would be justified. Perhaps we can start by grouping it under 'Inter', and then give it its own tab when it grows too large?

> Also, we may want to the let the left and right side scroll independently.

Maybe unrelated, but I like this idea too. We can do this too while we're at it. 

Next up: creating a mockup.

**Comment by susanodd** [comment]
This can be closed.
