### ISSUE TITLE
User werkcollege cannot see signs in list view

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#605]
This will not pertain to just user werkcollege, but it's my students now who have this problem. It looks like a rights issue. The problem: In the list view, hits are counted (say, 6 out of 4000), but not displayed. CSV export correctly gives the 6 records.
* I tried making them researcher not guest; to no avail.
* I double-checked whether they have view rights to the dataset (which I knew because they could search in it), all good
* I added a few specific view rights for this user; to no avail. Can't find any other assignable rights in the admin that seem to pertain.
Help!

**Comment by Woseseltops** [comment]
I'll look at it this Friday @ocrasborn !

**Comment by Woseseltops** [comment]
Okay, turns out this was not a permission problem but a simple bug. Here's what happened:
1. Apparently, somewhere in the list view there is functionality that completes your lemma as you type it in (typeahead). 
2. This functionality needs information about the currently selected dataset and what languages this dataset supports... and it gets this information by looking at the options in the dataset dropdown of the 'create new gloss' panel.
3. However, if this panel is not available, for example because the user cannot create new glosses, the code will give a Javascript error (which you don't see unless you open the dev tools).
4. Javascript immediately stops executing if it runs into an error. One important thing that it still had to do was loading the search results dynamically - as you might remember, they are no longer loaded when the page loads to make Signbank 'feel' faster, but are instead 'plugged in' later.

I've solved it for now by disabling the type-ahead functionality if they user cannot create new glosses. This issue is about solving it in a more complete way: #606 .

**Comment by ocrasborn** [comment]
Thanks @Woseseltops !

**Comment by vanlummelhuizen** [comment]
@Woseseltops I have thought of three alternative solutions:

1. Check the `dictionary. add_gloss` and `dictionary.add_morpheme` permissions when loading the lemmatypeahead.js in the template.
2. In lemmatypeahead.js, use the `user_can_add_gloss` and `user_can_add_morpheme` Javascript variables that are set in the template.
3. In lemmatypeahead.js, check whether `$('#id_dataset')` exists with `if($('#id_dataset').length) {...}`.

Any preference? Yours is also an option of course.
