### ISSUE TITLE
Datasets not displayed in header when using Public View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#608]

**Comment by susanodd** [comment]
This has been fixed. 
When the user is logged in, the datasets show up in the public view now.
However, if the user is not logged in, the datasets are not shown in the header.

**Comment by ocrasborn** [comment]
thanks @susanodd !

**Comment by susanodd** [comment]
There seems to be something with df869a805a0994cd10cbde213250225aeb79e6cb

**Comment by vanlummelhuizen** [comment]
@susanodd Please explain.

**Comment by susanodd** [comment]
Oh I didn't pay attention to the sorting. I had fixed this. Then yesterday I saw it had been recently updated. I thought you had removed the datasets code needed in the header accidentally as for the field choices page. Now I see the update was the "to be checked by reporter" tag. Never mind.

This issue is working. It can be closed.
