### ISSUE TITLE
Make unit tests database independent

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#615]
During the latest upgrade of the ASL Signbank server, we discovered that these tests require Global Signbank stuff to be in the database, which of course they don't have:

* test_delete_fieldchoice_othermediatype
* test_analysis_minimalpairs
* test_emptyvalues_minimalpairs
* test_analysis_frequency

For example, these tests should not query for a specifc handshape in the database, but instead create a temporary handshape for the test.

**Comment by susanodd** [comment]
The handshape objects used in the tests are now created abstractly.
This solves the machine value references in the following tests:

- MinimalPairsTests.test_analysis_minimalpairs
- MinimalPairsTests.test_emptyvalues_minimalpairs
- HandshapeTests.test_handshape_choices
- testFrequencyAnalysis.test_analysis_frequency

@Woseseltops in your list, the test_delete_fieldchoice_othermediatype test turned out to be the HandshapeTests.test_handshape_choices one.

**Comment by Woseseltops** [comment]
Updated the Global Signbank server and ran the tests, and they work! So this is probably fine now :)
