### ISSUE TITLE
Create standard format for metadata to be used in the generation of gloss frequency data

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#620]
* This is extracted from #354 , which has focused on the visualisation
* We would need a standard format for metadata that links EAF files to metadata categories. Signer identities are specified in the Participant tag of the gloss tiers in the EAF files, but the region where a signer is from, the age (group) of the signer, or any other relevant metadata property is not in the EAF. 
* The way to do this will relate to how the new frequency functionality in #354 
* For the Dataset Manager who has the ability to upload EAF files (#619), on the upload page we could instruct them as to the required format.

**Comment by susanodd** [comment]
At the moment, the metadata is obtained from the file:
CNGT_MetadataEnglish_OtherResearchers.csv

This file is where the (NGT) speaker ids are found.
The region, age (at time of recording, not a year), gender, handedness are stored here with the speaker identifier.

Would you like new metadata to be similarly specified in csv files for the newly uploaded EAF files (in the Datasets EAF location)?

Will the Dataset Manager maintain their own metadata file (and re-load it as needed to update it)?
Or would you like a data structure in Signbank? (And functionality to update it in the interface.)

**Comment by ocrasborn** [comment]
My idea was indeed to have people maintain their own CSV file with metadata, rather than providing an interface for it. It would however be important to specify the requirements for that file somewhere. We could do this in the manual, but why not repeat it on the upload page?

The CNGT CSV contains two tables, Sessions and Participants, and this we can expect from anyone working with ELAN files.

I see that there's quite some detail in the CNGT metadata, in terms of the fields (handedness could go out) and in terms of the values (we'd better specify age in 10-year ranges). It'd be important to let people decide themselves what they put in there.

**Comment by susanodd** [comment]
This is on the Manage Datasets page. (It's on my local machine at the moment.)
I can add functionality to process the CSV file.
Or otherwise simply to "parse" it to make sure the format is okay.

We have this functionality already for the CNGT data. Processing the metadata file creates Speaker objects. (To be associated with the EAF files and Frequency objects, etc.)

So far, I assumed there will be one Metadata CSV file per dataset.

Does this setup seem okay, @ocrasborn ?

I'm going to work out the uploading for EAF files next.
I discussed with @vanlummelhuizen to determine the appropriate locations for the files.

We will need functionality to process the files for the dataset managers. For the CNGT that's done at night.

**Comment by ocrasborn** [comment]
Yes, this does seem OK indeed @susanodd ! And I very much like the wording 'supported at the moment', sending people in a particular direction yet being open for their feedback.

**Comment by susanodd** [comment]
This has been pushed to github.
