### ISSUE TITLE
Check rights for users with 'write' permission on dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#623]
A dataset manager reported to me that a new user whom he gave change/write access to his dataset was not able to add signs. I had to assign the role of 'editor' to get around this, but would like to understand what the situation is. People with change permissions should be able to alter and add signs/glosses, lemmas, and morphemes (but not handshapes). If I as a superuser need to do something in the admin for these users, the management of dataset permissions for dataset managers wouldn't mean much. Do we need to change something here to make it work, or was something else going on for this particular case / at that particular time (late last week, when the registration was also broken, #622 )?

**Comment by susanodd** [comment]
In the code of template add_gloss.html
there is a permissions check
dictionary.add_gloss

**Comment by vanlummelhuizen** [comment]
@ocrasborn, what exactly does this mean, in terms of giving permissions?:
> gave change/write access to his dataset

In Signbank a permission applies to an action for either a model (e.g. Gloss) or for an individual object of a model (e.g. dataset 'NGT'). Normally a permission does _not_ apply to a model/object _and_ all things that are connected, e.g. dataset 'NGT' and all it's glosses.

So if a user has the 'change dataset X' object permission, but not the 'add gloss' model permission, the user may change the dataset's name, acronym, description and other Dataset fields, but not add a gloss to that dataset, since adding a gloss is about the Gloss model, not about a Dataset object.

So at first glance giving someone change-dataset permission and add-gloss permission (by adding the user to the Editor group) seems a about of right.

We could think of a way to check permissions in a different way, e.g. if a user had 'change dataset X' permission, the user also may add/change/delete glosses/lemmas/lemmaidglosstranslation. This may involve quite some changes to the codebase.

**Comment by ocrasborn** [comment]
Perhaps it need not be too complex: dataset managers have different roles than editors. On the page Datasets > Manage Datasets, the managers configure who has view access to the dataset including its lemmas/glosses/translations, and who has add/change/delete permissions for that content of the dataset, and thus can act as an editor for that dataset.
So "Users who can Change Dataset (Group permissions excluded)" that is modified on the Manage Datasets page should not be about modification of the dataset (that remains a privilege of the manager), but about modification of glosses/lemmas/translations.

**Comment by vanlummelhuizen** [comment]
@Woseseltops @susanodd As discussed with @ocrasborn, let's discuss more about this after a week or two when @ocrasborn return from his trip.

**Comment by susanodd** [comment]
Some tests will be written to explicitly test permissions for creating glosses.

**Comment by ocrasborn** [comment]
Hi @vanlummelhuizen @Woseseltops @susanodd : could we take up this issue again, it was on the shelf for a while when I was travelling, then as we didn't see each other regularly. I'm in the office tomorrow, will you have time to discuss it?

**Comment by vanlummelhuizen** [comment]
@ocrasborn I am in the office tomorrow morning. I have a meeting at 11:30

**Comment by susanodd** [comment]
Sure, okay.

**Comment by vanlummelhuizen** [comment]
As discussed with @ocrasborn : the idea is that if a user is given permission to `change` a dataset, it should also be placed in de `editor` group. Now this is done by an admin (@ocrasborn) to give the user permission to also change everything under the specific dataset (e.g. Gloss, Lemma).

We need to check (at least) four things:

1. Is adding a user to the `editor` group the solution? 
2. What are the consequences?
3. Are the `change` permission for Gloss etc. still restricted to the glosses of only correct datasets?
4. Do we need to remove a user from the `editor` group if `change` permission is revoked from the user's last dataset?

**Comment by vanlummelhuizen** [comment]
When discussing this with @susanodd we had the idea to make an overview of types of users and groups on one hand, and permissions on the other. Perhaps it the whole permission set up can be boiled down to hardly more than dataset managers, dataset editors and dataset researchers.

@ocrasborn @Woseseltops did we do this exercise before?

**Comment by susanodd** [comment]
I made a spreadsheet based on what permissions are checked and what is updated in update.py.

**GlossDetailView update_gloss** (and related methods)

It's true that for nearly everything for update_gloss (and its fields and relations) the initial check at the start of the code, **dictionary.change_gloss** is all that's done.

For fields where publication is possible, an additional check of **dictionary:can_publish** is done.
(This is for Notes and inWeb (Gloss)

There are some suspicious things related to updating the dataset and lemma.
Inside the update_gloss method, if the dataset is_public, the user can change the dataset.
(This is probably obsolete code, because it directly updates the dataset field of the gloss, which was subsumed by lemma.
But it's still in the code. Because it uses a variable called 'field' and the method 'setattr', the compiler doesn't flag this.)
If the dataset is not public, the code checks **dictionary.view_dataset**. If that's true, the user can update the dataset.
Again, this code uses variable 'field' and method 'setattr'.

Note: A few months ago I made it so the Dataset field can not be edited in GlossDetailView.
However, the update_gloss method in python still allows this. Although it probably gives a runtime error since dataset is a property, not a field value.

The other suspicious thing is updating the lemma of a gloss.

The code determines the dataset, then checks that the new lemma is in the same dataset.
However, if there is no dataset (thus no lemma, since it gets the dataset from the lemma),
then the user is allowed to assign a lemma. And hence, assign a dataset to the gloss.

**DatasetDetailView update_dataset** (and related method add_owner)

For updating a dataset, the permission **dictionary.change_dataset** is checked at the start of update_dataset.

Probably an additional test to see if the user is an owner is needed, but this is not done in this code.
Especially if we want to use **dictionary.change_dataset** in combination with **dictionary.change_gloss**.

There are no additional checks done for changing the owner (adding a new owner to the list).
In fact, the code that actually adds an owner to the dataset.owners set is commented out.
So this is probably only possible in the admin.
For datasets, there is a suspicious thing is related to adding an owner for a dataset.

**Comment by susanodd** [comment]
(add_gloss to follow....)

**Comment by susanodd** [comment]
**dictionary.update.add_gloss** (update.py)

To confirm @ocrasborn's initial issue description, the **dictionary.change_dataset** permission is checked here, both as user_perms and group_perms.
It looks like that's the only permission checked inside the method. Templates check the dictionary.add_gloss permission.
The url that directs to dictionary.update.add_gloss does not check permissions. Note that in the url, it is not known what the dataset is.

**add_gloss.html** (template)
The template checks the **dictionary.change_dataset** permission.
The template test for **dictionary.add_gloss** is commented out.

It's not entirely clear to me what combination of permissions is needed.
As pointed out by @vanlummelhuizen, the **dictionary.add_gloss** permission is for model Gloss, not necessarily the intended dataset.

**Comment by susanodd** [comment]
**DatasetManagerView**

Checks that the user is in group **Dataset_Manager** and that the user has **change_dataset** permission for the dataset.

**add_view_perm**

gives the user **view_dataset** permission. Additionally **dictionary.search_gloss** permission if the user is a new user.

**add_change_perm**

first checks whether the user has **view_dataset** permission. The manager is instructed to do this first if false.
Then gives the user **change_dataset** permission.

Indeed, NO PERMISSION for **change_gloss** or **add_gloss** or **can_publish** is given. And nothing is done with group membership for the user getting access.

**Comment by susanodd** [comment]
Responding to @vanlummelhuizen:

We need to check (at least) four things:

    Is adding a user to the editor group the solution?
    What are the consequences?
    Are the change permission for Gloss etc. still restricted to the glosses of only correct datasets?
    Do we need to remove a user from the editor group if change permission is revoked from the user's last dataset?

Regarding revoking permission for the dataset.
At the moment, only the **view_dataset** (and/or **change_dataset**) is revoked for the user.

The actual editing (change_gloss, add_gloss, can_publish) is not addressed in the Manager View.
So at the moment, the issue of editing is separate from access to the dataset.
(3) is true at the moment.

I can add **change_gloss** and **add_gloss** permission when a manager grants change permission for the dataset.
The code would check whether the user already has these, and if not, grant them.
Upon revoking, it could check whether the user has access to other datasets in order to revoke change_gloss and add_gloss if no other datasets are available to the user.
No idea what to do with **can_publish** permission.

**Comment by susanodd** [comment]
[CODE UPDATE DATASET]

I added an additional permissions check that to update the Dataset Detail fields, the user must be in group Dataset_Manager.

**Comment by susanodd** [comment]
[CODE UPDATE GLOSS] https://github.com/Signbank/Global-signbank/issues/623#issuecomment-697265174

I added granting of **change_gloss** and **add_gloss** to the Dataset Manager **add_change_perm**.
And likewise, revoking it again when **delete_change_perm** if the user has no **change_dataset** access to other datasets.

**Comment by ocrasborn** [comment]
Hi @Woseseltops , I'm still adding users that have received write permission for a dataset manually to the group Editors to make it work for them. How can we solve and close this issue?

**Comment by susanodd** [comment]
Do you want them to be in Group Editor too?

**Comment by ocrasborn** [comment]
> Do you want them to be in Group Editor too?

yes, indeed @susanodd

**Comment by susanodd** [comment]
This has been fixed and pushed to branch `group_editor_change_dataset`.

**Comment by susanodd** [comment]
This is live now.

**Comment by susanodd** [comment]
This is live.
