### ISSUE TITLE
Field choices for all datasets suddenly un-selected

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#626]
I have no idea what might have caused this, but I was switching between datasets today focussing on NTS, occasionally looking at Manage Datasets, and now suddenly all field choices have become un-selected for all datasets except for NTS. How on earth?!! 
Is it related to someone working on #625 ?
I don't think anyone had been using the option yet so far, so please re-select all field choices for all datasets -- in some magic way that only you can, @Woseseltops , @vanlummelhuizen or @susanodd !

**Comment by vanlummelhuizen** [comment]
@ocrasborn I removed all 'exclude_choices' from all datasets, so that all FieldChoice are available for all datasets. So any 'exclude_choices' settings before this problem happened, are lost.

**Comment by ocrasborn** [comment]
Thanks @vanlummelhuizen ! But: would you have any idea how it might have come about?

**Comment by vanlummelhuizen** [comment]
Why exactly this happened, I don't know. But my guess is that when sending (POSTing) new field choice settings these settings were not completely correct when they were used to change the relevant data in the database. And because the view starts with the assumption that all field choices are excluded (https://github.com/Signbank/Global-signbank/blob/4b77b1b0acfd9fb67c7a766188d96b7a8d7811c0/signbank/dictionary/update.py#L2036-L2039), it may result in the problem you described @ocrasborn .

I will open a new issue for rewriting the dataset field choice setting form.
