### ISSUE TITLE
Impossible to link morphemes to signs

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#636]
When I add a 'simultaneous morphology' link for a sign, the gloss field does not search in the list of morpheme glosses to present options for me. If I manually paste in a morpheme gloss and add meaning, clicking the Add Morpheme button leads to the cryptical error message in the screen shot below. 

<img width="879" alt="Screenshot 2020-04-02 16 15 17" src="https://user-images.githubusercontent.com/10242207/78259896-909d5780-74fd-11ea-981f-f01cbaf58c37.png">

I think this worked smoothly before.

**Comment by Woseseltops** [comment]
Autocompleting morphemes indeed did not work, autocompleting glosses did. I looked up the difference and it turned out to be that the morpheme variant had an 'idgloss' filter, while idgloss is no longer a Django field. I resynced the two by simply removing this idgloss filter, and now it works again, but I'm not sure about any effects this might have elsewhere in Signbank. Do you know this @susanodd ? Could you review my solution?

**Comment by susanodd** [comment]
It looks like it just wasn't revised. The morpheme pages weren't being used very much. It looks good to me.
