### ISSUE TITLE
Create way for users to see account expiry date and apply for extension

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#648]
Users start making new duplicate accounts because their old account is expired... Check: is it possible now to create two accounts linked to the same email address? That should be made impossible, but since people have so many email accounts nowadays, that's not a universal catch and we'd better facilitate for people to ask for an extension.

**Comment by susanodd** [comment]
@vanlummelhuizen and I are both looking at the accounts right now.

One observation, the test user accounts share your email @ocrasborn.
That may be why it is the way it is, to allow testing with different permissions, with real accounts.

**Comment by susanodd** [comment]
I'm creating a User Profile page for the logged in user.
Here it will show the expiry date.
There can be a button to make this farther in the future.
Can a user do this themself (i.e., automated)?
Should it go via the semester?

The user will need to be logged to view their profile (expiry date).

Do you want some way to alert users if their account is due to expire (automated)?
Or to check when the user attempts to login to an expired account, that something happens (automated)?

There's a Forgot Password facility.
Perhaps a Forgot Login? or Login Expired?
Is it possible people forget their username and therefore create a new username?

**Comment by ocrasborn** [comment]
Hi @susanodd : I really only set an expiry date for students who want access, and for whom I'm not sure they will stay in the field. For other users, I just leave the field blank. I'd rather keep control over this, so please do not allow users to update their own expiry date. Sending them a message is not necessary either.

**Comment by ocrasborn** [comment]
About the 'forgot password' etc.: no opinion myself, I would always ask @Woseseltops or @vanlummelhuizen for what they think is safe enough and/or what is considered best practice.

**Comment by susanodd** [comment]
The Forgot Password is already there. It's been there since donkey's.

So to clarify, merely let the user view the Expiry Date.

**Comment by susanodd** [comment]
Here is a mockup showing a Profile link to the left of the Logout link.
Clicking you get shown the following (without the actual data):

![userprofile-expiry-date](https://user-images.githubusercontent.com/24272544/94274794-69709180-ff46-11ea-8ad9-034a38a1c7f6.png)

**Comment by ocrasborn** [comment]
Seeing this in a screen shot, I realise what obvious information we should add there: datasets to which the user has read resp. write access! Could you add that?
Had you thought of how to make this accessible to the user, @susanodd ? By clicking on the user name next to 'logout', or would that be confusing? Perhaps a menu entry 'User profile' under the 'About' menu?

**Comment by vanlummelhuizen** [comment]
I think that the most conventional way is to have the current logout link divided into a link to the profile page and a link for logging out. 

About log in, forget password and expiry date: when an account is expired, a user should still be able to log in. Instead of viewing data, the user should be presented his profile page with a message saying his  account has expired and how they can request  an extension. 
Also, to prevent  this situation, we could think of a way to tell users that their account is about to expire and how they  can request an extension. We can make a Command and run it from a cronjob.

**Comment by susanodd** [comment]
Hmm. That sounds a bit like overriding the guardian checks. The check that users are not anonymous.
Then it becomes ambiguous if the user is logged in or not logged in.

I have a link to the left of the Logout link. ('Profile' in the mockup image above. That shows the page shown.)

What you suggest about displaying the profile if the user forgot their password.
At the moment, Forgot Password is already implemented in the Login Page.
(This already existed in the software.)

It seems kind of risky if people could keep typing in various usernames to get information displayed
Again, this seems like overriding guardian.

People should be logged in to see the profile.

Perhaps a problem arises that people create a new account because their email expired

Perhaps the User Profile could be shown right after logging in, instead of the Recently added signs.

**Comment by susanodd** [comment]
@ocrasborn, I assume it's okay to display the User Profile for one of the test account users which has your email ?
(Your email is published on the site.)

Here's a snap of what the user profile looks like if an anonymous user enters the url.
(There is currently no way to link to this page if one is not logged in.)

![userprifle-anonymous](https://user-images.githubusercontent.com/24272544/94421776-58ae5e80-0186-11eb-926f-4c5d6337b3cc.png)

**Comment by susanodd** [comment]
![userprofile-test-user](https://user-images.githubusercontent.com/24272544/94424617-cc526a80-018a-11eb-885c-6fac3448f4c5.png)

**Comment by vanlummelhuizen** [comment]
@susanodd Ah, ok. If that message is enough, we can leave it like this. if not, the message should be different. Perhaps a link to a page to request an extension. @ocrasborn ?

My idea was that if a account was expired, all permissions were revoked, not that the user could not log in anymore. If a user can still log in and can at least manage his/her account, he/she might be less tempted to register for a new account.

**Comment by ocrasborn** [comment]
Hi @susanodd , yes feel free to use my test account.
Hi @vanlummelhuizen @susanodd : yes, a button (rather than a link I'd say to a new page; the button sends a message to that effect to me) to request extension would be good.
And I agree with @vanlummelhuizen : let expired users log in, but revoke their permissions for anything else but seeing their own page.

**Comment by susanodd** [comment]
The user Profile is visible in the Menu bar now, to the left of the Logout button.
That's the first part of the issue, to let the users see the expiry date.
Next is to add the feature to apply for extension.

**Comment by ocrasborn** [comment]
Thanks @susanodd ! Can you follow up and implant the 'apply for extension' as well? Do you have a suggestion for what that should do? Send an email to the admin, with a hyperlink there to go to that user's page in the admin?

**Comment by susanodd** [comment]
![extend_expiry_user_profile](https://user-images.githubusercontent.com/24272544/168266848-0cf30910-6495-4a0d-b4ef-53c53e414cd7.png)

**Comment by susanodd** [comment]
Okay, this is what it looks like now, the form is a post form now so the parameters don't show in case of an extension.
This is before and after.
The button shows up if the users account is within 60 days of expiration, clicking the button extends it by 6 months.


![extend_expiry_button](https://user-images.githubusercontent.com/24272544/168275787-b8697c2d-0969-44a3-8d6c-f3489db677a5.png)


![user_profile_after_extension](https://user-images.githubusercontent.com/24272544/168275825-1bee2f4f-5e12-43db-a612-1e54c1368d5e.png)

**Comment by susanodd** [comment]
This has been pushed to branch `extend_expiry`.

**Comment by Woseseltops** [comment]
Already reviewed the code @susanodd , but shouldn't we wait until @ocrasborn agrees before we push this to master?

**Comment by susanodd** [comment]
Probably. Although this issue was opened in April 2020.
I kind of think it's less cumbersome like this, since otherwise there will be more email being sent.
(See #623 about putting them in Group Editor.)

**Comment by susanodd** [comment]
@ocrasborn what is your view on this? See screenshots above showing the button.

**Comment by susanodd** [comment]
This issue is waiting for approval from @ocrasborn for the new "automated" extend expiry button, which avoids deferring to the Admin.

**Comment by susanodd** [comment]
@ocrasborn approved this when I asked him in real life.

**Comment by susanodd** [comment]
This is live now.
