### ISSUE TITLE
Catalan: registration function doesn't work yet

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#655]
I get to the form from the login page, but submitting the form leads to an error

**Comment by Woseseltops** [comment]
This is a weird problem: apparently, for creating new users, you need a database table called 'registration_registrationprofile'. This is created by a legacy part of the code base, the 'registration app', which was disabled in the settings in March 2017. Apparently, in the other installations registration only works because their databases were created before that time.

**Comment by Woseseltops** [comment]
I think I fixed it with `CREATE TABLE "registration_registrationprofile" ("id" integer NOT NULL PRIMARY KEY, "user_id" integer NOT NULL UNIQUE, "activation_key" varchar(40) NOT NULL);`, but now there is a new problem.

**Comment by Woseseltops** [comment]
A the postfix email software needed to be installed, apparently not standard with this installation of Ubuntu. Now it works.

**Comment by Woseseltops** [comment]
> but I didn't yet get the email that the site promises to send me

I too don't get anything if I use my let.ru.nl email address, and I suspect the same goes for any major email provider. My best guess is that email addresses coming from an IP address without domain are blocked by default, as this is what a beginner spammer would do this send out millions of emails :). If I try an inbox with no protection at all, like temporary mail provider https://www.guerrillamail.com/, I get the email.

My proposal is to close this issue, and reopen if it turns out the emails are still not received with a good domain name present?
