### ISSUE TITLE
Make the combo of field and machine_value unique for the FieldChoice model

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#660]
The combination of `field` and `machine_value` fields in the FieldChoice model should be unique. That is not enforced right now.

**Comment by susanodd** [comment]
In the file translate_choice_list.py there used to be a warning printed for this error:
`    for choice in queryset:
        if choice.machine_value in machine_values_seen:
            # print('Duplicate machine value for FieldChoice ', choice.field, ' (', choice.machine_value, ')')
            # don't append to queryset_no_dupes
            continue`
The same was done in the tests to print a warning message.

**Comment by susanodd** [comment]
This is the commit that addressed this issue. It references several issues:
https://github.com/Signbank/Global-signbank/commit/e31b5062dca53ffb0b8708ab598f7a9fd3182762#diff-60b3618203fe39c19b98a41b3822c0b8

**Comment by susanodd** [comment]
It looks like the commit message was too long, so "duplicate" was truncated off.

**Comment by susanodd** [comment]
@vanlummelhuizen, 

It does not look like the Admin is causing machine value duplicates for a field.

The machine value is not writeable in the Admin form. It is generated.
The code automatically creates a new machine value larger than the others in use for that field category
The first machine value created if there are currently no choices, is 2.

The duplicates could be legacy code, or perhaps by editing a FieldChoice object and changing its field category?
I don't know if that's possible. (TO DO VIA A TEST.)

The Admin for FieldChoice has been revised.
It now checks for and prevents duplicate choices being created for a particular field category.
Furthermore, it's not possible to create new categories, as this does not serve a purpose, since these are in the fields in the models with choices.
The Admin interface restricts the category by showing a list of categories to choose from (as per the model).
(Ubuntu does not allow to make a screenshot.)

**Comment by susanodd** [comment]
Yykes!!! It is possible to change the field category of a FieldChoice!

On my local server, I just changed a Semantic Field (category SemField) called Tennis into a choice for Handedness.

So this would be a way to inadvertently end up with duplicate machine values.

**Comment by susanodd** [comment]
This has been fixed. A field choice that has already been created in a particular category can not be changed to a different category. Instead it will need to be deleted and another created in the other category.

**Comment by Woseseltops** [comment]
The code I reviewed so far is mostly bug fixes and making warning texts translatable, right?

**Comment by susanodd** [comment]
Yes.

**Comment by vanlummelhuizen** [comment]
@susanodd The changes you  made are live. However, in your code I see two things fixed:

1. An error is now raised instead of just stated. Good, that is probably the reason the problem existed.
2. Now only  FieldChoices for existing field categories can be made. That means that no new field categories can be made. Am I correct?

In the end I think a database unique constraint is what we want. This involves a migration so for now we will postpone that solution because of the FieldChoice revision migrations I am working on.

**Comment by susanodd** [comment]
2. Yes, that is correct, only existing categories can be used.
Because these are hard coded in the models. If the user created new categories, these would not be used for anything.

**Comment by susanodd** [comment]
I suppose (but probably not okay) we could instead dynamically fetch all field_choice_category attributes from the models, instead of querying the database.
But again, that doesn't seem like something wise. I guess it could catch errors if people modified the models but forgot to do anything else. Maybe while setting up a new signbank.

**Comment by susanodd** [comment]
I could make a test to check whether the categories in the database are the same as those in the models?

**Comment by vanlummelhuizen** [comment]
@susanodd Good point. So, as it is now, when a model gets a new FieldChoice field, we need to make at least one initial FieldChoice.

My revision of FieldChoice implementation covers this. So for now, let's leave it as it is.

**Comment by susanodd** [comment]
Okay, great!
