### ISSUE TITLE
Adjust Dutch field label for keywords-Dutch

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#664]
In the Public View, the Dutch field label for the keywords in Dutch now nicely reads "Mogelijke vertalingen in het Nederlands". In the Detail View, however, it says this for both the Dutch and English keywords fields "Mogelijke vertalingen in het Nederlands (Nederlands)". Please change those to "Mogelijke vertalingen in het Engels" and "Mogelijke vertalingen in het Nederlands", respectively.

**Comment by vanlummelhuizen** [comment]
The problem is slightly different. The English label "Translation equivalents" is translated into Dutch as "Mogelijke vertalingen in het Nederlands". The language name between brackets is the language as found in the database for those translation. The language name is also translated to the current interface language. 

What we could try:

1. Change "Translation equivalents" to "Translation equivalents for"
2. Translate it to Dutch as "Mogelijke vertalingen in het"
3. append the language name to these labels, without brackets. The result should be something like:
    - Translation equivalents for English
    - Translation equivalents for Dutch
    - Mogelijke vertalingen in het Engels
    - Mogelijke vertalingen in het Nederlands

**Comment by ocrasborn** [comment]
Sounds like a good solution to me, @vanlummelhuizen

**Comment by vanlummelhuizen** [comment]
@ocrasborn Done and live.
