### ISSUE TITLE
Error in changing a dataset description

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#667]
When I try to edit the Reference field for the NGT Dataset description, I get a pop-up signalling an error in the HTML of the whole page.

**Comment by vanlummelhuizen** [comment]
The error you get has the form of a HTML page. It is a normal 404 Not Found page display in a popup because the request was send under the hood (AJAX). The reason was that the thing that handles the short /dataset/<acronym>url was blocking the use of other /datasets/??? urls. It should be solved now.

**Comment by susanodd** [comment]
I put the wrong issue number in that commit so it's showing up here. It should be #677.
