### ISSUE TITLE
Relations View does not open

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#680]
I was at https://signbank.science.ru.nl/dictionary/gloss/639. When I click on the Relations tab (https://signbank.science.ru.nl/dictionary/gloss_relations/639), I get an error: 'list' object has no attribute 'filter'
Checked a few other signs: same thing.

**Comment by susanodd** [comment]
It says the choice list is empty in the details.

**Comment by susanodd** [comment]
I'm looking at the code now. It's like the control flow has changed.

**Comment by susanodd** [comment]
On my machine this was caused by a Boolean value being passed to the function that translates choice lists to human readable form.
That is very strange because that function does not handle other kinds of values.
There is an exception, which should catch this.
But the Errors the exception looks to catch has been made more specific, so the error isn't caught.

**Comment by susanodd** [comment]
I can fix this in a number of different ways.
The easiest would be to make the Except catch all errors again.

[Somebody has changed it to:
           `except (IndexError, ValueError):`
That may have to do with MySQL]

Or to build into the translation function to handle all kinds of data.
(Basically doing the work of what the Except used to do.)
Or at all the places the function is called, make sure it's not called with empty choice lists or non-choice-list types of values.

Previously, we have been moving all the fields lists to the settings file to keep explicit field lists out of the code.
Here you see an example of an error caused by that.
The type of field "useInstr" is a Boolean.
That's not in Phonology or Semantics.

**Comment by susanodd** [comment]
This has been pushed to github.
I implemented the first option.
