### ISSUE TITLE
Change dataset field label "Conditions of use by others"

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#683]
The dataset metadata contain a field "Conditions of use by others", but this is a bit of a misnomer. "Conditions of use" may suggest that a user already has access, but that certain conditions apply. Therefore, please change the label to "Conditions for access by others" -- unless you have a better suggestion, of course. Native intuitions welcome, @susanodd !

**Comment by susanodd** [comment]
Actually as you elaborate it in the description above, it makes me confused.

What does "use" mean?
Probably the permissions need to be checked for all export to CSV commands.
That's what pops to mind that somebody would be wanting to "use" the data elsewhere.

Is Export to CSV tied to Researchers?

And now "access by others" (if you assume the user already has access) sounds like it might mean showing it to "other" people (not the user who's reading this).

Perhaps you can give an example of something the user is not supposed to do.
Plus an example of something the user is allowed to do.
(Like educational and research uses, with proper citation, but not commercial uses, plus additional restrictions on the media and the signers. Perhaps some explanation about "persons in the videos" since this is like text authors.)

**Comment by susanodd** [comment]
Conditions for Data CItation

**Comment by susanodd** [comment]
![emblemsNL-dataset-detail](https://user-images.githubusercontent.com/24272544/93339249-a1cbed80-f82b-11ea-9388-ea4fe01562f2.png)

**Comment by susanodd** [comment]
For the EmblemsNL dataset, I think the Conditions description lines up with what you have written.
