### ISSUE TITLE
Search result scroll bar is not refreshed

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#687]
I switched selected datasets, from Kata Kolok to ISL. When displaying 'all signs' through the menu, the horizontal scroll bar still displays my last search result from Kata Kolok, also when I reload. See screen shot. Why?!

<img width="1536" alt="Screenshot 2020-09-24 at 11 18 21" src="https://user-images.githubusercontent.com/10242207/94126610-1e785080-fe58-11ea-8b1e-9135442c33f0.png">

**Comment by vanlummelhuizen** [comment]
@ocrasborn the results from your last search are saved in your profile at the back end. It is not cleared when you do something unrelated to searching/browsing search results. If you want that, we should carefully consider where to clear the profile's search results and where not to clear it.

**Comment by ocrasborn** [comment]
I see. To the user, the search feels like a filter, and 'Show all' undoes all filter options. But in fact they're two different things then. There's no safety issue here I think, but it would improve the user experience if 'Show all' would lead to a similar scroll bar at the top of the list view. Is that doable, @vanlummelhuizen , perhaps restricting the scroll bar items to the same items as displayed on the page below (so not loading thousands of items for the bigger datasets)?

**Comment by susanodd** [comment]
@ocrasborn can you think of cases where you don't want to see the results bar?

The Gloss Detail template merely tests if there are search results, and if so displays the bar.

At the moment, if one goes to Search and then without actually typing in any query parameters, just hits Search sign, then the search results parameter is filled (== show all). Then the bar is there on the Detail View.

**Comment by susanodd** [comment]
Cases where the results are explicitly discarded are when your last search was say Handshapes and you're now looking at Glosses or Morphemes.

Regarding changing the selected datasets, that should be discarded, because if you try to view something in a non-selected dataset it should give an error.
It sounds like a bug.

**Comment by susanodd** [comment]
The search_results are explicitly set to None when a new gloss or new morpheme is created.

https://github.com/Signbank/Global-signbank/blob/da7326de971f8b68c39237bfc178424bcef96110/signbank/dictionary/update.py#L112-L116

https://github.com/Signbank/Global-signbank/blob/da7326de971f8b68c39237bfc178424bcef96110/signbank/dictionary/update.py#L1579-L1580

**Comment by susanodd** [comment]
I made it so the Handshape View shows a scroll bar with all handshapes if no query has been done on handshapes. (Encountered this bug #688).

**Comment by susanodd** [comment]
@ocrasborn, I did exactly as you write above. https://github.com/Signbank/Global-signbank/issues/687#issue-708006079

Yes, this is a bug.

**Comment by susanodd** [comment]
The search bar gets its data via a session variable 'search_results'.
This needs to be set when a query is done.
As mentioned above, the search_results for the scrollbar are not objects, but data.
The results are made ready for display by a call to `gloss_ajax_search_results`. https://github.com/Signbank/Global-signbank/blob/853e24472a505cf83f0334805f0b70146fe9e7db/signbank/dictionary/adminviews.py#L4639
This code checks the 'search_type' to make sure it's sign or morpheme.
Otherwise the search results are set to None.
