### ISSUE TITLE
Morphemes?

### ISSUE THREAD

**Issue by susanodd** [Signbank/Global-signbank#689]
In the most recent database file, there are no morpheme objects.

**Comment by susanodd** [comment]
@ocrasborn did somebody remove the morphemes?

I switched back to a previous database on my local server.

There is a database table that lists all morphemes as pointer to a gloss, plus morpheme type.
That table is empty now.

In model Gloss, is_morpheme is implemented as a method and in the database there is a table with links to glosses. The extra morpheme fields are stored in this table. The fields morphemes share with glosses are stored in the gloss table.

Now the morpheme table is empty, so it's not possible to see what glosses are also morphemes either.
The morphemes have been deleted, because the gloss part of the morphemes are also gone from the gloss table.

**Comment by ocrasborn** [comment]
Hi @susanodd , yes, the deletion was my doing, and intentional. Sorry if it frustrates any development, do feel free to add morphemes with "TEST" in the gloss to try out things on the live server, for the NGT dataset. 
We're finishing off a project, and for that we'll be importing a longer fresh table of morphemes in the coming weeks. (Well, actually, we'll be asking one of you guys to do that for us, as there's not CSV import for morphemes ;-), which is just fine.)

**Comment by susanodd** [comment]
Now that the morphemes have appeared again...

@ocrasborn, can you try doing the following:

- https://signbank.cls.ru.nl/morphemes/search/

- Try Search by Morphology, Has Morpheme Type, Hands: Handedness

That gives results for NGT now, because there are morphemes again. Hurrah!

But doing the same in the normal Search, with "sign or morpheme" does not.

- https://signbank.cls.ru.nl/signs/search/

In the python, the two list views get_queryset are implemented in totally different ways.

For some reason, the GlossListView search on hasMorphemeOfType
is looking at model SimultaneousMorphologyDefinition
Does this ring any bells?

(This sign/search is looking at whether the simultaneous morphology has the required morphemetype.
I will make it do the same thing the Morpheme Search page is doing. I suspect we didn't notice this because there were no morphemes. Please check.)
