### ISSUE TITLE
Create CSV export for minimal pair list

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#692]
I thought we already had this, but I can't see it anywhere now. A button at the top like we have for search results would be most intuitive I think.

**Comment by susanodd** [comment]
Q @ocrasborn: Do you want the glosses without minimal pairs also exported in the CSV ?
At the moment, that's what I'm doing.
Those rows only have the (optional) Dataset, and the Focus Gloss, (ID), columns filled in.

The format of the Analysis->Minimal Pairs is so:
Shows a giant table, glosses without minimal pairs simply don't have the rest of the row filled in.

So far, the CSV mirrors what you see on the result pages.

Is this okay?

(Minimal pairs are computed, not stored.)

(This analysis page is implemented this way because it uses gloss ids to label the rows and ajax calls to fill in the data. So only the minimal pairs of the glosses on the visible page are computed.
Although it is possible to hide rows with no minimal pairs, it's not convenient to do extensive processing to figure out which of the glosses need to be hidden. As it is now, some pages would be much shorter if glosses were just hidden.)

**Comment by ocrasborn** [comment]
Hi @susanodd : yes, let's do that, also include the glosses without minimal pairs.

**Comment by susanodd** [comment]
![minimal-pairs-simple-filter](https://user-images.githubusercontent.com/24272544/96143406-5a588000-0f03-11eb-834c-936ec0d27319.png)

**Comment by susanodd** [comment]
I added a simple query on the focus gloss to be able to look for specific results.
The phonology query part is only those fields used in minimal pairs.
And the semantics fields are the ones with choices.
Further it's the normal annotation, lemma, and keywords like for other searches.
I realised that the list can be massive without filtering and just to test it, it's handy to reduce the number of results.

**Comment by ocrasborn** [comment]
That's so useful @susanodd !! Thanks!

**Comment by susanodd** [comment]
@vanlummelhuizen or @Woseseltops can you pull this issue to the master?

**Comment by vanlummelhuizen** [comment]
This should be live now. @susanodd @ocrasborn can you test?

**Comment by ocrasborn** [comment]
All looks good to me, thanks @susanodd & @vanlummelhuizen !

**Comment by hannahlutzenberger** [comment]
picking up on a short conversation Onno and I had on Tuesday, could someone spell out for me what exactly the minimal pair function does (i.e. what fields are taken into account etc.)? thank you!

**Comment by ocrasborn** [comment]
@hannahlutzenberger , I'm currently including this in the manual v. 2.1, will send you an intermediate update by tomorrow.
