### ISSUE TITLE
Enable the 'handshape' functionalities for ASL

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#698]
Not sure what all is involved. From the user side, in Global SB we have the Signs > Search Handshape item, which leads to the page with the handshape table. Also, in the gloss detail view, the values for Handshape Strong and Handshape Weak are hyperlinked to the entry in the handshape table, so to the handshape detail view. Anything else?
They will be creating their own list of handshapes in the end, but we would help them get started if we fill the table with our own handshape data, they can then throw out what they don't need, and save time in specifying the feature values.

**Comment by susanodd** [comment]
I originally set up the handshapes. Some of the code makes use of the fact that only NGT / Dutch was used.

That sounds like a good idea to let them start with our table and remove or modify for their own handshapes.

At the very start some handshape objects were created lazily when people used one of the handshape field choices.
That was because it was possible to create handshapes by adding new field choices for them.

The code has kept evolving. @vanlummelhuizen has been working on the hard coded name fields (models FieldChoice and Handshape share name fields).

In the beginning, only Dutch was filled in. It's just a field name in the database and lots of the names are symbolic, so not entirely Dutch. That has also caused other issues in pulldown menus because of > characters.

**Comment by Woseseltops** [comment]
As far as I'm aware they're not waiting for this (anymore?)
