### ISSUE TITLE
Lemma exists says change lemma form, but search lemma says not

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#707]
I try to change Lemma Gloss VERWARD-C to VERWARD-B. 'Dutch Lemma ID Gloss not unique' is what I get. But when I search for lemma 'VERWARD', I only see VERWARD-A and VERWARD-C. (Not a unique case, but forgot the other one I ran into earlier today.)

**Comment by susanodd** [comment]
I just searched (with NGT selected) on 'verward'.
I get two glosses, VERWARD-A and VERWARD-B.
But for the Lemma columns, VERWARD-A has a missing English (Lemma) translation.

![verward-zoek](https://user-images.githubusercontent.com/24272544/101492797-7ad21300-3965-11eb-9df3-9fde6e3eeb4c.png)


Could it be that some data was missing before you tried editing the lemma?
This was once causing problems, because technically, the "lemma" has one of the translations blank, so it thinks it's a different thing.
Did you change the lemma (what you describe above) in the Lemma Update (via the Lemma List) or via the Gloss ?

**Comment by vanlummelhuizen** [comment]
@ocrasborn There is a Lemma without any Glosses with translation VERWARD-B, ID: 6716. If you go to the list of lemma's, page 35, you'll able to delete it. I suspect this will solve your problem.

Perhaps it would be a good idea to make the list of lemma's searchable.

**Comment by ocrasborn** [comment]
Ah! Good find, @vanlummelhuizen , indeed I didn't find it as I wasn't going to click through the pages of the looooong lemma list somewhere. ;-) I've added you're idea as an issue, indeed exactly what we'd need. #708
