### ISSUE TITLE
New users get error upon logging in

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#710]
Or well, I've gotten the complaint only from people who registered recently, like rose_stamp and . Here's her error message. Never got this myself I think. Might it be related to work on #709 ?
Reloading the page (or loading the base url again?) makes the error go away, and users can enter like expected.
(This is not blocking like 'we cannot do anything now', but it'd be good to look at this first when returning to work in the new year :-))
![test](https://user-images.githubusercontent.com/10242207/102688419-de2a3380-41f6-11eb-8d84-e82fa3e394ec.png)

**Comment by Woseseltops** [comment]
> I've gotten the complaint only from people who registered recently

This was the observation that led me to the answer! Turned out not to be related to the ASL account issues I've been working on during the last two weeks, and actually not to logging in at al: the problem was the way the profile page was set up. It assumed the Signbank-specific 'profile' had the same ID as the generic Django 'user', which was incorrect. I now made the lookup the way it was intended to, and it works again.

Can you ask the reporters to confirm @ocrasborn ?
