### ISSUE TITLE
Incomplete log page for dictionary/import_videos/

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#717]
When I import videos, I get a correct list of videos that were not imported (they're still there, for NGT/nld/ you can try), but I get nothing for 'imported' or 'overwritten'. The latter I can imagine is simply because I didn't have anything to overwrite, but the many videos that are correctly linked each time never show up under the header 'Imported'. It'd be good to have that though.

**Comment by susanodd** [comment]
From the import_media code, it looks like this should be working correctly for images?

https://github.com/Signbank/Global-signbank/blob/affb3fa53a43b3adc8f0c1a53052423d2defe3a1/signbank/dictionary/views.py#L571-L580

But not for videos as you point out.

(I can't actually run this to confirm. But reading the code that last line looks to be what's missing from the else case.)

**Comment by Woseseltops** [comment]
Found this while going over high prio issues on my name! I had a look at the code and indeed it is not possible to have overwritten videos; unlike images, it looks like a video is just added to the list of videos instead. For the end users, though, this the same as overwriting a video, so I guess that instead of this

https://github.com/Signbank/Global-signbank/blob/affb3fa53a43b3adc8f0c1a53052423d2defe3a1/signbank/dictionary/views.py#L593

it should be something along the lines of

overwritten = len(GlossVideo.objects.filter(gloss=gloss)) > 1

**Comment by susanodd** [comment]
I'll see about adding that last overwritten line to the new code.

**Comment by susanodd** [comment]
Okay, that successfully determines that a video has been overwritten.
Do we want this in the table? (See #799)

**Comment by susanodd** [comment]
@Woseseltops what's the status of the live server compared to the master? The import_videos are on the master branch.

**Comment by susanodd** [comment]
The overwritten information has been added to the table next to Success if the video was successfully copied.

![feedback-import-videos-overwritten](https://user-images.githubusercontent.com/24272544/171868004-4468d9c8-152a-40d8-bccc-87b0e5e377b3.png)

**Comment by susanodd** [comment]
This is live.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Satisfied?

**Comment by ocrasborn** [comment]
yes, great, that's really helpful for me @susanodd @vanlummelhuizen @Woseseltops !
