### ISSUE TITLE
"The given Lemma Idgloss ID is unknown."

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#718]
For dataset NGT, I try to add the annotation gloss #X-B and link it to existing lemma gloss #X. But when I try that, I get the message "The given Lemma Idgloss ID is unknown.", even though I am positive it is there, and when I edit it from the linked Annotation ID Gloss #X-A, the Id of it (3293) is the one I find back in the Admin with Lemma.
Moreover, see screen shot below: I'm confronted with an odd page, where I don't know what to do: I'm out of the loop of creating a new annotation gloss, it seems, I'm forced to create a new lemma (am I?), yet the button at the bottom does not say 'Add new lemma' but 'Add new sign'. Either way, I shouldn't be forced to create a new lemma, as I'm positive it already exists.
Something to do with the # character in the gloss perhaps? But then what generates this odd page? Revising the text on the page to guide the user better would be appreciated, should it have a function (for cases where the error is justified).
<img width="713" alt="Screenshot 2021-01-26 at 15 22 53" src="https://user-images.githubusercontent.com/10242207/105860159-949ae880-5fed-11eb-9073-7b1b756151b6.png">

**Comment by vanlummelhuizen** [comment]
I think all of this is caused by the fact that you visit https://signbank.CLS.ru.nl while the lookup of the Lemma ID Gloss is done using https://signbank.SCIENCE.ru.nl. Quick workaround: visit the latter.

I will now try to also fix this permanently.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I think I fixed it already. 

First a bit more info: in the field Lemma ID Gloss you can search for an existing lemma. The options are given in a list below the field if there are any. You can choose a lemma from that list. 

The problem was that the list of options was made dynamically as you type. But because of the difference between the url you visited and the url used for the lookup the list never got any data. 

I now removed the host part of the url that was used for the lookup, so that the host that was visited is used. This solved it.

**Comment by ocrasborn** [comment]
Ah great @vanlummelhuizen !
Did you check by any chance whether there were more hard-coded instances of signbank.SCIENCE.ru.nl that could be similarly fixed?

**Comment by vanlummelhuizen** [comment]
I just did. There are a few places that have the 'science' url hard coded. They are all related to the reload_signbank functionality, which won't affect normal users.

However, there is also a URL setting with value 'https://signbank.science.ru.nl/'. This setting is used quite a number of times. I cannot say at this point how this affects normal users. If it does, we either could decide for either 'science' or 'cls' and redirect one to the other, or we could try to make both equally usable. The latter would probably involve a request based URL value.

**Comment by ocrasborn** [comment]
@Woseseltops , what do you think about this? Me, I would prefer consistently using CLS for the users; it would seem to be easier to also use that under the hood, but perhaps there are other considerations.

**Comment by susanodd** [comment]
Regarding the screenshot above, that's my coding. The error message is in the "messages" feature.
(That was to avoid crashing. Because the Dataset is retrieved from the Lemma, sometimes odd mismatches were arising.)

Once upon a time, the Lemma Update page was supposed to have a link back to the Gloss that you were editing.
Either that, **or** the Lemma List page where you can also "update" the lemma.

@vanlummelhuizen didn't like the (my) use of separate urls for these two functionalities.
These ended up merging into one.
It looks like the "return to the page you were on before updating the lemma" isn't there.
@vanlummelhuizen ?
(Since you removed the original solution. It apparently was ambiguous for Django. There is supposed to be a link back to either the Lemma List (page) or to the Gloss.)

**Comment by susanodd** [comment]
In one evolution of the Lemma Update code, it was looking at the HTTP that had been used in order to determine where it had been called from.
(Context sensitive. Perhaps something like that could be saved in Settings? To keep track of the last couple of things a user has been doing. Was that an Issue? Gloss edits are saved in Gloss History.)

**Comment by susanodd** [comment]
Okay.
@ocrasborn had mentioned that the page was not helpful: "out of the loop of creating a new annotation gloss"
Is it working now?

**Comment by ocrasborn** [comment]
It works, *almost*! Just typing in signbank.science.ru.nl redirects (quickly!) to the cls url, but when I try to test what happens if I type in signbank.science.ru.nl/anypath, it redirects to signbank.science.ru.nlanypath. This situation will only arise when people have included direct links to, say, their dataset info page somewhere on the web, so not too often, but let's correct this all the same.

**Comment by Woseseltops** [comment]
This is managed by C&CZ these days, I'll email them.

**Comment by Woseseltops** [comment]
Fixed!
