### ISSUE TITLE
Display compound parts in correct order at top of Detail View

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#721]
* This is an oddity we hadn't noticed before: if we first enter Compound Part 2, and later add Compound Part 1, they are not displayed in the correct order to the right of the Annotation ID Gloss in the Detail View. In the Morphology panel, however they are correctly sorted.
* Please adjust this so that Compound Part 1 always comes before Compound Part 2, Part 2 before Part 3, etc.
* (In practice, this occurs quite often: annotators immediately recognise the second part of a compound, start by entering that to have it off of their mind/list, and later discover what the first part should be. Or, they realise that the first part was not yet in the database, they create a new Annotation ID Gloss for it, and only then can link it as the Compound Part 1.)

![pastedImage](https://user-images.githubusercontent.com/10242207/106355624-843e8280-62f9-11eb-9987-b60a6ac4e368.png)

**Comment by susanodd** [comment]
I'm not able to repeat this error on my local server.

I tried to find a similar gloss by searching on glosses with Component 2.

Then I tried adding components to a test gloss. When doing that I got an error with the datasets.
I had all the datasets selected and it wasn't working to "typeahead" to choose any Gloss.
(Because there aren't very many glosses in tstMH. Probably some tip is needed if it's not working to find any glosses, since you can't just type in a gloss name, but have to know what they start with.)

Then I started adding and deleting components on a test gloss in NGT.
But they keep being sorted according to component in that preview area. No matter how I chose components, they kept getting sorting by Component, not by the gloss annotation.

@ocrasborn, can you try to do this on a test gloss to repeat the error?

**Comment by susanodd** [comment]
Okay, I seem to have fixed this while trying to debug it.
It is working okay now. At first, I thought it wasn't broken.

I had added some extra variables in the template to force it to evaluate the query before the loop.
Plus an order by 'role'.

It's solved. To check this,
in the "color preview" template, that still showed them unsorted, as you describe.
I will revise that the same way.

**Comment by susanodd** [comment]
BEFORE FIX:

![wesseltest10-preview-PRE](https://user-images.githubusercontent.com/24272544/106890272-5e462300-66e9-11eb-921b-c91c23aeb993.png)

**Comment by susanodd** [comment]
AFTER FIX:

![wesseltest10-preview-POST](https://user-images.githubusercontent.com/24272544/106890324-70c05c80-66e9-11eb-8faf-3a10415f93c5.png)

**Comment by susanodd** [comment]
@vanlummelhuizen, could you pull theoddbranch to the master?

**Comment by susanodd** [comment]
This issue is complete.

**Comment by Woseseltops** [comment]
Hey, @susanodd , you now have:

```
{% with gloss.parent_glosses.all as components %}
{% with components|dictsort:"role" as sorted_components %}
{% for component in sorted_components %}
```

Would this also work?

```
{% for component in gloss.parent_glosses.all|dictsort:"role" %}
```

While normally creating variables for intermediary steps creates more clarity (you 'name' things), in the template language this creates so much extra fluff that it actually becomes less readable in my personal opinion, so that's why I ask.

**Comment by susanodd** [comment]
I'll try it out. It looks much better that way.

Sometimes Django seems to evaluate things lazily that are in the context data.
That's happened a lot with queries that have not been evaluated yet.
So I end up writing the code that way to force it to evaluate things. It didn't work to sort them in the python part.
