### ISSUE TITLE
Use field value colours in pull-down menus the Edit mode

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#726]
Values are specified under the Settings menu by Admins, see #693 , but they do not yet appear when people are editing a sign.

**Comment by susanodd** [comment]
So far the colors only appear on the Settings Color Management page and the Settings Gloss List Search (#727) (and its results pages).

When colours are set for field choices, they are (already) stored in the FieldChoice objects.
But they are currently only displayed in the Settings pages, and the Gloss Detail Preview pages, which are the same as the normal Gloss Detail pages, but with colours.

For #727, the addition of colors to the Search pull-downs was more straightforward, because it doesn't mix with ajax update calls (which are done in Gloss Detail editing). This ought to be easier to add everywhere search pull-downs are shown.

@ocrasborn, do you need any kind of switch for turning colours on and off?

**Comment by susanodd** [comment]
TO SELF: This issue involves making colours visible in the normal Gloss Edit page, not just in the Settings Preview.

**Comment by susanodd** [comment]
I modified the Gloss Edit with colours so that if a field is empty, it shows up as ------ instead of None in the select button.

**Comment by susanodd** [comment]
This is working. I revised the Weak Prop and Weak Drop menu's so their width is more condensed in the layout.

**Comment by susanodd** [comment]
Here's the colors in the normal Gloss Edit

![gloss-edit-orientation-colors](https://user-images.githubusercontent.com/24272544/119470003-2d493700-bd48-11eb-9805-a810f51e1f4b.png)

**Comment by susanodd** [comment]
Here is what the steps of editing WD look like. I fixed the preview and width display. (That's in the javascript so it works in both the preview page and the Gloss Edit.)

![gloss-edit-wd-dashed](https://user-images.githubusercontent.com/24272544/119470236-6e414b80-bd48-11eb-91af-92f94c939631.png)

![gloss-edit-wd-neutral](https://user-images.githubusercontent.com/24272544/119470280-7a2d0d80-bd48-11eb-90c3-d13e450895f5.png)

![gloss-edit-wd-pulldown](https://user-images.githubusercontent.com/24272544/119470300-7f8a5800-bd48-11eb-84a5-023d4d474590.png)

**Comment by susanodd** [comment]
The previews of the (dynamically generated dropdown with colours) were showing up as None before being clicked upon.
That's been refined as shown above.

**Comment by susanodd** [comment]
I revised Morpheme Detail Edit View to use colours as well.

**Comment by susanodd** [comment]
While working on setting up colours in the pull-downs in the Morpheme Edit View.....
I came across some bugs with Tags on Morphemes, both in the Edit View and in the Morpheme List Search View.
Basically, it was not possible to add tags, and once that was repaired, it wasn't possible to search on them.
I have fixed both of these!
.
Question: @vanlummelhuizen @Woseseltops @ocrasborn 
Do I need to make an explicit issue for this?

**Comment by susanodd** [comment]
This has been pushed to branch colours_726_727

**Comment by susanodd** [comment]
This has been revised to hide an already open pull-down list when the user opens a different list; it is assumed the user has forgotten to select Cancel on the previous list.

**Comment by susanodd** [comment]
@ocrasborn could you see if this issue is already to close?

**Comment by susanodd** [comment]
This is live.
