### ISSUE TITLE
Use field value colours in pull-down menus in the search form

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#727]
So please make it cf. https://signbank.cls.ru.nl/settings/glosslist_colors/ (created for #693 ), but ensure that the enhanced keyboard navigation (#140 ) is kept intact.

**Comment by susanodd** [comment]
I've got this working!!!


![gloss-list-colors-select2-pulldown](https://user-images.githubusercontent.com/24272544/108994451-1a1cc180-769c-11eb-9834-4c6fd9ba2807.png)

**Comment by susanodd** [comment]
Once selected, they're just normal as before.

**Comment by ocrasborn** [comment]
Well done @susanodd ! Now you mention it, I realise we hadn't discussed this yet, but it was my intention that indeed the colours should only be visible when the menu is open, not after a value has been selected and edit mode is off.

**Comment by susanodd** [comment]
Here is the new solution that does not modify the select2 javascript.
It looks a bit cheesy.

![select2-span-height30px](https://user-images.githubusercontent.com/24272544/110102953-a66a6b00-7da5-11eb-8286-c0bddba0049a.png)

**Comment by susanodd** [comment]
This new solution is on github.
Kindly put theoddbranch live @vanlummelhuizen .

**Comment by Woseseltops** [comment]
You are now overriding the select 2 dependency instead of changing it, right @susanodd ? 

Furthermore, I noticed there are still a number of ``<!-- commented lines --> `` in the commits, I guess it's cleaner to remove these?

**Comment by susanodd** [comment]
I originally modified the select2 javascript source code.
The "solution" is now is one of the parameters that are given when the select2 is created.
(It doesn't override anything, it's an optional parameter.)

It's basically the same solution, except it had to be coded in a different way.
I left the commented out console logs in the code, because @vanlummelhuizen didn't like the original solution.
The new solution looks a bit like magic, but I already knew how the select2 javascript works.

I assumed @vanlummelhuizen was going to try out the code on his own server, and it seemed easier to just leave the console logs there so he could examine it.
I'll remove the comments if you want.

**Comment by ocrasborn** [comment]
It works like a charm, but now we still have the odd situation that to see the colours you need to go to the Settings menu instead of to the Signs menu, where users normally select Search. Can't we just discard the Preview Gloss Colors Search page, and instead use the colours in the regular search page, @susanodd ? Or is there another function of the Preview page that I'm missing, and do we simply need to link to that page also from the menu item Signs > Search?

**Comment by susanodd** [comment]
I'll check what @vanlummelhuizen is doing with FieldChoice translations. That keeps being almost ready.
This issue was intentionally kept on separate pages to avoid side effects on the rest of the site.
If it's okay with @vanlummelhuizen and @Woseseltops and doesn't interfere with their work, then it's good.

You're right, it's basically the same page, so it should be easy to modify. Perhaps just in the urls. But that requires a github update rather than just in the pages admin.
There are some differences. I trimmed down the Preview Search so it doesn't show e.g.,  grouping by Lemma's.

**Comment by susanodd** [comment]
@ocrasborn I got this done. Fairly straightforward. I only needed to change the Gloss List template.

I'll do it for the Morpheme List search too since it shares the multiple select fields.

Will you need this functionality for Handshapes?
At the moment, the Handshape Search is not multiple select, so it's just normal pulldowns. (There are five such fields, after the finger selection panels.)
It would be easiest to modify those to be multiple select pulldowns first. Then after that, adding colours to the search query area would be done the same way as for Gloss List Search..

**Comment by susanodd** [comment]
Okay, the Gloss Search and Morpheme Search both have colours now.

I'm waiting until branch  `lemmas_minimalpairs_733_743` has been reviewed merged so I can spawn a new branch for this issue.

**Comment by susanodd** [comment]
![gloss-search-with-colours](https://user-images.githubusercontent.com/24272544/119471355-806fb980-bd49-11eb-9d6e-388da068a4d4.png)

**Comment by susanodd** [comment]
This has been pushed to branch colours_726_727

**Comment by susanodd** [comment]
@ocrasborn could you see if this issue is okay to be closed?

**Comment by susanodd** [comment]
This is live.
