### ISSUE TITLE
Field value colour implementation blocks creating new field choice values in admin

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#729]
Now there's a field 'field color' for field values, I cannot add or change field choice values in the admin anymore: whatever I add, I get an error upon saving: "Enter a valid color". The values that are already there (like c4ffc4) are also considered invalid. A new field choice value I add has ffffff filled in by default, but that too will generate the error.

**Comment by susanodd** [comment]
The problem is in the admin, the Django automated form is showing the Field color field of a FieldChoice object as input type text instead of color.

**Comment by susanodd** [comment]
I got the colour picker in the admin.


![admin-field-color-picker](https://user-images.githubusercontent.com/24272544/109519862-eda5e280-7aab-11eb-8250-fef4cbc53e29.png)

**Comment by vanlummelhuizen** [comment]
On the live server, there is indeed no color picker. @susanodd any idea why this is the case?

Apparently, the hexadecimal notation of the RGB color. e.g. ffffff for white, needs to be prepended by a number sign (#), so for white #ffffff. You can use this a work around.

**Comment by susanodd** [comment]
I fixed this. I had to make a special form element for it.
I'll upload it shortly.
In the display, the colors need the # before the hex code.
But in the database, this is not used.

On inspection in the browser (in the other issues involving colors the past months), sometimes the browser uses the rgb(..) format, other times the # format with only 3 hex's. (Maybe 32 bit versus 64 bit?)
I siuspect something may also happen if the color picker is not used, because it's otherwise possible to construct colors that can't be displayed. (The browsers may convert things to web safe colors.)

**Comment by vanlummelhuizen** [comment]
@susanodd In the meantime I found out why there is no color picker on the live server: the Javascripts for the color field could not be loaded. I am now looking into why.

So your fix may not be necessary. What does it entail?

**Comment by susanodd** [comment]
Oh, see what happens.

In the browser source, the "input" field for field_color has type "text".
That must be "color".
I did that, but then it still wasn't giving a color picker.

Here is what I added (in a new FieldChoiceAdmin class, in order to create a form) in admin.py:

`self.fields['field_color'].widget = forms.TextInput(attrs={'type': 'color'})`

**Comment by susanodd** [comment]
Yeah, it's a bit longer. But that is what has to change in the template.

But the actual obj.save also needs to remove the # from the color.
That is also done in update.py in the update code for field choices.
(Don't ask why!)

I'm working on this still. I tried to set the default color of the color picker, but ended up messing the update again.

**Comment by vanlummelhuizen** [comment]
@susanodd I just made the Javascripts loadable. This results in a text field containing `#FFFFFF` with a background of the same color (white inittially) and when you click on it, a color picker is shown. No problem when saving.

**Comment by susanodd** [comment]
Okay! Did you check that it still displays on subsequent loads? And inside the Settings Management page?

**Comment by vanlummelhuizen** [comment]
If you set a color in the admin it displays correctly if you re-edit the FieldChoice. However, on the page Manage Field Choice Colors the color #FF60A8 (sort of pink) is displayed as black #000000.

**Comment by susanodd** [comment]
That's the # causing the problem. (I wrote about it above.)
There is a quirk in the way colors work. The # character can't be inside the database, only the actual "hex" part.
Because the browser also shows them as rgb(0,0,0) sometimes, there can't be a # character in the value representation.

This is what I had (analogous to what is done in update.py):

```
        # the color in the database needs to be without the #, which is for display
        new_color = form.cleaned_data['field_color']
        if new_color[0] == '#':
            new_color = new_color[1:]
        obj.field_color = new_color
        obj.save()
```
I wasn't finished before you got the colorpicker working. It was interfering with the initial value setting of the widget.

**Comment by susanodd** [comment]
The things stored in the database are colors, not string representations of colors.
(Although technically everything in the database is strings.)
The color picker is used to ensure the type of the "thing" constructed is a color, rather than just a code.

**Comment by vanlummelhuizen** [comment]
When changing the color in the admin, it is retained after saving and going to edit FieldChoice again. The new color is not correctly displayed on the page Manage Field Choice Colors.

The other way around, changing the color on the page Manage Field Choice Colors, the color is also correctly displayed on de FieldChoice edit page in admin.

**Comment by susanodd** [comment]
It's the # character. The admin is storing that. If you display what the admin is doing, you can see it's there.

**Comment by susanodd** [comment]
Do you want me to work on this?
I kept the colors separate and didn't do anything with the admin. I thought it was user friendly to have the Management page.

On my local server, the admin doesn't work to update field choices. (It's broken as is this issue.)
The admin on my local server is missing a lot of markup things.

**Comment by vanlummelhuizen** [comment]
The problem now is that there is also a workaround in place for the Summernote problem, see #730. I think for now, FieldChoices can be created without any problem and setting the color should be done on the page Manage Field Choice Colors. Your fix can be deployed when we merge your work into master.

**Comment by susanodd** [comment]
Okay. I started inspecting what the admin is actually doing on my local server.
For some reason the original code is calling its get_form method three times on loading a field choice (admin edit) page.
That seems a bit strange. It's subclassed on VersionAdmin.

**Comment by susanodd** [comment]
@vanlummelhuizen, on my local signbank admin, I noticed the same things of javascript not being found, as you pointed out.

It looks like perhaps the INSTALLED_APPS should have 'django_admin' instead of 'django.contrib.admin' ?

(That's in the description of django-admin 2.0.1 on pypi.org. That's what's installed in my virtual environment.)

**Comment by susanodd** [comment]
I've got it working!
Although the solution perhaps isn't so elegant 
But it works in the admin and the admin doesn't mess up the management page, and vice versa.

**Comment by susanodd** [comment]
I've got it working!
Although the solution perhaps isn't so elegant 
But it works in the admin and the admin doesn't mess up the management page, and vice versa.

**Comment by susanodd** [comment]
I'm working on the Add New FieldChoice now.

![admin-add-field-choice](https://user-images.githubusercontent.com/24272544/109969900-bbd38c80-7cf4-11eb-87b3-255f66c48d85.png)


It looks like there are no database constraints except for on machine_value, (which is generated automatically).

(On my local server), I was about to create a new SemField choice called Sport.
Only to discover that there already exists such a choice!
(I thought it was magic, because Chinese was filled in, but I hadn't filled that in.)

The new Sport has a new machine_value, of course.
And it has color white. (The default color.)
The color is what I was checking.

I revised the Add FieldChoice in Admin so that the particular field category is initialised to what you are adding.
(See screenshot showing SemField)

I'm guess there needs to be a check whether the new one already exists? @ocrasborn ?

**Comment by ocrasborn** [comment]
Yes, that would be helpful, @susanodd , checking for already existing values to prevent double entries.
BTW, I was able to add a field choice yesterday, the default colour was now appearing as #ffffff, and all went well. So I was under the impression that this issue was already finished; not so?

**Comment by susanodd** [comment]
I would recommend still using the Management page to update colours.
There is a glitch with the admin as far as I can tell.
For some reason it calls its code "get_form" (to set up the input form for a field choice), it calls this multiple times.
So there is sometimes an "appearing and disappearing" of the "#", which is used when colours are to be displayed.

The Admin uses VersionAdmin, which makes it possible to show change history.
I suspect that is doing something, but I don't know.
(Attempts to update field choices that caused errors also seem to be stored in the history. I'm concerned it will retrieve bad data from there if clicked on. I'm only doing this on my computer, not the live server!)

**Comment by susanodd** [comment]
The code now uses the setting SHOW_FIELD_CHOICE_COLORS.

**Comment by susanodd** [comment]
This has been pushed to github.

- Colors work in the admin the same way as in the rest of the site.
- The color field is hidden if the setting is turned off.
- The field category is now either filled in already, or a list of field categories is shown.
(Field categories can not be created by the user, only choices within a category.)
- There is a check that the particular field choice for the category does not already exist.

**Comment by susanodd** [comment]
Tests on Admin FieldChoice all work.

**Comment by Woseseltops** [comment]
I noticed that in ``dictionary/admin.py``, you are using ``form.__dict__['base_fields']`` a number of times... Perhaps a ``base_fields = form.__dict__['base_fields']`` somewhere near the beginning would make things more readable?
