### ISSUE TITLE
"PermissionError" making system unusable

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#730]
It appears on almost anything we do. Sometimes reloading generates the 'closed database' issue, but reloading the page upon that one gets me back to the permission error.

**Comment by vanlummelhuizen** [comment]
@ocrasborn I saw something like this in the Admin. I am looking into to problem right now.

**Comment by vanlummelhuizen** [comment]
@ocrasborn Most of Signbank is working again. The problem was related to Summernote, a Wysiwyg editor. For now I disable it on the live server. I think this only affects the content field when editing a Page in the admin. Now you will see the text including the HTML markup instead of a formatted text.

@Woseseltops Any idea why this happened? I think the core of the problem is
```
  File "./signbank/pages/admin.py", line 7, in <module>
    from django_summernote.admin import SummernoteModelAdmin
ImportError: No module named 'django_summernote.admin'
```
as if Summernote is not in installed in the virtual environment. This import has no problem when done in a Django shell. Both the webapp and the shell seem to use the same virtual environment (/var/www/signbank/live/sb-env).

**Comment by Woseseltops** [comment]
Okay @vanlummelhuizen I discovered that the problem goes away if you don't use emperor, just uwsgi. For now, we are back to running it on your account in a screen session again. I'm thinking this is some kind of emperor bug that accidentally uses the wrong environment? Will ask C&CZ to restart.

Also, another weird thing I had to do is rename the summernote static folder to django_summernote.

**Comment by susanodd** [comment]
To my surprise this happened on my local server!!!

I have been working with the Admin Glosses and I tried to edit one of the glosses.
Up to now, I have only been scrolling. Which is absurdly slow and keeps choking.
Just now, trying to edit, my entire system froze up and the database became locked. I needed to reboot multiple times to get rid of this.

I have the impression that something is wrong with the Admin Gloss section.
I going try to forcing all fields to be read-only and merely allow to Delete a Gloss Object.
To see if it works at a normal speed.
I have the impression it's searching infinite loops of related objects.

**Comment by susanodd** [comment]
See #739 for improvements to speed of Admin Gloss.

**Comment by susanodd** [comment]
Probably this can be closed.

**Comment by vanlummelhuizen** [comment]
@susanodd I agree
