### ISSUE TITLE
HandshapeListView is used via 3 separate urls

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#732]
The HandshapeListView is reachable via

* /dictionary/handshapes/
* /signs/search_handshape/
* /handshapes/show_all/

Questions for @susanodd and @ocrasborn:
1. How do they differ technically?
2. How do they differ for the user? Can the user easily see the difference?
3. Do we need all three? Can we just use one?

**Comment by susanodd** [comment]
From memory,
At the start it was not possible to search handshapes. When this functionality was added it was analogous to signs.
There are also multiple urls for signs.
That there are two menu items for handshapes in the menu bar was @ocrasborn.

It's possible to search for handshapes and also to search for signs that use a handshape.
There is also a results bar of handshapes shown in Handshape Detail.
It's kept track of what kind of previous search was done and also to know what the results bar items should link to. Like if a user has searched on signs using a handshape, the results are signs, not handshapes.
(TO DO: The items bar code uses the Dutch name because at the start only Dutch was filled in.)

I recall that I have sometimes been attempting to use context dependent urls.
(DONE: In one of the Lemma Update issues, I finally removed an extra url -- deemed unneccessary by @vanlummelhuizen  -- because it could not "reverse".)

I will have to look into the code to see if all three are needed, but when they were constructed they fulfilled different functionalities. There was also some aspect that the handshape images had to be visible also for anonymous users.
So it could be that one url works differently because of anonymous users. (No idea if that's true.)

**Comment by susanodd** [comment]
- /handshapes/show_all/

Visible for anonymous users also. Show all handshapes does not have a search panel. The results go to handshape detail views where editing is not possible.

- /signs/search_handshape/

Signs search handshapes is in the menu bar, but if you choose that, you are prompted to log in if you are not.

**Comment by susanodd** [comment]
- /dictionary/handshapes/

That one does not look like it can be navigated to via the menus.
It looks identical to the /signs/search_handshape/ url

**Comment by susanodd** [comment]
Okay, it seems they do the same thing, except the top one is used within templates.

I suspect the different urls arose to keep new code from interfering with existing code. (aka @susanodd does this)

It's also related to whether the user is allowed to edit handshapes or not.

Handshapes existed before datasets. At the beginning handshapes were only in NGT. (They still are.)
We're going to need additional kinds of edit permissions if handshapes are in a dataset you can't edit.

Any preference on naming convention?

**Comment by susanodd** [comment]
Just a guess, I think the /dictionary/handshapes/ url is the intended one. From Handshape Detail View, it links back to that one.

**Comment by susanodd** [comment]
This url:

- /signs/search_handshape/

only appears in signbank/urls.py
and in the e-mail text sent to new users.

**Comment by susanodd** [comment]
This url:

- /handshapes/show_all/

only appears in signbank/urls.py
and as a link in handshape_detail.html when the user is anonymous.

**Comment by susanodd** [comment]
@vanlummelhuizen do you need me to do anything with this?
As described in the two comments right above this comment, It's specific usages of the two extra urls.

**Comment by susanodd** [comment]
@vanlummelhuizen There was/is a similar issue with some pages that are in the pull-down menu bar. (With the urls in the Pages in Admin).

The Admin on my PyCharm runserver did not like putting the url of `signbank/dictionary/urls.py`:
`/dictionary/semanticfields/`
underneath the Settings menu,
so the url also appears in `signbank/urls.py` as:
`/setttings/semanticfields/`

**Comment by vanlummelhuizen** [comment]
@susanodd The url under the Settings menu seems to be `/dictionary/semanticfields/`, both on the live server and in my dev environment. Therefore, I think `/setttings/semanticfields/` could and should be removed.

**Comment by susanodd** [comment]
It was supposed to become the latter. I had to add a duplicate (chicken or egg scenario). I'd prefer to remove the dictionary one and change that in Pages.

**Comment by vanlummelhuizen** [comment]
Aha, I think I understand now. Can you make it so and then close this issue?

**Comment by susanodd** [comment]
Okay, pushed to master.
