### ISSUE TITLE
User registration is broken

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#755]
Got message from two (prospective) users; could replicate it myself. Here's the error message:
![Bildschirmfoto 2021-06-09 um 18 25 54](https://user-images.githubusercontent.com/10242207/121880344-30639180-cd0e-11eb-8cb3-ca528ff4f444.png)

**Comment by susanodd** [comment]
Did you perhaps copy paste the first password?
I'm attempting to replicate on my local computer, although to avoid actually executing it, I keep leaving fields empty.
I copied the password to the other field using copy paste. I noticed that it's got longer in the second field.
(There is a password2 showing up in your screenshot, but this should not be visible. Perhaps because of the error.)

It shows the request and request.session in the error message.
But those are not accessible unless logged in. (These are still available from other windows.)

Perhaps there needs to be an additional check that the session is indeed empty.
From the error message, it appears the session variables are not empty. But they also do not have the required data.
Perhaps the session variables need to be made empty just in case somebody has already been using the system before creating an account. (@vanlummelhuizen @Woseseltops ?)

**Comment by ocrasborn** [comment]
I normally do just that, @susanodd , copy-paste passwords, but this time as I made up a temporary password for the test, I think I did not. Either way, we didn't get this error before until recently, plus: users should get friendly feedback if the passwords wouldn't match, before the form is submitted.

**Comment by susanodd** [comment]
Okay, thanks. I see what the problem is now. I tried it on Global.

**Comment by susanodd** [comment]
There is something not working with selecting datasets. The code in the form is conditional on whether SHOW_DATASET_INTERFACE_OPTIONS is set. So it only shows the dataset and motivation fields if that is set.
I repaired the error message, but now it's showing Error processing your request instead.
Although it's not crashing, that is not helpful either.

Any idea when this was last working?

**Comment by ocrasborn** [comment]
No, don't know when it was last working. The setting you mention is probably there for the ASL signbank / other mono-dataset uses.

**Comment by susanodd** [comment]
So far, I have no idea how to fix it.
The form is not valid. In spite of the validation checks, it is somehow still not valid even after passing the checks.
It then fails in a later step and gets kicked back to the form again.
This is very strange.

**Comment by susanodd** [comment]
Okay, I got it working again. I need to test it a bit more.

Since the last time this was worked on, the select2 library requires the parameter 'placeholder' on initialisation. (That was needed in some other issues, but I hadn't realised it's also used here for chosing datasets.)

I also had to remove some 'form.errors' lines in the template loginform.html (That syntax seems to be really old.)

There might have been something upgraded in wsgi? Some of the errors were complaining about this.

**Comment by susanodd** [comment]
@vanlummelhuizen @Woseseltops 
I'm working on this issue and looking at the browser console.
It's about a new user wanting to register.
In the console, I'm getting a warning about SameSite cookies changing.
(Cookie 'csrftoken' wordt binnenkort afgewezen omdat het attribuut 'SameSite' is ingesteld op 'None' of een ongeldige waarde, zonder het attribuut 'secure'.)
This seems to also relate to Django settings.
I tried searching on "SameSite" and  "_COOKIE" to see if we have these defined anywhere, but not found.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by susanodd** [comment]
I'm having a lot of trouble getting this to work.
I had it working for a while yesterday, for Registration of a new user.
But to my dismay, whatever I had done to repair it broke the normal login and I was not able to login myself anymore.
After fixing it so I could login, the Registration was broken again.

**Comment by susanodd** [comment]
@Woseseltops @vanlummelhuizen 

Is there any reason why this "next" needs to be included in the url?

https://github.com/Signbank/Global-signbank/blob/c419f836e32ee3c5d84901346ad5dd4f5e121a25/templates/global-templates/loginform.html#L9

**Comment by susanodd** [comment]
This line looks misplaced, since it's surrounding the entire code. the Sign In as well as the Register link.

https://github.com/Signbank/Global-signbank/blob/c419f836e32ee3c5d84901346ad5dd4f5e121a25/templates/global-templates/loginform.html#L5

**Comment by susanodd** [comment]
Debugging does not work for the Registration form because it's not generating any errors for the form, but it is not valid.

I removed the "session" variable code that it was (probably) complaining about in the screenshot (but that did not fix it).
https://github.com/Signbank/Global-signbank/blob/c419f836e32ee3c5d84901346ad5dd4f5e121a25/signbank/registration/forms.py#L153-L156
That code is actually already available in the template itself (the requested datasets if they've already been filled in).
https://github.com/Signbank/Global-signbank/blob/c419f836e32ee3c5d84901346ad5dd4f5e121a25/signbank/registration/templates/registration/registration_form.html#L14-L18

So I'm investigating where else the failure can be arising.

Since Registration of a new user worked, but then I was not able to login as myself anymore, something else is messed up.

Perhaps this "next" link (in paragraph above) that goes to other pages. If there are tests about whether or not the user is anonymous going on, maybe Django can't tell?

**Comment by susanodd** [comment]
This is still broken.

**Comment by susanodd** [comment]
Okay, I fixed it!

**Comment by susanodd** [comment]
This has been pushed to branch `user_registration_755`.

**Comment by Woseseltops** [comment]
This is live, just verified that you can requests accounts again!

**Comment by Woseseltops** [comment]
This time email software Postfix needed to be installed!
