### ISSUE TITLE
Add 'tags' to Revision History

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#760]
Tag editing/adding/removing is not yet listed in the revision history, but this would be helpful to us at times. (See #115 )

**Comment by susanodd** [comment]
Okay, this one is next.

**Comment by susanodd** [comment]
Here's what this looks like.


![revision_history_tags](https://user-images.githubusercontent.com/24272544/165090127-01de9e86-5ea9-4313-b1a4-d57f85a1c93e.png)


Because the table for the Gloss Revision History includes columns for field, old value, and new value, I've made the list of tags become the value.

**Comment by susanodd** [comment]
The revision history items have existed for a while. So far there isn't any conversion of already existing field into user friendly names. For the labels code I made use of Django translation as `_('Tags')`
If needed this could also be done for other fields, or it could be done in the template.
Issue #800 reveals a similar quirk in the display of the gloss revision history.

**Comment by susanodd** [comment]
I see in #115 that it looks like the intention was that the display is the "original human value".

So what about field names? These as well?

(I ask because at the moment, the stored data in the history uses the field names. This can be made user friendly during generation of the template for the interface, including translation.)

**Comment by susanodd** [comment]
Okay, I've added dynamic translation of the field names in the Gloss Revision History. The actual field names are stored in the history.


![gloss_history_fieldname_translation_en](https://user-images.githubusercontent.com/24272544/165289941-1f3502d0-087a-4251-9cfd-b7f03d03ce9e.png)

![gloss_history_fieldname_translation_nl](https://user-images.githubusercontent.com/24272544/165289973-f739d0cf-9bae-4cc9-b8a5-b6bf6a995f56.png)

**Comment by susanodd** [comment]
Regarding Tags, the set of tags is shown, before and after.
Tags is not a field, it's a relation.

At the moment, other types of modification to a gloss (i.e., relations rather than fields) are not stored in the history.
These could also be saved, although the GlossRevision has fields for `old_value` and `new_value`, which doesn't lend itself to relations. That's why it's done as shown above.

The table above could be "split" to show the history as changes to fields and to relations.

Above, the actual tags of "before" and "after" are retrieved when a tag is added or removed from a Gloss.

At this moment, this update to tags is added to the GlossRevision history. Above, this has been done by storing the before and after lists of tags (reformatted as a string). (Basically what you see in the table for `old_value` and `new_value` is stored in the GlossRevision history.)

Alternatively, some behind the scene mechanism could be used to "toggle" the tag as being added or deleted.
(E.g., instead of `old_value` being the list of tags, it would either be empty and the `new_value` be the added tag, or vice versa going the other way.) Then on retrieval from the GlossRevision history, it would be implicitly either added or removed.
Then a "relations" section of the template above could show Tags with the operation "Add" or "Delete" and the relevant Tag.
This would avoid duplicating the entire list of tags.

**Comment by susanodd** [comment]
Here is the user friendlier looking gloss history for weak drop and weak prop and booleans. (Related to issue #800)


![gloss_history_weak_drop_prop_friendly](https://user-images.githubusercontent.com/24272544/165315317-c724f1b5-f589-4148-8288-812b3826a41f.png)

**Comment by susanodd** [comment]
This has been pushed to branch `weakdrop_neutral` because they both concern GlossHistory objects and the display of the Revision History template.

**Comment by Woseseltops** [comment]
Hey @susanodd , looks good! Would it be a lot of work to make tags look like like they do in the detail view? Because if not, that would be cool :) .

About your question, I like your suggestion

> Perhaps the most user friendly would be to put the field in parentheses next to the human translation. (Field column)

**Comment by susanodd** [comment]
Here's what it looks like now.


![tags_gloss_history](https://user-images.githubusercontent.com/24272544/165754387-9b1fb5ec-15bd-4df8-999f-463e4a03abab.png)

**Comment by susanodd** [comment]
Here's what it looks like with the actual field name in parentheses. When the field is Tags, the operation is shown. The translations annotating the Tags (Labels) are shown as used in the interface (caps or non-caps, the translations only exist in this form, since that's how it's been defined elsewhere.)

![revision-history-labels-field](https://user-images.githubusercontent.com/24272544/165764108-612e8820-8477-4b3e-8081-a6b9490eef74.png)

![revision-history-tags-field](https://user-images.githubusercontent.com/24272544/165764382-a80fb72d-0da4-40eb-889b-794d18b78f0a.png)

**Comment by susanodd** [comment]
The values (other than Tags) for the old value and new value are as they appear in the GlossRevision objects. They were translated to human values upon storage. That's why those above are in Dutch in both screenshots.
They reveal the original interface language the user who made the change was using at the time.
I'm not sure about translating these. (Is this needed?) 
If we'd change the GlossRevision to merely store the "machine value" of the choice, then translate it dynamically in the view above, this could have a weird side effect if the field choice was somehow changed in the time between.

**Comment by susanodd** [comment]
This is live now.
