### ISSUE TITLE
Make the CSV import more user friendly

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#761]
The CSV import already contains some functionality to detect any problems the user may have accidentally introduced, but there are still many other things that could be 'caught' by Signbank. I just tried to import a Catalan file, and these things would have helped me:

* Verify that the filename ends in .csv. If not, suggest that the user uploads a CSV. Current behavior: encoding error.
* If there encoding errors (because the CSV is not a UTF-8 file), explain how the user can user Notepad++ to convert. Current behavior: Django error page.
* Check for extra empty row, and automatically ignore them. Current behavior: complains about missing dataset information.

**Comment by ocrasborn** [comment]
Re: bullet 2: on Mac I always use LibreOffice for this, Excel/Mac's CSV output is not accepted; I'm assuming that's also a file encoding issue. So if that's indeed the case, please add this suggestion for Mac users in the feedback.

**Comment by susanodd** [comment]
This is also relevant for the metadata file of Issue #756.

@Woseseltops what is the naming convention for a CSV file that uses tabs?

**Comment by susanodd** [comment]
I've revised the CSV import routine for issue #756 to use the Python Sniffer to determine the separation character. I'll do that for this one, too.

One caveat for skipping empty rows, I once had a LibreOffice file problem where LibreOffice was not able to detect the end of the file. It got into an infinite loop when trying to open the file. You could scroll down in the window of LibreOffice and there was no end, all the rows were empty but it couldn't find the end. With the spinning timer symbol that it was still loading.
This had something to do with importing files made on a different system, which either had special characters in the cells or somehow a different line break or missing an end of document symbol. We were using NULL values in the database at one time.
So I'm a bit weary of skipping empty rows rather than just stop when the first empty row is encountered.

The Python Sniffer routine, so far it works. Although I just realised it's making use of a readline() to inspect the header row. (To identify the separator. There are other code examples in the documentation that specify a number of bytes to read. But that actually didn't work because it was spanning multiple rows and couldn't identify a separator.)

What I've done is to include a <code> element in the template for creating a Corpus, with the header row for Metadata for Speakers for EAFs so the users can copy that to start with.
(@ocrasborn will need to approve something like that.)

**Comment by susanodd** [comment]
I'm working on this issue now.

**Comment by susanodd** [comment]
I've modified the file input field of the three upload csv templates to only accept various csv encodings 
(as recognised by html input). 
This makes it only show csv files in the file browser selection window.
(So e.g., it's no longer possible to choose a pdf file. Once the changes are live, of course.)

There is already a selector for choosing the delimiter.

I need to create sneaky test files that pretend to be csv now and try to fool the code.

**Comment by susanodd** [comment]
Okay, I managed to create some bogus files.

Here is what the feedback to the user looks like. The first is a non-`UTF-8` encoding (I created a file with Arabic letters and saved it in a different format in LibreOffice.
The other feedback is for a `.pdf` file that was renamed to end with `.csv` instead. (The code actually can determine this is really a pdf file. Although telling the user this probably isn't necessary.)


![import_csv_encoding_feedback](https://user-images.githubusercontent.com/24272544/158405532-d8a4b282-0f74-4065-a6ee-7d275219a4b5.png)


![import_csv_unrecognised_format](https://user-images.githubusercontent.com/24272544/158406037-64ce5761-5308-4a0f-aefd-96dfa7c5749a.png)

**Comment by susanodd** [comment]
It works to use the Python module `chardet` to determine the encoding of a non-utf-8 encoded text file.
This makes the import even more user friendly!
Although in doing so the Python code of the template has become less user friendly given all the exception handling...
(@Woseseltops I'll fix this.)

**Comment by susanodd** [comment]
Inferring the encoding when not utf-8 is more tricky that at first assumed.
It only works part of the time.
I have an example file from @ocrasborn that is either Turkish, French, or Arabic. It looks like the language is French, but it's encoded as being Turkish. But this causes the built-in decoders to malfunction.
This seems best if the user encodes it as UTF-8 themself.

**Comment by susanodd** [comment]
Oops, I put the wrong issue in my push. That should have been #793

**Comment by susanodd** [comment]
This issue has been resolved as described in the bullets above.

Some test csv files with unknown character encoding (supplied by @ocrasborn) could not be guessed correctly by the available Python modules. However, the LibreOffice spreadsheet software was able to correctly determine this and decode into UTF-8.

As the CSV Import is done now, an error message is shown to the user if the CSV has an unrecognised format.
This seems okay, as the main problem with "python intelligent guessing" is that a human still needs to inspect whatever data is deciphered to make sure it's not nonsense.

**Comment by susanodd** [comment]
@ocrasborn identified an error with the delimiter not being recognised in the Header of Apple (Numbers) files.
This has been repaired for Import CSV Update.
The file wasn't exactly a Numbers file, but on MacOS, the OS recognised the file as being a Numbers file for some reason.

**Comment by susanodd** [comment]
I'm not sure whether this is live yet. It's merged into the master branch.
@ocrasborn can you try your csv update file again that was causing problems?

**Comment by susanodd** [comment]
This is live now.
