### ISSUE TITLE
I can't access GlobalSignBank at all 

### ISSUE THREAD

**Issue by rosestamp** [Signbank/Global-signbank#766]
I can't access GlobalSignBank at all. Is it down?
The following error appears:
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by susanodd** [comment]
Still not working.

**Comment by ocrasborn** [comment]
@Woseseltops , it might be useful to enable the reload URL again for me, so I can at least run that when no system admin is available to look into the matter -- although of course I don't know whether that would solve the issue in this particular case.

**Comment by susanodd** [comment]
I tried the science url too. I get a security warning message in the browser.

**Comment by Woseseltops** [comment]
Hi everyone, I sent Onno an email about this earlier, but I guess he missed it because of his vacation. The Signbank installation on Applejack is down, already for quite a few days, and after many hours I have given up trying to get it back online. Instead, I have installed it inside a container on Lightning (another server) successfully this morning. I'm currently moving the writable files (videos, images, etc), and if all goes well it should be back online today or tomorrow.

In case you're curious, what happened is that 4 cases of personal and work-related bad luck all happened at the same time:
* We were notified that the OS on Applejack was no longer supported and thus a security risk, and needed to be upgraded quickly.
* Totally unexpected for me, the new OS brought a new version of Python that was no longer compatible with Django 1.11, which we are using for Signbank.
* At home, I have to care for a 2 year old and 1 month old alone (my wife still not able to walk, sit or stand), giving me zero options to work extra hours and thus shorten the downtime. 
* Micha, as my backup, is unavailable for a long time because of illness.

What I learned for next time is that I should always check compatibility between OS, Python and Django versions before I accept an upgrade.

**Comment by susanodd** [comment]
Best wishes @Woseseltops

**Comment by Woseseltops** [comment]
Thanks Susan! 

Took yet a few more hours than I thought, but Signbank is up again, now running on another server! I sometimes get the impression that the performance is not as good here, but we'll see.

Related practical thing: the next 5 weeks I will be unavailable due to parental leave. If there are more severe problems, @ocrasborn has my phone number (and otherwise Henk has).

**Comment by rosestamp** [comment]
Hi, I don't know if it's only me but I still can't access the website for the following reason:
Your connection is not private
Attackers might be trying to steal your information from signbank.science.ru.nl (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

But I don't have problems on other websites. I tried with Chrome and Safari, same issue.

**Comment by susanodd** [comment]
Did you try the signbank.cls.ru.nl  ?
