### ISSUE TITLE
[updated] Cron job for frequency counts not yet working well

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#769]
I get no daily log mails anymore; see also @susanodd 's comment in #602

**Comment by vanlummelhuizen** [comment]
@ocrasborn Was it your crontab we used for these jobs? The crontab was gone, as was mine, due to the server upgrade. I asked the admin to recover them. I will send you an email about how to put it back.

**Comment by susanodd** [comment]
@vanlummelhuizen @Woseseltops there will need to be cron jobs for the EAF files for all datasets.
At the moment, the CNGT is done by these urls (or maybe not):

https://github.com/Signbank/Global-signbank/blob/94dbe93ee7552b7d9cd19416ee29b86d5d18dd61/signbank/dictionary/urls.py#L88-L89

To my surprise, those functions are no longer in the code.

In any case, i have a similar functionality for a dataset:

`def update_corpus_counts(dataset_acronym=None):`

This is invoked by a button on a DatasetFrequency template for a corpus.

How to organise cron jobs for this?

**Comment by ocrasborn** [comment]
@Woseseltops, Daily logs are coming in fine, but two report errors right now: write_ecv_files_for_all_datasets and configure_corpus_documents lead to errors.

For the first: 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

For the second: 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

(So Backups and corpusEcvUpdater are doing fine)

**Comment by Woseseltops** [comment]
Ah, I never had a good look at the cronjobs, but they were still referring to the old installation, not the Lightning container one. I have now moved `write_ecv_files_for_all_datasets` into the container, let me know if this works!

As for `configure_corpus_documents`, as part of of recent refactor this is now in `frequency.py`, and seems to need a corpus acronym as an argument. I guess the cronjob should work for all corpora, right? @susanodd , do you think it would be a good solution to make this argument optional, and that the default is to just do all corpora?

Also, @susanodd, was this the issue you were talking about yesterday?

**Comment by susanodd** [comment]
Yes, this is what I was talking about yesterday.

There should already be eaf files and the metadata file stored for NGT.here:

https://github.com/Signbank/Global-signbank/blob/e145fc9b10c46e137447c9827957aad48274ad94/signbank/settings/server_specific/default.py#L19-L20

**Comment by susanodd** [comment]
On my local server they are shown here:

![corpus-overview-ngt](https://user-images.githubusercontent.com/24272544/150525870-0e26f590-877f-4bfa-ad2e-3bd052ed24f3.png)

**Comment by susanodd** [comment]
This is the same location where files are uploaded to on the Dataset Manager page. That's where it's looking.

**Comment by susanodd** [comment]
I'm not sure about the argument. We only ever had the cron job for NGT.

**Comment by susanodd** [comment]
Can you first put the eaf files from the old server there to see what already exists?
I don't really know if managers were already putting files for other datasets yet?
But there is already frequency data for NGT so the files ought to be there.

**Comment by susanodd** [comment]
![dataset-manager-ngt](https://user-images.githubusercontent.com/24272544/150527131-65b5f1d3-e44c-4e9c-a5ab-fe834339d1a2.png)

**Comment by susanodd** [comment]
I'm not a manager on the live server.

**Comment by Woseseltops** [comment]
Okay @susanodd , sorry it took me so long to understand you, but the EAF files are finally usable on the new server. 

For completeness, the files actually already were on the new server, the settings file just wasn't pointing to them. I now moved the files to where the settings were pointing (cleaner than the other way around :) ) .

**Comment by Woseseltops** [comment]
> I'm not sure about the argument. We only ever had the cron job for NGT.

But now there are also EAF files for BalHS and BaliHS, so we need to take that into account. What do you think would be the best solution @susanodd ?

**Comment by susanodd** [comment]
The folder should match the dataset acronym.
https://signbank.cls.ru.nl/datasets/BaliHS
So it should be BaliHS

TO DO:
There will need to be some code in the Dataset Update View for when a user modifies the acronym.
This is probably already done elsewhere because the acronym is also used as a folder for images and videos.
Nope, it would seem this is not done. One can freely modify the dataset acronym:
https://github.com/Signbank/Global-signbank/blob/7b8fe899c16a8a9779f32254d4f25c2a1df76c6a/signbank/dictionary/update.py#L2091-L2095
So the metadata filename and folder related to EAFs may or may not need to be revised at the same place when an acronym is modified.

For NGT, it's showing on the Corpus Overview that there is no metadata file:
https://signbank.cls.ru.nl/datasets/frequency/5
The metadata files belong under the folder DATASET_METADATA_DIRECTORY
There are no subfolders.

**Comment by susanodd** [comment]
@Woseseltops, there ought to be a meta data file for NGT at the following location:

writable/metadata_eafs/NGT_metadata.csv

Can you check if this is still residing someplace else on the new server?
The Corpus Overview for NGT (accessible via the Dataset Detail page) still shows this file as missing.

**Comment by susanodd** [comment]
I'm nearly finished with the subfolders addition. (#793 )
In doing so, I've processing all the CNGT subfolders. It's quite time consuming.
(On the Corpus Overview page there are buttons for processing individual documents to ease this.)
There are quite a lot of CNGT files with no annotations. I can't yet tell whether this is slowing it down.
It may because there is some overhead in preparing a file for processing.

**Comment by susanodd** [comment]
I've made a new url `update_corpora` for updating all corpora as a cron job.

**Comment by susanodd** [comment]
@Woseseltops does this seem to be working now?

I'm working on #703 right now and I've come across two "stub" functions for corpus frequencies.
(They basically only call other functions.)
These include many untranslated texts.

https://github.com/Signbank/Global-signbank/blob/5a6317b04d92838886cd15ebbcf699e816147b73/signbank/dictionary/views.py#L2581

https://github.com/Signbank/Global-signbank/blob/5a6317b04d92838886cd15ebbcf699e816147b73/signbank/dictionary/views.py#L2600

I am considering making a template for these in order to do the translations.
However, at the moment, I can't tell if these are actually being used?
There are newer functions in frequency.py.
These functions basically check a bunch of stuff then call the other functions.

Thus I'm wondering if these were meant to support cron jobs?
They basically make the functions get their argument via the url instead of being called as a function.

**Comment by susanodd** [comment]
I determined that these two functions are not being used anymore.
Issue #703 is deleting these functions rather than creating translations in templates, since the code isn't being used.

**Comment by susanodd** [comment]
@ocrasborn sent me the error log so I could see what the problem is.
I'm revising the code so it works properly with the cron job invocation as its written.

**Comment by susanodd** [comment]
The function called by the cron job for frequency counts has been repaired.

**Comment by susanodd** [comment]
I ran the tests and fixed a bug in the CRUD tests with keywords. Now the tests only generate the long existing failure with the settings files.
https://github.com/Signbank/Global-signbank/blob/e9fc1ded695003f5113484c85efcf1bfb01d3407/signbank/dictionary/tests.py#L2401

**Comment by susanodd** [comment]
I pushed this onto the master branch.
The code has been checked with the develop.py call of the function on my local server with the entire NGT folder, with subfolders of eaf files.

**Comment by susanodd** [comment]
This no longer generates an error.

**Comment by vanlummelhuizen** [comment]
@susanodd So this issue can be closed?

**Comment by susanodd** [comment]
Yes, this can be closed. :)
