### ISSUE TITLE
Make menu item 'Select datasets' available to anonymous users

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#780]
Now that more dataset managers are making data available to the public, it becomes desirable to have anonymous users also select a specific dataset. Please make that menu item available to them.

**Comment by susanodd** [comment]
![anonymous_user_select_dataset](https://user-images.githubusercontent.com/24272544/146001524-f87dc678-4791-4445-95fe-6d40592f0084.png)

**Comment by susanodd** [comment]
@ocrasborn can you check on EmblemsNL. I followed the instructions above and made datasets which are public available to select for anonymous users. In addition, datasets which contain public glosses are available to select and shown in the header. (#781).
However, some datasets, e.g. EmplemsNL is accessible by others, but has no public glosses.
What should an anonymous user be allowed to do?

**Comment by susanodd** [comment]
(This is all on my local server, not online.)

**Comment by ocrasborn** [comment]
Ah, good point, @susanodd. Only datasets with public glosses should be selectable by anonymous users, not those datasets that are available to other researchers. Should have made that clearer before.
(In fact, we strive towards harmony here (datasets available to other researchers should have public glosses), but copyright reasons may prevent full public access to glosses.)

**Comment by susanodd** [comment]
I've finally got this working for just the datasets with public glosses. (#781).
One thing that I'm not sure about is the situation where the user chooses "None" in the select view.
At the moment, this defaults to "all". This is visible in the header. Although the list shows nothing selected.
Once upon a time, this was desired because otherwise the "no datasets selected" becomes a problem elsewhere.
However it is maybe confusing.

For anonymous users, the header shows with nothing highlighted. (A session variable is used for anonymous users),
whereas for normal users, the default is to highlight the datasets they have access to (when nothing is selected).

Screenshots are below.

**Comment by susanodd** [comment]
This shows test **user_dataset**, who only has permission for two datasets. Now all datasets are shown in the header.
But the user can only select from those that can be accessed. Here "None" has been selected. The header defaults to highlight those this user has access to (rather than "none"). The code has had this behaviour for several years.

![user_dataset_nothing_selected_header](https://user-images.githubusercontent.com/24272544/146546655-1a1f5ccf-8a3b-40b9-83fb-ed2153c6164c.png)

**Comment by susanodd** [comment]
Here is the new anonymous user header (for all pages), showing those datasets with public glosses, followed by the select list. The default is NGT. (As defined in the Settings file.) In this example, the anonymous user has selected "None". Here, the header shows nothing highlighted.

![anonymous_user_default_header](https://user-images.githubusercontent.com/24272544/146547152-a5e4ee25-7b32-466b-a28f-9455a4f9b581.png)

![anonymous_default_select_screen](https://user-images.githubusercontent.com/24272544/146547165-f1cbf063-9ad4-4058-9d20-b6b05fc68493.png)

![anonymous_default_select_none](https://user-images.githubusercontent.com/24272544/146547176-2de58e2c-498b-4adf-ac38-afaa3fa51723.png)

**Comment by susanodd** [comment]
This is live now.
