### ISSUE TITLE
The cron job that creates ecv files is reporting an error

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#795]
Not sure since when. Here's the latest log: 

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x0000151884ab9180 (most recent call first):
Aborted

**Comment by Woseseltops** [comment]
This error suggests an incorrect Python version. I had a look at your crontab, @ocrasborn , and it turns out that when I moved the cronjobs from Applejack to the Lightning container (https://github.com/Signbank/Global-signbank/issues/769#issuecomment-1018403650) , I did not turn off the old jobs . If everything's okay, the error should go away now, without affecting any functionality.
