### ISSUE TITLE
Video import: separate the log messages per dataset

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#799]
When batch importing videos from writable/import_videos (or something of the like), the system looks in all subfolders for all datasets and does its thing. The log message that the user then gets (admin users, for now) combines log info for all datasets. Please separate the log per dataset with a clear header, keeping the different categories of log for each dataset.

The present situation can be a bit confusing, as I often add new videos for dataset X, while there are also some remaining problematic files for other datasets (where the filenames don't match a gloss in that dataset for the specified language in the subfolder). Cleaning those up would be good practice, of course...

**Comment by susanodd** [comment]
@ocrasborn do you know if the folders per dataset remain? Or is this cleared up afterwards? Do you typically upload an entire folder with the name of the dataset at the top level? Or do you upload files to a dataset folder? (How do the files get into the folder writable/import_videos ?) The url command in question assumes there are already files and folders at this location.

In order to rewrite the code (on my local server), I commented out the specific code that stores the videos in the database and removes files. I replaced this with print statements to see what's going on, and facilitate development using test data.

I will make the output as you describe, by maintaining a data structure during processing.
At the moment, the code seems to just ramble along listing stuff and "printing" to the output string that is given at the end as the result.
If you actually try it with absolutely nothing in the directory, it still prints stuff by no data (no file names).
It looks like the code removes things it has copied to the normal location.
So from what you describe, it leaves files it cannot process?

**Comment by susanodd** [comment]
The code is a bit weird. This is what it looks up for the Gloss:

https://github.com/Signbank/Global-signbank/blob/1d9c7b6c9bd58ebd16c1d9bbbc61cf89509b032b/signbank/dictionary/views.py#L544-L555

The error message shown to the user mentions gloss ID. But the code is looking up on annotationidglosstranslation.

**Comment by susanodd** [comment]
@ocrasborn I had a look at the folder on lightning. Indeed, there are folders for datasets underneath import_videos.
The subfolders underneath the dataset acronym (or name) are e.g.: nld, eng
So this is a subfolder named by a language code, as observed in the code:

https://github.com/Signbank/Global-signbank/blob/1d9c7b6c9bd58ebd16c1d9bbbc61cf89509b032b/signbank/dictionary/views.py#L538

So far I can't find any code that puts the files in this location. I assume you upload them?
The folders do not get deleted. From the code, it looks like videos that have sucessfully been moved get deleted from this location, otherwise there is an error message feedback.

**Comment by susanodd** [comment]
Here's what the feedback looks like so far. I set up some test files on my local server using a few of the remainder file names on lightning in order to show glosses that are not found.
@ocrasborn would this be better with a page header and/or possible interaction to remove or rename files?
When the url is invoked, it basically parses the entire folder, that's why it shows info from other folders (in the log). It isn't parameterized on a particular dataset.

![import_videos_table_feedback](https://user-images.githubusercontent.com/24272544/161083445-e7f3c0a1-5910-4166-b8ab-f54a003c423c.png)

**Comment by susanodd** [comment]
As per @Woseseltops feedback in #762 and  #794, this code needs to become a template.

**Comment by ocrasborn** [comment]
Hi @susanodd , very good like this! A page header would be friendly (and a link to get back to the home page or previous page), but let's not develop any further functionality: other issues have more priority.

**Comment by susanodd** [comment]
I've made the feedback table into a template with the usual Signbank header.
Some feedback appears in the last column, Status, as shown above.
Additional feedback appears in a bullet list underneath the table, e.g., if a folder for a bogus dataset acronym or bogus language abbreviation has been encountered.
Some other errors are also tallied by the (original) code, such as failure to delete the original file (in the import folder) or failure to copy a file to the new location. These go in the error log.

**Comment by susanodd** [comment]
![import_videos_template](https://user-images.githubusercontent.com/24272544/164467925-6c8e0993-42c0-42ba-af23-a2b5d6a5a82f.png)

**Comment by susanodd** [comment]
This has been pushed to branch video_import and is awaiting review.

**Comment by susanodd** [comment]
I'm updating the table now as suggested by @Woseseltops in the review of the pull request.

One thing that is not clear to me, where do the media files to be imported come from? Are they uploaded by hand to the folder?
There are url commands to import media, but no commands to upload the files. (@ocrasborn ?)
Once the new code is on the live server, there can be a menu item to import media (for dataset managers) in order to navigate to this page.

**Comment by susanodd** [comment]
![import_videos_table_simple](https://user-images.githubusercontent.com/24272544/166432491-1c75e78e-7618-4d06-bc7c-ca216ce72b84.png)

**Comment by susanodd** [comment]
I've made the code to detect dataset or language abbreviations that do not exist.
The language abbreviations are printed as errors.
Here, there is a folder called "bogus_language" underneath folder NGT.
I'm not sure who should delete this?
Assuming people are uploading files themselves, I thought it would be useful to show if an abbreviation does not match a language.

So far there is no functionality for removing glosses that were not found.
This could be solved by creating the gloss, by renaming the file, or by removing the file (in the case of weird file names not corresponding to anything.)

Since I don't know how the files are getting into the folder, I don't know what the best solution is.
Say for example, offer a "clean up not imported files or bogus folders" button.
Or a "rename folder or media file" button.

**Comment by susanodd** [comment]
Here is the version pushed to branch `video_import`
I decided on a colon separator.

![import_media_separate_tables_colon](https://user-images.githubusercontent.com/24272544/166442390-ee431fab-ceea-498a-9530-fc8a8a5c3198.png)

**Comment by susanodd** [comment]
What is the relation of this issue to #717 ?

**Comment by susanodd** [comment]
This is live now. It will be aborbed by issue #717 to add additional feedback.
