### ISSUE TITLE
Searching for translation equivalents on the search page doesn't work anymore

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#801]
Searching for any string in the Translation Equivalent fields per language, in the search form, incorrectly returns all signs in the selected data sets. Searching for a translation equivalent in the menu bar search field works fine, though.

**Comment by susanodd** [comment]
This has probably been broken for a while. I kind of didn't remember there was such a functionality. But yes, it's right there in the header! There didn't used to be many glosses for which this information had been filled in.

**Comment by susanodd** [comment]
I found it. There is a discrepancy in the identifier used in the form.
One place uses "keyword_" and the other uses "keywords_".

**Comment by susanodd** [comment]
We kind of ignored a forms setting that defines the "keywords_" prefix and basically hard-coded it as "keyword_" in lots of templates where this search field occurs.
I chose to make it be "keyword_" as the constant in forms, since this is how it's hard coded elsewhere.
Less coding to fix it this way.

**Comment by susanodd** [comment]
This has been repaired and is on branch translation_equivalents.

**Comment by susanodd** [comment]
This is live now.
