### ISSUE TITLE
Add tab 'List view' in detail view to go back to the search results

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#816]
Or alternatively, create a button to go back to the search result list -- if any was generated to get to this sign, of course. (Now users have to use their browser buttons to go back if they don't want to recompose the search, but just going back page by page often means they are first sent back to the edit view of the sign, which confuses them: am I undoing what I just edited?! A separate function in the interface to move back to the search result list would be user-friendly and avoid confusion.)

**Comment by susanodd** [comment]
I noticed while working on this that the code keeping track of all the search parameters is extremely lengthy.
I've made a data structure to save the ones that are filled in while going through the parsing.
I'll try to improve this code. It looks like we just kept adding additional if-constructs as new things were added.
Perhaps this will combine with #34 .

**Comment by susanodd** [comment]
I've added the current query parameters to the top of the "query results list view".
The results shown below the parameters are those of the search_results horizontal bar.
The results are just links to the other glosses. Other information could be shown in the list.
Next is to add a link to go to the query page.
At the moment, I've made several helper functions, several for pretty printing the query parameters to the table (in human readable form), and another for generation of a Q query filter with all the specific fields and values of the parameters. That is passed as a parameter to the filter on the (Gloss) model objects.


![list_query_view_en](https://user-images.githubusercontent.com/24272544/174280406-aa334cee-03bb-4938-b601-480489665e03.png)

![query_list_view_nl](https://user-images.githubusercontent.com/24272544/174280434-cd1de244-ab79-4cd4-b5e6-0f642e519550.png)

**Comment by susanodd** [comment]
It's working now!

Here is the List View showing the parameters and results and a button Run Query.
The button goes back to the Gloss Search page with those parameters filled in.


![query-k-1_curved-chin-nose](https://user-images.githubusercontent.com/24272544/174793890-aea5e2d1-e884-48e0-bff8-ada962fea030.png)


![run_query_search_parameters](https://user-images.githubusercontent.com/24272544/174793921-9ec0c57e-956f-4629-8059-dc5f64afd964.png)

**Comment by susanodd** [comment]
Oh, the Values of the query parameter Fields are merely shown blue if they are multiple select fields.
It looked a bit weird in a list because they are independent.
At the moment, the query parameters are done with a session variable.
A new url parameter "query" has been added when going back to the Gloss Search List View.
This is needed in order to make it unambiguous as to whether this is a previous search parameters.
The parameters themselves are filled in in get_context_data, and the query is done in get_queryset.
Both of these need to identify whether this is a new query or a previous query.
I revised the GlossSearchForm in the template to initialize the form fields using the parameters if available.
Many of the fields are multiselect, with select2, so this had to be coded in javascript and applied after the select2s had been created.

**Comment by susanodd** [comment]
I think this is quite exciting to use!

![query_m_1_neutralspace_repeat](https://user-images.githubusercontent.com/24272544/174807569-bfc86e5c-ffb3-4e46-901c-93f76a84bcd5.png)

**Comment by susanodd** [comment]
I pushed this to branch list_view but forgot the hash tag in the commit comment.

**Comment by susanodd** [comment]
I've accounted for all of the GlossSearchForm query parameters in the query_parameters dictionary that is passed around as a session variable. This is used to pass information to the List View shown above, and to re-query using the same parameters.

**Comment by susanodd** [comment]
![search-gloss-morpheme-tag](https://user-images.githubusercontent.com/24272544/175497330-e1fb83b7-d9f4-47b3-a35d-6557a5cdfed0.png)

![query-view-tag-gloss-with-morpheme](https://user-images.githubusercontent.com/24272544/175497362-d78ee490-d57e-469e-a842-b546f20a05a6.png)

**Comment by susanodd** [comment]
In the GlossSearchForm, multiselected Tags are **AND**-ed (this is also the case on Global Live).
Here's what it looks like in the new Query View, first the search, followed by the Query View of the result gloss, followed by the Search form with the same fields filled in. (NOTE: These are on my local server where I've added tags for testing things.)

![search-radboud-sign-check-phonology](https://user-images.githubusercontent.com/24272544/175498114-3a8ebc7e-4111-45e7-adc7-b92497bd62d5.png)

![query-view-two-tags](https://user-images.githubusercontent.com/24272544/175498173-5f5c8a31-7a51-4798-87df-f0a47b28c8c8.png)

![run-query-two-tags](https://user-images.githubusercontent.com/24272544/175498640-d1dbfa84-eb1a-4418-865b-ec639fa08a7e.png)

**Comment by susanodd** [comment]
![two-tags-query](https://user-images.githubusercontent.com/24272544/175499891-888f58ad-64f2-4955-9052-b6b6763d688b.png)

**Comment by ocrasborn** [comment]
Hi @susanodd , I love the clear overview of query parameters, very helpful for the user! With 'list view', I was thinking of the display like the user initially sees in the list of search results, so the multi-column view showing some of the phonology as well. Could you duplicate that display here for the present display of what's under 'glosses matching query'? See screen shot below:

<img width="1290" alt="Screenshot 2022-06-24 at 17 51 50" src="https://user-images.githubusercontent.com/10242207/175571969-7ee13957-3648-40e1-9f02-946a5d006fb4.png">

**Comment by susanodd** [comment]
![buttermilk_list_view_matching_query](https://user-images.githubusercontent.com/24272544/176144518-be7a8cc8-b217-43c8-a42a-264526ef6683.png)

**Comment by Woseseltops** [comment]
I'm reviewing the work on this issue, and my first step is to understand things on a functional level. My first thought is that this solution might solve the direct problem, but might also create some confusion itself, because:

* I would say a tab in the detail view is for information about the gloss itself, while information on the query used to find a gloss  is something on a 'higher level'. This is why I made sure to keep the horizontal bar of other search result 'above/outside' the detail view.
* Speaking of the horizontal bar, wouldn't that always show the same results as the new 'Run query' button? That is, duplication of functionality?
* I feel that with adding search results to inside the detail view, we are getting recursion:

```
* List view
   |-Detail view
     |-List view
```

Alternative approach:
* Besides the horizontal bar of 'other search results', add button saying 'Query'.
* On click, unfold some kind of modal like window, showing the beautiful query representation @susanodd created.
* Inside this modal, there is a button 'Run query', which will bring you back to original search results where you started.

Very curious what is your opinion on this line of thinking, @susanodd and @ocrasborn

**Comment by susanodd** [comment]
Yes I understand what you're pointing out. It was I guess how I understand what the issue was to do.

If anything, it's really fun to use this feature. It makes it a lot easier to see what you actually filled in for the query itself.
The search for on the gloss list view is very lengthy.

I know that many of the results chosen can end up having nothing to so with the specific gloss.
I starting considering partitioning the query in different aspects. I guess the the publication fields or the relation fields.
It's clearer that these are quite different kinds of results.

This issue is also related to #34.

Yes, it was the same as the search results in the bar.
Although now, it looks the same (as per @ocrasborn feedback request).

It would be nice if you could incrementally refine your query. (Also #34.)
Although it could perhaps be gloss-centric based on this gloss.

I was thinking of making the results shown something like showing the respective fields that are queried upon.
That was the results would be more specific to this gloss.
It's like a superset of things that are similar in some way to this gloss.
I don't know, I honestly think it's really fun to use.

**Comment by susanodd** [comment]
If you start using this query display, then go back to the search page via Run Query, you see the parameters displayed there again too, so you can modify it by adding more things. Basically refine your query.
Although then you can end up modifying it so that your gloss isn't included any more among the results.
(I can't determine to what extent that would happen as I'm not a signer.)

Is it possible to put it live and let @ocrasborn check it out to further refine it?
Or I can modify what it displayed in the results shown there.
I thought it was interesting because I made some queries with a certain handshape then also multi-selected with handedness to include one-handed and two-the-same, etc.
So then you see glosses that are similar because they use either one or two hands for the particular handshape.

**Comment by susanodd** [comment]
It could become a kind of "centric" query.
So if you didn't already do any query, you could give "default" "starter parameters" with fields of this gloss filled in.
(So basically, running the query would find this gloss or glosses with identical phonetics.)
And if from the query starting in the gloss search form, and clicking on a gloss in the results, then if you had queried "created before" and/or "created after" then you could see some other representation of the query results (as viewed from the context of this gloss). Then you'd be focussing that this gloss was created within a certain period of time. Perhaps you were trying to find glosses that you had uploaded or created at the same time. So your interest in this gloss would be for a different reason. The results could be displayed to reflect this differently (since the result is not gloss-centric.)

**Comment by susanodd** [comment]
Context-sensistive display of query results.

**Comment by susanodd** [comment]
I've made some revisions in the results display. This is intended to make the results more specific to this gloss.

The Dataset column is hidden if there is only one. The languages and non-empty fields of the focus gloss (this gloss) are shown as buttons to toggle the visibility of the columns.

![query-view-toggle-fields](https://user-images.githubusercontent.com/24272544/177529188-e61c5f54-c33a-4f2e-9308-f40b969bfabe.png)
![query-view-toggle-some-off](https://user-images.githubusercontent.com/24272544/177529215-5b4c63fa-91d3-4217-9bbf-d0238f255f99.png)

**Comment by susanodd** [comment]
inching along

![query-view-related-to-foreign-sign-chest-upwards](https://user-images.githubusercontent.com/24272544/177768898-54df30a7-eb1f-4ee6-9e14-3e454100ee82.png)

**Comment by susanodd** [comment]
In the meantime (please see the screenshots below, then I'll answer you afterwards), I've implemented a refinement to the previous.
(I'll revise it again with your comments.)
I made it so that if the user currently got to the gloss without search parameters (i.e., just press Search without having selected anything in the form, so it shows all the glosses....), it shows the "non-empty" fields of the gloss.
Then you can run the query with those as starting parameters. (So you "start" a query from "the current gloss".)

![query-view-no-active-parameters](https://user-images.githubusercontent.com/24272544/178008185-090cae59-dcda-4116-99d3-dbf0c1198303.png)

![default-query-gloss-non-empty](https://user-images.githubusercontent.com/24272544/178008217-83a6ee8e-559a-407e-bd71-d715cc6be363.png)

**Comment by susanodd** [comment]
![accidentally-identical-phonology](https://user-images.githubusercontent.com/24272544/178009345-d8453a36-f5f0-4862-9cc6-92f561732038.png)

**Comment by susanodd** [comment]
@Woseseltops I like your mockup!

Okay, we'll wait until @ocrasborn is back.
Probably the new feature needs to appear someplace else where you can refine your query.
I've been dreaming about this issue while trying to sleep the past days.
It's all the spaghetti I guess.

**Comment by susanodd** [comment]
Oh, and here's the same Query View once again, after the parameters are set.
The idea is that you can toggle all the various parameters to inspect the results. That's when I started noticing that the Search form didn't match up with what the get_queryset was looking up since some things aren't in the search form.


![query-view-accidentally](https://user-images.githubusercontent.com/24272544/178013202-5abf31b3-7532-4697-9117-025602fd6662.png)

**Comment by susanodd** [comment]
I'm working on making it more parametric so less excessive and less repetitive and less redundant code, etc. :)

**Comment by susanodd** [comment]
Here I've implemented the idea from @Woseseltops.

![gloss_detail_query_modal_no_qp](https://user-images.githubusercontent.com/24272544/180215418-f8e51c23-c08a-4ad4-8f79-64b723184350.png)

![gloss_detail_query_modal_qp_after_run_default](https://user-images.githubusercontent.com/24272544/180215447-380a8c90-06ce-44ac-818d-7b3251c8921f.png)

**Comment by susanodd** [comment]
The Query-button-popup and the Query View can be set to show in settings.

**Comment by Woseseltops** [comment]
Awesome. Perhaps a little more space right of the query button?

**Comment by susanodd** [comment]
I've added an easter egg to the stealth query view.
There are buttons for all of the displayed fields and these toggle the columns of the table.
Here is a query on Dutch Lemma "zetten-leggen" with the results shown.
Because these are lemmas, there is a lot of duplication in the columns. The hidden columns have line-through buttons.

![query-view-toggling-table-elements](https://user-images.githubusercontent.com/24272544/182832634-c24bf350-5340-463e-b67a-9bdac44838e7.png)

**Comment by susanodd** [comment]
Okay, I successfully transplanted the Query View to be under the Analysis menu rather than a tab for Gloss (as it is in the above screenshots.)

I revised the template to include toggle buttons for the search parameter fields as well as show columns for them in the results table. This (made up) example shows the three multi-select fields as query parameters.

![query-view-under-analysis](https://user-images.githubusercontent.com/24272544/183064734-9734d39c-790e-463a-bac2-d09a28f55af4.png)

**Comment by susanodd** [comment]
To avoid excessive fields in the results, the table includes the Gloss_LIST_DISPLAY_FIELDS as for the normal Gloss Search List View. Plus it adds extra toggle buttons. On the normal list view, the toggles for languages only appear if there are more than two languages, because the table gets very wide. Here in this new view, you can toggle the different languages also per category (annotation, lemma, translation), plus you can toggle the queried upon fields as well.

**Comment by susanodd** [comment]
Here's another example, showing a query on sequential morphology.

![query-view-sequential-morphology](https://user-images.githubusercontent.com/24272544/183085299-2d8a60bc-d78b-4384-8652-40154d10ebc0.png)

**Comment by susanodd** [comment]
Here are examples showing Simultaneous and Sequential Morphology in the Query View. (Test glosses.)

![query-view-simultaneous-morphology](https://user-images.githubusercontent.com/24272544/183388727-6e831b3e-5b67-4647-a3bf-371c88cac892.png)

![query-view-sim-seq-morph](https://user-images.githubusercontent.com/24272544/183388801-e75d301a-1079-4103-bc8c-6e4cdd907455.png)

**Comment by susanodd** [comment]
Compared to the initial version of this view, this one is under Analysis instead of with the Gloss.
I left the tab at the top in expectation of having additional information to view regarding queries, such as the list of queries for the user.
Perhaps another tab for refining the query. That needs to be worked out.
In the examples above, it's still the results of the original query. If additional filters need to be applied, a new query must be done.
Perhaps a tab if the kinds of information being displayed get overwhelming. I'm adding search filters to the Results table one at a time.

**Comment by susanodd** [comment]
Here's a query on Morpheme Type. (The query is on Sign or Morpheme.)

![query-view-morpheme-type](https://user-images.githubusercontent.com/24272544/183405366-e3613fcb-99e5-4488-ad64-d9bb37e7e344.png)

**Comment by susanodd** [comment]
Here's a search on gloss of related sign. I encountered a few bugs related to "idgloss" still being used in some older code. I revised it so it also allows regular expressions now. It now filters on annotationidglosstranslation__text__iregex.

![query-view-gloss-of-related-sign](https://user-images.githubusercontent.com/24272544/183868190-7e6b2b00-4e73-4a5c-90c8-6e77b2b55ef3.png)

**Comment by susanodd** [comment]
I revised Type of Relation to show the actual relation that was being searched on in the results.

I searched on Type of Relation Antonym and this is what it looks like:

![query-view-type-of-relation-antonym](https://user-images.githubusercontent.com/24272544/183882053-d83b6b9d-48f8-48e5-b388-4fca20016988.png)

As you can see, it looks like some duplicates. But this is actually true if you go to the detail view of Black-A. You can see that its relation to White is duplicated. Indeed the relation appears three times in the database, two of which are the same direction with Black-A as the source.

![zwart-A-detailview](https://user-images.githubusercontent.com/24272544/183882490-3ee1ad55-4463-4150-94ec-dbca8d238912.png)

**Comment by susanodd** [comment]
Here's an example searching on two Relation fields. These are not tied together in the Gloss Search. As you can see homonyms are returned as well as other relations (of the same gloss) where the target gloss starts with GE.

![query-view-relation-gloss-of-related](https://user-images.githubusercontent.com/24272544/183886827-4bca18ff-ba22-4d0d-82f4-bfe728d06146.png)

![query-view-more-results-homonym-GE](https://user-images.githubusercontent.com/24272544/183887270-988b8573-c743-40d5-a872-8a01f11dcf4c.png)

**Comment by susanodd** [comment]
I've added Other Media to the Query View. I purposefully searched on ^open to restrict the results since most media is absent locally. Next this needs to be a preview. Or perhaps a different view tab.

![query-view-other-media](https://user-images.githubusercontent.com/24272544/183897888-dd172863-b8ff-41e1-a18b-8e003589272d.png)

**Comment by susanodd** [comment]
@ocrasborn also look at this one. @Woseseltops merged it earlier, so I'll put it live tomorrow.

**Comment by susanodd** [comment]
This issue, all the comments I made, most are discussing how to solve the problem.
Basically this issue introduced the Query View and the saving of query parameters in order to achieve "going back" to the query.
Probably this can be closed.

**Comment by ocrasborn** [comment]
Hi @susanodd , I can't see the tab Query view yet once I'm in the detail view. I see the tabs that were there before, and I see the button 'Query' that pops up a spec of the query and where I can run the query again to get to the list view again. I don't see how to ever get to the Query view tab like in the screen shots above.

**Comment by susanodd** [comment]
@ocrasborn The Query View is underneath the Analysis menu now.
Originally it was a tab, but together with @Woseseltops we thought it was too much overlap with the normal Search page. The functionality has been expanded so under Query View it shows the fields that were queried on on the results table, rather than be the same as the normal search.

**Comment by susanodd** [comment]
This can be closed now.
