### ISSUE TITLE
Revise column toggles

### ISSUE THREAD

**Issue by Woseseltops** [Signbank/Global-signbank#835]
@susanodd added column toggles on at least two locations , like so

![image](https://user-images.githubusercontent.com/1909317/186936880-729afb43-c853-448c-9845-2d8f2e1d661f.png)

Now they're live, I've spent some more time playing around with them, and figured that they could be more space efficient. Suggestions:
* If a column is empty, disable the column by default
* Behind each column header, add a cross (or some other icon that indicates 'hide'), that hides the column when clicked
* For the buttons, only show the buttons of hidden columns
* Make the buttons something you have expand. So by default you only get one larger button 'add more columns', and only if you click it you get the column toggle buttons as in the screenshot above.

**Comment by susanodd** [comment]
I like the suggestions!

One quirk is about empty columns.
For the queried upon fields, they will never be empty.
For the four columns that correspond to those in the normal Gloss Search (Handedness, Weak Hand, Strong Hand, Location,
those are shown separately so it matches the normal search.
That's a great idea to just show an X on the header. !! (But to get it back?)
These may or may not be empty, but....

With languages, it's possible to hide empty columns, that was the original intention, the same buttons show up on the Gloss Search when more than two languages are involved...., 
but...

The rows are each generated by ajax calls. So it's not know whether the column is empty until all the rows have been generated.
They are generated and shown dynamically, so the table rows are still being drawn. The header is drawn first.
I suppose the number of visible columns could initially be reduced not based on whether empty or not.

Or there could be additional calculations at the time the query is formed in order to identify empty columns. But that might not work well because Django typically is passing around unevaluated queries.

**Comment by susanodd** [comment]
Here is a simple toggle panel of the buttons.

![query-view-hidden-buttons](https://user-images.githubusercontent.com/24272544/187161413-d9216a7d-bfce-435a-a346-62462b597aad.png)

![query-view-revealed-buttons](https://user-images.githubusercontent.com/24272544/187161443-ee7ea6a7-d083-4b08-b4d3-05cf8a5f5a6e.png)

**Comment by susanodd** [comment]
I pushed the simple solution to branch list_view.

![query-view-with-buttons-icon](https://user-images.githubusercontent.com/24272544/187167655-638458f6-c92d-417f-94c9-b410fb111cc8.png)

**Comment by susanodd** [comment]
This can be closed. The buttons are toggled on and off and are hidden by default.
