### ISSUE TITLE
Concatenate paths in settings with  os.path.join instead of +

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#845]
In the settings the paths (e.g. ROOT, WRITABLE, etc.) are now concatenated using `+`. When a trailing slash is forgotten, the concatenation results in a non existent path. To avoid these issues, we can use `os.path.join` (https://www.geeksforgeeks.org/python-os-path-join-method/).

**Comment by vanlummelhuizen** [comment]
Perhaps something for you, @Jetske (@Woseseltops ?)

**Comment by Woseseltops** [comment]
Just for completeness, I often choose `+` instead of `join` because I feel it's easier to read, but I do agree it's more error prone, so this issue has my seal of approval

**Comment by susanodd** [comment]
There were some weird things going on with path names and the first two characters of the gloss being used for the folder name.
Sometimes there were non-Ascii and non-Latin characters and even symbols in the folder names.
At that time, there is some code that iterates through the directory listing in order to avoid making paths and using checks for existence, because the check for existence would fail if there were weird characters in the constructed path name. But if you "fetched" the things from the file system and compared, this could be circumvented.

**Comment by susanodd** [comment]
I recently used a plus sign in a path name. The problem is if it's part of a bigger string that includes translations.
Django can't concatenate some things any more.
