### ISSUE TITLE
Add Sense, ExampleSentence and ExampleSentenceTranslation models

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#884]
1. Add a Sense model between Gloss and Translation+Keyword models.
2. Add ExampleSentence and ExampleSentenceTranslation with a many-to-many link to Sense.

Schematic:
![IMG_20230216_143820293](https://user-images.githubusercontent.com/16682631/219388389-370ea6e3-89ad-4531-aa22-eda5f85e8124.jpg)

**Comment by vanlummelhuizen** [comment]
@ocrasborn Can upload your proposal you handed out?

**Comment by ocrasborn** [comment]
[Signbank_NieuweInfo_20230118_ontwikkelaars.pdf](https://github.com/Signbank/Global-signbank/files/10793248/Signbank_NieuweInfo_20230118_ontwikkelaars.pdf)

**Comment by ocrasborn** [comment]
Additional request: in the Sense model, please add an index field (like for the comments) that allow us to order the different senses per gloss manually.

**Comment by Jetske** [comment]
I made a new field for Senses which shows some keywords to define the sense. And a table of example sentences. 

![image](https://user-images.githubusercontent.com/10157482/231691210-5f8a6ccb-af4c-4865-97c3-ae1ca8649392.png)

In this example there are no translation equivalents for English given but is it true that that should show the same structure as for Dutch, with the senses given as keywords and literal translations of the Dutch example sentences? @ocrasborn 

And do you have a preference for opening the video of an example sentence (if there is one) as pop-up or listed in the 'videos' tab?

**Comment by ocrasborn** [comment]
Hi @Jetske , 
1. That looks good! 
2. Yes, this should be available for all the languages in a dataset. It's true we haven't spent much attention adding translation equivalents for English for the NGT dataset, but for Kata Kolok for instance this has been done. Does this perhaps require more discussion? Is it related to how @vanlummelhuizen re-designed the language coding?
3. In the screen shot above I still miss the 'type' for each sentence (like interrogative, negative, etc.). (Well, and links to the movies.)

**Comment by vanlummelhuizen** [comment]
> 2\. Is it related to how @vanlummelhuizen re-designed the language coding?

The re-designing of the language coding was related to FieldChoices and similar. The translations for these entities should parallel the *interface languages*, since they are presented in drop down lists, as part of the interface.

The languages that are mentioned here, in relation to senses, are *data languages*. They are the languages that are set for a dataset, and give an editor the option to enter data in languages that are not in the interface languages.

So, is this related to my re-designing? No.

**Comment by susanodd** [comment]
If you look at the coding of the Semantic Field model and its translations, the translations are for all (dataset) languages, whereas the "name" field uses the interface languages (model translations).

**Comment by Jetske** [comment]
Update:

![image](https://user-images.githubusercontent.com/10157482/233974950-aa24ad02-7c29-4e9d-93a1-64962760b3bc.png)

What are the options for types of sentences? At the moment you can choose between declarative, interrogative, imperative, and exclamative and have the possibility to add that it's a negation.

**Comment by Jetske** [comment]
Okay, sounds good. At the moment it's only editable in the admin, so I still have to make it possible that you can add, delete and change senses on the page itself. And I think it should be possible that the type list can be edited.. but I'll look into it. 

For now the sentence leads to a pop-up window. 

One thing I don't really understand yet is where ExampleSentenceTranslation as shown in the model schema would be placed. Should the languages always have the same sentences as translation or is it okay if they are separated like as shown above?

**Comment by susanodd** [comment]
@Jetske will you post the class models soon?

I'm working on #938 as it applies to all text search fields, not just the menu bar fields. I'm working on Handshape search now. This is actually the first time (first place) the user can search on a model translation field (the 'name' field of Handshape, which includes behind the scenes all five of the interface languages. As I write this, I haven't finished it yet.)

I've fixed most occurrences of the Translations field (in the menu bar). But when this is changed to Senses, this will impact all of this code again. This will add the actual dataset data languages to the parameters. The reason for needing the languages is to determine what form fields are used in the active query form, since those are all dynamic based on the selected dataset languages.)

It looks like ultimately, users will be able to search on data languages, not just interface languages.
(Issue #938 deals with the user entering special characters in the input.)

**Comment by Jetske** [comment]
> Not sure I understand you well, but perhaps this helps: the videos are the core of Signbank entries, the text (including glosses of signs) is always secondary. In the case of the ExampleSentence, there is only one video per example sentence per sense (of NGT for example), and it receives a ExampleSentenceTranslation in English and Dutch. (In the Norwegian SL dataset, the one video receives a translation in English and Norwegian. Etc.) Does that help?

Yes, that helps. So if I understand it correctly, 'translation' here is not from one language to the other but from a sign (or signed sentence) to text? Then I'm not sure if this setup is the most optimal, because for English and Dutch the ExampleSentenceTranslations should link to the same ExampleVideos so (in the image above) the table for English would be an exact copy of Dutch and that takes up a lot of space. And besides, if something in a Dutch sense keyword set changes, it should also change for the associated English sense keywords. Maybe it is better to show a sense, with videos of ExampleSentences, with all ExampleSentenceTranslations next to it. 

I think this affects the models so they are not ready to be posted.. @susanodd maybe we can sit together soon because it's not all that clear to me what are data/dataset/interface languages.

**Comment by susanodd** [comment]
@Jetske yes, that would be good to discuss in real.

I suspect we need to add an extra language to tstMH that is not an interface language. (For ourselves to make testing easier.)
It's actually very confusing now that we have model translations too.
The 2-char language codes are used everywhere in all the forms where multiple languages are possible.
There are also numerous mini-dictionaries constructed for looking up the languages inside of loops in the templates.

A valuable suggestion during development was @Woseseltops insisting to put e.g., query parameters, frequencies, search histories, in separate files to keep the code separate. Perhaps the code related to the Senses can be set up this way.
Unfortunately all the models still have to be inside models. (You saw this already with the videos. There is lots of code related to videos in the models file. But also code that does very similar things.)
If you can put the new code into separate files, with specific functionality then that will help plug it in to the places @ocrasborn has identified. When we were working on the field choices, they were just everywhere and all the code ended up needing to be modified. It took many months to do that. For efficiency in integration, it would be good if the senses code can be a bit modular.

The only "multi-lingual" fields are in the menu bar.
I guess those are dataset languages, but we just don't have any examples for our test dataset of languages that are not also interface languages. (Debugging stuff is a bit frustrating sometimes.)

**Comment by susanodd** [comment]
@ocrasborn are there plans to migrate the current translations to senses?

I'm asking because I noticed that they were sorted differently in the detail view versus the public view.
Then I noticed in your example that some of the comma-separated things are grouped together.
At present, as translations are, the comma is used to separate them into (possibly multi-word) keywords, each of which is stored in the database as a keyword. Then there is translation (relation object) between the gloss and the keyword.
At present, the keywords are sorted by text.
(So any implied grouping together of keywords that appear next to each other doesn't happen.)

(This could impact a migration mapping current keywords to senses. Probably a human will need to do something. Perhaps export keywords to csv and (manipulate to group them) then import them again as senses. By a human.)

**Comment by susanodd** [comment]
I tried searching on translations with a "," (by just searching on comma) to see what happens. There is only one result, the gloss 1,5

https://signbank.cls.ru.nl/dictionary/gloss/2895/

It has two keywords, 1,5 and anderhalf
The comma is inside the first one.

Probably need to be able to add functionality to search on "non-empty" translations in order to readily export them.
(With the intention of exporting the existing ones in order to group them, to import them again as senses, to accomplish migration.)

**Comment by ocrasborn** [comment]
> @ocrasborn are there plans to migrate the current translations to senses?

Yes, that's indeed the plan, cf #965 

After that, the translation field(s) can be deleted from the model, database, and the interface.

**Comment by Jetske** [comment]
![image](https://user-images.githubusercontent.com/10157482/235460380-8439f008-e446-4885-bdf9-20aa915db7fe.png)
 
I've switched everything around such that translations of all languages are shown in one table (if available) alongside the corresponding video. Better, right?

**Comment by ocrasborn** [comment]
Yes, better, @Jetske , thanks

**Comment by susanodd** [comment]
@ocrasborn How does this work for Morphemes?

They also have translations.

**Comment by Jetske** [comment]
Yes, then every line would become a keyword. I think with a textbox like this it's pretty easy to both add and delete keywords in one go, but do you think that this is confusing for users?

**Comment by Jetske** [comment]
Also, unrelated but for order index of the senses we need to add it to the through model like [this](https://stackoverflow.com/questions/9602217/define-an-order-for-manytomanyfield-with-django). I'll work on that now.

**Comment by susanodd** [comment]
> Also, unrelated but for order index of the senses we need to add it to the through model like [this](https://stackoverflow.com/questions/9602217/define-an-order-for-manytomanyfield-with-django). I'll work on that now.

Ah, so it labels the relation.

**Comment by susanodd** [comment]
@Jetske I'm trying out the sense branch on my local computer.
I'm merely working on the Keywords List Mapping view.

It's extremely difficult to do a simple task like iterating over all the senses for a gloss.
I did the query `gloss.senses.all() ` for a particular gloss.

But somehow, when I retrieve the senses for a particular gloss, it also retrieves senses for totally different datasets.

I tried to just use tstMH. But the glosses with keywords "brother" and "sister" are somehow linked to `ADIK` of dataset `BISINDO`.

Is this why there is a field dataset inside of model Sense ?

I used the command you made to populate the senses on dataset `tstMH`.

**Comment by Jetske** [comment]
That is problematic indeed.. Thanks for letting me know, I will try to find how that happened. Where and how did you come across that?

I did actually use gloss.senses.all() successfully in various places. If you want them in the order of orderindex, you can use gloss.ordered_senses().all(). Maybe that helps?

The reason that there is a dataset field added for senses is that they are not tied to 1 single gloss anymore. So when trying to add a sense in one dataset, you don't want it to find and add an existing matching sense from another dataset (which apparently now happened anyway). It would be possible to find the right dataset by looking at which glosses the sense is related to, but wouldn't that be inefficient?

**Comment by Jetske** [comment]
Actually, I think this might be because when adding a SenseTranslation object it checks if there is a matching one already to add. But then it doesn't check if their related senses have the same dataset. So sensetranslations are shared across datasets. It's pretty much the same problem as why I added the dataset field to Sense. I don't know how to filter on many to many related objects by a dataset somewhere higher up: in lemma. 

So I think in conclusion either we need a way of tracing that back (and then senses and sensetranslations can have duplicates related to different datasets) or we add the dataset field also to the sensetranslation model... The same goes for examplesentence and examplesentencetranslation, btw.

**Comment by Jetske** [comment]
Okay it is probably possible by doing something like
```
senses = []
for gloss in Gloss.objects.filter(lemma__dataset = dataset):
    senses.extend(gloss.senses.all())
```
instead of 

`senses = Senses.objects.filter(dataset=dataset)`

And similarly to find all sensetranslations within one dataset. But there must be a smarter way in Django, right? 
Then with some rewriting the dataset field can be removed from both the sense and examplesense model.

**Comment by susanodd** [comment]
@Jetske the senses should only be to one dataset, but the glosses of the sense should also be in the same dataset. The user has different permissions for different datasets.
Since the dataset appears in multiple places in the new classes, it's hard to tell if this can have side effects.
There aren't any constraints on the new classes.
The constraints need to be added at the start before migrating data. The constraints only apply to things created after the constraint was added, so old data could be violating them and cause weird errors.
(I'm wondering if the dataset field will cause problems. I can't tell. Since it's repeated in multiple places, it's hard to tell. There definitely should not be a default for it.)

This is one artifact of the Keywords themselves. The glosses end up linking to the keywords.
It seems like Django has its own backward links so it might be doing stuff behind the scenes say for "brother" since all datasets have English as one of their languages.
If you'd end up with the Keyword "brother" then there are lots of other objects pointing to it since there is only one object. Via those "cascade" things Django seems to be able to know what things are linked to other things too. (Outside of classes we declare.)

I looked at the tables in the database to see what the sense model migration created in it.
The most useful class to me is GlossSense, btw.
There are lots of tables with just pairs of ids into other tables. (Like every time a ManyToMany appears Django makes these.) There is actually no data in these tables, just ids of things linked together.
Is there any way to modify the classes to generate fewer of these?
(Perhaps @vanlummelhuizen knows.)
It seems risky to have so many links around, since all of these things would need to be updated.
So the dataset id appears in many tables paired up with ids of things in other tables.
Although very inconvenient and annoying, I suspect that that the Dataset field was put in Lemma to avoid having it duplicated everywhere. (@vanlummelhuizen ?)

**Comment by susanodd** [comment]
@Jetske I wrote an alternative command to map the translations to senses. When they are first mapped, there are no senses yet so it's possible to make the function much simpler. I put this in a separate command.

Will you change the sense numbering to begin at 1 rather than 0. It just looks really weird to start at 0.

One thing that seems to be not be working is the scroll bar of search results, it's completely missing.
There are some errors related to this in the error log, but the site doesn't crash.

I'm trying to avoid editing anything, so I don't know what is causing this.
I only just added a new command. If I push it onto your branch it won't affect anything else.

**Comment by susanodd** [comment]
I pushed the alternative initial populate command. The new senses editing of GlossDetailView works for the new command too. I'm not entirely sure if the display looks okay on Safari. It's kind of not clear at first where to click to edit since nothing turns red now.

The bug with the scroll bar, the code I changed to fix it (uncommenting out an assignment to the search_type session variable), on the master this line is also commented out, so it's unclear why this was needed. So something else is probably wrong. I'll alter it on master. It could be that there is a try except that gracefully does an except but then alters the control flow so the search_type doesn't get assigned.

**Comment by susanodd** [comment]
I pushed the srollbar edit fix on master. For some reason the search_type was not getting set, depending on control flow, so the scrollbar results were not being filled. Now it gets initialized if it hasn't been set in the session variables yet. Maybe keep an eye out for if the control flow is doing something different than it used to before the senses. The error was appearing in the log in the middle of generating rows in the GlossListview.

@Jetske can you pull master again to this branch, so the fix gets here. Then I'll try to debug it some more.

**Comment by susanodd** [comment]
Just for reference, a while back there was a weird error that was only showing up on Safari. It was a missing close tag on one of the `div` elements! Safari apparently is not graceful, whereas Firefox just ignores this.

**Comment by susanodd** [comment]
I'm moving the Add Sense buttons of the individual language popups to be inside the Senses Matrix.
It's too difficult to update all the template data otherwise.

**Comment by susanodd** [comment]
Wow, I just looked at the branch commits, and it says able to merge now.
I moved the Language class in models.py upwards in the code on master last week to make it follow the order on this branch. That seems to have helped.

**Comment by vanlummelhuizen** [comment]
@susanodd You wanted me to look into the following:

> I tried to just use tstMH. But the glosses with keywords "brother" and "sister" are somehow linked to `ADIK` of dataset `BISINDO`.
> That is obvously wrong.

I think this is caused by the fact that Translation has a direct link, i.e. ForeignKey, to Gloss. Also, Keywords are in a way Dataset agnostic. Keywords are reused whenever a translation text happens to be the text of an existing Keyword object. 

So, a Dataset may be linked to a Keyword in (at least) 2 way:
1. LemmaIdGloss -> Gloss -> GlossSense -> Sense -> SenseTranslation -> Translation -> Keyword
2. LemmaIdGloss -> Gloss -> Translation -> Keyword

Run for example the following two querysets:
```python
Dataset.objects.filter(lemmaidgloss__gloss__glosssense__sense__senseTranslations__translations__translation__text="brother").distinct()

Dataset.objects.filter(lemmaidgloss__gloss__translation__translation__text="brother").distinct()
```

The first will only return *tstMH* because I ran the `translation_to_sense` command for *tstMH*.
The second returns many more including *BISINDO* because of the directer route.

I leave it to you and @Jetske to handle the direct Gloss-Translation link.

**Comment by vanlummelhuizen** [comment]
To see the Glosses that have links to Translations via Senses, where the Translation links to *another* gloss:

```python
for gloss in Gloss.objects.filter(lemma__dataset__acronym="tstMH"):
    print(gloss)
    print(Translation.objects.filter(sensetranslation__sense__glosssense__gloss=gloss).exclude(gloss=gloss))
```

**Comment by susanodd** [comment]
Okay, thanks for investigating, @vanlummelhuizen!

There's still some weirdness because of the empty Keyword being used for all new glosses.
That seems to connect all glosses.
I removed that code, so new glosses won't have it anymore. (Senses branch.)
