### ISSUE TITLE
Error in creating new signs/lemmas

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#892]
We encountered some problems in adding new signs to the NGT dataset, possibly related:
* When we try to add Annotation glosses AFSTEMMEN/TO-ATTUNE, with the same values for Lemma glosses, we get the error 'value not unique for lemma 42674'. Lemma 42674 does not exist, however (at least that's what the system tells me when I try https://signbank.cls.ru.nl/dictionary/lemma/update/42674). Searching for Dutch lemma AFSTEMMEN or English lemma TO-ATTUNE, nothing comes up.
* When we try to add Annotation gloss LAWAAI-B/NOISE-B, and search for a possible existing lemma, entering 'LAW' leads to a suggest list with two existing Lemma glosses LAWAAI-B -- but that shouldn't be possible, lemma glosses need to be unique within their own list. 
* Another area for improvement while you're at it: Selecting the first LAWAAI-B to link to leads to the error 'Annotation ID Gloss not unique', which is correct because NOISE-B already turns out to exist -- for Dutch Annotation ID Gloss RUIS. To help data entry, it'd be helpful to tell the user this in the error message: 'The English Annotation ID Gloss X already exists, in combination with the Dutch Annotation ID Gloss Y' (and vice versa for Dutch ... English).'
* And finally: the radio button in this new sign window for looking up existing lemma glosses to link to is set to Dutch by default, but it leads to searching for English glosses. Only toggling back and forth gives me Dutch glosses.

**Comment by susanodd** [comment]
If you search in the Lemma List search panel on LAW in the Dutch field,
it shows that there are two matches, but one of them has nothing filled in for English. (lemma 5120)
The combination of languages is what's unique.

[This was causing problems when the translations were first introduced. You can update the English to make it non-empty. The preview lookahead menus where you select the lemma make use of all the translations. The database thinks these are two separate lemmas because one just has "" as its translation. The lemmas already existed and were in use before the constraint was added. The Update form should let you repair the one that has an empty field.]

**Comment by susanodd** [comment]
As a sidenote, the gloss videos are stored under 
`glossvideo / DatasetAcronym / <first two characters of Lemma> / .... glossid.mp4
`The lemma is being used, not the annotation.

On the server the NGT videos are stored under the first two characters of the Dutch Lemma.
For some datasets this is English, because of the character sets.

**Comment by susanodd** [comment]
[BUG IGNORE NOTE TO SELF This might be related to #889 .
I tried selecting all datasets to see if the missing lemma could be from another dataset.

I did a search on "test" in field Lemma English.
Then found a tstMH gloss to view, wesseltest6. Then went to view its Lemma Group. This yields two glosses.
But to my surprise the display fills in the annotation in all the language columns not just those of the dataset.]

**Comment by susanodd** [comment]
NOTE TO SELF
In the Admin there are some Lemmas without a dataset.
However, at the moment, it's not possible to assign a dataset.
Neither in the Admin nor via the lemma update (it gives an error that the dataset is missing, then doesn't display the form).
This was once done to prevent users from doing this, since a gloss belongs to a dataset via its lemma (where the dataset is stored.)

**Comment by susanodd** [comment]
I suspect the error that the Lemma disappeared is linked to it being created but then something went wrong and it wasn't deleted. (Bug) (NOTE TO SELF)

**Comment by susanodd** [comment]
There is a similar problem with LOPEND-VOORTBEWEGEN (lemma)
There are actually two lemmas, but one has missing English, so it doesn't put the variants in the same lemma group.

In the Admin, there two Lemmas:
LOPEND-VOORTBEWEGEN
LOPEND-VOORTBEWEGEN-B

BUT THESE HAVE NO DATASET

There is also a lemma with BOTH languages that has NGT as the dataset.
LOPEND-VOORTBEWEGEN

The gloss  LOPEND-VOORTBEWEGEN-B
was created recently, it was involved in another issue with videos not displaying.

It looks like it's the missing English of old lemmas that is causing them not to be found.
We since have required English to exist otherwise sorting doesn't work.

**Comment by susanodd** [comment]
@ocrasborn what you describe as happening corresponds to the way the code has been written.

In searching for lemma's in the pull-downs:
At one point, the Dataset default language is used.
At another point, the interface language is used.
(So this has a side effect if English is missing, since you can't search with the "lookahead" on an empty string. )

**Comment by susanodd** [comment]
@ocrasborn :
> - And finally: the radio button in this new sign window for looking up existing lemma glosses to link to is set to Dutch by default, but it leads to searching for English glosses. Only toggling back and forth gives me Dutch glosses.

This part has been repaired. It's live now.
(Make sure to reload the page to use newest javascript code for lookahead.)

**Comment by susanodd** [comment]
@ocrasborn can you try this again:

> - When we try to add Annotation glosses AFSTEMMEN/TO-ATTUNE, with the same values for Lemma glosses, we get the error 'value not unique for lemma 42674'. Lemma 42674 does not exist, however (at least that's what the system tells me when I try https://signbank.cls.ru.nl/dictionary/lemma/update/42674). Searching for Dutch lemma AFSTEMMEN or English lemma TO-ATTUNE, nothing comes up.

Since the lemma's with empty datasets have been removed, and the "pre-selected" language now works in the Add Gloss template, I don't get any problems with this bullet.

I was able to successfully create a new gloss as decribed for AFSTEMMEN/TO-ATTUNE with the same values for the lemma fields.
(Tested LOCALLY in dataset tstMH.)
