### ISSUE TITLE
Can't assign users to datasets on new server

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#903]
Looking up of existing users on /datasets/manager is not working, so I cannot assign users to datasets (or withdraw permissions)

**Comment by Jetske** [comment]
Actually, I'm not sure if this will become a problem: I changed the 'view_dataset' permission to 'can_view_dataset' because Django added it as default permission and I suppose that doesn't work well together. But 'view_dataset' is still as permission in the database right, or does Django/a migration handle that already?

**Comment by susanodd** [comment]
I was already looking at the code of this page because one of the tests for export ECV was broken.

I noticed the manage datasets page does not restrict to the selected datasets.
(That could have a side effect because the individual permissions are per dataset.)
(Scope of the variables might be doing something. Wondering out loud. Nested variable scopes and reuse of the perms.)
(The permissions of the user are checked as well as "other" users.)

**Comment by susanodd** [comment]
This is the problem:
```

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://signbank.cls.ru.nl//dictionary/ajax/user/m. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://signbank.cls.ru.nl//dictionary/ajax/user/m. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://signbank.cls.ru.nl//dictionary/ajax/user/e. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://signbank.cls.ru.nl//dictionary/ajax/user/e. (Reason: CORS request did not succeed). Status code: (null).
```

It's not allowing the ajax call to obtain the users

**Comment by susanodd** [comment]
The javascript:
[var url = .....](https://github.com/Signbank/Global-signbank/blob/11321692875241ab97f024536d6f8ca15ba403a3/signbank/dictionary/templates/dictionary/admin_dataset_manager.html#L13)

is being assigned signbank rather than signbank-new

**Comment by susanodd** [comment]
This works correctly on localhost server on Safari.

It's the hard-coded URL setting shown above. (The settings on server_specifc on the new signbank.)

**Comment by susanodd** [comment]
I removed the suspected bug. 

> The javascript: [var url = .....](https://github.com/Signbank/Global-signbank/blob/11321692875241ab97f024536d6f8ca15ba403a3/signbank/dictionary/templates/dictionary/admin_dataset_manager.html#L13)
> 
> is being assigned signbank rather than signbank-new

Hopefully it solves the bug on the new server. In any case it didn't break it on localhost.
(Needs to be deployed to new signbank.)

**Comment by susanodd** [comment]
This is live. It works now!
