### ISSUE TITLE
Cannot add lemma while editing existing sign

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#921]
This is related to #892, just closed, but it's a rather specific bug so a new issue: I use the new button 'Create New' under Lemma Gloss while editing an existing gloss, but get an error when I confirm the new values. "name 'self' is not defined" is the message. (Editing an existing lemma 'in-line', so in the detail view when editing a gloss, works fine, and so does 'Choose Other'.) Working on Chrome/Mac.

**Comment by susanodd** [comment]
When I try it, I'm getting the closed database error (#441)
That error is happening quite a lot now. (That's on Global. I'll try it locally.)

**Comment by susanodd** [comment]
The error might arise because the "lemma" field is stored inside the gloss, and the "dataset" field is stored inside the "lemma" (not inside the gloss). There is code in the form template iterates over the `gloss.lemma.dataset.translation_languages` in order to display the lemma translation fields.
So if you change the lemma it is probably having a side effect on that expression, since reference to the translation languages would disappear. And the new to create lemma would need to be in the same dataset, and be stored in the gloss before you would know the gloss was still in the same dataset. (It's like a chicken or egg scenario.)

**Comment by susanodd** [comment]
@ocrasborn I found something else in the relevant code:

https://github.com/Signbank/Global-signbank/blob/baaa21f6e57827902d53759865b64f63e09c673f/signbank/dictionary/adminviews.py#L7072-L7075

In the query that checks whether the combination language, text already exists, it's converting the text to upper case.
Is that still relevant? (@vanlummelhuizen ?)

**Comment by susanodd** [comment]
> This is related to #892, just closed, but it's a rather specific bug so a new issue: I use the new button 'Create New' under Lemma Gloss while editing an existing gloss, but get an error when I confirm the new values. "name 'self' is not defined" is the message. (Editing an existing lemma 'in-line', so in the detail view when editing a gloss, works fine, and so does 'Choose Other'.) Working on Chrome/Mac.

Yes, it's true the self is not defined in the function that is being called!! Here it is:
https://github.com/Signbank/Global-signbank/blob/baaa21f6e57827902d53759865b64f63e09c673f/signbank/dictionary/adminviews.py#L7120

**Comment by susanodd** [comment]
@ocrasborn this is live now!!!!

**Comment by ocrasborn** [comment]
That was quick, thanks @susanodd !
