### ISSUE TITLE
Add option to delete lemma after searching for it

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#930]

**Comment by susanodd** [comment]
Ahah. Good find. I just tried searching. At the moment, it's only offered to delete ones with 0 glosses.

This is kind of a safety net, because a Gloss **must** have a lemma because the Dataset is stored in the Lemma.
So you can't actually delete Lemmas that have glosses linking to them.

Do you need some other functionality like a multi-step swap with a different lemma?

Probably the Lemma Search Page (Show All Lemmas) ought to not show the list until the user has searched?
Since it takes a long time for NGT.

**Comment by susanodd** [comment]
I tried exporting the lemmas of NGT and tstMH. Then changed exactly one missing English entry.

However, Import CSV Lemmas (which should allow you to fill in all the missing English translations), the import is broken!!

I exported from Numbers via Export to CSV. But none of the delimiters on the template works.

**Comment by susanodd** [comment]
@ocrasborn I added a command under the Datasets menu:
Show Glosses Without Lemma

This shows the annotations and languages for the glosses.
It doesn't yet offer to assign a dummy lemma to a gloss. It only shows the choices.
As can be seen, they're not all from NGT.

The "view" code creates the necessary dummy lemmas for each dataset, with resp. lemma translations for the dataset's languages.
(The dummies have already been created as it only creates them once.)
The page shows the lemma choices (that have the necessary languages).

![dummy-lemmas-per-dataset](https://github.com/Signbank/Global-signbank/assets/24272544/eef74003-0f32-41e5-91d3-7add7c14dc20)

**Comment by susanodd** [comment]
@ocrasborn I'm working on a button to set the chosen (dummy) lemma once the "dataset languages combination" is selected for the gloss in the Show Glosses WIthout Lemma template (under Datasets).

It's perhaps confusing because the glosses without lemmas also do not belong to any dataset.
(The lemma field is in gloss, and the dataset field is in lemma. So because the glosses do not have a lemma, they do not have a dataset.)
The page shows all such glosses. But once you want to assign a lemma, then probably the selected datasets is going to mess this up the permissions for the gloss. Something like "grab a gloss" if it's allowed, it has the right translations for your dataset.

(This is also why we can't just delete lemmas. That's why the lemma search page allows to delete lemmas with no glosses.)

**Comment by susanodd** [comment]
@ocrasborn I modified the view to show a Save button to save the gloss to an appropriate dataset. (Via the dummy lemmas we talked about.)

Since you're superuser, you will be able to modify them. Otherwise the user must have change_dataset permission for the target dataset. (Hardly any users have this permission.)

I tried this out with numerous combinations, also using a test user and kept modifying what that user was allowed to do.

Some of the glosses have PHONOLOGY filled in!!!!

![glosses-without-lemma-assign-dataset](https://github.com/Signbank/Global-signbank/assets/24272544/84179673-a659-4c73-88c2-82e6eee13b4c)

Note, while you're on the template, you can actually apply the Save a couple of times.
But once you reload the page, the gloss is in the last dataset / lemma you assigned.

I used the save on one gloss that was obviously a test gloss and put it in tstMH.

Here's what it looks like now with it's dummy lemma.

![tstmh-assigned-dummy-lemma](https://github.com/Signbank/Global-signbank/assets/24272544/afae7e2a-5c1e-4d93-86de-38589d1c67fa)


The Gloss Detail View now has the Copy button, so you can always copy it to another dataset that way.

**Comment by Woseseltops** [comment]
Sounds like this is done? Feel free to reopen if not
