### ISSUE TITLE
Error when entering only a single plus sign (+) in the Search Gloss field

### ISSUE THREAD

**Issue by vanlummelhuizen** [Signbank/Global-signbank#938]
When entering only a single plus sign (+) in the Search Gloss field in the header, you get

OperationalError at /signs/search/
user-defined function raised exception

This is probably also the case for other incorrect regular expression strings.

**Comment by susanodd** [comment]
This is pretty weird. I'll investigate.

**Comment by susanodd** [comment]
Since validate isn't done the existing code actually doesn't actually cause the error until it attempts to sort the results.

I inserted a call to a function that checks all the language search field text for a plus sign at the start.
That now happens before any query is constructed. It gives feedback to the user and returns no results.

I need to see how to make it explicitly refer to the problem in the search form. As described in #954 the gloss search form doesn't validate anything. It's also non-trivial to add this since we have a mixture of model fields and form fields, with dynamic data, and we also use multi-select and dynamically generate choice lists, model translations, etc. This adds lots of extra code as part of generating the template. (I couldn't figure out how to add validation for the DateFields. So here, I added an extra check function for the language fields.)


![glosssearch_plus_sign_show_message](https://user-images.githubusercontent.com/24272544/232466515-21966f7b-7a83-4536-8c87-57e711da7c43.png)

**Comment by susanodd** [comment]
Any other special characters we need to check for?

**Comment by susanodd** [comment]
I revised it a bit to show the field labels in the error message.

![plus-sign-error-message-gloss-search](https://user-images.githubusercontent.com/24272544/232476185-c505e1c7-c532-44ca-834f-b6f6a84bc8dd.png)

**Comment by susanodd** [comment]
The tests had an error. In the url of a search (generated by the gloss search form) all of the parameters are present, even the ones not filled in.
The tests only have some parameters in the url.
The tests discovered that the code did not check whether the language parameters were present.
This has been repaired.

**Comment by susanodd** [comment]
This is live now.

**Comment by vanlummelhuizen** [comment]
@susanodd I still get an error. I do the following:

![image](https://user-images.githubusercontent.com/16682631/233384055-54e0fbb3-3ee0-4efa-9f21-a64c2ced2c74.png)

and I get this:

![image](https://user-images.githubusercontent.com/16682631/233384507-bdefd39e-cd31-4e45-ad6e-53e7206909a7.png)

**Comment by susanodd** [comment]
Hmm. Well I was going to ask if you reloaded. But I can't actually load the session I was in.

**Comment by susanodd** [comment]
```
<h1>OperationalError
       at /logout/</h1>
  <pre class="exception_value">database is locked</pre>
  

Request Method: | GET
-- | --
http://signbank.cls.ru.nl/logout/
4.1.7
OperationalError
database is locked
/var/www/env/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py, line 357, in execute
django.contrib.auth.views.LogoutView
/usr/bin/uwsgi
3.10.6


```

**Comment by susanodd** [comment]
```
<h1>TransactionManagementError
       at /accounts/login/</h1>
  <pre class="exception_value">An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.</pre>
  

Request Method: | POST
-- | --
http://signbank.cls.ru.nl/accounts/login/
4.1.7
TransactionManagementError
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
/var/www/env/lib/python3.10/site-packages/django/db/backends/base/base.py, line 520, in validate_no_broken_transaction
signbank.registration.views.mylogin
/usr/bin/uwsgi
3.10.6


```

**Comment by susanodd** [comment]
After successfully logging in.

![live-server-search-plus](https://user-images.githubusercontent.com/24272544/233388811-5e3f9a90-4aea-4afa-ac16-220bf3da9595.png)

**Comment by susanodd** [comment]
It seems old sessions are persisting somehow. It took lots of fiddling to login again.
I used to site first while being logged out to search to make sure the old session would be killed.
Then logged in, then searched on a + in the Gloss (Dutch) field. It works correctly for me on the live server.

**Comment by susanodd** [comment]
This works as shown above.

**Comment by susanodd** [comment]
Okay, I see you typed it in the menu bar.

It looks like this a **Django / Python upgrade** thing. (Unless nobody ever typed in a plus sign in the past 10 years..)

It looks like **all** the text fields in the forms have this same problem, also the Annotation Instructions.

Basically all the text fields of all the forms need the same code applied.

**Comment by susanodd** [comment]
Did you trying typing in other character sets?

**Comment by susanodd** [comment]
The solution catches the plus signs in the other fields, but this is causing problems with trying to _( ) the field labels in the message.

Another problem, should this be an error? Or can this be escaped?
I found some additional code that deals with the menu bar, but this is in the context data for pre-filling the form.
The current code removes an ending backslash from the input. (No error message for this, it just does it.)

https://github.com/Signbank/Global-signbank/blob/7749caa278911a9bcca6c4f7cd6474f90ae02171/signbank/tools.py#L2096-L2105

**Comment by susanodd** [comment]
Related to this:

https://github.com/Signbank/Global-signbank/blob/7749caa278911a9bcca6c4f7cd6474f90ae02171/signbank/dictionary/adminviews.py#L367-L380

That code is pretty weird if the user has entered a plus sign. (Which is basically a no-op if it's removed and there's nothing else.)
I'm modifying it to escape the plus sign as for the ending backslash which is already done.)

Unfortunately it's not possible to use form validation for any of these. (The forms are too dynamic and too complex. The majority of form fields are created in the form `__init__` method, as they take dataset languages as a dynamic parameter, plus dynamically obtain the field choices.)

**Comment by vanlummelhuizen** [comment]
Some other characters that also result in a error: 
- `*` (asterisk)
- `[` (opening square bracket, NOT the closing one)
- `(` and `)`
- `?`

**Comment by susanodd** [comment]
I'm removing that code just quoted. It's filling a context variable that is actually no longer used in the template.
It was getting really weird side effects because stuff had been done to the field. (Although probably now those additional characters will be needed, plus the backslash.)

There is code at some places removing characters and code other places adding characters (escapes). Probably because of all the usage of utf-8 before that became the standard.

**Comment by susanodd** [comment]
Okay, it's working okay now. It's possible to try out just a + (then get an error message) then try out \+ and see results that include a plus sign.

Although when the error message shows, the field has already been made empty. (The normal language fields the non-escaped plus sign remains visible.)

**Comment by susanodd** [comment]
I suspect the code I removed was intended to put the menu bar fields back in the form. (Although it's not being used anymore.)
The menu bar query is treated differently that the other fields because it's actually in the menu code.
So probably need a condensed form that just fills the menu. (Because otherwise it's difficult to see what the message is about if the field is empty.)

**Comment by susanodd** [comment]
![menu_bar_search_plus](https://user-images.githubusercontent.com/24272544/233629042-2b8b12fb-a659-4f7b-906e-e00a40b3b83f.png)

**Comment by susanodd** [comment]
The updates to the gloss search / gloss list template menu bar are deployed and live.

Probably need to expand the issue title now. The menu bar fields are everywhere.
Also need the new special characters.
Plus all the other text fields (other than the language fields).

I had to add a form declaration for the message label, since generating the message didn't like the `_( ) `labels.
(See the two label declarations below without translation. Later the gettext is applied to these.)

https://github.com/Signbank/Global-signbank/blob/e2f4936e35d5ce3451ee33591e261243e34c33f6/signbank/dictionary/forms.py#L330-L331

https://github.com/Signbank/Global-signbank/blob/e2f4936e35d5ce3451ee33591e261243e34c33f6/signbank/dictionary/forms.py#L415

https://github.com/Signbank/Global-signbank/blob/e2f4936e35d5ce3451ee33591e261243e34c33f6/signbank/dictionary/forms.py#L437-L443

**Comment by susanodd** [comment]
Hmm. This is kind of weird. All the pages where the menu bar is visible that get handled by a view/template will need to accommodate the menu bar fields.
Although when you enter data in the menu bar search while being in a different page, it redirects to the gloss search page (to show the results).

**Comment by susanodd** [comment]
I may have found something relevant.
I'm working on the MorphemeSearch now (#936) and checking the same things as for the GlossSearch.

Luckily, the menu fields redirect to the sign/search template, so those don't cause problems in the rest of the code.
But the checks for the e.g., plus sign is still needed for the normal (language) fields.

With one discrepancy, the Annotation Instruction on Gloss Search causes the same error if you enter a plus.
But on Morpheme Search it does not.
The difference, the query itself:

Gloss Search:

https://github.com/Signbank/Global-signbank/blob/e2f4936e35d5ce3451ee33591e261243e34c33f6/signbank/dictionary/adminviews.py#L1074-L1076

Morpheme Search:

https://github.com/Signbank/Global-signbank/blob/e2f4936e35d5ce3451ee33591e261243e34c33f6/signbank/dictionary/adminviews.py#L2612-L2613

The difference is the filter `__iregex` (causes error on `+)` versus `__icontains` (does not cause an error on `+)`

**Comment by susanodd** [comment]
The modifications for the morpheme search page are done. That's live now.

Still a few other templates left to do. (Plus other characters and other regex searched text fields.)

**Comment by susanodd** [comment]
I added the checks for FocusGlossSearch minimal pairs and HandshapeSearch name field.
The latter has a new function that checks the 'name' field (of model translations) for the class model parameter.

**Comment by susanodd** [comment]
Here's the error message showing for the Handshape Name field in EN and NL.

![search-handshape-en-special](https://user-images.githubusercontent.com/24272544/234260616-2b207dbd-686b-4608-ac76-ffd4034716cc.png)

![search-handshape-nl-special](https://user-images.githubusercontent.com/24272544/234260642-21b7791d-7b83-48a5-ab81-9ea8f589f022.png)

And escaped (by the user):

![search-handshape-nl-plus](https://user-images.githubusercontent.com/24272544/234260733-278bf82c-0672-4842-8c70-995634a585f8.png)


(I just noticed duplicate search field labels in the search form. Multiselect as well as non.)

**Comment by susanodd** [comment]
The Lemma List View also checks for special characters now.

I also revised the `check_language_fields` function to make sure the fields exist in the form. Now it works on whatever form is given.
However, some form field names are hard coded. (This is a bit weird. We can't really check whether attributes exist in a given form without already knowing what attributes we are looking for. I made it so the same names are used in the different forms.)

**Comment by susanodd** [comment]
@vanlummelhuizen I added the other special characters. Also the case for ending with a plus.
(It seems it's okay to use it infix.)

**Comment by susanodd** [comment]
The remaining fields that use a query filter `__iregex` are:
useInstr
Definistion.text
createdBy
RelationToForeignSign.other_lang_gloss

I modified them to `__icontains`

There are some miscellaneous gloss fields of type text that are also filtered using `__iregex` inside of loops that construct searches based on field type

**Comment by susanodd** [comment]
This is completed.

**Comment by susanodd** [comment]
This may not work for regex anymore.

**Comment by susanodd** [comment]
This is the code that solved this issue:

https://github.com/Signbank/Global-signbank/blob/2fa094c47c9a042637c25b68be5fcbd73ba1cb15/signbank/dictionary/forms.py#L354

It's looking for this:
```
    # check for matches starting with: + * [ ( ) ?
    # or ending with a +
```

The check for this follows the check on a well-formed regular expression.

The question is, such a well-formed regular expression as this:
`[a-z]`
is not allowed.
Something about this might be needed in the tooltip.
Since such an expression gets flagged that backslashes are missing.
