### ISSUE TITLE
Users' dataset selection is not effectuated

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#940]
I have no problem, but it seems non-superuser users can select a dataset like they normally do, but it doesn't actually have any effect: the header doesn't show the white highlight for the selected datasets, and searching whatever (or 'show all signs') leads to no hits. I double-checked this on two computers with the dataset-test user. (The page Dataset > Select Datasets saves the checkmarks correctly though, and in the admin I do see the dataset selection correctly in the user profile.)

**Comment by susanodd** [comment]
Why was this code removed @Jetske ?

https://github.com/Signbank/Global-signbank/commit/aefad1b84bbed0cefdea6c7dc161e32d520b9a1e

**Comment by susanodd** [comment]
I see that a permission was removed. 'view_dataset' was removed. Because Django has a 'can_view_dataset'.
But originally, I think this was added on purpose in order to distinguish between viewing the Dataset (object) versus the glosses in the dataset.
@vanlummelhuizen  ?

I'm trying to debug what is going on with the Select Datasets template. If the user isn't a superuser, it's not showing anything.

**Comment by susanodd** [comment]
There is something very weird going on with this code.
In the get_queryset method, all the datasets are present in object_list.
But by the time the template displays, only one dataset remains.

It seems to be something with this:
https://github.com/Signbank/Global-signbank/blob/79fa56e8228a7050c751dbc99c16f262a71dfb5c/signbank/dictionary/adminviews.py#L4738-L4757

At the end, before the `return qs`, the qs contains all the datasets.
But by the time the object_list is displayed in the template, there is only one in the list.
Perhaps the permissions are evaluated dynamically and it throws away objects from the query?

**Comment by susanodd** [comment]
A logged out user can now view more than a (newly created) user.

**Comment by susanodd** [comment]
@ocrasborn can you try this again?

Hopefully it is fixed now.

I lost the test user passwords when I upgraded Ubuntu, so I can't test this on the live server myself.

**Comment by ocrasborn** [comment]
Nope, @susanodd , don't think so. Same problem. Emptied cache to be sure, no difference. Interesting: the dataset selection is displayed correctly on the lists of available datasets page (/datasets/available).

**Comment by susanodd** [comment]
This is probably tied to the 'can_view_dataset' permission (as described above).
Old users have the 'view_dataset' permission. But the code now tests for 'can_view_dataset'.

**Comment by susanodd** [comment]
I found another inconsistency.
The 'selected_datasets' is used everywhere as a context variable.
But it is also used as a session variable. (with exactly the same name, selected_datasets)
The session variable is used in the context_processor.py code (which determines the header).
Both implementations live along side each other.
But they actually have different types. The session variable is a list of acronyms. Whereas the context variable is a query of dataset objects.

**Comment by vanlummelhuizen** [comment]
@susanodd It seems one of the two `selected_datasets` is unnecessary. How does the code arrive at the context variable? Can you point us to pieces of  code to see for ourselves?

**Comment by susanodd** [comment]
I'm still trying to figure it out!

The actual "updating" is done in update.py

**Comment by susanodd** [comment]
I see I have a console.log in the admin_dataset_select.html file.
https://github.com/Signbank/Global-signbank/blob/1ca8ad3dc41b31122995b421aec03632b295f65f/signbank/dictionary/templates/dictionary/admin_dataset_select_list.html#L15
(I removed that since it was generating a syntax error.)

In the template, there are some template commands that are flagged in PyCharm
https://github.com/Signbank/Global-signbank/blob/1ca8ad3dc41b31122995b421aec03632b295f65f/signbank/dictionary/templates/dictionary/admin_dataset_select_list.html#L57
(it says the part surrounding the checked is not allowed here.)

**Comment by susanodd** [comment]
> @susanodd It seems one of the two `selected_datasets` is unnecessary. How does the code arrive at the context variable? Can you point us to pieces of code to see for ourselves?

It seems that maybe the context variables couldn't be passed "up" to the menu bar?
The menu bar uses the session variable.
Except it's because it has to support users that are not logged in, that they can also select datasets (!!)
Anonymous users don't have a user profile, and hence no selected datasets.

**Comment by susanodd** [comment]
NOTE TO SELF:
I vaguely recall that some modifications to selected datasets were done (back in the days of field choices).
Because of the different types. Plus some code was using "name" and other code was using "acronym".
(Those have hopefully all been fixed. But it's possible with all the updates that something got messed up or reverted during merging.)

**Comment by vanlummelhuizen** [comment]
@susanodd It is the can_view_dataset vs view_dataset permission problem: if you change `can_view_dataset` to `view_dataset` in https://github.com/Signbank/Global-signbank/blob/1ca8ad3dc41b31122995b421aec03632b295f65f/signbank/tools.py#L1560 it works again. 

So we probably need to iron out all the can_view_dataset vs view_dataset discrepancies. Perhaps make a specific issue for it.

**Comment by Jetske** [comment]
If I remember correctly it gave an error that 'view_dataset' wasn't allowed as it was a default permission, that's why I changed it to 'can_view_dataset'. Maybe removing 'view' from default_permissions could make it allowed again, I'm not sure though. https://docs.djangoproject.com/en/4.1/releases/1.7/

**Comment by susanodd** [comment]
Okay, now that I can see the Admin on my local server, here is what "adding permissions" looks like:

![adding-permissions-for-user](https://user-images.githubusercontent.com/24272544/229788974-5cd5fd17-eeff-421a-803c-ad8ac4f41895.png)

There seem to be two identical "dictionary|dataset|View dataset" permissions in the list to choose from.....

**Comment by susanodd** [comment]
@vanlummelhuizen can you please help? What's going on here?

**Comment by ocrasborn** [comment]
I think it looks good now @susanodd @vanlummelhuizen , both Lianne and the data manager test user can see data again, search for signs, etc.

**Comment by vanlummelhuizen** [comment]
@susanodd Good work solving this. I made an issue to see whether this should be ironed out elsewhere: #946

**Comment by ocrasborn** [comment]
Sorry all @susanodd @vanlummelhuizen , not quite solved yet: when selecting one of the items in the 'Recently added signs', the person who added the items gets the message 'The gloss you are trying to view is not in a dataset you can view.' Confirmed by me by logging in as the dataset test user. I imagine this must be related, but feel free to open a new issue :-)

**Comment by susanodd** [comment]
Hmmm. That's interesting. There are actually two urls for recently_added(_glosses)

https://github.com/Signbank/Global-signbank/blob/591dbecb087afb3ae182f35846ac0bd3c6473433/signbank/urls.py#L81

https://github.com/Signbank/Global-signbank/blob/591dbecb087afb3ae182f35846ac0bd3c6473433/signbank/dictionary/urls.py#L63

The first one is linked to by the navigation bar Signs pulldown

**Comment by susanodd** [comment]
I think I know what it is.

**Comment by susanodd** [comment]
I have updated the code so that all the places that look up 'can_view_dataset' (read permissions) also look up 'view_dataset' (old permission name, legacy code).
And the places that assign (new) view permissions use 'can_view_dataset', as per new Django, @Jetske :



> If I remember correctly it gave an error that 'view_dataset' wasn't allowed as it was a default permission, that's why I changed it to 'can_view_dataset'. Maybe removing 'view' from default_permissions could make it allowed again, I'm not sure though. https://docs.djangoproject.com/en/4.1/releases/1.7/

**Comment by susanodd** [comment]
Hmmm. Something related to this. I can't check this on the live server.

The "test" user on my local machine can now see the Manage Datasets page. (But then not actually do anything, a warning shows up that the user must be in group Dataset Manager.)

Can you check this @ocrasborn if on the live server, a "non-dataset manager" can see this in the pull-down?

**Comment by vanlummelhuizen** [comment]
> I have updated the code so that all the places that look up 'can_view_dataset' (read permissions) also look up 'view_dataset' (old permission name, legacy code).

Isn't it possible to give users the new can_view_dataset permission if they also have the old view_dataset permission, and then just test for can_view_dataset permission and remove (checking for) the old view_dataset permission altogether? See also #946.

**Comment by susanodd** [comment]
In the amin (locally), I tried out a bunch of get... functions on 

https://github.com/Signbank/Global-signbank/blob/513579cc9f15609c2298989f26e66d49472c399e/signbank/dictionary/admin.py#L21

The (Django Admin) function:

def get_obj_perms_base_context(self, request, obj):

which calls super()

can be used to obtain context field 'model_perms'
which has a bunch of Permission objects, with fields 'id', 'name', and 'codename'.
The 'name' field is the "View dataset" string.

**Comment by susanodd** [comment]
In the Admin, it actually looks like the Object Permissions under (a specific) Dataset, that the can_view_dataset permission is the one that's wrong. This should not be assigned to new users.
The column on the right (the old view_dataset), seems to come from the Group permission.

And the Manage Datasets page only is restricted by the Group Permission. (There are no individual permissions on Page objects.)

**Comment by susanodd** [comment]
In the admin under Dataset Object Permissions, the "first" occurrence of View Dataset (in the columns, left to right), that is the "can_view_dataset" permission. Nobody actually has that permission for NGT.

**Comment by susanodd** [comment]
See pull request #948

**Comment by susanodd** [comment]
> > I have updated the code so that all the places that look up 'can_view_dataset' (read permissions) also look up 'view_dataset' (old permission name, legacy code).
> 
> Isn't it possible to give users the new can_view_dataset permission if they also have the old view_dataset permission, and then just test for can_view_dataset permission and remove (checking for) the old view_dataset permission altogether? See also #946.

After inspecting the code (see snippets above and screenshots) it seems we can just remove the (renamed) permission can_view_dataset and use the original one view_dataset (which doesn't need to be declared anymore, basically).

**Comment by susanodd** [comment]
I put the code that checks for both live, since discussing it didn't happen.

This should solve the issue and allow users to work.

Meanwhile, it's probably necessary to create an explicit manage_dataset permission to user in combination with the group Dataset_Manager, but for specific datasets.

**Comment by susanodd** [comment]
I found a related example and repaired it.
(If you switched from multiple datasets to a single dataset, or otherwise removed datasets from your selection, this was causing problems with the scroll bar, since it included the previous search.
To fix this, if you change the selected datasets, the previous search results are removed from the session, so they don't show anymore.
Recall that you can now save queries, so it's easier to redo things again.)
(The minimal pairs now requires a single dataset, to avoid huge processing times.)
