### ISSUE TITLE
Move data from fields 'translation equivalents' to new fields for 'sense'

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#965]
1. This follows on #884 
2. After this has happened, the fields for translation equivalents can be deleted from the database
3. ...and from the detail view
4. ...and from the list view
5. ...and from the search form [see #966 ; #964]
6. ...and from the CSV export
Did I forget anything?

**Comment by susanodd** [comment]
I see there is an issue for this now. I started contemplating this in #884 in relation to the existing translations.

> I noticed in your example that some of the comma-separated things are grouped together.
> At present, as translations are, the comma is used to separate them into (possibly multi-word) keywords, each of which is stored in the database as a keyword. Then there is translation (relation object) between the gloss and the keyword.
> At present, the keywords are sorted by text.
> (So any implied grouping together of keywords that appear next to each other doesn't happen.)
> 
> (This could impact a migration mapping current keywords to senses. Probably a human will need to do something. Perhaps export keywords to csv and (manipulate to group them) then import them again as senses. By a human.)

> I tried searching on translations with a "," (by just searching on comma) to see what happens. There is only one result, the gloss 1,5
> 
> https://signbank.cls.ru.nl/dictionary/gloss/2895/
> 
> It has two keywords, 1,5 and anderhalf
> The comma is inside the first one.
> 
> It works to search on "non-empty" translations using ".*" as the search term.
These can then be exported to csv.
> (With the intention of exporting the existing ones in order to group them, to import them again as senses, to accomplish migration.)

**Comment by susanodd** [comment]
If all the current translations/keywords of a gloss are not separate senses, but just one sense, then this should be okay to migrate.

But if a gloss has multiple senses then the translations/keywords will need to be grouped.

I just tried to check in the database for gloss BRUS-A (2693) to see what's actually in the database fields.
There is a field `index` in the translation (relation between keyword and gloss).
@ocrasborn  Would you recognise if they are sorted by the index if this is the order in which they were entered, and whether the displayed translation keywords represents sequential senses, if more than one sense is present?
For this gloss, ordered by index:
<body>

broer
neef
nicht
vriend
vriendin
zus
iemand die dichtbij je staat op hetzelfde niveau

</body>

**Comment by susanodd** [comment]
Here's gloss BRUS-C (1311):

<body>

broer
zus
vriend
vriendin
broers
zussen
vrienden

</body>

Those are ordered by the index field.
Given that there were migrations when the translations were made multi-lingual, it's not clear if the index is the order of entry.
Does the ordering above relate to senses? In the example in #884, `broer` and `broers` are in the same sense.

**Comment by susanodd** [comment]
I made a sample list view to display Gloss | Translations | Senses
(This is meant to show what will happen.)

![gloss-translations:keywords-senses](https://user-images.githubusercontent.com/24272544/235626997-18cef441-c08b-43a7-a7b8-fcc0a1ee6fbd.png)

The vertical bar is just syntactical. The (current) keywords (translations) are normally displayed with a comma to separate.

There are two choices for migrating the exisitng translations to senses.
Either use the comma (as it is now) to yield separate senses, or put all the comma-separated things into a single sense.

I'm trying out a middle ground (to be used before migration to group keywords, or after migration to split them into separate senses.)

At present, when the Translations field of a gloss is edited, the split(',') is used to break up the keywords.
This can be modified with a separate function (say as an edit feature in the list view shown above) to allow to "group" keywords by using a vertical bar to split and a comma to join/group them. (Or vice versa.)
Thus allow the "multiple sense" translations to be resolved into (separate) senses.
This will still need to be done by a human.

**Comment by susanodd** [comment]
Here's the idea. The translation objects currently have an 'index' field (the sequential order of keywords when the translation field is edited in Gloss Detail View -- the index is not an object id). Here it's used to artificially group the (current) translations into senses.
The idea is that the user can choose to have them all in one group (same index) resulting in one sense, or move them around to group them (by sharing the same index).

(This would be done before / or after migration, to group keywords.)

![group_translations_into_senses](https://user-images.githubusercontent.com/24272544/235655639-196cd16c-f8c0-4661-8b8d-fb4b5b94ef5b.png)

**Comment by ocrasborn** [comment]
>There are two choices for migrating the exisitng translations to senses.
Either use the comma (as it is now) to yield separate senses, or put all the comma-separated things into a single sense.
>
>I'm trying out a middle ground (to be used before migration to group keywords, or after migration to split them into separate senses.)

Hi @susanodd @Jetske : please put all comma-separated things in a single sense (index 1) for now. Signers will then manually move words/phrases to separate senses if appropriate. (Using the CSV route when that's modified to include the new sense fields)

**Comment by susanodd** [comment]
Since the Sense model isn't available yet, I've been making mockups using the translations and the index field.

(As shown above.)

What is very weird, the current model does not allow one to change an index of 0 to be 1.
It could be that the field name 'index' has become a reserved word in the new Django.

I tried to implement the screen shown above to allow users to "move" keywords to a different sense.
But it does not work to change the index to 1 of the one that is a 0.

Moreover, the Keywords seem to be also used for Tag labels. (!!)

https://github.com/Signbank/Global-signbank/blob/8945c25c4a830af74c091c9a5214763fcf55a89e/signbank/dictionary/models.py#L195-L208

**Comment by susanodd** [comment]
I modified the admin to make the index field be editable in admin. (On local branch.)
It's now possible to modify the index to be 1 instead of 0.
For some very strange reason, the Translations with index = 0 are not "seen" when looping over all the translations.
This was causing some keywords to be invisible.
There is also a strange thing going on that there exist translations with "" (empty) text as the keyword.
Perhaps ions ago, it was causing a problem to distinguish and empty field (not filled in) as being the wrong type.
This probably happened before the translations were made multilingual.

**Comment by susanodd** [comment]
I want to add a field to the Translation model "sense_index" initialised to 1.
I'm concerned that that weird thing going on with index = 0 is going to mess up migration, since the translations seem to be ignored in comprehensions.

**Comment by susanodd** [comment]
![map_keywords_to_senses](https://user-images.githubusercontent.com/24272544/236188066-cb9d2d64-ec7d-47cb-994c-06d50c4785da.png)

**Comment by ocrasborn** [comment]
Hi @susanodd , from looking at the screen shot: that's a great way for editors to regroup the keywords in senses, thanks! In fact, if editors will have access to this for some time to come, we could immediately remove all the Keyword/Translation Equivalent appearances in the interface, immediately displaying only the Senses.

**Comment by susanodd** [comment]
I'm working on it!

In the process, I added a field to the Translation model to represent the sense number.

But when I went to apply the migration, the unique contraint on Translation failed!
(@Jetske , @vanlummelhuizen , @Woseseltops )

https://github.com/Signbank/Global-signbank/blob/f4d8e01efe183f4a0843ee007516f89247b4d950/signbank/dictionary/models.py#L161

I created a test to check consistency, but since the tests don't run on the actual database, it needs to be a command (for the virtual environment).

There are about 40 glosses with messed up keywords/translations. It seems when a new constaint is introduced, it does not apply to already entered data, only data after it was introduced.
During migration, when I wanted to add a field to Translation (a new field that has nothing to do with the constraint fields), it checked the above constraint for the Translation table and wouldn't let me migrate the database.

The problems are where they are duplicate keywords listed for the same language.

(This may cause problems when migrating to add the new senses in #884 )

In any case, the duplicates need to be removed to get the database constraint to hold. Then we all need to be using a new copy of the database for development.

**Comment by susanodd** [comment]
On the live server, I repaired the translations of the glosses that violated the constraint!

**Comment by susanodd** [comment]
@ocrasborn, I just repaired them by hand on the server. (I'll send a link to a file with the output of the command that detected them.)

**Comment by susanodd** [comment]
I've made this be multilingual. This is to show what it looks like. I'm only using test dataset tstMH for development.

![multilinguage-keywords-mapping-to-senses](https://github.com/Signbank/Global-signbank/assets/24272544/b5e910a4-a126-4fb7-ad4c-0875abac5fab)

![multilingual-keywords-modal](https://github.com/Signbank/Global-signbank/assets/24272544/2d9ce546-228d-4078-bd15-2cd0ff28c3b0)

**Comment by susanodd** [comment]
I modified the mapping view as shown below.
The keywords can also be edited (with appropriate permission), or viewed.

![edit-keywords-mapping-view](https://github.com/Signbank/Global-signbank/assets/24272544/09a0721d-742b-4e50-8c64-a0e953314b6a)

![view-keywords-mapping-view](https://github.com/Signbank/Global-signbank/assets/24272544/67e0dd40-10d9-444f-8b78-4e21ae427532)

At the moment, it's only allowed to edit a specific keyword phrase to fix typos. Updating also modifies the display since it's ajax.

**Comment by susanodd** [comment]
There's a filter now for filtering on Tags. Plus a "quick tag" toggle button for each row so the user can browse the list and tag glosses with "check senses". This toggles only a check senses tag. Then the user can then filter based on this tag to keep refining what is still to be done.

![mapping-quick-toggle-1](https://github.com/Signbank/Global-signbank/assets/24272544/64583d4c-2d58-4253-8893-f4c212369146)

![mapping-quick-toggle2](https://github.com/Signbank/Global-signbank/assets/24272544/d37f5c71-35d8-4d75-922d-e5116e20e8c3)


![keywords-mapping-filter-tags](https://github.com/Signbank/Global-signbank/assets/24272544/21ba80bd-9621-4fca-98fa-e8665218b410)

**Comment by susanodd** [comment]
Hmmm. Perhaps an additional tag for senses okay.

(There are thousands and thousands of NGT signs!)

**Comment by susanodd** [comment]
Pagination has been added to the above so it works now for very large dataset NGT.

This is on the live server now.

@ocrasborn the quick tag feature to tag glosses with "check sense" is available and can already be put in use.
If somebody wants to browse pages and pages of glosses and tag them... :)

**Comment by susanodd** [comment]
The improved version is live now.

**Comment by ocrasborn** [comment]
Hi @susanodd @Jetske Just played around a bit with the function, works great! One request: to change the pagination to 50 items per page -- or add a option to change the pagination yourself like in the regular list view of signs.

**Comment by Jetske** [comment]
@susanodd I said I'd think about a setup that matches the senses in the gloss detail view. Most importantly, I think the languages should be shown together in the modal when regrouping the senses, to prevent that for example Dutch sense number 1 translates to English sense number 2. (Not all language fields are required to be filled. )

![image](https://github.com/Signbank/Global-signbank/assets/10157482/59e31db7-ccd8-48d7-a842-2063340f8d07)

So I suggest something like this where you can change the sense number. Would that be possible?

**Comment by ocrasborn** [comment]
>@ocrasborn the quick tag feature to tag glosses with "check senses" is available and can already be put in use.
If somebody wants to browse pages and pages of glosses and tag them... :)

@susanodd yes, I saw, works well. We won't be tagging endless items, only those that need discussion. So this is a very helpful feature: someone can go through the list and act on it immediately, adding a tag where s/he's in doubt about what to do.

**Comment by susanodd** [comment]
I'm wondering about the word "vriendin" that's a keyword of BRUS-A.

This translates to friend who is a girl, or else to girlfriend.

Same for "vriend" but that is also neutral.

Could perhaps do "best bud". But then there would be endless paraphrasing of things that are being translated....

I'll start out by making a separate modal for "multilingual parallel senses" as shown.
But without adding new senses in the same modal because that could lure one to keep generating more paraphrase translations.
The modal will allow one to fill in translations of senses that already exist for one language.

**Comment by susanodd** [comment]
Here's a go at a matrix.

First, this is what the improved single modal for editing dutch keywords/senses, then the table matrix modal.

![senses-edit-dutch-plaatsen](https://github.com/Signbank/Global-signbank/assets/24272544/bf0a8eb0-0d37-4d44-935a-d118c8f04061)

![sense-matrix-translations-plaatsen](https://github.com/Signbank/Global-signbank/assets/24272544/855f4a01-7510-4852-949f-6cb407e612ba)

**Comment by ocrasborn** [comment]
> I'll start out by making a separate modal for "multilingual parallel senses" as shown.
> But without adding new senses in the same modal because that could lure one to keep generating more paraphrase translations.
> The model will allow one to fill in translations of senses that already exist for one language.

Hi @susanodd , please let's wait with this until we have some more experience with separating the senses. Family terms cross-linguistically are known to be complex in this way, and we shouldn't adapt the whole model for a few difficult cases. The senses are more translation equivalents in the sense that we used to use, not definitions. For more info on semantics we also have a link to a Wordnet in the pocket, and there's already a link to Concepticon under the Semantics panel.

**Comment by susanodd** [comment]
Okay. The first version shown above (showing Dutch) is finished. It's also very basic functionality.
You can either change the "sense number" or "edit the text".

The second one is what @Jetske suggested yesterday. Although that will be difficult to implement if one language surrently has nothing and the other is still inside one sense. Ideally they should be separated before adding translations. That to make sure the sense number corresponds across languages.

**Comment by Jetske** [comment]
I just added a command in [add_sense_examplestc_884](https://github.com/Signbank/Global-signbank/tree/add_sense_examplestc_884) that adds senses to glosses based on their existing translation equivalents. It makes one sense for every gloss, so we can run that for all datasets to get started (at the moment I only tried it for NGT and Kata Kolok and that worked fine). 

The sense mapping page is nice @susanodd but that means it should in the end work together with senses instead of translation equivalents (but we talked about that)


> I'm wondering about the word "vriendin" that's a keyword of BRUS-A.
> 

And about that: actually my example was confusing, sorry. Translations in different languages are not linked and hopefully that just makes it easier. so I think you can add a keyword for one or for multiple languages at once and they will be added separately as single translation objects to different sensetranslations (in red circles). So 'brothers' would be added to 'sisters' in this example. If that makes sense (see below)

![image](https://github.com/Signbank/Global-signbank/assets/10157482/689f25b8-5645-4bef-af88-2119f87ec745)

**Comment by susanodd** [comment]
Great about the command!!

The only piece of information really needed is the object id of the sense. All the "places in the forms" are identified for editing by the gloss id, the language id, and the translation id (so unique within the entire page).

I added an additional dictionary for the "object list" that stores "sense translations", that instead of mapping languages to the keywords and translations, it maps order index to languages to sense translations. Then the loop in the template is over the order index instead of over the languages. (That is what's displayed above to get your matrix. That's what you said you were trying to modify but the loop was over languages.

I'll see if the cells can be marked with the needed information for editting as you show. We probably need the cell label to be suffxed with the e.g.  _nl etc codes. So regroup_nl instead of regroup. (For the index number cell.)
Once the command is applied to create senses, we can just use their ids instead of the translation ids.

**Comment by susanodd** [comment]
Yes, the explaination helps showing it like that.
I started to suspect from the earlier example that they might end up being huge "keywords" instead of separate.

**Comment by susanodd** [comment]
Okay, I see it now. You want the same interface but with an extra column for the other language.
I'm working on getting the necessary ids for the cells so they're unique.

**Comment by susanodd** [comment]
@Jetske regarding the keywords per language per sense as shown in the table, should the "keywords" also be across languages?
Within a sense, does the number of "things" for a particular "sense index" need to be the same across languages?
In the above table, can there be say "three things" for one language for a particular sense and "one thing" for another language?
Pretend the only word I use is "dude" for everybody else. (Or I guess "to be filled in later".)

**Comment by Jetske** [comment]
> @Jetske regarding the keywords per language per sense as shown in the table, should the "keywords" also be across languages? Within a sense, does the number of "things" for a particular "sense index" need to be the same across languages? 

@susanodd No, it doesn't need to be the same. For one language there can be 5 translations, for the other 3 or 0 or 10. 

> Does the thing previously know as "index" play any role?

Which index do you mean?

**Comment by susanodd** [comment]
Yes, the index of the keywords within the sense.

**Comment by susanodd** [comment]
The one on my local host, "vriendin" apparently has a lower "index". Apparently I should put a blank field "next" to it.
(But if I just think of them as "strings" then there's not really anything wrong. It's only because I know "vriendin" doesn't map to "sister". I can actually just edit the right field to change it though. I made all the cells editable. I'll figure out how to make the same number of cells since it just looks weird now.)

**Comment by susanodd** [comment]
You can play with this on the live server. Or merge it into your own branch.

I'll work on it on my branch to fix it. At the moment, you need to reload after changing things to get the modals updated....
(It will be more complicated to get the matrix modal updated because things can change from being an empty cell to being an object.)

**Comment by susanodd** [comment]
@Jetske if I move a keyword from one sense to another, does this have any effect on keywords of the other language?
Is there any relation between a sense keyword for one language and a sense keyword for another language for the same sense order index?
For example, if I have the keyword "broer" (nl) and another keyword "brother" (en) both in sense "1".
If I move "broer" to a new sense "3", should the keyword "brother" also move?
I assume it does not.
Is this correct?

**Comment by Jetske** [comment]
@susanodd yes correct, there is no such relation at the moment

**Comment by susanodd** [comment]
The Keywords Mapping to Senses has been integrated with the Senses as part of #884.
This was necessary because the Senses model is not yet on the master branch. It's in a pull request now.

The revised Keywords Mapping works without reloading the page. (It's part of a pull request.)

There is a populate function to copy the existing translations into the senses.
(This is for the virtual environment not the end users.)
There are actually two populate functions and these are awaiting review.
Ideally, this should probably be done in a migration to make sure it's only applied once.

**Comment by susanodd** [comment]
I suspect this code is part of the bug mentioned above:

https://github.com/Signbank/Global-signbank/blob/05e85eae014814cd5490ede3e5740e1e26f15e89/signbank/dictionary/update.py#L412-L416

**Comment by susanodd** [comment]
@vanlummelhuizen can you please check this out?

In a related issue, it was always needed to retrieve the translations for a gloss using `gloss.translation_set.all()` rather that try to obtain them via `Translation.objects.filter(gloss=gloss)`. I assume this has something to do with the Django-created extra tables.

The first line above (the try) will retrieve for example English translations not necessarily for this gloss.
The keywords are unique and all glosses / languages share Keyword objects when the text is the same.

**Comment by vanlummelhuizen** [comment]
> In a related issue, it was always needed to retrieve the translations for a gloss using `gloss.translation_set.all()` rather than try to obtain them via `Translation.objects.filter(gloss=gloss)`. I assume this has something to do with the Django-created extra tables.

I tried it out and it seems the actual SQL is the same:
```python
brus_c_dup = Gloss.objects.filter(lemma__dataset__acronym="tstMH", glosssense__sense__senseTranslations__translations__translation__text="brother").first()
str(brus_c_dup.translation_set.all().query) == str(Translation.objects.filter(gloss=brus_c_dup).query)
# output: True
```
---
> The keywords are unique and all glosses / languages share Keyword objects when the text is the same.

See also https://github.com/Signbank/Global-signbank/issues/884#issuecomment-1613111014

**Comment by vanlummelhuizen** [comment]
> This looks iffy because the Translation objects are related to glosses and hence (other) datasets.

I think it would work correctly if you would do

```python
translation = Translation.objects.filter(translation = keyword, language = dataset_language, gloss=gloss).first()
```
in the `try` clause.

**Comment by susanodd** [comment]
This works really well now. It's on the senses branch.

**Comment by susanodd** [comment]
This keywords mapping code has been enhanced with consistency checks. It has also been tested with combinations of editing and creating senses in GlossDetailView back to Keywords Mapping back to editing in GlossDetailView.

There is a consistency check on GlossDetailView that is invoked when you load the page.
It checks numerous things when the gloss object is fetched. It prints that to the error log.
There are numerous checks now in the Gloss Edit pane for Senses and more try-except clauses.
Since those operations on the Senses are complex and multipart, it was causing weird errors if it didn't finish something. Hence, the consistency check behind the scenes, for the developers.

**Comment by susanodd** [comment]
This is completed.
