### ISSUE TITLE
Search field in menu bar should change from Translation Equivalents to Senses

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#966]
This follows on #884 ; see also #964

**Comment by susanodd** [comment]
The translation search is actually searching on keywords.

For the menu bar search, this is across all languages, whereas in the search form, it's per language of the selected datasets.

Since Senses are built on top of keywords, this should just be a name change in the template label.

Behind the scenes, searching on the database obtains the glosses via the sense-gloss-keyword relations.
Also in addition this would also obtain senses (and/or sentences) containing the keywords.
Is the result offered to be "senses" or "sentences" in addition to glosses? Should there be another search option (in addition to sign or morpheme)?

**Comment by ocrasborn** [comment]
>Is the result offered to be "senses" or "sentences" in addition to glosses? Should there be another search option (in addition to sign or morpheme)?

The result should be the standard list view of signs, that is also obtained through the search-for-sign pane. That list view will need some rethinking, because the senses may take up more space than the single string of keywords of the translation equivalents, cf. #967
