### ISSUE TITLE
Include new sense and sentence fields in the CSV export/import routines

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#970]
This follows on #884

**Comment by ocrasborn** [comment]
@susanodd , I was thinking of the same solution as for Notes. Note text can also have punctuation, they should be dealt with in a similar way. (No, I don't have any example excel files.)

**Comment by susanodd** [comment]
Export is done. (On senses branch.)
I put newline characters between the numbered senses inside the cell for the Senses (<language>) column for the gloss row.
Now I need to work on parsing that same format as input.

**Comment by susanodd** [comment]
The \n is not going to work. Although the exported csv looks okay, it's actually introduced separate row (with the other columns empty for the "senses on a different row"

**Comment by susanodd** [comment]
It works to separate the senses with `' | '` on export to successfully import them again.

(The csv writer is already adding its own `'"' `around the large senses cells, so it does not work to add an additional `'"' `around something that includes `'\n'`. So `' | ' `will be used instead.

**Comment by susanodd** [comment]
@ocrasborn is it safe to assume a max number of senses as say 9 ?
This is needed to parse the senses cell in the CSV.
The code needs to check that only numbers are used and that they fall between say 1 and 9 and don't repeat.

**Comment by susanodd** [comment]
I'm writing it so the "import csv update" can be used to modify the senses.
The most simple way is

-  to "replace" all the existing senses of the gloss with the contents of the senses (language) cells.

So far, I'm trying to avoid that because it means an excessive amount of object creation and deletion.

But to do it elegantly

- move the existing senses around by new numbering, or simple text editing on a few keywords

this is more complicated as it involves numerous comparisons of all the objects to identify what has been changed.

It would be preferable if users make use of the Keywords Mapping functionality to split the original senses, rather than trying to do this in a spreadsheet.

There is error reporting now for "senses cells" that don't match the required format for senses.
But this becomes tedious really fast for the user.

**Comment by susanodd** [comment]
I pushed a version of the code with the actual "senses updates" code commented out.

This is necessary to first entirely debug the import of the cells to catch user syntax errors.
So actually clicking on "do changes" currently does not modify any senses, it merely prints data about what the code "plans to do".

**Comment by susanodd** [comment]
One glitch in the pending CSV import.
All the work to allow "keywords" to contain comma's will not be available.
The old implementation of Translations used the comma as a separator between keywords.
The new Senses functionality allows keywords to contain commas now.
But this is not possible on importing new senses via CSV.

A separator character is needed between the "keywords" in each "sense".
At the moment, a vertical bar "` | `" is being used to separate senses and a "`, `" is being used to separate keywords.
An additional glitch is the ordering of keywords within a sense.
The "index" field of Translation used to used to order them, in order given by the user.
This is actually needed to facilitate import, to more easily check whether a sense has indeed been changed in the CSV.
If the user merely rearranges the keywords, then this is difficult to check, especially considering the "index" which seems to not be being used in the new Senses model.

**Comment by susanodd** [comment]
The above is the reason for introducing the Keywords Mapping page.

**Comment by susanodd** [comment]
Import CSV Update is implemented now for Senses.

To speed things up the code offers Creation of Senses for when the Gloss Senses Language is currently empty.
If the user modifies senses that already exist these changes are just ignored.

It will take much more time to implement actual updates of existing senses, due to consistency.
However, it would be possible to simply "replace" existing senses. (That could end up risky as it would delete existing senses before creating new ones. That's why that is not completed yet.)

**Comment by susanodd** [comment]
This is completed but on the Senses branch.

**Comment by susanodd** [comment]
Hmm. The sentences have not been done yet.
It took a while to get the Sentence Type Field Choice working.

**Comment by susanodd** [comment]
See #1019.
I implemented Export CSV for example sentences as Export Gloss CSV columns per language.

The syntax resembles that of Notes as it is based on tuples.

Import is not available for sentences.

**Comment by susanodd** [comment]
Example sentences can be imported now.

There is some redundancy at the moment because the sentence fields are also included in the normal Gloss Update CSV.
However, those do not update anything.

**Comment by susanodd** [comment]
I revised the sentence tuples to include the sentence ID.
As a consequence, the normal (Gloss) csv update can only update sentences, not create sentences. The other command must be used.
Because the languages appear in columns, it won't be allowed to change the Negative or Sentence Type field, because those must match for all languages and cannot be changed independently. Only the actual sentence text can be changed.

**Comment by susanodd** [comment]
This is completed and live now.

**Comment by susanodd** [comment]
@Woseseltops there is a weird error happening now with the CSV import.
The "double quote" characters surrounding the sentences are being hijacked by other software and being converted to "pretty" quotes. Making the import regex not recognise them anymore.

But if I remove the quotes from the export csv (for the sentences column, they're not going to parse because sentences can have punctuation. The sentence text is enclosed in double quotes to allow parsing. But some other software is messing with this. I'm editing the exported CSV in Apple Numbers (spreadsheet analogous to Excel.) But since we use UTF-8 to support languages, then this pretty double quote is also included.

**Comment by susanodd** [comment]
See the last quote in #1030 about the quote characters.

**Comment by susanodd** [comment]
This is completed now. See #1030 for some screentshots. And #1045 for some comments about the double quotes.

**Comment by susanodd** [comment]
One thing to be cautious of is that the software itself does not recognise English or Dutch, etc.
If you type a Dutch sentence in the Example Sentences (English), the software will go ahead and put that in the database.

https://signbank.cls.ru.nl/dictionary/gloss/44102/

**Comment by susanodd** [comment]
@ocrasborn can this be closed? It's all been implemented.
