### ISSUE TITLE
Clicking OK in edit mode for a field clears the following field

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#971]
When I fill a blank field in the phonology panel and click OK to confirm, the cursor opens the next field for editing -- great. But it also clears the existing value in that field -- not great! A bug?

**Comment by susanodd** [comment]
@ocrasborn is it a particular field that does this? I'm not able to replicate this error.

**Comment by susanodd** [comment]
Apparently you can also navigate up and down in the lists in some browsers. And if you type the first character it moves to find that in the list. (You might want to experiment with stuff in tstMH.)

I am probably using the interface differently because I always click Cancel rather than OK. Once you click Cancel it stops advancing. So because of how I use it, it might be that I've imbued semantics on how it works.
Ahah. But Cancel can't be the default because then it wouldn't advance.

I'll try to think if it's doing something weird.
It definitely should not erase something.

**Comment by vanlummelhuizen** [comment]
@susanodd @ocrasborn This is live now. Please test.

**Comment by susanodd** [comment]
@ocrasborn this is more or less repaired. However, if you keep clicking on the same field, it will set it back to the original value. 

[NOTE TO SELF] There were some bugs in the code related to field choices, and related to empty values (new jquery).
The code for the "editable" fields needs to have its javascript/jquery updated to the new versions of the library. Although the library is actually very old. The functionality has been added to other things like bootstrap and jquery itself.
Because we use a (self-modified to add colours) library code "editable" this has the effect that the original values of the fields are embedded during creation of the 'editable'. So these pop up and replace the new one again. The original values (the _ machine values in the choice list) seem to be stored in the dynamic "select" (`<option>` elements with colours -- what we implemented inside the "editables") these are storing the machine value that has been selected. But because these forms are dynamically generated and keep disappearing when other fields are edited, it's not possible to "replace" the original value. It's probably possible to trace through the code to find out "where" this is being stored. So far I did not find out where exactly this is being done. The editable objects are being created, then pop up again. They are not being destroyed, since they have all the colours added to the lists.)

**Comment by susanodd** [comment]
I made some more modifications to this. It now works also if you keep clicking on the same field.

I'll test it some more tomorrow with fresh eyes.

**Comment by susanodd** [comment]
This is on the live server now.

@ocrasborn make sure you reload the page a few times, since all the javascript files have been modified.

**Comment by ocrasborn** [comment]
Looks good, thanks @susanodd
