### ISSUE TITLE
Calculation of minimal pairs disregards handshape

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#977]
It seems that somehow the calculation/generation of minimal pairs has gone off-track: from what I can see, it disregards the handshape of the strong hand (and possibly also of the weak hand), so that for a sign like https://signbank.cls.ru.nl/dictionary/gloss/44303, there are suddenly many dozens of (incorrect) minimal pairs.

**Comment by susanodd** [comment]
That might have something to do with field choices.

**Comment by susanodd** [comment]
I think I found it. It looks like there are still some fields of type BooleanField that were not upgraded to NullBooleanField when Django and Python were upgraded.

**Comment by susanodd** [comment]
I modified the code to ignore number and letter signs as indicated by the fields mentioned above (domhndsh_number, domhndsh_letter, subhndsh_number, subhndsh_letter).

Can you check this again, @ocrasborn ?

**Comment by susanodd** [comment]
Should the ALWEER-B gloss have any minimal pairs?

**Comment by susanodd** [comment]
NOTE TO SELF:
It's a bit confusing because the comparison tuples contain either field choice object ids, or handshape machine values. These are stored as strings in the tuples (since it's just used to generate simplified queries to find matches.)
But the queries actually use the strings rather than the integers. It's not entirely clear why this works with Sqlite.
There is a glitch going on with the tests, which use handshape objects.
But the tests cause an error because they notice that the integer is not a string. (Or vice versa.) I was not able to figure out why that happens. It broke entirely when I (temporarily during debugging) tried to use integers instead.
So whatever Django code creates the queries is maybe glitchy.

**Comment by susanodd** [comment]
This is live now.

**Comment by susanodd** [comment]
This is completed.
