### ISSUE TITLE
Finger Configuration field missing from Handshape description

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#978]
I just noticed: we used to have a field 'Finger configuration', but that is gone now. See #345 for when it was created. It should be linked to the field choices for JointConfiguration, just like Finger configuration 2 (which is still there). Please do bring it back! (should the data have gone, no worries, it's easily entered again)

**Comment by susanodd** [comment]
It's still there. But for some reason the code keeps loading an old version of the javascript file.

**Comment by susanodd** [comment]
I think this got messed up during the field choice model translation django upgrade sequence.

I tried to find out why the particular code block was missing, but in the history of the detail view template, the code is just replaced with a totally different file rather than modified. It looks like an older file replaced a newer file at one point and we started working on that one.

In any case I found the code and put it back.

**Comment by susanodd** [comment]
This has been fixed. On master, waiting for deployment.

**Comment by susanodd** [comment]
This is live now.

**Comment by ocrasborn** [comment]
Thanks @susanodd ! Happy to have it back. Could you still move it down three places in the view before I close the issue, to right above Finger Selection 2?

**Comment by susanodd** [comment]
This is live now!

**Comment by susanodd** [comment]
This is completed.

**Comment by susanodd** [comment]
This seems to have broken the search on finger configuration.

**Comment by susanodd** [comment]
This is working for queries again.
