### ISSUE TITLE
Create a new view that shows all available videos for a sign

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#98]
i.e. the standard video and all Other Videos ( #47 )

**Comment by henrinie** [comment]
There can be several 'standard videos' for one Gloss too.

**Comment by vanlummelhuizen** [comment]
@ocrasborn What to do with this old issue?

**Comment by ocrasborn** [comment]
well, hm. I'm moving this to lower priority

**Comment by susanodd** [comment]
I've implemented #99 which allows searching for glosses with Other Media.

**Comment by susanodd** [comment]
Here is what this looks like so far.
Related to #818, here is the gloss Paraplu, showing the videos stored as other media.

![gloss-videos-view-paraplu](https://user-images.githubusercontent.com/24272544/184372539-94bdb641-1050-45c9-b721-4033c8f32a13.png)


I copied the two other media files shown for this gloss to my local server. 
On the first go, one of the files is in Quicktime format and did not display. 
I needed to run ffmpeg on it to convert it. That is what's done when "normal" videos are uploaded. 
So it would seem this also needs to be done on other media when uploaded.
Of course, it's possible to download other media, it's just getting them to preview (on firefox under ubuntu).

**Comment by susanodd** [comment]
I revised the upload other media code so that upon encountering a quicktime file, it uses ffmpeg to convert it to mp4, as is done for uploading gloss videos.

Additionally, if this fails, or if the user attempts to upload an existing file again, a message is given that the filename already is in use. Currently it's already possible to delete other media via Gloss Edit.
But the OtherMedia is merely removed from the database; the actual files are not removed.

Because the files also appear in the database, it seems preferable that the user manages the other media by deleting it, or downloading it and then changing the name or whatever is desired and uploading it again.

Perhaps this new view needs to also display "dangling" other media that isn't stored in the database anymore but is still in storage.
And then allow the user to remove the unwanted files.
I assume we originally didn't remove the files in case these were needed for backups, or for recovery?

Any suggestions? @vanlummelhuizen you did quite a lot with the videos.

**Comment by ocrasborn** [comment]
I like it, @susanodd !

**Comment by vanlummelhuizen** [comment]
> Perhaps this new view needs to also display "dangling" other media that isn't stored in the database anymore but is still in storage.
> And then allow the user to remove the unwanted files.
> I assume we originally didn't remove the files in case these were needed for backups, or for recovery?

@susanodd @ocrasborn do you think that those dangling media files is of any concern to the users? If it is just because the system did not delete a file when a media item was deleted from the database, I think we should just clean up dangling media files so that what is in the database is also on disk and vice versa. Perhaps make a backup first, of course.

**Comment by susanodd** [comment]
Yes, that has become overridden by a new issue: #833

**Comment by vanlummelhuizen** [comment]
@susanodd Good! Can this issue be closed then?

**Comment by susanodd** [comment]
This has been merged into the master, but it's not live yet.

**Comment by susanodd** [comment]
This is live.

**Comment by vanlummelhuizen** [comment]
Thanks @susanodd Closing now.
