### ISSUE TITLE
Include Other Videos in search options

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/Global-signbank#99]
• Other videos: added in #47 
- 'Has/does not have other video, of type X'
- Types to be selected from the list in Django, plus 'any type'
- See also #98

**Comment by vanlummelhuizen** [comment]
@ocrasborn Do you still want this?

**Comment by ocrasborn** [comment]
Yes, please @vanlummelhuizen

**Comment by susanodd** [comment]
By chance I came across this yesterday in #816. The 'hasvideo' is being processed in get_queryset, but nowhere on the Gloss Search Form Query are you able to enter this.

**Comment by susanodd** [comment]
I've added a search on `Has Other Media` in the panel `Search by Publication Status and Notes`.
I put the fields of this panel in a setting `SEARCH_BY_PUBLICATION_FIELDS` in order to make the Gloss Search template more concise. At the moment, this has the side effect of showing them all vertically rather than in two columns. The columns were hard-coded.

![gloss-search-publication-status-notes](https://user-images.githubusercontent.com/24272544/182159455-61ed5d72-67cf-4910-aed3-153ef9175db7.png)

**Comment by susanodd** [comment]
I added a couple lines of CSS to get the publication fields to be two-column. I rearranged the order of the fields in the settings in order to make them pleasing to look at instead of illogical due to row pairings. (use your own imagination. the sentence sounds weird since I tried to make it sound like it makes sense rather than arbitrary.) Created After is before Created Before since that's the time interval.


![gloss-searchby-pub-notes-2column](https://user-images.githubusercontent.com/24272544/182187542-27becc90-7fb0-4a05-8a28-33a059f7c45a.png)

**Comment by susanodd** [comment]
I revised Type of Relation to show the actual relation that was being searched on in the results.

I searched on Type of Relation Antonym and this is what it looks like:

![query-view-type-of-relation-antonym](https://user-images.githubusercontent.com/24272544/183882053-d83b6b9d-48f8-48e5-b388-4fca20016988.png)

As you can see, it looks like some duplicates. But this is actually true if you go to the detail view of Black-A. You can see that its relation to White is duplicated. Indeed the relation appears three times in the database, two of which are the same direction with Black-A as the source.

![zwart-A-detailview](https://user-images.githubusercontent.com/24272544/183882490-3ee1ad55-4463-4150-94ec-dbca8d238912.png)

**Comment by susanodd** [comment]
See https://github.com/Signbank/Global-signbank/issues/816#issuecomment-1210590160

**Comment by susanodd** [comment]
@ocrasborn there are two possibilities in the Search now, under Search by Publication Status and Notes.
Here you can select Has Video (Boolean) and Has Other Media (Boolean).
As the code works now, the videos become converted to mp4 during upload, so there isn't really any type of video to choose from. The search is the default of any type.

**Comment by susanodd** [comment]
This can be closed as completed.
